[build]
  command = "ionic build --prod"
  publish = "www"

[build.environment]
  # Give Node 8 GB of heap
  NODE_OPTIONS = "--max-old-space-size=8192"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
