import {IonIcon} from '@ionic/react';
import Link, {ThLink} from '../../components/Link';
import ScrollContainer from '../../components/ScrollContainer';
const _not_found = {title: "Unknown", jsx: <><h2 id="arcanedisc-not_found-unknown">Unknown</h2>
<p>Unable to find the requested arcane discovery.</p>
</>};
const _alchemical_affinity = {title: "Alchemical Affinity", jsx: <><h2 id="arcanedisc-alchemical_affinity-alchemical-affinity">Alchemical Affinity</h2>
<p><strong>Sources</strong> <Link to="/source/magical_marketplace">Magical Marketplace pg. 18</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-alchemical_affinity--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>5th level wizard</td></tr></tbody></table></ScrollContainer></div><p>Having studied alongside <Link to="/class/alchemist">alchemists</Link>, you've learned to use their methodologies to enhance your spellcraft. Whenever you cast a spell that appears on both the wizard and alchemist spell lists, you treat your caster level as 1 higher than normal and the save DC of such spells increases by 1. Additionally, you may copy spells from an alchemist's formula book into your spellbook just as you could with another wizard's spellbook.</p>
</>};
const _arcane_builder = {title: "Arcane Builder", jsx: <><h2 id="arcanedisc-arcane_builder-arcane-builder">Arcane Builder</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link><br/>You have an exceptional understanding of the theory behind creating magical items. Select one type of magic item (potions, wondrous items, and so on). You create items of this type 25% faster than normal, and gain a +4 bonus on Spellcraft checks (or other checks, as appropriate) to craft items of this type. You may select this discovery multiple times; its effects do not stack. Each time you select this discovery, it applies to a different type of magic item.</p>
</>};
const _balanced_summoning = {title: "Balanced Summoning", jsx: <><h2 id="arcanedisc-balanced_summoning-balanced-summoning">Balanced Summoning</h2>
<p><strong>Sources</strong> <Link to="/source/champions_of_balance">Champions of Balance pg. 20</Link><br/>You maintain balance by calling on opposing forces when summoning. Whenever you cast a <em>summon monster</em> spell, you can summon two creatures from a single list 1 or more levels lower than the level of the spell. The two creatures must have alignments that are opposite along at least one axis (chaotic and lawful or evil and good). For example, if you cast <Link to="/spell/summon_monster_iii">summon monster III</Link>, you could summon a <Link to="/template/celestial">celestial</Link> wolf and a <Link to="/template/fiendish">fiendish</Link> hyena from the 2nd-level list.</p>
</>};
const _beyond_morality = {title: "Beyond Morality", jsx: <><h2 id="arcanedisc-beyond_morality-beyond-morality-su">Beyond Morality (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/champions_of_balance">Champions of Balance pg. 21</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-beyond_morality--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>9th level wizard</td></tr></tbody></table></ScrollContainer></div><p>As long as you are neutral, you may choose to be treated as the most favorable alignment when affected by spells whose effects vary based on alignment (such as <Link to="/spell/holy_word">holy word</Link>). If you are neutral in relation to evil and good, you may choose to be treated as good or evil. If you are neutral in relation to chaos and law, you may choose to be treated as lawful or chaotic. You may only choose to be treated as one alignment type along a single axis at a time (for instance, if you were within the area of both a <Link to="/spell/magic_circle_against_evil">magic circle against evil</Link> spell and an <Link to="/spell/unholy_blight">unholy blight</Link> spell, you would have to choose to be either evil, good, or neutral for the purpose of determining the spells' effects).</p>
</>};
const _bonded_mask = {title: "Bonded Mask", jsx: <><h2 id="arcanedisc-bonded_mask-bonded-mask">Bonded Mask</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_80_empty_graves">Pathfinder #80: Empty Graves pg. 26</Link><br/>Your devotion to the Forgotten Pharaoh enables you to select a mask - typically an Osirian funerary mask - as your bonded item. The mask must be worn to have effect, and occupies the <Link to="/rule/head_slot">head slot</Link>. In addition, the mask shields you from notice. While wearing your bonded mask, efforts to use the Diplomacy skill to gather information about you take a -1 penalty, and you gain a +1 competence bonus on all saving throws against scrying and mind-reading effects that allow saving throws.</p>
</>};
const _creative_destruction = {title: "Creative Destruction", jsx: <><h2 id="arcanedisc-creative_destruction-creative-destruction-su">Creative Destruction (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/champions_of_balance">Champions of Balance pg. 21</Link><br/>You have learned how to use destructive energy to empower yourself. When you cast an evocation spell that deals damage, you gain a number of <Link to="/rule/temporary_hit_points">temporary hit points</Link> equal to the total number of dice used to determine the damage caused by the spell. Temporary hit points gained from this discovery do not stack and disappear after 1 hour.</p>
</>};
const _defensive_feedback = {title: "Defensive Feedback", jsx: <><h2 id="arcanedisc-defensive_feedback-defensive-feedback-su">Defensive Feedback (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/champions_of_balance">Champions of Balance pg. 21</Link><br/>Rather than dissipate damaging energy, you can redirect some of it back to its source. When an abjuration spell you cast prevents damage (with damage reduction or energy resistance), if the attacking creature is within 30 feet of the protected creature, the foe takes 1d6 points of damage for every 10 points of damage prevented.</p>
</>};
const _faith_magic = {title: "Faith Magic", jsx: <><h2 id="arcanedisc-faith_magic-faith-magic">Faith Magic</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 3</Link><br/>Select one spell granted by a domain belonging to the god you worship. This spell must be at least 2 levels lower than the highest-level wizard spell you can cast. When you first prepare your spells for the day, you can prepare this spell once, using a spell slot 1 level higher than the spell's actual level. This is cast as a divine spell.</p>
</>};
const _fast_study = {title: "Fast Study", jsx: <><h2 id="arcanedisc-fast_study-fast-study">Fast Study</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-fast_study--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>5th level wizard</td></tr></tbody></table></ScrollContainer></div><p>Normally, a wizard spends 1 hour preparing all of his spells for the day, or proportionately less if he only prepares some spells, with a minimum of 15 minutes of preparation. Thanks to mental discipline and clever mnemonics, you can prepare all of your spells in only 15 minutes, and your minimum preparation time is only 1 minute.</p>
</>};
const _feral_speech = {title: "Feral Speech", jsx: <><h2 id="arcanedisc-feral_speech-feral-speech-su">Feral Speech (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-feral_speech--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>5th level wizard</td></tr></tbody></table></ScrollContainer></div><p>You gain the ability to speak with and understand the response of any animal as if using <Link to="/spell/speak_with_animals">speak with animals</Link>, though each time you speak to animals, you must decide to communicate with either amphibians, birds, fish, mammals, or reptiles, and can only speak to and understand animals of that type. You can make yourself understood as far as your voice carries. This discovery does not predispose any animal addressed toward you in any way. When you reach 12th level, you can also use this ability to communicate with vermin.</p>
</>};
const _golem_constructor = {title: "Golem Constructor", jsx: <><h2 id="arcanedisc-golem_constructor-golem-constructor">Golem Constructor</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-golem_constructor--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>9th level wizard</td></tr></tbody></table></ScrollContainer></div><p>You have learned the art and craft of creating a single type of <Link to="/family/golem">golem</Link> (such as <Link to="/monster/stone_golem">stone golems</Link> or <Link to="/monster/iron_golem">iron golems</Link>). When creating a golem of this type, you count as having the <Link to="/feat/craft_wondrous_item">Craft Wondrous Item</Link>, <Link to="/feat/craft_magic_arms_and_armor">Craft_Magic_Arms_and_Armor</Link>, and <Link to="/feat/craft_construct">Craft Construct</Link> feats. You must meet all other construction requirements for the golem as normal. You may select this discovery multiple times. Each time you select this discovery, it applies to a different kind of golem.</p>
</>};
const _idealize = {title: "Idealize", jsx: <><h2 id="arcanedisc-idealize-idealize-su">Idealize (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/champions_of_balance">Champions of Balance pg. 21</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-idealize--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>10th level wizard</td></tr></tbody></table></ScrollContainer></div><p>In your quest for self-perfection, you have discovered a way to further enhance yourself and others. When a transmutation spell you cast grants an enhancement bonus to an ability score, that bonus increases by 2. At 20th level, the bonus increases by 4.</p>
</>};
const _immortality = {title: "Immortality", jsx: <><h2 id="arcanedisc-immortality-immortality-ex">Immortality (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-immortality--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>20th level wizard</td></tr></tbody></table></ScrollContainer></div><p>You discover a cure for aging, and from this point forward you take no penalty to your physical ability scores from <Link to="/rule/age">advanced age</Link>. If you are already taking such penalties, they are removed at this time.</p>
</>};
const _infectious_charms = {title: "Infectious Charms", jsx: <><h2 id="arcanedisc-infectious_charms-infectious-charms">Infectious Charms</h2>
<p><strong>Sources</strong> <Link to="/source/magical_marketplace">Magical Marketplace pg. 18</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-infectious_charms--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>11th level wizard</td></tr></tbody></table></ScrollContainer></div><p>Your charms are so smooth that they're contagious. Anytime you target and successfully affect a single creature with a charm or compulsion spell and that creature is within 30 feet of another opponent, your spell has a chance of affecting the second creature as well. As a swift action immediately after affecting a creature with a charm or compulsion spell, you can cause the spell to carry over to the nearest creature within 30 feet. The spell behaves in all ways as though its new target were the original target of the spell.</p>
</>};
const _ioun_bond = {title: "Ioun Bond", jsx: <><h2 id="arcanedisc-ioun_bond-ioun-bond">Ioun Bond</h2>
<p><strong>Sources</strong> <Link to="/source/people_of_the_river">People of the River pg. 9</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-ioun_bond--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>Arcane bond class ability, choosing bonded object</td></tr></tbody></table></ScrollContainer></div><p>You can form an arcane bond with an <Link to="/magic-wondrous/ioun_stone">ioun stone</Link>. If you choose this arcane discovery at 1st level, you gain a <Link to="/magic-ioun/dull_gray">dull gray</Link> ioun stone as a bonded object at no cost. A bonded ioun stone must be orbiting your head to have effect. At 12th level, you can turn a bonded dull gray ioun stone into another kind of ioun stone as if you possessed the <Link to="/feat/craft_wondrous_item">Craft Wondrous Item</Link> feat; if you die or replace a bonded ioun stone that has been transformed in this way, the stone reverts to a dull gray ioun stone.</p>
</>};
const _knowledge_is_power = {title: "Knowledge Is Power", jsx: <><h2 id="arcanedisc-knowledge_is_power-knowledge-is-power-ex">Knowledge Is Power (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/people_of_the_river">People of the River pg. 9</Link><br/>Your understanding of physical forces gives you power over them. You add your Intelligence modifier on combat maneuver checks and to your CMD. You also add your Intelligence modifier on Strength checks to break or lift objects.</p>
</>};
const _multimorph = {title: "Multimorph", jsx: <><h2 id="arcanedisc-multimorph-multimorph-su">Multimorph (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-multimorph--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>5th level wizard</td></tr></tbody></table></ScrollContainer></div><p>Your studies in transmogrification have increased your control over shapechanging spells. When you cast a spell of the polymorph subschool on yourself, you may expend 1 minute of the spell's duration as a standard action to assume another form allowed by the spell. You can do this as often as you like, subject to the duration of the spell.</p>
</>};
const _observant_illusion = {title: "Observant Illusion", jsx: <><h2 id="arcanedisc-observant_illusion-observant-illusion-su">Observant Illusion (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 23</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-observant_illusion--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>9th level wizard</td></tr></tbody></table></ScrollContainer></div><p>You can project your senses into any ongoing figment or shadow illusion you create with a spell of at least 3rd level. You can see through its eyes and hear through its ears as if you were standing where it is, and during your turn you can switch from using its senses to using your own, or back again, as a swift or move action. While you are using its senses, your body is considered <Link to="/misc/blinded">blinded</Link> and <Link to="/misc/deafened">deafened</Link>.</p>
</>};
const _opposition_research = {title: "Opposition Research", jsx: <><h2 id="arcanedisc-opposition_research-opposition-research">Opposition Research</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-opposition_research--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td><ul><li>9th level wizard</li><li>Have at least one opposition school</li></ul></td></tr></tbody></table></ScrollContainer></div><p>By completing strenuous studies, you have broken through the mental barriers that made it hard for you to prepare spells from one of your opposition schools. Select one wizard opposition school; preparing spells of this school now only requires one spell slot of the appropriate level instead of two, and you no longer have the -4 Spellcraft penalty for crafting items from that school.</p>
</>};
const _psychic_preparation = {title: "Psychic Preparation", jsx: <><h2 id="arcanedisc-psychic_preparation-psychic-preparation">Psychic Preparation</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 3</Link><br/>You have learned a limited way to access <Link to="/rule/psychic_magic">psychic magic</Link>. When you first prepare your spells for the day, you can prepare one spell as a psychic spell. This spell must be at least 2 levels lower than the highest-level wizard spell you can cast, and takes a slot 1 level higher than the spell's actual level. When you cast this spell, it operates as a psychic spell, including using emotional and thought components in place of somatic and verbal components, and only having expensive material components.</p>
</>};
const _resilient_illusions = {title: "Resilient Illusions", jsx: <><h2 id="arcanedisc-resilient_illusions-resilient-illusions">Resilient Illusions</h2>
<p><strong>Sources</strong> <Link to="/source/magical_marketplace">Magical Marketplace pg. 18</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-resilient_illusions--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>8th level wizard</td></tr></tbody></table></ScrollContainer></div><p>You are able to conjure illusions so lifelike that they defy disbelief. Anytime a creature tries to disbelieve one of your illusion effects, make a caster level check. Treat the illusion's save DC as its normal DC or the result of the caster level check, whichever is higher.</p>
</>};
const _split_slot = {title: "Split Slot", jsx: <><h2 id="arcanedisc-split_slot-split-slot">Split Slot</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 86</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-split_slot--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>5th level wizard</td></tr></tbody></table></ScrollContainer></div><p>Once per day when you prepare spells, you may treat any one of your open spell slots as if it were two spell slots that were two spell levels lower. For example, a 9th-level wizard can split a 5th-level slot into two 3rd-level slots, preparing <Link to="/spell/fireball">fireball</Link> and <Link to="/spell/lightning_bolt">lightning bolt</Link> in those 3rd-level slots. For all purposes, the two lower-level slots are treated as that lower level (so the split 5th-level slot used for a fireball has a DC as if it were in a normal 3rd-level slot). Splitting a 2nd-level slot lets you prepare two additional cantrips (which you can cast over and over, just like normally prepared cantrips). This discovery has no effect on cantrips or 1st-level spells. You may select this discovery multiple times; each time you select it, you may split another spell slot when you prepare spells. You cannot split a slot that you created by splitting a higher-level slot.</p>
</>};
const _staff_like_wand = {title: "Staff-Like Wand", jsx: <><h2 id="arcanedisc-staff_like_wand-staff-like-wand">Staff-Like Wand</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 87</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-staff_like_wand--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td><ul><li>11th level wizard</li><li><strong>Feat:</strong> <Link to="/feat/craft_staff">Craft Staff</Link></li></ul></td></tr></tbody></table></ScrollContainer></div><p>Your research has unlocked a new power in conjunction with using a wand. Similar to using a magic staff, you use your own Intelligence score and relevant feats to set the DC for saves against spells you cast from a wand, and you can use your caster level when activating the power of a wand if it's higher than the caster level of the wand.</p>
</>};
const _steward_of_the_great_beyond = {title: "Steward of the Great Beyond", jsx: <><h2 id="arcanedisc-steward_of_the_great_beyond-steward-of-the-great-beyond">Steward of the Great Beyond</h2>
<p><strong>Sources</strong> <Link to="/source/champions_of_purity">Champions of Purity pg. 27</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-steward_of_the_great_beyond--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>9th level wizard</td></tr></tbody></table></ScrollContainer></div><p>Whenever a creature attempts to use a teleportation effect or summon a creature within 30 feet of you, you may attempt to block the effect. Make an opposed caster level check (1d20 + caster level) as an immediate action. If the check succeeds, the spell or effect fails and is wasted; otherwise, it is unaffected. You can use this ability once per day plus one additional time for every 5 wizard levels you possess beyond 10th.</p>
</>};
const _time_stutter = {title: "Time Stutter", jsx: <><h2 id="arcanedisc-time_stutter-time-stutter-sp">Time Stutter (Sp)</h2>
<p><strong>Sources</strong> <Link to="/source/people_of_the_river">People of the River pg. 9</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-time_stutter--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>10th level wizard</td></tr></tbody></table></ScrollContainer></div><p>You can briefly step out of time, pausing the world around you. This ability acts as the <Link to="/spell/time_stop">time stop</Link> spell, except that you gain only 1 round of apparent time. You can use this ability once per day plus one additional time for every 5 wizard levels you possess beyond 10th.</p>
</>};
const _true_name = {title: "True Name", jsx: <><h2 id="arcanedisc-true_name-true-name-sp">True Name (Sp)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_magic">Ultimate Magic pg. 87</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-true_name--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>11th level wizard</td></tr></tbody></table></ScrollContainer></div><p>Your researches into ancient tomes and your inquisitions of bound spirits have led you to one of the best-hidden secrets of the multiverse: the true name of an outsider - the name that defines the very essence of the creature and that gives the speaker control over the being. This outsider can have no more than 12 Hit Dice. Once per day, you can speak the common name by which the outsider is known, and the outsider travels to you as if you had cast <Link to="/spell/planar_binding">planar binding</Link> upon it. It must obey you to the best of its ability, without pay or bargaining for its services, for its fear that you might release its true name to the wider world is enough to bring even the most recalcitrant of outsiders to bear.</p>
<p>If the creature is within 100 feet, as a move action, you may punish it by deliberately mispronouncing its name, wracking its very essence and giving it the <Link to="/misc/sickened">sickened</Link> and <Link to="/misc/staggered">staggered</Link> conditions for 1 round (even if the creature is normally immune to these conditions). You cannot use true name in an area of <Link to="/spell/silence">silence</Link>, but the creature does not have to be able to hear you for it to be harmed by the ability.</p>
<p>It is in your best interest to call this creature only sparingly, and occasionally reward it in some fashion to mollify its wrath. If you repeatedly fail to offer it a reward appropriate to its type and ethos, the creature may begin plotting ways to destroy the bond between you, whether by creating an accident that will destroy your memory of the name, by plaguing you with nuisances or dangers until you vow never to call on it again, or by actively seeking to destroy you through its own devices or those of an underling. If this creature is of a lawful type and you are violating its ethos, its superiors may even destroy it or you rather than allow you to contaminate their servant further. Worse, they may establish situations where it is necessary for you to summon this outsider, opening gateways to infernal or angelic interference, in order to gain a foothold on the Material Plane.</p>
<p>You may select this discovery multiple times. Each time you select this discovery, it applies to a different, specific outsider. If you select this discovery at 15th level or higher, the creature may have up to 18 Hit Dice and the call acts as <Link to="/spell/greater_planar_binding">greater planar binding</Link> instead of <em>planar binding.</em></p>
</>};
const _werewolf_shape = {title: "Werewolf Shape", jsx: <><h2 id="arcanedisc-werewolf_shape-werewolf-shape">Werewolf Shape</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_moon">Blood of the Moon pg. 25</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-werewolf_shape--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>15th level wizard</td></tr></tbody></table></ScrollContainer></div><p>When you cast <Link to="/spell/beast_shape_iv">beast shape IV</Link> or <Link to="/spell/shapechange">shapechange</Link>, you can choose to take the shape of a werewolf in addition to the other shapes available. While in werewolf shape, you gain all the effects of the <Link to="/template/lycanthrope">lycanthrope</Link> template instead of the spell's normal benefits. You act in all respects as a natural lycanthrope for the duration of the spell, including the ability to inflict the <Link to="/umr/curse_of_lycanthropy">curse of lycanthropy</Link> using the spell's save DC.</p>
</>};
const _yuelrals_blessing = {title: "Yuelral's Blessing", jsx: <><h2 id="arcanedisc-yuelrals_blessing-yuelrals-blessing">Yuelral's Blessing</h2>
<p><strong>Sources</strong> <Link to="/source/champions_of_purity">Champions of Purity pg. 27</Link>  </p>
<div className="sideNoteWrap startAlign singular delist"><ScrollContainer id="arcanedisc-yuelrals_blessing--table-0"><table><tbody><tr><ThLink scope="row" to="/icons/confirmed"><IonIcon aria-label="Prerequisites" icon="/icons/confirmed.svg" /></ThLink><td>5th level wizard</td></tr></tbody></table></ScrollContainer></div><p>You cast any spells that appear on both the wizard and druid spell lists at +1 caster level and with +1 to the save DC. In addition, you may replace the material component of any arcane spell with gems of the same value.</p>
</>};
export default {not_found:_not_found,alchemical_affinity:_alchemical_affinity,arcane_builder:_arcane_builder,balanced_summoning:_balanced_summoning,beyond_morality:_beyond_morality,bonded_mask:_bonded_mask,creative_destruction:_creative_destruction,defensive_feedback:_defensive_feedback,faith_magic:_faith_magic,fast_study:_fast_study,feral_speech:_feral_speech,golem_constructor:_golem_constructor,idealize:_idealize,immortality:_immortality,infectious_charms:_infectious_charms,ioun_bond:_ioun_bond,knowledge_is_power:_knowledge_is_power,multimorph:_multimorph,observant_illusion:_observant_illusion,opposition_research:_opposition_research,psychic_preparation:_psychic_preparation,resilient_illusions:_resilient_illusions,split_slot:_split_slot,staff_like_wand:_staff_like_wand,steward_of_the_great_beyond:_steward_of_the_great_beyond,time_stutter:_time_stutter,true_name:_true_name,werewolf_shape:_werewolf_shape,yuelrals_blessing:_yuelrals_blessing}