import Link from '../../components/Link';
const _bracers_of_antiquity = {title: "Bracers of Antiquity", jsx: <><h2 id="magic-legacy-bracers_of_antiquity-bracers-of-antiquity">Bracers of Antiquity</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 20</Link><br/><strong>Slot</strong> wrists; <strong>CL</strong> 13th; <strong>Weight</strong> 1 lb.<br/><strong>Aura</strong> strong divination</p>
<p>Despite the fact that they are millennia old, these polished metal armbands, inlaid with intricate patterns in gold and platinum, are in remarkable condition. Part of a cache of Azlanti artifacts discovered by Arustun in the Cave of Tiandra in approximately -4160 AR, the bracers became a treasured possession of the Jistka Imperium's founder and a valuable tool in his decades-long quest to recover and interpret remnants of Azlanti and Thassilonian culture.</p>
<p>Each of the bracers has one slot in which an ioun stone can be embedded. An <Link to="/magic-wondrous/ioun_stone">ioun stone</Link> embedded in this manner grants the bearer its normal benefits as if it were orbiting her head and resonates its powers as if it were slotted in a <Link to="/magic-wondrous/wayfinder">wayfinder</Link>. Additionally, as long as at least one ioun stone is slotted into the bracers, the wearer can understand any written language, as per <Link to="/spell/comprehend_languages">comprehend languages</Link>.</p>
<p><strong>6th Level</strong> The wearer gains a +2 competence bonus on Knowledge (arcana), Spellcraft, and Use Magic Device checks.</p>
<p><strong>9th Level</strong> The bracers act as <Link to="/magic-enh/spell_storing_a">spell storing</Link> <Link to="/magic-wondrous/bracers_of_armor">bracers of armor</Link>.</p>
<p><strong>12th Level</strong> While at least one ioun stone is embedded in the bracers, the wearer can speak and understand any language, as per <Link to="/spell/tongues">tongues</Link>.</p>
<p><strong>15th Level</strong> The wearer gains a +4 insight bonus on saving throws against language-dependent spells and effects and on saving throws against magical glyphs, symbols, sigils, or similar written traps.</p>
<p><strong>18th Level</strong> Twice per day, the wearer can temporarily drain the magic of one of the bracers' embedded ioun stones to cast <Link to="/spell/plane_shift">plane shift</Link>. After powering this ability, the ioun stone becomes inert for 24 hours and impossible to remove from the bracer.</p>
<p><strong className="hl">Goal:</strong> Recover and identify 30 named texts or artifacts that were created more than 4,000 years before the present day. Recovering a major artifact counts as 3 artifacts toward the completion of this goal.</p>
<p><strong className="hl">Reward:</strong> By handling a magic item for 1 minute, the wearer can identify its properties and command word as if she had successfully examined the item using <Link to="/spell/detect_magic">detect magic</Link> and succeeded at a Spellcraft check. This ability does not reveal whether the item is cursed unless the wearer's character level is equal to or greater than the caster level of the item.</p>
</>};
const _carved_kings_band = {title: "Carved King's Band", jsx: <><h2 id="magic-legacy-carved_kings_band-carved-kings-band">Carved King's Band</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 20</Link><br/><strong>Slot</strong> headband; <strong>CL</strong> 17th; <strong>Weight</strong> 1 lb.<br/><strong>Aura</strong> strong transmutation</p>
<p>The runic scrollwork that decorates this thick iron headband calls to mind the intricate tattoos of the Blue Warders, the dwarven caretakers of Tar-Kazmukh's arcane libraries. An heirloom of King Kazmukh of Doggadth who signed the Kerse Accords in 2332 AR, the band has long been stored in the heavily warded levels of the city's labyrinthine archives.</p>
<p>A wizard who wears the headband gains two extra uses per day of a 1st-level arcane school power that is normally usable a number of times per day equal to 3 + the wizard's Intelligence modifier.</p>
<p><strong>4th Level:</strong> The carved king's band acts as a <Link to="/magic-wondrous/headband_of_vast_intelligence_2">headband of vast intelligence +2</Link> (granting skill ranks in Perception).</p>
<p><strong>7th Level:</strong> Once per day when the wearer attempts a saving throw against a magical glyph, symbol, sigil, or similar written trap, as an immediate action, he can attempt a Spellcraft check against the same DC to dispel the effect.</p>
<p><strong>10th Level:</strong> The carved king's band acts as a <Link to="/magic-wondrous/headband_of_vast_intelligence_4">headband of vast intelligence +4</Link> (granting skill ranks in Knowledge [history] and Spellcraft).</p>
<p><strong>13th Level:</strong> The DC and caster level of all spells with the earth descriptor that the wearer casts increase by 1.</p>
<p><strong>15th Level:</strong> The carved king's band acts as a <Link to="/magic-wondrous/headband_of_vast_intelligence_6">headband of vast intelligence +6</Link> (granting skill ranks in Knowledge [history], Sense Motive, and Spellcraft).</p>
<p><strong className="hl">Goal:</strong> Prepare and cast 50 unique spells, at least three of which must be 8th-level or higher.</p>
<p><strong className="hl">Reward:</strong> The wearer can spontaneously cast any spell with the earth descriptor from his spellbook by sacrificing a prepared spell of equal or higher level. He can apply any metamagic feats he has to this spell when he casts it. This increases the minimum level of the prepared spell sacrificed in order to cast it but does not affect the casting time.</p>
</>};
const _conquerors_breastplate = {title: "Conqueror's Breastplate", jsx: <><h2 id="magic-legacy-conquerors_breastplate-conquerors-breastplate">Conqueror's Breastplate</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 20</Link><br/><strong>Slot</strong> armor; <strong>CL</strong> 10th; <strong>Weight</strong> 15 lbs.<br/><strong>Aura</strong> moderate enchantment</p>
<p>The chasing of this +1 <Link to="/eq-material/mithral">mithral</Link> <Link to="/eq-armor/breastplate">breastplate</Link> makes it appear to be crafted of dragon's scales. Originally worn by Choral Rogarvia, the armor was imitated, at great expense, by Issian nobles hoping to curry favor with the new ruler of Brevoy, but its power was never duplicated.</p>
<p>The armor's dazzling finish often impresses onlookers, and its wearer can adjust a creature's attitude up to three steps when using Diplomacy, instead of the normal limit of two steps.</p>
<p><strong>5th Level:</strong> Conqueror's breastplate acts as a +2 mithral breastplate.</p>
<p><strong>10th Level:</strong> Once per day as an immediate action, the wearer can use <Link to="/spell/draconic_reservoir">draconic reservoir</Link> as a spell-like ability.</p>
<p><strong>15th Level:</strong> Conqueror's breastplate acts as a +3 <Link to="/magic-enh/determination">determination</Link> mithral breastplate.</p>
<p><strong className="hl">Goal:</strong> At least 20 people whose CR is equal to or greater than the wearer's Hit Dice - 4 must swear fealty or pledge their loyalty to the wearer.</p>
<p><strong className="hl">Reward:</strong> The wearer's grandiose bearing cows the weak willed. He gains the <Link to="/umr/frightful_presence">frightful presence</Link> universal monster ability with a 30-foot-radius range and a Will save DC equal to 10 + his character level + his Charisma modifier. He can suppress or resume this ability as a free action.</p>
</>};
const _ring_of_sealed_souls = {title: "Ring of Sealed Souls", jsx: <><h2 id="magic-legacy-ring_of_sealed_souls-ring-of-sealed-souls">Ring of Sealed Souls</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 21</Link><br/><strong>Slot</strong> ring; <strong>CL</strong> 15th; <strong>Weight</strong> -<br/><strong>Aura</strong> strong abjuration</p>
<p>According to records salvaged from abandoned temples of Aroden, the high priest Narthoc was wearing a ring of sealed souls when he trapped <Link to="/monster/the_whispering_tyrant">the Whispering Tyrant</Link> under Gallowspire in 3827 AR.</p>
<p>If the wearer of this braided ring is slain while wearing the ring, he cannot be raised as undead. Additionally, the wearer can be revived with <Link to="/spell/raise_dead">raise dead</Link> or similar effects even if he was slain by a death effect.</p>
<p><strong>8th Level:</strong> The wearer can use <Link to="/spell/hold_portal">hold portal</Link> at will as a spell-like ability, though he can have only one portal held by this ability at a time. Should he use the ability again while the spell is already active, the first casting is immediately dismissed.</p>
<p><strong>11th Level:</strong> Weapons wielded by the wearer gain the <Link to="/magic-enh/ghost_touch">ghost touch</Link> weapon property.</p>
<p><strong>14th Level:</strong> The wearer can use <Link to="/spell/guards_and_wards">guards and wards</Link> once per day as a spell-like ability.</p>
<p><strong>17th Level:</strong> The wearer adds <Link to="/spell/binding">binding</Link> to his class spell list and list of spells known. The wearer can use <em>binding</em> once per day as a spell-like ability, but he must provide the expensive material component for the spell.</p>
<p><strong className="hl">Goal:</strong> The wearer must defeat an undead creature or evil outsider whose CR is at least 4 greater than his Hit Dice.</p>
<p><strong className="hl">Reward:</strong> The wearer is constantly under the effect of <Link to="/spell/protection_from_evil">protection from evil</Link> with a caster level equal to his character level. Should this effect be <Link to="/spell/dispel">dispelled</Link>, he can resume it as a free action.</p>
</>};
const _scimitar_of_deliverance = {title: "Scimitar of Deliverance", jsx: <><h2 id="magic-legacy-scimitar_of_deliverance-scimitar-of-deliverance">Scimitar of Deliverance</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 21</Link><br/><strong>Slot</strong> none; <strong>CL</strong> 6th; <strong>Weight</strong> 1 lb.<br/><strong>Aura</strong> moderate transmutation</p>
<p>The hilt of this +1 <Link to="/eq-material/adamantine">adamantine</Link> <Link to="/eq-weapon/scimitar">scimitar</Link> has a gritty texture, as if sprinkled with invisible grains of sand. A favorite weapon among the Templars of the Five Winds during their struggle against the genie binder Kinroth, in the hands of a mighty warrior this blade can cut through spell and shackle alike. After the Templars defeated the efreeti Jhavhul in 4300 AR, their <Link to="/monster/genie_djinni">djinni</Link> leader, Nefeshti, passed the blade to a group of worthy adventurers, though what happened to the blade afterward has been lost to history.</p>
<p>When the wielder of the scimitar of deliverance hits a target with a melee attack, as a free action she can attempt to identify any abjuration spells currently effecting the target as if she had studied it for 3 rounds using <Link to="/spell/detect_magic">detect magic</Link>.</p>
<p><strong>7th Level:</strong> The scimitar of deliverance acts as a +2 <Link to="/magic-enh/keen">keen</Link> adamantine scimitar.</p>
<p><strong>11th Level:</strong> As a full-round action, the wielder can flourish the scimitar of deliverance. All creatures within 60 feet who see the display can immediately attempt a new saving throw with a +4 morale bonus against any effect they are under that causes the confused, frightened, panicked, paralyzed, shaken, or staggered condition.</p>
<p><strong>15th Level:</strong> The scimitar of deliverance acts as a +4 keen adamantine scimitar.</p>
<p><strong>19th Level:</strong> Once per round when the wielder confirms a critical hit against a target with the scimitar of deliverance, the foe is targeted by a <Link to="/spell/greater_dispel_magic">greater dispel magic</Link> spell, with a caster level equal to the wielder's character level.</p>
<p><strong className="hl">Goal:</strong> The bearer must free at least 50 creatures from captivity, slavery, or unlawful imprisonment.</p>
<p><strong className="hl">Reward:</strong> As an immediate action a number of times per day equal to his character level, the wielder can use <Link to="/spell/liberating_command">liberating command</Link> as a spell-like ability.</p>
</>};
const _totemic_figurine = {title: "Totemic Figurine", jsx: <><h2 id="magic-legacy-totemic_figurine-totemic-figurine">Totemic Figurine</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 22</Link><br/><strong>Slot</strong> none; <strong>CL</strong> 13th; <strong>Weight</strong> 2 lbs.<br/><strong>Aura</strong> strong transmutation</p>
<p>Unlike most <Link to="/magic-wondrous/figurines_of_wondrous_power">figurines of wondrous power</Link>, this amber statuette depicts three creatures rather than one a dire tiger, a mastodon, and a megaloceros locked in an eternal battle. This powerful totem was created by orc shamans for the warlord Belkzen to aid in his conquest of the dwarven stronghold of Koldukar. To this day, many orcs are fascinated with the strength and ferocity of the megafauna that roam the edges of the Hold of Belkzen. While orcs might seek the massive creatures as prey or train them as powerful allies in battle, the totemic figurine magically harnesses the power of these megafauna.</p>
<p>The totemic figurine follows all the normal rules for figurines of wondrous power. When animated, the totemic figurine turns into a <Link to="/monster/megaloceros">megaloceros</Link> that understands Common and is under the command of the figurine's bearer. The totemic figurine can be used up to 3 times per week for up to 1 hour with each use. Should the creature be slain while it is animated, it reverts to the form of a statuette and cannot be activated for 1 week.</p>
<p><strong>7th Level:</strong> The bearer gains the <Link to="/ability/wild_empathy">wild empathy</Link> class feature as a druid of her character level, but the ability is effective only with dinosaurs, dire tigers, mastodons, and other megafauna.</p>
<p><strong>11th Level:</strong> The totemic figurine can instead take the form of a <Link to="/monster/dire_tiger">dire tiger</Link>.</p>
<p><strong>15th Level:</strong> The totemic figurine can instead take the form of a <Link to="/monster/mastodon">mastodon</Link>.</p>
<p><strong className="hl">Goal:</strong> The bearer must successfully rear a dinosaur, dire tiger, mastodon, or other megafauna from infancy using the Handle Animal skill.</p>
<p><strong className="hl">Reward:</strong> Dinosaurs, dire tigers, mastodons, and other megafauna will not willingly attack the bearer unless they are magically compelled to do so or the bearer attacks them first. In addition, the bearer can spend one use to cause the totemic figurine to take the form of two different creatures at once.</p>
</>};
const _trailblazers_boots = {title: "Trailblazer's Boots", jsx: <><h2 id="magic-legacy-trailblazers_boots-trailblazers-boots">Trailblazer's Boots</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 22</Link><br/><strong>Slot</strong> feet; <strong>CL</strong> 11th; <strong>Weight</strong> 1 lb.<br/><strong>Aura</strong> moderate transmutation</p>
<p>Worn by the Tian-Min explorer Amatatsu Aganhei on his treks across the Crown of the World, these utilitarian leather boots remain comfortable on even the longest journeys. Decorated with only a faint tracery of Minkaian designs, there is little to indicate the many leagues these boots have traveled.</p>
<p>The wearer of the trailblazer's boots is immune to fatigue caused by hustling or forced marches (though he still takes nonlethal damage as usual). Whenever he successfully uses the Survival skill to get along in the wild, he treats his result as 4 higher for the purpose of determining how many additional people he can provide for.</p>
<p><strong>4th Level:</strong> The wearer gains a +10-foot enhancement bonus to his base speed.</p>
<p><strong>8th Level:</strong> The wearer gains <Link to="/ability/woodland_stride">woodland stride</Link>, as the druid class ability.</p>
<p><strong>12th Level:</strong> The wearer is constantly under the effect of <Link to="/spell/endure_elements">endure elements</Link> and is automatically considered <Link to="/rule/mountain_travel">acclimated to high altitudes</Link>. Should the <em>endure elements</em> effect be dispelled, he can resume it as a free action.</p>
<p><strong>16th Level:</strong> Once per day, the wearer can use <Link to="/spell/find_the_path">find the path</Link> as a spell-like ability.</p>
<p><strong className="hl">Goal:</strong> The wearer must travel 1,000 miles by foot.</p>
<p><strong className="hl">Reward:</strong> Each morning the wearer can designate one type of terrain from the <Link to="/class/ranger">ranger's</Link> list of <Link to="/ability/favored_terrain">favored terrain</Link> as his favored terrain for the day. While in that terrain, he gains a bonus on initiative checks and Knowledge (geography), Perception, Stealth, and Survival checks. If he already has the favored terrain class feature for the chosen type of terrain, he instead increases his favored terrain bonuses for that terrain by 2.</p>
</>};
const _unyielding_aegis = {title: "Unyielding Aegis", jsx: <><h2 id="magic-legacy-unyielding_aegis-unyielding-aegis">Unyielding Aegis</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 22</Link><br/><strong>Slot</strong> shield; <strong>CL</strong> 10th; <strong>Weight</strong> 10 lbs.<br/><strong>Aura</strong> moderate abjuration</p>
<p>This shield is made from a thick glass that is as sturdy as steel. The shield functions as a +1 <Link to="/eq-armor/heavy_steel_shield">heavy steel shield</Link>. The former First Captain of the <Link to="/rule/risen_guard">Risen Guard</Link> known as the Spearwoman of Sothis originally crafted the shield using glass from the nearby deserts. Legends claim that she originally perished attempting to hold off an uprising in Sothis, but her shield continued to defend innocents, animated by some unknown force. The Spearwoman reclaimed the shield after her resurrection and has since gifted the unyielding aegis to the Risen Guard who loan it to members about to embark on particularly dangerous tasks.</p>
<p>As an immediate action, the wielder of the unyielding aegis can raise the shield to intercept an attack targeting her or an ally within reach. The shield reduces the damage from the attack by 5, as if the target had DR 5/-. This does not damage the shield in any way.</p>
<p><strong>3rd Level:</strong> The wielder gains a +2 bonus to Reflex saves.</p>
<p><strong>7th Level:</strong> The unyielding aegis acts as a +2 <Link to="/magic-enh/animated">animated</Link> heavy steel shield. The wielder can still activate the shield's intercepting ability, even while it is animated.</p>
<p><strong>11th Level:</strong> The unyielding aegis reduces damage from attacks by 10, as if the target had DR 10/-. In addition, the wielder's bonus to Reflex saves increases to +4.</p>
<p><strong>15th Level:</strong> The unyielding aegis acts as a +3 animated <Link to="/magic-enh/reflecting">reflecting</Link> heavy steel shield.</p>
<p><strong>19th Level:</strong> The unyielding aegis reduces damage from attacks by 15, as if the target had DR 15/-.</p>
<p><strong className="hl">Goal:</strong> The wielder must prevent a total of 1,000 points of damage with the unyielding aegis.</p>
<p><strong className="hl">Reward:</strong> The wielder can animate the unyielding aegis as if it had the animated special property for up to 1 minute at a time. While animated in this way, the wielder can command the shield to defend a creature within 30 feet as a swift action. The shield flies to that creature immediately, granting that creature the benefits of the shield as if it were wielding the shield. The original wielder of the shield can still spend her immediate action to use the shield to intercept attacks while the shield is defending a different creature.</p>
</>};
const _wayfinder_of_cooperation = {title: "Wayfinder of Cooperation", jsx: <><h2 id="magic-legacy-wayfinder_of_cooperation-wayfinder-of-cooperation">Wayfinder of Cooperation</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 23</Link><br/><strong>Slot</strong> none; <strong>CL</strong> 17th; <strong>Weight</strong> 1 lb.<br/><strong>Aura</strong> strong transmutation</p>
<p>Aspiring <Link to="/rule/pathfinder_society">Pathfinder Society</Link> field agents are often entertained by dramatic stories featuring Ling Yayao, a near-mythic Pathfinder renowned for her ability to perform daring rescues. Though several early Pathfinder Chronicles make mention of the Tian heroine galloping to the aid of imperiled Pathfinders on her horse, Fallow Grain, some jaded agents thought Ling Yayao entirely legendary until the discovery of her intact wayfinder of cooperation in the vaults below the Grand Lodge.</p>
<p>In addition to its ability to cast <Link to="/spell/light">light</Link>, as a typical <Link to="/magic-wondrous/wayfinder">wayfinder</Link>, the wayfinder of cooperation can be attuned to an <Link to="/magic-wondrous/ioun_stone">ioun stone</Link> as a standard action by touching the stone to the wayfinder's sturdy rosewood casing. Once the wayfinder of cooperation is attuned, the bearer of the wayfinder of cooperation can concentrate as a standard action to sense the direction of and distance to the attuned ioun stone. This bond functions across any distance, a long as the bearer and the stone are on the same plane. The wayfinder can be attuned to only one ioun stone at a time, and the bearer can dismiss the attunement at any time as a free action.</p>
<p><strong>6th Level:</strong> The bearer increases the bonus she grants from the aid another action by 1. This does not stack with the benefits of other feats or class features that improve the bonus she grants to an ally with aid another.</p>
<p><strong>8th Level:</strong> Once per day as a standard action, the bearer can use <Link to="/performance/inspire_competence">inspire competence</Link> as if she were a bard with a level equal to her character level. The bonuses granted by this ability last until the ally completes the task he is attempting.</p>
<p><strong>11th Level:</strong> The bearer is constantly aware of the position and condition (as <Link to="/spell/status">status</Link>) of anyone who has activated an ioun stone attuned to the wayfinder of cooperation.</p>
<p>The bearer can use <Link to="/spell/shadow_walk">shadow walk</Link> once per day as a spell-like ability.</p>
<p><strong>16th Level:</strong> Once per day, the bearer of an ioun stone attuned to the wayfinder of cooperation can summon the wayfinder's bearer to her side as if she were activating an appropriately keyed charm from a <Link to="/magic-wondrous/bracelet_of_friends">bracelet of friends</Link>.</p>
<p><strong className="hl">Goal:</strong> The bearer must successfully use the aid another action to increase an attack roll, a skill check, or a saving throw of at least 10 allies. To count toward this goal, the bearer's assistance must have made the difference between success and failure on the roll.</p>
<p><strong className="hl">Reward:</strong> The wayfinder of cooperation can be simultaneously attuned to a number of additional ioun stones equal to half the bearer's character level, rather than a single ioun stone.</p>
</>};
export default {bracers_of_antiquity:_bracers_of_antiquity,carved_kings_band:_carved_kings_band,conquerors_breastplate:_conquerors_breastplate,ring_of_sealed_souls:_ring_of_sealed_souls,scimitar_of_deliverance:_scimitar_of_deliverance,totemic_figurine:_totemic_figurine,trailblazers_boots:_trailblazers_boots,unyielding_aegis:_unyielding_aegis,wayfinder_of_cooperation:_wayfinder_of_cooperation}