import Link from '../../components/Link';
const _not_found = {title: "Unknown", jsx: <><h2 id="soctalent-not_found-unknown">Unknown</h2>
<p>Unable to find the requested vigilante social talent.</p>
</>};
const _always_prepared = {title: "Always Prepared", jsx: <><h2 id="soctalent-always_prepared-always-prepared-ex">Always Prepared (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 7</Link><br/>The vigilante can set aside resources to plan for future contingencies. The vigilante gains the <Link to="/feat/brilliant_planner">Brilliant Planner</Link> feat except he can spend up to 100 gp per character level for his brilliant plan fund and only requires 1 minute to enact his brilliant plan. In addition, while in a settlement for at least 1 week, he can spend 24 hours and up to 500 gp per character level to create a stash somewhere within the settlement. Once per day, the vigilante can take 1 hour to retrieve a stash, retrieving any number of items that would have been available in a settlement he visited at the time of making the stash, regardless of the weight of the items. Once he retrieves a stash in this way, he subtracts the price of the items from the stash's value and the stash is exhausted and lost, regardless if he used the full value of the stash. The vigilante can maintain any number of stashes, but a stash is lost if he does not spend 1 hour to maintain the stash at least once per month. A vigilante's stash is well-hidden and only the vigilante knows the location of a stash he creates.</p>
</>};
const _ancestral_enlightenment = {title: "Ancestral Enlightenment", jsx: <><h2 id="soctalent-ancestral_enlightenment-ancestral-enlightenment-ex">Ancestral Enlightenment (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 23</Link><br/>The vigilante can attempt any Knowledge check untrained. If he already has ranks in a particular Knowledge skill, he gains a +4 bonus on checks with that skill. A vigilante must be at least 5th level to select this talent.</p>
</>};
const _beginners_luck = {title: "Beginner's Luck", jsx: <><h2 id="soctalent-beginners_luck-beginners-luck-ex">Beginner's Luck (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/antiheros_handbook">Antihero's Handbook pg. 16</Link><br/>The vigilante appears so harmless and innocent that onlookers dismiss his incredible abilities as nothing more than beginner's luck. When the vigilante uses a vigilante talent while in his social identity, he can add the +20 circumstance bonus from seamless guise to his Disguise check to fool onlookers, so long as the number of onlookers witnessing him is no greater than his vigilante level. The vigilante's PC allies do not count as onlookers (and at the GM's discretion, a closely allied NPC might not count as an onlooker, either). He loses this bonus against onlookers who have already witnessed him using a vigilante talent in his social identity within the last week.</p>
</>};
const _bellflower_innuendo = {title: "Bellflower Innuendo", jsx: <><h2 id="soctalent-bellflower_innuendo-bellflower-innuendo-ex">Bellflower Innuendo (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 33</Link><br/>A vigilante with this talent has learned to pass secret messages more efficiently by observing the coded messages of the <Link to="/rule/bellflower_network">Bellflower Network</Link> or another secret organization. He can pass a secret message with Bluff in the same amount of time it would normally take to convey the message without encryption. The words and meaning of his secret messages cannot be gleaned from him or those he directly delivered the message to by divinations unless the caster succeeds at a caster level check (DC = 15 + the vigilante's level).</p>
</>};
const _case_the_joint = {title: "Case the Joint", jsx: <><h2 id="soctalent-case_the_joint-case-the-joint-ex">Case the Joint (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 10</Link><br/>The vigilante can use his social identity to learn important facts about a location before returning later in his vigilante identity. If he spends at least 1 hour in a location while in his social identity, he can attempt a DC 20 Knowledge (engineering) check. If he succeeds, he gains the ability to later reroll any one failed skill check involving the location's layout (such as a Stealth check to sneak into the location, a Disable Device check to disable an alarm, or a Sleight of Hand check to snatch an object from a pedestal). For every 10 by which the check exceeds 20, the vigilante gains an additional reroll. If the vigilante fails to return to the location within 1 week, the situation changes too much and he cannot use the rerolls. A vigilante can't case the same joint more than once a week.</p>
</>};
const _companion_to_the_lonely = {title: "Companion to the Lonely", jsx: <><h2 id="soctalent-companion_to_the_lonely-companion-to-the-lonely-ex">Companion to the Lonely (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 33</Link><br/>Whether religiously motivated, as are followers of <Link to="/faith/arshea">Arshea</Link>, <Link to="/faith/calistria">Calistria</Link>, or <Link to="/faith/shelyn">Shelyn</Link>, or for purely carnal reasons, physical intimacy helps the vigilante cope with the loneliness of his double life. Once per day, the vigilante can spend at least 1 hour engaged in acts of physical pleasure with a willing partner to gain a pool of morale points equal to his Charisma bonus or his partner's Charisma bonus, whichever is higher. For the next 24 hours, the vigilante can spend a morale point as an immediate action to roll a Charisma-based skill check or a Will saving throw again after rolling the die but before learning the consequences; he must take the second result even if it is lower.</p>
</>};
const _conflicted_identity = {title: "Conflicted Identity", jsx: <><h2 id="soctalent-conflicted_identity-conflicted-identity-ex">Conflicted Identity (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/antiheros_handbook">Antihero's Handbook pg. 16</Link><br/>The vigilante's mind is in a constant state of turmoil, which makes him even more ethically and morally fluid than other vigilantes. When targeted by a harmful spell or effect that would affect the vigilante in his current identity but not his other identity (or when he would suffer a lesser effect in his other identity), he has a 50% chance of being affected as though he were in his other identity. This chance is rolled when the spell or effect is cast or triggered and before any spell resistance roll, if applicable. For example, if a vigilante has a lawful-neutral social identity and a neutral vigilante identity, he has a 50% chance of taking only half damage from a <Link to="/spell/chaos_hammer">chaos hammer</Link> spell while in his social identity, since he would always take only half damage from a chaos hammer spell when in his vigilante identity.</p>
</>};
const _double_time = {title: "Double Time", jsx: <><h2 id="soctalent-double_time-double-time-ex">Double Time (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante's social identity is that of a skilled and respected artisan or professional, rather than a merchant or noble. In order to complete his day's work while still continuing his vigilante activities, he has learned to work faster than normal, hiding his progress so it seems like he is working full shifts at his day job rather than spending some of that time on other pursuits. The vigilante needs to spend only 6 hours each day for mundane uses of the Craft or Profession skill, rather than 8 hours. If he has the <Link to="/soctalent/social_grace">social grace</Link> social talent, he needs to spend only 4 hours for any skill he's chosen with social grace. A vigilante must have a social identity appropriate to the chosen skill to select this talent.</p>
</>};
const _in_vogue = {title: "In Vogue", jsx: <><h2 id="soctalent-in_vogue-in-vogue-ex">In Vogue (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante's crafting or professional business is always at the height of the local trends, allowing the vigilante to gain more profits than usual. Goods he crafts with a Craft skill he chose with social grace are worth 1/3 more gp than normal due to his celebrity, without increasing the cost to create. Whenever he uses a Profession skill he chose with social grace to make money, he makes twice as much money. A vigilante must be at least 5th level and have both the <Link to="/soctalent/double_time">double time</Link> and <Link to="/soctalent/social_grace">social grace</Link> social talents to take this talent.</p>
</>};
const _entrepreneur = {title: "Entrepreneur", jsx: <><h2 id="soctalent-entrepreneur-entrepreneur-ex">Entrepreneur (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 26</Link><br/>Select any one Intelligence-, Wisdom-, or Charisma-based skill other than Perception or Use Magic Device. The vigilante can use the selected skill to earn money as if he were using a Profession skill. If he selects Perform or Profession, the vigilante instead gains the skill unlock powers for those skills as appropriate for his number of ranks in that skill. If he has the <Link to="/soctalent/social_grace">social grace</Link> social talent, he can apply this benefit to all skills selected with the social grace talent.</p>
</>};
const _gossip_collector = {title: "Gossip Collector", jsx: <><h2 id="soctalent-gossip_collector-gossip-collector-ex">Gossip Collector (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante sits at the center of a web of gossip, granting him access to the latest scuttlebutt with baffling speed. Whenever the vigilante is presented with a topic about which he would normally need to spend 1d4 hours to gather information, he must spend only 1d2 hours instead. If he has the <Link to="/soctalent/renown">renown</Link> social talent and gathers the information in his area of renown, he must instead spend only 1d4 &times; 10 minutes, and if he beats the DC to gather a piece of information by 20 or more, he knows that piece of information without spending any time at all; he has simply already heard that gossip. This ability doesn't allow him to gather information that isn't available in the locale he is canvassing, even if that locale is his area of renown.</p>
</>};
const _guise_of_life = {title: "Guise of Life", jsx: <><h2 id="soctalent-guise_of_life-guise-of-life-su">Guise of Life (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 26</Link><br/>An undead vigilante with this talent gains an additional social identity in the form of one living creature identical to the vigilante's appearance in life. Successful Knowledge checks reveal information about the vigilante as if he were a living creature, and he counts as living for the purpose of divination spells and effects. He gains no other benefit from appearing to be a living creature, and remains vulnerable to positive energy and spells that effect undead. The vigilante must be a corporeal undead creature to select this talent. Humanoid vigilantes with the negative energy affinity racial trait can also select this talent, gaining a human social identity.</p>
</>};
const _guise_of_unlife = {title: "Guise of Unlife", jsx: <><h2 id="soctalent-guise_of_unlife-guise-of-unlife-su">Guise of Unlife (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 26</Link><br/>A vigilante with this talent gains an additional social identity in the form of an undead version of one of his existing social identities, such as a <Link to="/monster/ghoul">ghoul</Link>, <Link to="/template/vampire">vampire</Link>, or <Link to="/template/zombie">zombie</Link>. Successful Knowledge checks reveal information about the vigilante as if he were undead, and he counts as undead for the purpose of divination spells and effects. He gains no other benefit from appearing to be an undead creature, and remains vulnerable to negative energy and spells that effect the living. The vigilante must be a living creature to select this talent.</p>
</>};
const _hidden_magic = {title: "Hidden Magic", jsx: <><h2 id="soctalent-hidden_magic-hidden-magic-ex">Hidden Magic (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/antiheros_handbook">Antihero's Handbook pg. 16</Link><br/>The auras of magic items the vigilante is carrying are hidden (as per <Link to="/spell/magic_aura">magic aura</Link>). The vigilante can suppress or reactivate this effect as a standard action. At 11th level, the vigilante and any magic items he is carrying appear to be nonmagical (as if he had cast <Link to="/spell/greater_magic_aura">greater magic aura</Link>). The vigilante must be at least 5th level to select this talent.</p>
</>};
const _intrigue_feats = {title: "Intrigue Feats", jsx: <><h2 id="soctalent-intrigue_feats-intrigue-feats-ex">Intrigue Feats (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 2</Link><br/>The vigilante gains one of the following feats as a bonus feat: <Link to="/feat/blustering_bluff">Blustering Bluff</Link>, <Link to="/feat/but_a_scratch">But a Scratch</Link>, <Link to="/feat/call_truce">Call Truce</Link>, <Link to="/feat/confabulist">Confabulist</Link>, <Link to="/feat/criminal_reputation">Criminal Reputation</Link>, <Link to="/feat/cutting_humiliation">Cutting Humiliation</Link>, <Link to="/feat/esoteric_linguistics">Esoteric Linguistics</Link>, <Link to="/feat/intoxicating_flattery">Intoxicating Flattery</Link>, <Link to="/feat/ironclad_logic">Ironclad Logic</Link>, <Link to="/feat/nerve_racking_negotiator">Nerve-Racking Negotiator</Link>, <Link to="/feat/orator">Orator</Link>, <Link to="/feat/persuasive_bribery">Persuasive Bribery</Link>, <Link to="/feat/play_to_the_crowd">Play to the Crowd</Link>, <Link to="/feat/quick_favor">Quick Favor</Link>, <Link to="/feat/rhetorical_flourish">Rhetorical Flourish</Link>, <Link to="/feat/sense_assumptions">Sense Assumptions</Link>, <Link to="/feat/sense_relationships">Sense Relationships</Link>, or <Link to="/feat/street_smarts">Street Smarts</Link>. He must meet the feat's prerequisites. This talent can be selected multiple times; each time, the vigilante gains a new feat from the above list.</p>
</>};
const _kalistocrats_acumen = {title: "Kalistocrat's Acumen", jsx: <><h2 id="soctalent-kalistocrats_acumen-kalistocrats-acumen-ex">Kalistocrat's Acumen (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 33</Link><br/>A vigilante with this talent must follow the dietary and sexual prohibitions of <Link to="/eq-misc/the_prophecies_of_kalistrade">the Prophecies of Kalistrade</Link> in his social identity or he loses the talent's benefit until he atones. He can treat <Link to="/rule/the_settlement_stat_block">settlements</Link> as one size category larger when determining their base values and purchase limits. At 9th level, the vigilante can treat settlements as two size categories larger for the above purposes. At 15th level, the vigilante can treat settlements as four size categories larger for the above purposes.</p>
</>};
const _many_guises = {title: "Many Guises", jsx: <><h2 id="soctalent-many_guises-many-guises-ex">Many Guises (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante can take on any number of mundane guises. Whenever he changes his identity, he has a third option (instead of social or vigilante): he can become mundane. The mundane identity is not a specific individual. Each one is created at the moment it is assumed, and quickly forgotten as soon as it is removed. While in a mundane identity, the vigilante does not gain the benefit of either his social or vigilante identity, but instead appears as a member of his race, usually a common laborer, farmer, or peasant of any gender. His alignment is treated as neutral when he is in his mundane identity. While in this identity, he receives a +20 circumstance bonus on Disguise checks to appear like an ordinary member of his race. Spells and abilities that are looking for the vigilante in either of his other identities fail while he is in his mundane identity. He must build the appearance for this identity using whatever clothing and tools he has at his disposal. While he can use magic (such as a <Link to="/magic-wondrous/hat_of_disguise">hat of disguise</Link>), his mundane identity can never be anything other than an ordinary member of a society or large group (subject to GM discretion). A vigilante must be at least 5th level to select this talent.</p>
</>};
const _everyman = {title: "Everyman", jsx: <><h2 id="soctalent-everyman-everyman-ex">Everyman (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante can take on the appearance of a specific individual whenever he assumes a mundane guise using his many guises social talent. The individual must be a farmer, laborer, or peasant. While disguised as this individual, the vigilante receives a +20 circumstance bonus on Disguise checks to appear as that individual. Any spell or ability designed to locate the individual has a 50% chance of finding the vigilante instead of the actual individual, and divination spells and abilities used on the vigilante give results as if he were the actual individual. Although this doesn't grant the vigilante any special knowledge of the individual, the vigilante's training grants him a +10 circumstance bonus on Bluff checks to properly play the part of the individual. A vigilante must be at least 11th level and have the <Link to="/soctalent/many_guises">many guises</Link> social talent to select this talent.</p>
</>};
const _any_guise = {title: "Any Guise", jsx: <><h2 id="soctalent-any_guise-any-guise-su">Any Guise (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 10</Link><br/>A vigilante can use his everyman social talent to disguise himself as any specific person, even a king or high priest. Furthermore, if the actual individual wouldn't normally be able to be found via magic (such as by being dead or protected from divinations designed to locate the individual), such divinations always find the vigilante instead. A vigilante must be at least 17th level and have the <Link to="/soctalent/everyman">everyman</Link> social talent to select this talent.</p>
</>};
const _mockingbird = {title: "Mockingbird", jsx: <><h2 id="soctalent-mockingbird-mockingbird-ex">Mockingbird (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante can mimic almost any sort of voice, or even animal calls and sound effects, and he can throw his voice at a distance. This functions similarly to a combination of the <Link to="/spell/ghost_sound">ghost sound</Link>, <Link to="/spell/ventriloquism">ventriloquism</Link>, and <Link to="/spell/vocal_alteration">vocal alteration</Link> spells. A vigilante must be at least 5th level to choose this talent.</p>
</>};
const _morphic_mask = {title: "Morphic Mask", jsx: <><h2 id="soctalent-morphic_mask-morphic-mask-su">Morphic Mask (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 7</Link><br/>The vigilante's physical form in his vigilante identity can differ significantly from that of his social identity, within the norms for his race &mdash; this can include changes to the vigilante's proportions, coloration, gender characteristics, and other physical characteristics. This increases the vigilante's bonus from seamless guise by 2 for every significant change, as per the Disguise skill. The vigilante always assumes the same form when using this ability. A vigilante with multiple natural forms, such as a <Link to="/race/kitsune">kitsune</Link>, can alter each of his forms using this talent.</p>
</>};
const _notorious_fool = {title: "Notorious Fool", jsx: <><h2 id="soctalent-notorious_fool-notorious-fool-ex">Notorious Fool (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/antiheros_handbook">Antihero's Handbook pg. 16</Link><br/>While in his social identity, the vigilante can feign absentmindedness, clumsiness, drunkenness, or eccentricity very convincingly. When he fails an opposed Sleight of Hand or Stealth check while in his social identity, he can immediately attempt a Bluff check opposed by the onlookers' Sense Motive checks to appear as though he had only blundered or stumbled in a spectacular fashion. If he succeeds at this Bluff check, the onlookers do not realize the vigilante was attempting the action that prompted him to attempt a Sleight of Hand or Stealth check, although being in the wrong place or behaving in an inappropriate manner may still have negative consequences. This talent is ineffective against any onlooker who has already witnessed the vigilante faking a blunder within the last 24 hours.</p>
</>};
const _obscurity = {title: "Obscurity", jsx: <><h2 id="soctalent-obscurity-obscurity-ex">Obscurity (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 15</Link><br/>The vigilante is relatively unknown socially. In fact, he makes a point of keeping the life of his social identity as ordinary as possible. This social talent functions exactly as the renown social talent, but instead of improving the starting attitude of all NPCs within the community, it empowers the vigilante so that he no longer needs to succeed at Disguise checks to appear as his social identity while assuming that identity within his area of obscurity. He still has to attempt Disguise checks when NPCs within this settlement are confronted with indisputable proof that the vigilante could be more than he appears to be, such as when he uses a vigilante talent while in his social identity. This social talent counts as <Link to="/soctalent/renown">renown</Link> for the purpose of meeting the prerequisites of social talents that list renown as a prerequisite and can be improved by such talents. A vigilante with this talent cannot select renown, nor can he select any social talent that requires him to be famous (such as <Link to="/soctalent/celebrity_discount">celebrity discount</Link> or <Link to="/soctalent/celebrity_perks">celebrity perks</Link>).</p>
</>};
const _owls_sight = {title: "Owl's Sight", jsx: <><h2 id="soctalent-owls_sight-owls-sight-ex">Owl's Sight (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/heroes_of_golarion">Heroes of Golarion pg. 19</Link><br/>The vigilante gains low-light vision. If he already has low-light vision, he gains a +4 competence bonus on Perception checks in low light. The vigilante also gains a +2 competence bonus on Sleight of Hand and Stealth checks at night.</p>
</>};
const _quick_change = {title: "Quick Change", jsx: <><h2 id="soctalent-quick_change-quick-change-ex">Quick Change (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante learns to shift between his identities with ease. Instead of needing 1 minute to change his identity, he can now do so as a full-round action. If, after a quick change, he encounters any creature familiar with both of his identities, he must attempt a Disguise check to avoid the creature seeing through his hastily donned disguise and realizing that the identities are, in fact, the same person. The vigilante can spend 1 additional round adjusting and perfecting his appearance and persona to negate the need for this check. A vigilante must be at least 7th level to select this talent.</p>
</>};
const _immediate_change = {title: "Immediate Change", jsx: <><h2 id="soctalent-immediate_change-immediate-change-ex">Immediate Change (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante can change identities as a move action, and he no longer needs to spend extra time to adjust his appearance and persona. A vigilante must be at least 13th level and must have the <Link to="/soctalent/quick_change">quick change</Link> social talent to select this talent.</p>
</>};
const _renown = {title: "Renown", jsx: <><h2 id="soctalent-renown-renown-ex">Renown (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante becomes known for deeds and abilities regardless of his current identity. This renown grants him favorable treatment in civilized company and lends him an air of menace while facing down his enemies. While he is in his social identity, a vigilante can spend 1 week gaining renown among the locals of any community of no more than about 200 individuals (<Link to="/rule/the_shape_of_civilization">a village</Link>). This could be the entire community or a smaller neighborhood in a larger settlement. He must spend at least 4 hours each day socializing and making contacts. After spending 1 week doing this, whenever he is in his social identity, all NPCs in the community have a starting attitude toward him that is one category better, as long as each person's <Link to="/skill/attitude">initial attitude</Link> would have at least been indifferent. While he gains renown in an area using his social identity, he also spreads rumors and tales about his vigilante identity. Once he has gained renown in a community, he gains a +4 circumstance bonus on Intimidate checks whenever he is in his vigilante identity. This bonus applies only while he is near the community in which he has gained renown; he must be within a number of miles equal to his vigilante level.</p>
<p>A vigilante can hold renown in a limited number of communities (normally one, with other social talents allowing two). If he gains renown in a new community, he must decide which one of his previous communities to lose. These effects are subject to GM approval. For example, the GM might rule that an NPC or monster has not heard any tales about the vigilante. Or, a foe may have a starting attitude toward him that's one category worse, rather than one category better.</p>
</>};
const _celebrity_discount = {title: "Celebrity Discount", jsx: <><h2 id="soctalent-celebrity_discount-celebrity-discount-ex">Celebrity Discount (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 10</Link><br/>The vigilante's social identity is popular enough to receive discounts in his area of renown. Whenever he buys an item in his area of renown that costs 500 gp or less, he can buy it at 90% of the market price, rather than the full price. If he has the <Link to="/soctalent/great_renown">great renown</Link> social talent, the gp limit increases to 2,000 gp, and if he possesses the <Link to="/soctalent/incredible_renown">incredible renown</Link> social talent, the gp limit increases to 8,000 gp. A vigilante must be at least 3rd level and have the <Link to="/soctalent/renown">renown</Link> social talent to select this talent.</p>
</>};
const _celebrity_perks = {title: "Celebrity Perks", jsx: <><h2 id="soctalent-celebrity_perks-celebrity-perks-ex">Celebrity Perks (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante is a celebrity in his area of renown, and adoring fans are all too eager to shower him with the fundamental necessities. While within his area of renown, he can always receive common meals or lodging (worth up to 1 gp per meal or night) for free, and can avoid paying taxes or bribes of 1 gp or less. If he wants a particular nonmagical item worth 1 gp or less, he can spend 1d10 minutes interacting with people in his area of renown to receive the item from a fan (if he ever sells such a gift from a fan, he loses this social talent permanently). If he has the <Link to="/soctalent/great_renown">great renown</Link> social talent, he can receive gifts of up to 5 gp, receive fine food and lodgings (worth up to 10 gp per meal or night) for free, and avoid paying taxes or bribes of 10 gp or less. If he has <Link to="/soctalent/incredible_renown">incredible renown</Link>, he can receive gifts of up to 25 gp, receive exquisite food and lodgings (worth up to 100 gp per meal or night) for free, and avoid paying taxes or bribes of 100 gp or less. A vigilante must be at least 5th level and have the <Link to="/soctalent/renown">renown</Link> social talent to select this talent.</p>
</>};
const _discreet_inquiries = {title: "Discreet Inquiries", jsx: <><h2 id="soctalent-discreet_inquiries-discreet-inquiries-ex">Discreet Inquiries (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 33</Link><br/>The vigilante can attempt Diplomacy checks to gather information without being obvious he is seeking any, whether by buying the silence of informants or by talking foes into revealing information without realizing they are doing so. While the vigilante is in his area of <Link to="/soctalent/renown">renown</Link>, gathering information in this way takes 2d4 hours and costs 2d4 gp. Anyone who might take notice of the information gathering does not notice unless she succeeds at a Sense Motive check opposed by the vigilante's Bluff check. The vigilante gains a +4 bonus on this Bluff check.</p>
</>};
const _feign_innocence = {title: "Feign Innocence", jsx: <><h2 id="soctalent-feign_innocence-feign-innocence-ex">Feign Innocence (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante's social identity seems so innocent that it is hard to believe he was involved in wrongdoing. Within his area of renown, this provides a nonmagical effect identical to the <Link to="/spell/innocence">innocence</Link> spell. A vigilante must be at least 5th level and have the <Link to="/soctalent/renown">renown</Link> social talent to take this talent.</p>
</>};
const _subjective_truth = {title: "Subjective Truth", jsx: <><h2 id="soctalent-subjective_truth-subjective-truth-ex">Subjective Truth (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante's disparate identities allow him to defeat magic that detects lies. As long as what he says is true from the point of view of his current identity, it detects as true to effects such as discern lies, and he can say it in effects such as <Link to="/spell/zone_of_truth">zone of truth</Link> that force him to speak the truth. A vigilante must be at least 9th level and have the <Link to="/soctalent/feign_innocence">feign innocence</Link> social talent to select this talent.</p>
</>};
const _great_renown = {title: "Great Renown", jsx: <><h2 id="soctalent-great_renown-great-renown-ex">Great Renown (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante is known on a broader scale. He can gain renown in a single community of up to 5,000 individuals (a large town) or up to two communities of no more than 2,000 individuals each (two small towns). The bonus while he is in his social identity remains unchanged, but the circumstance bonus on Intimidate checks from his renown social talent while he is in his vigilante identity increases to +6. A vigilante must be at least 7th level and have the <Link to="/soctalent/renown">renown</Link> social talent to select this talent.</p>
</>};
const _incredible_renown = {title: "Incredible Renown", jsx: <><h2 id="soctalent-incredible_renown-incredible-renown-ex">Incredible Renown (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante is incredibly famous in both identities. He can gain renown in a single community of up to 25,000 individuals (a large city) or up to two smaller cities of no more than 10,000 individuals each (two small cities). The bonus while he is in his social identity remains unchanged, but the circumstance bonus to Intimidate from his great renown social talent while in he is in his vigilante identity increases to +8. A vigilante must be at least 11th level and have the <Link to="/soctalent/great_renown">great renown</Link> social talent to select this talent.</p>
</>};
const _instant_recognition = {title: "Instant Recognition", jsx: <><h2 id="soctalent-instant_recognition-instant-recognition-ex">Instant Recognition (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante is so well known that his name precedes him, even to other communities. It only takes 4 hours of effort to get the word out to transfer his renown benefits to a new community. A vigilante must be at least 13th level and have both the <Link to="/soctalent/incredible_renown">incredible renown</Link> and <Link to="/soctalent/triumphant_return">triumphant return</Link> social talents to select this talent.</p>
</>};
const _loyal_aid = {title: "Loyal Aid", jsx: <><h2 id="soctalent-loyal_aid-loyal-aid-ex">Loyal Aid (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante gains the service of a number of loyal allies who can help him gather information, cover for his two identities, or perform minor tasks. Inside his area of renown, a vigilante with this talent gains a bonus on Diplomacy checks to gather information equal to half his vigilante level.</p>
<p>In addition, if the vigilante wants, he can task his friends to help cover for him by spreading false tales of his location and activities to others. This has the effect of increasing the DC of Diplomacy checks to gather information about the vigilante and Survival checks to track him by an amount equal to his level. This lasts for 1 day, and can be used only once per week.</p>
<p>Finally, once per day, the vigilante can ask his allies to perform a minor task for him. This usually involves delivering a message, purchasing a piece of mundane gear worth 100 gp or less (which the vigilante must pay for), or retrieving an object owned by the vigilante (that would be easily accessible by the ally). This task might take other forms as well, subject to GM discretion, but can never involve combat or danger. A vigilante must be at least 3rd level and have the <Link to="/soctalent/renown">renown</Link> social talent to select this talent.</p>
</>};
const _triumphant_return = {title: "Triumphant Return", jsx: <><h2 id="soctalent-triumphant_return-triumphant-return-ex">Triumphant Return (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante's tales are never truly forgotten. This makes it easier to establish his renown in a place he has established it before. In any settlement where the vigilante previously gained renown, it takes only 3 days, rather than 1 week, to gain renown again. A vigilante must be at least 3rd level and have the <Link to="/soctalent/renown">renown</Link> social talent to select this talent.</p>
</>};
const _safe_house = {title: "Safe House", jsx: <><h2 id="soctalent-safe_house-safe-house-ex">Safe House (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante can establish a safe house in his area of renown, and he can change it every time he changes his area of renown. If he doesn't have the <Link to="/soctalent/renown">renown</Link> talent, he can still select this talent and place the safe house in a single location to which he has access, but he can never move the safe house from its initial location until he gains the renown talent. This safe house must be an area no larger in volume than a cube that is a number of feet per side equal to 10 feet per vigilante level. The safe house can be arranged any way he likes and it can be part of a larger building, like a secret room or an underground cave. Objects within this safe house can't be located by any effect that is less powerful than a <Link to="/spell/discern_location">discern location</Link> spell. At 7th level, this protection from being located also applies to creatures in the safe house. At 13th level, the entire area is protected from scrying effects (though not mundane snooping) like a <Link to="/spell/mages_private_sanctum">mage's private sanctum</Link>.</p>
</>};
const _seemless_shapechanger = {title: "Seemless Shapechanger", jsx: <><h2 id="soctalent-seemless_shapechanger-seemless-shapechanger-ex">Seemless Shapechanger (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 15</Link><br/>The vigilante seamlessly adopts any persona he assumes with magic. The vigilante adds his seamless guise bonus to the bonus on Disguise checks that he gains to assume the shape of another creature with a polymorph spell or effect. A vigilante must have the shapechanger subtype to select this talent.</p>
</>};
const _skill_familiarity = {title: "Skill Familiarity", jsx: <><h2 id="soctalent-skill_familiarity-skill-familiarity-ex">Skill Familiarity (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 23</Link><br/>The vigilante choses four skills when he gains this talent. He can take 10 on checks with his chosen skills even when distracted or threatened. If he takes 10 on checks with these skills while not distracted or threatened, he gains a bonus on the check equal to one-quarter his vigilante level (minimum +2). A vigilante must be at least 9th level to select this talent.</p>
</>};
const _social_grace = {title: "Social Grace", jsx: <><h2 id="soctalent-social_grace-social-grace-ex">Social Grace (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_intrigue">Ultimate Intrigue pg. 1</Link><br/>The vigilante selects any one Intelligence-, Wisdom-, or Charisma-based skill other than Perception or Use Magic Device. Whenever the vigilante is in his social identity, he receives a +4 circumstance bonus on checks with the selected skill. At 5th level and every 4 levels thereafter, he can select another skill (with the same restrictions) to gain this bonus.</p>
</>};
const _songbird = {title: "Songbird", jsx: <><h2 id="soctalent-songbird-songbird-su">Songbird (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/heroes_of_golarion">Heroes of Golarion pg. 19</Link><br/>The vigilante gains the use of <Link to="/spell/animal_messenger">animal messenger</Link> once per day as a spell-like ability, with a caster level equal to his character level. He also gains <Link to="/skill/handle_animal">Handle Animal</Link> as a class skill.</p>
</>};
const _beast_friend = {title: "Beast Friend", jsx: <><h2 id="soctalent-beast_friend-beast-friend-su">Beast Friend (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/heroes_of_golarion">Heroes of Golarion pg. 19</Link><br/>The vigilante can cast <Link to="/spell/charm_animal">charm animal</Link> once per day as a spell-like ability, with a caster level equal to his level. The vigilante must have the <Link to="/soctalent/songbird">songbird</Link> talent to select this talent.</p>
</>};
const _beast_speech = {title: "Beast Speech", jsx: <><h2 id="soctalent-beast_speech-beast-speech-su">Beast Speech (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/heroes_of_golarion">Heroes of Golarion pg. 19</Link><br/>The vigilante can cast <Link to="/spell/speak_with_animals">speak with animals</Link> once per day as a spell-like ability, with a caster level equal to his character level. The vigilante must have the <Link to="/soctalent/songbird">songbird</Link> talent to select this talent.</p>
</>};
const _transformation_sequence = {title: "Transformation Sequence", jsx: <><h2 id="soctalent-transformation_sequence-transformation-sequence-su">Transformation Sequence (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 15</Link><br/>The vigilante's transformation between identities is assisted by magic. This makes it faster than usual, but also more noticeable. The vigilante can complete the switch between his identities in 5 rounds, improving to a standard action if he has the <Link to="/soctalent/quick_change">quick change</Link> social talent, and to a swift action if he has the immediate change social talent. However, the transformation causes quite a spectacle, involving loud sounds or music, brilliant colorful energies, and swift motions. A vigilante can select this talent only if he is able to cast spells or spell-like abilities (this needn't be from his vigilante class). A vigilante with the <Link to="/arc-vigilante/magical_child">magical child</Link> archetype effectively gets this social talent for free at 1st level.</p>
</>};
const _well_known_expert = {title: "Well-Known Expert", jsx: <><h2 id="soctalent-well_known_expert-well-known-expert-ex">Well-Known Expert (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 2</Link><br/>The vigilante's social identity is known as an expert in numerous fields, including areas and topics the vigilante hasn't actually taken the time to study. As a result the vigilante is skilled at encouraging others to discover solutions to difficult problems themselves by asking probing questions, while appearing to give the information himself.</p>
<p>In his social identity, the vigilante can take 10 when attempting to <Link to="/rule/aid_another">aid another</Link> on Appraise, Craft, and Knowledge checks. He also gains a bonus equal to half his class level (minimum +1) on Bluff checks to appear knowledgeable in Appraise, Craft (all), and Knowledge (all). If he has the renown social talent, he grants a +3 bonus when he successfully aids another on these skill checks, rather than +2.</p>
<p>In his area of renown, the vigilante's social identity is so trusted as an expert that scholars are inspired to make amazing deductions and intuitive leaps in discussions with him. A creature that has already failed a Knowledge check on a specific subject can attempt one additional check to gain information on the same topic if it receives an aid another bonus from the vigilante when doing so.</p>
</>};
export default {not_found:_not_found,always_prepared:_always_prepared,ancestral_enlightenment:_ancestral_enlightenment,beginners_luck:_beginners_luck,bellflower_innuendo:_bellflower_innuendo,case_the_joint:_case_the_joint,companion_to_the_lonely:_companion_to_the_lonely,conflicted_identity:_conflicted_identity,double_time:_double_time,in_vogue:_in_vogue,entrepreneur:_entrepreneur,gossip_collector:_gossip_collector,guise_of_life:_guise_of_life,guise_of_unlife:_guise_of_unlife,hidden_magic:_hidden_magic,intrigue_feats:_intrigue_feats,kalistocrats_acumen:_kalistocrats_acumen,many_guises:_many_guises,everyman:_everyman,any_guise:_any_guise,mockingbird:_mockingbird,morphic_mask:_morphic_mask,notorious_fool:_notorious_fool,obscurity:_obscurity,owls_sight:_owls_sight,quick_change:_quick_change,immediate_change:_immediate_change,renown:_renown,celebrity_discount:_celebrity_discount,celebrity_perks:_celebrity_perks,discreet_inquiries:_discreet_inquiries,feign_innocence:_feign_innocence,subjective_truth:_subjective_truth,great_renown:_great_renown,incredible_renown:_incredible_renown,instant_recognition:_instant_recognition,loyal_aid:_loyal_aid,triumphant_return:_triumphant_return,safe_house:_safe_house,seemless_shapechanger:_seemless_shapechanger,skill_familiarity:_skill_familiarity,social_grace:_social_grace,songbird:_songbird,beast_friend:_beast_friend,beast_speech:_beast_speech,transformation_sequence:_transformation_sequence,well_known_expert:_well_known_expert}