import Link from '../../components/Link';
const _not_found = {title: "Unknown", jsx: <><h2 id="invtalent-not_found-unknown">Unknown</h2>
<p>Unable to find the requested investigator talent.</p>
</>};
const _blinding_strike = {title: "Blinding Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-blinding_strike-blinding-strike-ex">Blinding Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator deals damage with studied strike, the opponent must succeed at a Fortitude saving throw or be permanently <Link to="/misc/blinded">blinded</Link>. A successful saving throw reduces this to <Link to="/misc/dazzled">dazzled</Link> for 1d4 rounds. The DC for this Fortitude save is equal to 10 + 1/2 the investigator's level + his Intelligence modifier. This talent has no effect on creatures that do not rely on eyes for sight or creatures with more than two eyes (although multiple critical hits might cause blindness, at the GM's discretion). Blindness can be cured by <Link to="/spell/heal">heal</Link>, <Link to="/umr/regeneration">regeneration</Link>, <Link to="/spell/remove_blindness">remove blindness</Link>, or similar abilities. An investigator must be at least 17th level to select this talent.</p>
</>};
const _confusing_strike = {title: "Confusing Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-confusing_strike-confusing-strike-ex">Confusing Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator deals damage with studied strike, the opponent must succeed at a Fortitude saving throw or become <Link to="/misc/confused">confused</Link> for 1d4+1 rounds. A successful saving throw reduces the duration to 1 round. The DC for this Fortitude save is equal to 10 + 1/2 the investigator's level + his Intelligence modifier. Constructs, mindless creatures, oozes, plants, undead, incorporeal creatures, and creatures immune to critical hits are not affected by this ability. An investigator must be at least 19th level to select this talent.</p>
</>};
const _deafening_strike = {title: "Deafening Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-deafening_strike-deafening-strike-ex">Deafening Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When an investigator deals damage with studied strike, the opponent must succeed at a Fortitude saving throw or be permanently <Link to="/misc/deafened">deafened</Link>. A successful Fortitude saving throw reduces the duration of this effect to 1 round. The DC for this save is equal to 10 + 1/2 the investigator's level + his Intelligence modifier. This talent has no effect on deaf creatures. Deafness can be cured by <Link to="/spell/heal">heal</Link>, <Link to="/umr/regeneration">regeneration</Link>, <Link to="/spell/remove_blindness">remove blindness</Link>, or similar effects. An investigator must be at least 15th level to select this talent.</p>
</>};
const _domino_effect = {title: "Domino Effect", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-domino_effect-domino-effect-ex">Domino Effect (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_origins">Advanced Class Origins pg. 15</Link><br/>When the investigator uses studied strike, he uses his opponents against each other and sets himself up for his next move. Whenever he successfully deals damage to an opponent with studied strike, as a free action the investigator can apply the effects of studied combat to an opponent adjacent to the first. An investigator must be at least 5th level to select this talent.</p>
</>};
const _iconclastic_strike = {title: "Iconclastic Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-iconclastic_strike-iconclastic-strike-ex">Iconclastic Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 31</Link><br/>When the investigator deals damage with a studied strike, she can perform a <Link to="/rule/sunder">sunder</Link> combat maneuver as a free action against the creature the studied strike damaged. If the object targeted is a holy symbol or divine scroll, this sunder does not provoke attacks of opportunity and deals maximum damage on a successful check. An investigator must be at least 13th level to select this talent.</p>
</>};
const _numerical_strike = {title: "Numerical Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-numerical_strike-numerical-strike-ex">Numerical Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 17</Link><br/>Once per day when the investigator has confirmed a critical hit with a studied strike, he can deal average damage instead of rolling damage as normal. This includes the damage dealt by the successful attack as well as the additional damage from the studied strike. He can expend a use of inspiration to use this ability a second time per day. Using this ability doesn't require an action. The investigator must be at least 5th level to select this talent.</p>
</>};
const _greater_numerical_strike = {title: "Greater Numerical Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-greater_numerical_strike-greater-numerical-strike-ex">Greater Numerical Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 17</Link><br/>Once per day, when the investigator has confirmed a critical hit with a studied strike, he can deal the strike's maximum damage instead of rolling damage as normal. This includes the damage dealt by the successful attack as well as the additional damage from the studied strike. He can expend a use of inspiration to use this ability a second time per day. Using this ability doesn't require an action. The investigator must have the <Link to="/invtalent/numerical_strike">numerical strike</Link> talent and be at least 13th level to select this talent.</p>
</>};
const _masterful_numerical_strike = {title: "Masterful Numerical Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-masterful_numerical_strike-masterful-numerical-strike-ex">Masterful Numerical Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 17</Link><br/>The investigator can use both numerical strike and greater numerical strike three times per day. The investigator doesn't need to expend uses of inspiration to use either ability, but he can never use either more than three times per day each. The investigator must have the <Link to="/invtalent/numerical_strike">numerical strike</Link> and <Link to="/invtalent/greater_numerical_strike">greater numerical strike</Link> talents and be at least 17th level to select this talent.</p>
</>};
const _prolonged_study = {title: "Prolonged Study", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-prolonged_study-prolonged-study-ex">Prolonged Study (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_origins">Advanced Class Origins pg. 15</Link><br/>The investigator can study his opponents for long periods of time. The effects of his studied combat ability last for a number of rounds equal to twice his Intelligence modifier (minimum 2) or until he deals damage with a studied strike, whichever comes first. The investigator must be at least 13th level to select this talent.</p>
</>};
const _repositioning_strike = {title: "Repositioning Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-repositioning_strike-repositioning-strike-ex">Repositioning Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator deals damage with studied strike, he can perform a <Link to="/rule/reposition">reposition</Link> combat maneuver as a free action against the creature damaged by studied strike. This reposition does not provoke attacks of opportunity. An investigator must be at least 13th level to select this talent.</p>
</>};
const _sapping_offensive = {title: "Sapping Offensive", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-sapping_offensive-sapping-offensive-ex">Sapping Offensive (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator damages a studied target, that creature cannot make attacks of opportunity for 1 round. An investigator must be at least 5th level to select this talent.</p>
</>};
const _sickening_offensive = {title: "Sickening Offensive", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-sickening_offensive-sickening-offensive-ex">Sickening Offensive (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator damages a studied target, that creature is also <Link to="/misc/sickened">sickened</Link> for 1 round. An investigator must be at least 7th level to select this talent.</p>
</>};
const _silencing_strike = {title: "Silencing Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-silencing_strike-silencing-strike-ex">Silencing Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 31</Link><br/>When the investigator deals damage with a studied strike, the target must succeed at a Fortitude save (DC = 10 + 1/2 the investigator's class level + her Intelligence modifier) or be unable to speak (even for verbal components) for 1d4+1 rounds. A successful save reduces the duration to 1 round. This talent has no effect on creatures immune to critical hits. An investigator must be at least 15th level to select this talent.</p>
</>};
const _slowing_strike = {title: "Slowing Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-slowing_strike-slowing-strike-ex">Slowing Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_origins">Advanced Class Origins pg. 15</Link><br/>When the investigator deals damage with studied strike, the opponent must succeed at a Fortitude save (DC = 10 + 1/2 the investigator's class level + his Intelligence modifier) or be slowed by the crippling blow. A slowed opponent's movement speeds are each reduced by 5 feet (to a minimum of 5 feet) until the creature is healed through the application of any spell that cures hit point damage or with a successful DC 15 Heal check. Multiple slowing strikes stack, to a minimum of 5 feet. An investigator must be at least 7th level to select this talent.</p>
</>};
const _stealing_strike = {title: "Stealing Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-stealing_strike-stealing-strike-ex">Stealing Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator deals damage with studied strike, he can perform a <Link to="/rule/steal">steal</Link> combat maneuver as a free action against the creature damaged by studied strike. This steal does not provoke attacks of opportunity. An investigator must be at least 13th level to select this talent.</p>
</>};
const _timed_strike = {title: "Timed Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-timed_strike-timed-strike-ex">Timed Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_origins">Advanced Class Origins pg. 15</Link><br/>The longer the investigator studies his opponent, the greater the damage he ultimately deals with his studied strike. When the investigator makes a studied strike, he deal a number of points of additional damage equal to the number of consecutive rounds he studied the target with studied combat.</p>
</>};
const _toppling_strike = {title: "Toppling Strike", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-toppling_strike-toppling-strike-ex">Toppling Strike (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator deals damage with studied strike, he can perform a <Link to="/rule/trip">trip</Link> combat maneuver as a free action against the creature damaged by studied strike. This trip does not provoke attacks of opportunity. An investigator must be at least 9th level to select this talent.</p>
</>};
const _twilight_talon_improvisation = {title: "Twilight Talon Improvisation", addenda: ["studiedstrike"], jsx: <><h2 id="invtalent-twilight_talon_improvisation-twilight-talon-improvisation-ex">Twilight Talon Improvisation (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 31</Link><br/>Whenever the investigator deals studied strike damage with an <Link to="/misc/improvised_weapon">improvised weapon</Link>, she can perform a <Link to="/rule/dirty_trick">dirty trick</Link> combat maneuver targeting that foe as a free action. This combat maneuver provokes attacks of opportunity as normal unless the investigator has a feat or other ability to prevent it.</p>
</>};
const _didactic_strike = {title: "Didactic Strike", jsx: <><h2 id="invtalent-didactic_strike-didactic-strike">Didactic Strike</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_guide">Adventurer's Guide pg. 147</Link><br/>When the investigator activates his studied strike, he can end his studied combat and choose not to deal his studied strike damage. He is instead able to show any allies within 30 feet who can see him a weak spot on the target. Until the beginning of the investigator's next turn, each affected ally's first attack that hits the target deals additional damage equal to one-third the investigator's level. He can end this effect as an immediate action to instead cause an affected ally's first successful attack to deal the investigator's studied strike damage. This additional damage is <Link to="/misc/precision_damage">precision damage</Link> and does not affect creatures that are immune to sneak attacks.</p>
</>};
const _quick_study = {title: "Quick Study", jsx: <><h2 id="invtalent-quick_study-quick-study-ex">Quick Study (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator can use his studied combat ability as swift action instead of a move action.</p>
</>};
const _studied_defense = {title: "Studied Defense", jsx: <><h2 id="invtalent-studied_defense-studied-defense-ex">Studied Defense (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When an investigator with this talent uses his studied combat ability, he can chose to apply that ability's insight bonus to his AC against attacks made by the target of his studied combat instead of to attack rolls against the target of his studied combat. (The insight bonus on damage rolls remains.) He must choose which type of bonus he gains when using studied combat, and it cannot be changed until he uses studied combat again. An investigator must be at least 9th level to select this talent.</p>
</>};
const _amazing_inspiration = {title: "Amazing Inspiration", jsx: <><h2 id="invtalent-amazing_inspiration-amazing-inspiration-ex">Amazing Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When using inspiration, the investigator rolls a d8 instead of a d6. At 20th level, the investigator rolls 2d8 and adds both dice to the result. An investigator must be at least 7th level to select this talent.</p>
</>};
const _applied_engineering = {title: "Applied Engineering", jsx: <><h2 id="invtalent-applied_engineering-applied-engineering-ex">Applied Engineering (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_origins">Advanced Class Origins pg. 15</Link><br/>The investigator can leverage his knowledge of engineering to solve tasks that normally require brute strength or keen eyes. He can expend one use of inspiration as a full-round action to study an object or area and attempt a Knowledge (engineering) check. On his next turn, he can use the result of that Knowledge (engineering) check in place of a Strength check to break the object or in place of a Perception check to locate hidden doors or compartments in that area.</p>
</>};
const _atheist_inspiration = {title: "Atheist Inspiration", jsx: <><h2 id="invtalent-atheist_inspiration-atheist-inspiration-ex">Atheist Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 31</Link><br/>The investigator can use her inspiration on saving throws against divine spells without expending uses of inspiration. This talent counts as the <Link to="/feat/divine_defiance">Divine Defiance</Link> feat for the purpose of meeting the prerequisites of other feats.</p>
</>};
const _chroniclers_insight = {title: "Chronicler's Insight", jsx: <><h2 id="invtalent-chroniclers_insight-chroniclers-insight-ex">Chronicler's Insight (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_guide">Adventurer's Guide pg. 146</Link><br/>The investigator can peruse a <Link to="/eq-misc/pathfinder_chronicle">Pathfinder Chronicle</Link> as a standard action, applying its benefits as though he had studied it for the full 1d4 rounds. Upon studying a Pathfinder Chronicle, the investigator can expend one use of inspiration to apply the volume's benefits for a number of hours equal to his Intelligence modifier and gain an additional benefit based on the volume's associated Knowledge skill during that time. The investigator can have only one such ongoing benefit at a time, and activating a new benefit ends the first one.</p>
<blockquote>
<p><strong>Arcana, Nature, Planes, or Religion:</strong> When performing a studied strike, the investigator's attack overcomes damage reduction as if it were a weapon with the following property based on the associated Knowledge check: adamantine (arcana), chaotic (planes), cold iron (nature), evil (planes), good (planes), lawful (planes), silver (religion). He also gains a +1 insight bonus on saving throws against creatures identifiable by the associated Knowledge check (for example, outsiders for Knowledge [planes]).</p>
<p><strong>Dungeoneering:</strong> The investigator can deal half his studied strike damage to creatures immune to sneak attacks.</p>
<p><strong>Engineering:</strong> Whenever he uses his inspiration on Disable Device checks to open locks or on Perception checks to find hidden compartments, the investigator gains a circumstance bonus on the check equal to one-third his level.</p>
<p><strong>Geography:</strong> The investigator increases any bonuses to AC and on Reflex saving throws he gains from partial cover, total cover, and improved cover by 1.</p>
<p><strong>History:</strong> The investigator can study a foe using studied combat a second time in 24 hours as a full-round action without expending inspiration. Subsequent uses of studied combat require inspiration as normal.</p>
<p><strong>Local:</strong> Whenever he uses his inspiration on Bluff checks to feint, Diplomacy checks to gather information, or Intimidate checks to improve a creature's attitude, the investigator gains a circumstance bonus on the check equal to one-third his level.</p>
<p><strong>Nobility:</strong> Whenever he uses his inspiration on Bluff checks to lie, Diplomacy checks to request favors, or Intimidate checks to demoralize, the investigator gains a circumstance bonus on the check equal to one-third his level.</p>
</blockquote>
</>};
const _combat_inspiration = {title: "Combat Inspiration", jsx: <><h2 id="invtalent-combat_inspiration-combat-inspiration-ex">Combat Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When an investigator uses inspiration on an attack roll or saving throw, he expends one use of inspiration instead of two. An investigator must be at least 9th level to select this talent.</p>
</>};
const _greater_combat_inspiration = {title: "Greater Combat Inspiration", jsx: <><h2 id="invtalent-greater_combat_inspiration-greater-combat-inspiration-ex">Greater Combat Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>Choose a single weapon type (such as <Link to="/eq-weapon/sword_cane">sword cane</Link> or <Link to="/eq-weapon/short_sword">short sword</Link>). As long as the investigator has at least 1 inspiration point in his inspiration pool, he no longer has to expend a use of inspiration to use that ability with attacks made with this weapon. An investigator must have the <Link to="/invtalent/combat_inspiration">combat inspiration</Link> investigator talent and be at least 19th level to select this talent.</p>
</>};
const _eidetic_recollection = {title: "Eidetic Recollection", jsx: <><h2 id="invtalent-eidetic_recollection-eidetic-recollection-su">Eidetic Recollection (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator can always choose to take 10 on any of his Knowledge checks, even if he's in immediate danger or distracted. An investigator may expend one use of inspiration to take 20 on a Knowledge skill check even if he's in immediate danger or distracted. An investigator must be at least 11th level to select this talent.</p>
</>};
const _empathy = {title: "Empathy", jsx: <><h2 id="invtalent-empathy-empathy-ex-su">Empathy (Ex, Su)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When attempting a Sense Motive check, the investigator makes two d20 rolls and takes the higher result. If an investigator uses inspiration on a Sense Motive check, he rolls the inspiration dice twice and takes the higher result. Once per day, the investigator can expend one use of inspiration to target a single creature that he can see and hear within 30 feet. Upon doing so, the investigator detects the surface thoughts of the target's mind, as if he concentrated for 3 rounds while using the <Link to="/spell/detect_thoughts">detect thoughts</Link> spell, unless the creature succeeds a Will saving throw. The DC of this save is 10 + 1/2 the investigator's level + his Intelligence modifier. If the target fails, the investigator can continue to detect the surface thoughts of the target creature for a number of rounds equal to 1/2 his investigator level. An investigator must be at least 5th level to select this talent.</p>
</>};
const _expanded_inspiration = {title: "Expanded Inspiration", jsx: <><h2 id="invtalent-expanded_inspiration-expanded-inspiration-ex">Expanded Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator can use his inspiration ability when attempting Diplomacy, Heal, Perception, Profession, and Sense Motive checks without expending uses of inspiration, provided he's trained in the skill.</p>
</>};
const _rapid_perception = {title: "Rapid Perception", jsx: <><h2 id="invtalent-rapid_perception-rapid-perception-su">Rapid Perception (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 27</Link><br/>An investigator with this talent can attempt a Perception check to intentionally search for a specific item or creature as a swift action instead of a move action. If she is intentionally searching for an invisible creature, the creature's bonus on its Stealth check from its <Link to="/spell/invisibility">invisibility</Link> is halved. An investigator must have the <Link to="/invtalent/expanded_inspiration">expanded inspiration</Link> investigator talent before selecting this talent.</p>
</>};
const _hidden_agendas = {title: "Hidden Agendas", jsx: <><h2 id="invtalent-hidden_agendas-hidden-agendas-ex">Hidden Agendas (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator learns to obscure his thoughts and endeavors from prying eyes and even intrusive magic. When an investigator uses inspiration while attempting a Bluff check to pass secret messages or attempting a Linguistics check to create forgeries, he can roll his inspiration dice twice and take the higher result. In addition, the investigator can use inspiration when attempting a saving throw against a divination spell or effect without expending a use of inspiration. An investigator must be at least 11th level to select this talent.</p>
</>};
const _inspirational_expertise = {title: "Inspirational Expertise", jsx: <><h2 id="invtalent-inspirational_expertise-inspirational-expertise-ex">Inspirational Expertise (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When an investigator succeeds at a Knowledge check to identify a monster's special powers or vulnerabilities, he can expend one use of inspiration as a swift action to grant allies within 30 feet that can hear him a +4 insight bonus on attack rolls against that monster or type of monster for 1 round. An investigator must be at least 7th level to take this talent.</p>
</>};
const _sustained_inspirational_expertise = {title: "Sustained Inspirational Expertise", jsx: <><h2 id="invtalent-sustained_inspirational_expertise-sustained-inspirational-expertise-ex">Sustained Inspirational Expertise (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 31</Link><br/>When granting a bonus to allies via the inspirational expertise investigator talent, the investigator can spend one use of inspiration as a swift action the following round to extend the duration of the granted bonus for 1 additional round. The insight bonus granted decreases by 1 each round this ability is used. The investigator must be at least 11th level and have the <Link to="/invtalent/inspirational_expertise">inspirational expertise</Link> talent to select this talent.</p>
</>};
const _inspired_alertness = {title: "Inspired Alertness", jsx: <><h2 id="invtalent-inspired_alertness-inspired-alertness-ex">Inspired Alertness (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>Whenever the investigator becomes <Link to="/rule/flat_footed">flat-footed</Link>, he can expend one use of inspiration to ignore that condition. He must be conscious to do so, and must decide to do so when he becomes flat-footed. Using this ability doesn't require an action.</p>
</>};
const _inspired_intelligence = {title: "Inspired Intelligence", jsx: <><h2 id="invtalent-inspired_intelligence-inspired-intelligence-ex">Inspired Intelligence (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator can add his inspiration die to all Knowledge, Linguistics, or Spellcraft checks without expending a use of inspiration, even those he's not trained in.</p>
</>};
const _inspired_intimidator = {title: "Inspired Intimidator", jsx: <><h2 id="invtalent-inspired_intimidator-inspired-intimidator-ex">Inspired Intimidator (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When the investigator succeeds at an Intimidate check to demoralize an opponent, he can expend one use of inspiration to automatically increase the result of the check by 5 for the purpose of determining the duration of the demoralize effect. He can choose to spend multiple uses to inspiration in this manner to further increase the duration of the demoralize effect. He must be trained in Intimidate to take this talent. The <Link to="/invtalent/underworld_inspiration">underworld inspiration</Link> investigator talent has no effect on this talent.</p>
</>};
const _tenacious_inspiration = {title: "Tenacious Inspiration", jsx: <><h2 id="invtalent-tenacious_inspiration-tenacious-inspiration-ex">Tenacious Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>When an investigator rolls his inspiration die, he can roll an additional inspiration die and take the higher result. The investigator must at least 13th level to select this talent.</p>
</>};
const _unconventional_inspiration = {title: "Unconventional Inspiration", jsx: <><h2 id="invtalent-unconventional_inspiration-unconventional-inspiration-ex">Unconventional Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator with this talent can pick any one skill. He can add his inspiration die to checks attempted with that skill without expending a use of inspiration.</p>
</>};
const _underworld_inspiration = {title: "Underworld Inspiration", jsx: <><h2 id="invtalent-underworld_inspiration-underworld-inspiration-ex">Underworld Inspiration (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator can use his inspiration on Bluff, Disable Device, Disguise, Intimidate, or Sleight of Hand checks without expending uses of inspiration, provided he's trained in the skill.</p>
</>};
const _innocent_facade = {title: "Innocent Facade", jsx: <><h2 id="invtalent-innocent_facade-innocent-facade-sp">Innocent Facade (Sp)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 27</Link><br/>Once per day, an investigator with this talent can use <Link to="/spell/innocence">innocence</Link> as a spell-like ability, using her investigator level as the spell's caster level. An investigator must have the <Link to="/invtalent/underworld_inspiration">underworld inspiration</Link> investigator talent before selecting this talent.</p>
</>};
const _alchemist_discovery = {title: "Alchemist Discovery", jsx: <><h2 id="invtalent-alchemist_discovery-alchemist-discovery-ex">Alchemist Discovery (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>The investigator can select one of the following <Link to="/ability/discoveries">alchemist discoveries</Link> as an investigator talent: <Link to="/discovery/combine_extracts">combine extracts</Link>, <Link to="/discovery/concentrate_poison">concentrate poison</Link>, <Link to="/discovery/dilution">dilution</Link>, <Link to="/discovery/elixir_of_life">elixir of life</Link>, <Link to="/discovery/enhance_potion">enhance potion</Link>, <Link to="/discovery/eternal_potion">eternal potion</Link>, <Link to="/discovery/extend_potion">extend potion</Link>, <Link to="/discovery/infusion">infusion</Link>, <Link to="/discovery/mutagen">mutagen</Link>, and <Link to="/discovery/poison_conversion">poison conversion</Link>. He can also choose to learn an <Link to="/ability/annointings">annointing</Link>, instead. When selecting an alchemist discovery or annointing, he must be high enough level to qualify for it, using his investigator level as his alchemist level to determine if he qualifies. This talent can be selected multiple times; each time grants a new alchemist discovery.</p>
</>};
const _anathema = {title: "Anathema", jsx: <><h2 id="invtalent-anathema-anathema-ex">Anathema (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 15</Link><br/>When an investigator creates or prepares a poison, including poisons derived from racial or class abilities, he can spend one use of inspiration to create an anathema instead. Anathemas count as poisons, but they can affect creatures that are normally immune to poison, as they exploit vulnerabilities in their very nature rather than their biology. When an anathema is created, select a creature type (and subtype, if applicable) from the ranger <Link to="/ability/favored_enemy">favored enemy</Link> list; the anathema functions only against this chosen type. The investigator also chooses one of the following special abilities for the anathema to affect: damage reduction (except DR/-), energy resistance (one type chosen by the investigator), <Link to="/umr/fast_healing">fast healing</Link>, movement speed, or spell resistance.</p>
<p>The method of delivery (contact, ingested, inhaled, or injury) and the DC of the anathema's save are identical to those of the poison used to make the anathema. If the target fails its save against the anathema (even if the enemy is normally immune to effects that require a specific save, such as undead's immunity to effects that require a Fortitude save), the value of the chosen ability is lowered by 5 (minimum 0) for 1 round per investigator level.</p>
</>};
const _greater_anathema = {title: "Greater Anathema", jsx: <><h2 id="invtalent-greater_anathema-greater-anathema-ex">Greater Anathema (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 15</Link><br/>The ability reduction of the investigator's anathemas increases to 10, and he adds DR/- and regeneration to the list of abilities he can lower with an anathema. In addition, when an investigator creates an anathema, he can designate a specific kind of creature (such as <Link to="/template/vampire">vampires</Link>) in addition to the creature type. When used against this specific foe, the DC of the save against the anathema is 2 higher than the component poison. An investigator must have the <Link to="/invtalent/anathema">anathema</Link> investigator talent to select this talent.</p>
</>};
const _false_spellcaster = {title: "False Spellcaster", jsx: <><h2 id="invtalent-false_spellcaster-false-spellcaster-ex">False Spellcaster (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 31</Link><br/>The investigator can modify her extracts to be delivered as oils she can apply covertly to her skin. She can fake verbal or somatic components as she uses an extract this way to trick observers into thinking she cast a spell to produce the extract's effect. She attempts a Bluff check to determine how convincing the ruse is. If observers attempt to determine the spell she is casting, those who succeed at a Spellcraft check opposed by her Bluff check realize the truth. Whether or not an observer recognizes what is going on, the DC to identify the effect of the extract is equal to 20 + the extract's spell level. If the investigator has the <Link to="/discovery/infusion">infusion</Link> alchemist discovery, she can deliver her infusions with a range of touch, but the hint of residue grants targets a +2 bonus on the opposed Spellcraft check to realize she is not truly casting spells.</p>
</>};
const _lingering_venom = {title: "Lingering Venom", jsx: <><h2 id="invtalent-lingering_venom-lingering-venom-ex">Lingering Venom (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 15</Link><br/>Poisons that the investigator personally applies to weapons and traps, or otherwise inflicts upon foes, require one additional successful save to cure. An investigator must be at least 5th level to select this talent.</p>
</>};
const _numerical_alchemy = {title: "Numerical Alchemy", jsx: <><h2 id="invtalent-numerical_alchemy-numerical-alchemy-su">Numerical Alchemy (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 17</Link><br/>The investigator's skill with mental mathematics allows him to know exactly which muscle movements are necessary to mix an extract in the quickest, most efficient way. The investigator can expend one use of inspiration to mix an extract in 1 round (as opposed to 1 minute).</p>
</>};
const _greater_numerical_alchemy = {title: "Greater Numerical Alchemy", jsx: <><h2 id="invtalent-greater_numerical_alchemy-greater-numerical-alchemy-su">Greater Numerical Alchemy (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 17</Link><br/>The investigator can calculate his movements and account for his reactions to danger or unexpected situations with lightning speed. He can expend a use of inspiration to mix an extract as a standard action. The investigator must have the <Link to="/invtalent/numerical_alchemy">numerical alchemy</Link> talent and be at least 11th level to select this talent.</p>
</>};
const _castling = {title: "Castling", jsx: <><h2 id="invtalent-castling-castling-ex">Castling (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/elemental_masters_handbook">Elemental Master's Handbook pg. 9</Link><br/>The investigator treats soft cover granted by creatures of her size or larger as though it were <Link to="/rule/cover">cover</Link> instead. Cover the investigator gains from this talent does not allow her to attempt Stealth checks.</p>
</>};
const _device_talent = {title: "Device Talent", jsx: <><h2 id="invtalent-device_talent-device-talent-ex">Device Talent (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>The investigator can use the Use Magic Device skill even if not trained in that skill. If the investigator is trained in Use Magic Device, he can use the inspiration ability with that skill without expending uses of inspiration.</p>
</>};
const _effortless_aid = {title: "Effortless Aid", jsx: <><h2 id="invtalent-effortless_aid-effortless-aid-ex">Effortless Aid (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>The investigator can use an <Link to="/rule/aid_another_2">aid another</Link> action as a move action instead of as a standard action. An investigator can expend one use of inspiration to instead perform an aid another action as a swift action.</p>
</>};
const _eldritch_conduit = {title: "Eldritch Conduit", jsx: <><h2 id="invtalent-eldritch_conduit-eldritch-conduit-su">Eldritch Conduit (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 7</Link><br/>Survival in the Mana Wastes between the nations of Nex and Geb can depend heavily on locating sufficient magical equipment, which sometimes involves stealing power from a wand or scroll to power a more necessary one. As a full-round action, an investigator with this talent can use two potions, two wands, or two scrolls. Each item is expended or loses a charge as if used normally. The investigator chooses to gain the magical effect of one, but calculates its effects using the caster level of the other. The investigator must still succeed at a Use Magic Device check to operate scrolls or wands unless some other ability allows him to do so, but makes only one skill check to operate both items.</p>
</>};
const _extra_earthcraft = {title: "Extra Earthcraft", jsx: <><h2 id="invtalent-extra_earthcraft-extra-earthcraft">Extra Earthcraft</h2>
<p><strong>Sources</strong> <Link to="/source/elemental_masters_handbook">Elemental Master's Handbook pg. 9</Link><br/>The investigator gains 2 additional earthcraft points each day. The investigator must have the <Link to="/arc-rogue/earthshadow">earthcraft</Link> ability to select this talent.</p>
</>};
const _favored_beat = {title: "Favored Beat", jsx: <><h2 id="invtalent-favored_beat-favored-beat-ex">Favored Beat (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_intrigue">Inner Sea Intrigue pg. 31</Link><br/>The investigator is familiar with a specific community in which she gains the benefits of renown. She gains the <Link to="/soctalent/renown">renown</Link> vigilante social talent. This community can be an entire settlement or portions of a settlement (such as a particular district or neighborhood) depending on the population, as allowed by the renown social talent. Anytime she could select another investigator talent, the investigator can also select from the following list of vigilante social talents, using her investigator level as her vigilante level for the purposes of meeting prerequisites: <Link to="/soctalent/celebrity_discount">celebrity discount</Link>, <Link to="/soctalent/celebrity_perks">celebrity perks</Link>, <Link to="/soctalent/gossip_collector">gossip collector</Link>, <Link to="/soctalent/great_renown">great renown</Link>, <Link to="/soctalent/incredible_renown">incredible renown</Link>, and <Link to="/soctalent/loyal_aid">loyal aid</Link>. For the purpose of vigilante social talents, the investigator does not have a vigilante identity and is always considered to be in her social identity.</p>
</>};
const _fortified_position = {title: "Fortified Position", jsx: <><h2 id="invtalent-fortified_position-fortified-position-ex">Fortified Position (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/elemental_masters_handbook">Elemental Master's Handbook pg. 9</Link><br/>Whenever the investigator gains a bonus on Reflex saves due to cover, she gains an equal bonus on Fortitude saves.</p>
</>};
const _graceful_athlete = {title: "Graceful Athlete", jsx: <><h2 id="invtalent-graceful_athlete-graceful-athlete">Graceful Athlete</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 6</Link><br/>Gain <Link to="/feat/graceful_athlete">Graceful Athlete</Link> as a bonus feat. You must meet the prerequisites for the feat.</p>
</>};
const _item_lore = {title: "Item Lore", jsx: <><h2 id="invtalent-item_lore-item-lore-ex">Item Lore (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator can use Spellcraft to identify the properties and command words of magic items without the use of <Link to="/spell/detect_magic">detect magic</Link> or similar spells. An investigator must be at least 7th level to take this talent.</p>
</>};
const _just_a_face_in_the_crowd = {title: "Just a Face in the Crowd", jsx: <><h2 id="invtalent-just_a_face_in_the_crowd-just-a-face-in-the-crowd-su">Just a Face in the Crowd (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 7</Link><br/>The rabble-rousers of Galt can blend into a crowd and are able to hide and spot others who appear to be hiding. The investigator gains a bonus equal to half his class level on Disguise and Perception checks when 10 or more creatures of his size are within 30 feet of him.</p>
</>};
const _occult_dungeoneer = {title: "Occult Dungeoneer", jsx: <><h2 id="invtalent-occult_dungeoneer-occult-dungeoneer-su">Occult Dungeoneer (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 7</Link><br/>Street thieves in Absalom expect wares to be securely locked, and sometimes it takes high-quality tools and magic training to ensure there's a meal at the end of the day. An investigator with this ability can use spell trigger and spell completion items as if the following spells were on a spell list to which he has access: <Link to="/spell/detect_secret_doors">detect secret doors</Link>, <Link to="/spell/find_traps">find traps</Link>, <Link to="/spell/knock">knock</Link>, <Link to="/spell/locate_object">locate object</Link>, and <Link to="/spell/obscure_object">obscure object</Link>. If the <Link to="/misc/spell_trigger">spell-trigger</Link> device allows a wielder to apply his own caster level (such as with a staff), the investigator may use his class level as his caster level. The investigator may also use <em>knock</em> as a supernatural ability once per day, using his investigator level as his caster level.</p>
</>};
const _one_of_those_faces = {title: "One of Those Faces", jsx: <><h2 id="invtalent-one_of_those_faces-one-of-those-faces-sp">One of Those Faces (Sp)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 21</Link><br/>Each day, you can use <Link to="/spell/disguise_self">disguise self</Link> as a spell-like ability for up to 10 minutes per character level. This duration need not be continuous, but it must be used in 10-minute increments. Additionally, once you have used this ability, whenever you use it for the next 24 hours you must take the same alternate appearance.</p>
</>};
const _perceptive_tracking = {title: "Perceptive Tracking", jsx: <><h2 id="invtalent-perceptive_tracking-perceptive-tracking-ex">Perceptive Tracking (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>The investigator can use Perception instead of Survival to both find and follow tracks, using the same DCs listed under the Survival skill. An investigator must be trained in Perception to select this talent.</p>
</>};
const _rogue_talent = {title: "Rogue Talent", jsx: <><h2 id="invtalent-rogue_talent-rogue-talent-ex">Rogue Talent (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/advanced_class_guide">Advanced Class Guide pg. 32</Link><br/>An investigator can select one of the following rogue talents in place of an investigator talent: <Link to="/talent/acrobatic_assist">acrobatic assist</Link>, <Link to="/talent/assault_leader">assault leader</Link>, <Link to="/talent/black_market_connections">black market connections</Link>, <Link to="/talent/camouflage">camouflage</Link>, <Link to="/talent/canny_observer">canny observer</Link>, <Link to="/talent/charmer">charmer</Link>, <Link to="/talent/coax_information">coax information</Link>, <Link to="/talent/combat_swipe">combat swipe</Link>, <Link to="/talent/convincing_lie">convincing lie</Link>, <Link to="/talent/cunning_trigger">cunning trigger</Link>, <Link to="/talent/deft_palm">deft palm</Link>, <Link to="/talent/demand_attention">demand attention</Link>, <Link to="/talent/expert_leaper">expert leaper</Link>, <Link to="/talent/fast_fingers">fast fingers</Link>, <Link to="/talent/fast_getaway">fast getaway</Link>, <Link to="/talent/fast_picks">fast picks</Link>, <Link to="/talent/fast_stealth">fast stealth</Link>, <Link to="/talent/firearm_training">firearm training</Link>, <Link to="/talent/got_your_back">got your back</Link>, <Link to="/talent/guileful_polyglot">guileful polyglot</Link>, <Link to="/talent/grit">grit</Link>, <Link to="/talent/hard_to_fool">hard to fool</Link>, <Link to="/talent/hold_breath">hold breath</Link>, <Link to="/talent/honeyed_words">honeyed words</Link>, <Link to="/talent/iron_guts">iron guts</Link>, <Link to="/talent/lasting_poison">lasting poison</Link>, <Link to="/talent/ledge_walker">ledge walker</Link>, <Link to="/talent/major_magic">major magic</Link>, <Link to="/talent/minor_magic">minor magic</Link>, <Link to="/talent/nimble_climber">nimble climber</Link>, <Link to="/talent/peerless_maneuver">peerless maneuver</Link>, <Link to="/talent/quick_disable">quick disable</Link>, <Link to="/talent/quick_disguise">quick disguise</Link>, <Link to="/talent/quick_trapsmith">quick trapsmith</Link>, <Link to="/talent/resiliency">resiliency</Link>, <Link to="/talent/rogue_crawl">rogue crawl</Link>, <Link to="/talent/rope_master">rope master</Link>, <Link to="/talent/stand_up">stand up</Link>, <Link to="/talent/strong_stroke">strong stroke</Link>, <Link to="/talent/terrain_mastery">terrain mastery</Link>, <Link to="/talent/trap_spotter">trap spotter</Link>, or <Link to="/talent/wall_scramble">wall scramble</Link>. Any talent effects based on rogue level use the investigator's class level. If the rogue talent has a prerequisite (such as the <em>major magic</em> rogue talent requiring the <em>minor magic</em> talent), the investigator must fulfill the prerequisite before selecting that rogue talent. This talent can be selected multiple times; each time, it grants the investigator a new rogue talent.</p>
</>};
const _scry_slip = {title: "Scry Slip", jsx: <><h2 id="invtalent-scry_slip-scry-slip-su">Scry Slip (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 27</Link><br/>Whenever an investigator with this talent is targeted by a scrying effect that allows a Will save, the caster of the divination must succeed at a caster level check (DC = 15 + the investigator's class level). This talent wards the investigator and any objects she is holding or carrying.</p>
</>};
const _scrying_familiarity = {title: "Scrying Familiarity", jsx: <><h2 id="invtalent-scrying_familiarity-scrying-familiarity-ex">Scrying Familiarity (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/spymasters_handbook">Spymaster's Handbook pg. 2</Link><br/>You are well acquainted with scrying sensors. You can roll twice and take the better result on saving throws against divination (scrying) spells and effects, on Perception checks to notice scrying sensors, and on caster level checks to overcome spell resistance when you use a scrying spell or effect. If you notice a magical sensor, you can attempt a Stealth check opposed by the caster's caster level check to avoid being detected by the sensor.</p>
</>};
const _spell_storing = {title: "Spell Storing", jsx: <><h2 id="invtalent-spell_storing-spell-storing-su">Spell Storing (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 7</Link><br/>The investigator can store within himself a single targeted harmless spell of up to 2nd level. The spell must have a casting time of 1 standard action. Anytime a spell that meets these conditions is cast on the investigator, and he does not already have a spell stored, he can choose to store it rather than have it take effect immediately. Anytime afterward, as a standard action, the investigator can have the spell take effect (acting in all ways as if it had just been cast on him). An investigator must have 1 rank of Use Magic Device to select this talent.</p>
</>};
const _the_whole_time = {title: "The Whole Time", jsx: <><h2 id="invtalent-the_whole_time-the-whole-time-su">The Whole Time (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/magic_tactics_toolbox">Magic Tactics Toolbox pg. 7</Link><br/>Mercenaries in the employ of the <Link to="/rule/aspis_consortium">Aspis Consortium</Link> often use wands of <Link to="/spell/invisibility">invisibility</Link> to attack protected targets, then blend into the crowd to escape or disguise the source of the next attack. An investigator with this ability is practiced at attacking from magical concealment. He can use spell trigger and spell completion items as if the following spells were on a spell list to which he has access: <Link to="/spell/greater_invisibility">greater invisibility</Link>, <em>invisibility,</em> and <Link to="/spell/vanish">vanish</Link></p>
<p>Additionally, if the investigator becomes visible as a result of a weapon or spell attack, he can sheathe his weapon as a free action and instantly adopt a neutral posture. With a successful Bluff or Disguise check (opposed by witnesses' Sense Motive or Perception checks, whichever is higher), there is no obvious sign that the investigator is the source of the attack (though a lack of any other reasonable candidate can still lead observers to draw the correct conclusion).</p>
</>};
const _unbalancing_trick = {title: "Unbalancing Trick", jsx: <><h2 id="invtalent-unbalancing_trick-unbalancing-trick-ex">Unbalancing Trick (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/elemental_masters_handbook">Elemental Master's Handbook pg. 9</Link><br/>The investigator gains <Link to="/feat/improved_trip">Improved Trip</Link> as a bonus feat, even if she does not meet the prerequisites. At 6th level, she is treated as if she meets all the prerequisites of <Link to="/feat/greater_trip">Greater Trip</Link> (although she must take the feat as normal to gain its benefits).</p>
</>};
export default {not_found:_not_found,blinding_strike:_blinding_strike,confusing_strike:_confusing_strike,deafening_strike:_deafening_strike,domino_effect:_domino_effect,iconclastic_strike:_iconclastic_strike,numerical_strike:_numerical_strike,greater_numerical_strike:_greater_numerical_strike,masterful_numerical_strike:_masterful_numerical_strike,prolonged_study:_prolonged_study,repositioning_strike:_repositioning_strike,sapping_offensive:_sapping_offensive,sickening_offensive:_sickening_offensive,silencing_strike:_silencing_strike,slowing_strike:_slowing_strike,stealing_strike:_stealing_strike,timed_strike:_timed_strike,toppling_strike:_toppling_strike,twilight_talon_improvisation:_twilight_talon_improvisation,didactic_strike:_didactic_strike,quick_study:_quick_study,studied_defense:_studied_defense,amazing_inspiration:_amazing_inspiration,applied_engineering:_applied_engineering,atheist_inspiration:_atheist_inspiration,chroniclers_insight:_chroniclers_insight,combat_inspiration:_combat_inspiration,greater_combat_inspiration:_greater_combat_inspiration,eidetic_recollection:_eidetic_recollection,empathy:_empathy,expanded_inspiration:_expanded_inspiration,rapid_perception:_rapid_perception,hidden_agendas:_hidden_agendas,inspirational_expertise:_inspirational_expertise,sustained_inspirational_expertise:_sustained_inspirational_expertise,inspired_alertness:_inspired_alertness,inspired_intelligence:_inspired_intelligence,inspired_intimidator:_inspired_intimidator,tenacious_inspiration:_tenacious_inspiration,unconventional_inspiration:_unconventional_inspiration,underworld_inspiration:_underworld_inspiration,innocent_facade:_innocent_facade,alchemist_discovery:_alchemist_discovery,anathema:_anathema,greater_anathema:_greater_anathema,false_spellcaster:_false_spellcaster,lingering_venom:_lingering_venom,numerical_alchemy:_numerical_alchemy,greater_numerical_alchemy:_greater_numerical_alchemy,castling:_castling,device_talent:_device_talent,effortless_aid:_effortless_aid,eldritch_conduit:_eldritch_conduit,extra_earthcraft:_extra_earthcraft,favored_beat:_favored_beat,fortified_position:_fortified_position,graceful_athlete:_graceful_athlete,item_lore:_item_lore,just_a_face_in_the_crowd:_just_a_face_in_the_crowd,occult_dungeoneer:_occult_dungeoneer,one_of_those_faces:_one_of_those_faces,perceptive_tracking:_perceptive_tracking,rogue_talent:_rogue_talent,scry_slip:_scry_slip,scrying_familiarity:_scrying_familiarity,spell_storing:_spell_storing,the_whole_time:_the_whole_time,unbalancing_trick:_unbalancing_trick}