import {IonList,IonItem,IonLabel} from '@ionic/react';
import Link from '../../components/Link';
import MainLink from '../../components/MainLink';
const _traits_religion_lg = {title: "Religion Traits: Lawful Good", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-inspiring-leader"><Link to="/trait/inspiring_leader">Inspiring Leader</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/apsu">Apsu</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Imitating the leadership of your deity, you spur others on to great deeds. When you cast a spell that grants allies a morale bonus, you cast that spell at +1 caster level.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-scaly-ally"><Link to="/trait/scaly_ally">Scaly Ally</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/apsu">Apsu</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>Because of your devotion to Apsu, you gain a +2 trait bonus on Diplomacy checks involving reptiles or those of draconic blood, whether they are good-aligned or not.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-deadeye-bowman"><Link to="/trait/deadeye_bowman">Deadeye Bowman</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/erastil">Erastil</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>When you are using a longbow, if only a single creature is providing soft cover to your target, your target does not receive the +4 bonus to AC.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-erastils-speaker"><Link to="/trait/erastils_speaker">Erastil's Speaker</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/erastil">Erastil</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You understand the importance of keeping the peace in your community, and you have learned how to speak to the faithful in ways that they understand. You gain a +1 trait bonus on Diplomacy checks, and Diplomacy is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-patient-optimist"><Link to="/trait/patient_optimist">Patient Optimist</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/erastil">Erastil</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link>, <Link to="/source/cheliax_empire_of_devils">Cheliax, Empire of Devils</Link><br/>You know that all things pass in time, and are used to having to repeat arguments multiple times to convince stubborn believers. You gain a +2 trait bonus on Diplomacy checks to influence hostile or unfriendly creatures, and if you fail at such an attempt, you may retry it once.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-provider"><Link to="/trait/provider">Provider</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/erastil">Erastil</Link><br/><strong>Requirements:</strong> Halfling</p>
<p><strong>Sources</strong> <Link to="/source/halflings_of_golarion">Halflings of Golarion</Link><br/>Few things exalt your faith more than feeding the hungry with your own honest sweat. You gain a +1 trait bonus on any d20 roll to acquire food or water for others. Though this bonus most often applies to Survival checks, it could also apply to attacking monsters that are safe and nutritious to eat (mainly animals and plants). However, Erastil takes a dim view of waste and of those who scorn his favor, and if you abuse this gift (for example, by using the bonus to defeat a bear, then only eating one bite of it), he punishes you with a -2 penalty on attacks, checks, and saves for 24 hours.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-wise-teacher"><Link to="/trait/wise_teacher">Wise Teacher</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/erastil">Erastil</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You are skilled in passing along knowledge of rural matters. If you have 4 or more ranks in Knowledge (Nature) or Survival, when you aid another with these skills, you grant a +4 bonus on the check you are aiding instead of the normal +2.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-a-shining-beacon"><Link to="/trait/a_shining_beacon">A Shining Beacon</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/iomedae">Iomedae</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You carry a burning hatred in your heart for all things demonic, and have studied their weaknesses carefully. You deal an amount of additional damage equal to your weapon's critical hit modifier when you score a successful critical hit with a weapon against a demon. This damage is added only after the damage is totaled, and is not multiplied by the critical hit multiplier.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-divine-warrior"><Link to="/trait/divine_warrior">Divine Warrior</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/iomedae">Iomedae</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/taldor_echoes_of_glory">Taldor, Echoes of Glory</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>From an early age, you were trained by a militaristic order of clerics. You are devoted to the teachings of Iomedae and to spreading those teachings by force. Whenever you cast a divine spell that affects any melee weapons, choose one of those weapons; it gains a +1 trait bonus on damage rolls for the duration of the spell.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-inheritors-immunity"><Link to="/trait/inheritors_immunity">Inheritor's Immunity</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/iomedae">Iomedae</Link></p>
<p><strong>Sources</strong> <Link to="/source/people_of_the_wastes">People of the Wastes</Link><br/>Iomedae's valor fills you with divine energy, allowing you to stave off even the worst plague. Once per day, you can reroll a saving throw against a disease or poison. You must take the second result, even if it is worse.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-purity-of-faith"><Link to="/trait/purity_of_faith">Purity of Faith</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/iomedae">Iomedae</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>Your soul is free from impurity, and you are deeply committed to fulfilling your duties to the church. You gain a +1 trait bonus on Will saving throws and a +1 trait bonus on saving throws against spells and effects originating from an outsider with the evil subtype.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-regal-presence"><Link to="/trait/regal_presence">Regal Presence</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/iomedae">Iomedae</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You've always had a presence that people respect. You gain a +1 trait bonus on Diplomacy checks, and Diplomacy is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-searing-beacon"><Link to="/trait/searing_beacon">Searing Beacon</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/iomedae">Iomedae</Link><br/><strong>Requirements:</strong> Knight of Ozem</p>
<p><strong>Sources</strong> <Link to="/source/knights_of_the_inner_sea">Knights of the Inner Sea</Link><br/>You deal additional precision damage equal to your Wisdom modifier when you score a critical hit with a melee weapon against an undead opponent.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-ancestors-blade"><Link to="/trait/ancestors_blade">Ancestor's Blade</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/shizuru">Shizuru</Link></p>
<p><strong>Sources</strong> <Link to="/source/divine_anthology">Divine Anthology</Link><br/>You were trained by your family with a weapon passed down from a venerable ancestor. You begin play with an heirloom masterwork weapon worth up to 400 gp. You gain a +1 trait bonus on attack rolls with weapons of this type (not just your initial heirloom weapon) when you smite evil.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-pristine-reputation"><Link to="/trait/pristine_reputation">Pristine Reputation</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/shizuru">Shizuru</Link></p>
<p><strong>Sources</strong> <Link to="/source/divine_anthology">Divine Anthology</Link><br/>You come from an especially esteemed family, religious order, school, or other group that worships Shizuru, and draw upon that tradition to maintain your identity. The first time each day that you fail a saving throw against a charm or compulsion effect, you can reroll that saving throw. If you do so, you gain a +2 trait bonus on this roll and use this result as the actual result for that saving throw.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-defensive-strategist"><Link to="/trait/defensive_strategist">Defensive Strategist</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/torag">Torag</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>Your study of dwarven history has trained you in defensive strategy. You aren't flat-footed during a surprise round that you don't get to act in or before you get to act at the start of a battle.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-eye-of-the-father"><Link to="/trait/eye_of_the_father">Eye of the Father</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/torag">Torag</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You have an innate sense of what is right and wrong in the works you craft, based on your years studying with the church elders at their forges. Choose one Craft skill; you gain a +1 trait bonus on Craft checks of the selected type.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-guardian-of-the-forge"><Link to="/trait/guardian_of_the_forge">Guardian of the Forge</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/torag">Torag</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/dwarves_of_golarion">Dwarves of Golarion</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>Torag's sacred duties are to protect the faithful, take lessons from the great craftsmen and strategists of the past, and prepare against dark times. You receive a +1 trait bonus on Knowledge (engineering) and Knowledge (history) checks. One of these skills (your choice) is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_lg-protective-faith"><Link to="/trait/protective_faith">Protective Faith</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/torag">Torag</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Your faith in the Father of Creation strengthens your ability to shield others. When you use the aid another action to grant your ally a bonus to AC, you grant a +3 bonus to AC instead of the normal +2.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_ln = {title: "Religion Traits: Lawful Neutral", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-eye-for-quality"><Link to="/trait/eye_for_quality">Eye for Quality</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/abadar">Abadar</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Your deity has granted you an uncanny ability to find the true worth of items. You gain a +1 trait bonus on Appraise checks, you don't suffer the effects of failing such checks by 5 or more, and Appraise is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-eyes-and-ears-of-the-city"><Link to="/trait/eyes_and_ears_of_the_city">Eyes and Ears of the City</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/abadar">Abadar</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link>, <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide</Link><br/>Your religious training involved serving in the city watch of a large city, the primary duty of which was standing sentinel on a city wall. You gain a +1 trait bonus on Perception checks, and Perception is always a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-honey-tongued"><Link to="/trait/honey_tongued">Honey-Tongued</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/abadar">Abadar</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Your deep understanding of human nature and social philosophy grants you a +1 trait bonus on Diplomacy or Bluff checks when dealing with agents of the law, such as judges, guards, and paladins.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-lover-of-the-law"><Link to="/trait/lover_of_the_law">Lover of the Law</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/abadar">Abadar</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You have a strong belief in the righteousness of law and justice. You receive a +1 trait bonus on saving throws against charm and compulsion effects, and may attempt a new saving throw with an additional +1 bonus (for a total of +2) if you are directed to break the law.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-sense-of-order"><Link to="/trait/sense_of_order">Sense of Order</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/abadar">Abadar</Link><br/><strong>Requirements:</strong> Halfling</p>
<p><strong>Sources</strong> <Link to="/source/halflings_of_golarion">Halflings of Golarion</Link><br/>Your ability to notice even the slightest change, and the discomfort it causes, made service to Abadar a logical choice. You gain a +3 trait bonus on any Perception check made to identify any changes to a location that have occurred since you last visited it.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-the-city-protects"><Link to="/trait/the_city_protects">The City Protects</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/abadar">Abadar</Link></p>
<p><strong>Sources</strong> <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide</Link><br/>You feel safe and secure in urban environments, even in cities whose laws you find unjust - it is the physical fact of the city that you take solace in. In any settlement, you gain a +2 trait bonus against fear effects. If you fail a save against a fear effect, you may make a new save each round you remain in the city to overcome the fear effect as long as the fear effect persists. If you are a paladin, this ability to make additional saves to overcome fear extends to all allies within your aura of courage.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-opener-of-doors"><Link to="/trait/opener_of_doors">Opener of Doors</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/alseta">Alseta</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Because of your devotion to Alseta, you are blessed with the ability to find hidden portals. You gain a +2 trait bonus on Perception checks to find secret doors.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-centered"><Link to="/trait/centered">Centered</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/irori">Irori</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Having anchored yourself in your faith and your knowledge of yourself, you've made it difficult for others to dominate you. You gain a +1 trait bonus on saving throws against charm and compulsion effects, and the DC of any attempts to use the Intimidate skill on you increases by 1.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-eternal-understanding"><Link to="/trait/eternal_understanding">Eternal Understanding</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/irori">Irori</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Though you haven't been traditionally educated, you're blessed with potent observation and discernment. You can attempt Knowledge checks with a DC of 15 or lower untrained.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-seer-of-reality"><Link to="/trait/seer_of_reality">Seer of Reality</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/irori">Irori</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You have a deep understanding of the world around you, and thus you are more perceptive about what belongs and what does not. You gain a +2 trait bonus on saving throws against illusion magic.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-sensing-imperfection"><Link to="/trait/sensing_imperfection">Sensing Imperfection</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/irori">Irori</Link><br/><strong>Requirements:</strong> Halfling</p>
<p><strong>Sources</strong> <Link to="/source/halflings_of_golarion">Halflings of Golarion</Link><br/>Your belief in Irori has honed your ability to recognize when someone lies or dissembles. Sense Motive is a class skill for you, and you gain a +1 trait bonus on Sense Motive checks.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-wisdom-in-the-flesh"><Link to="/trait/wisdom_in_the_flesh">Wisdom in the Flesh</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/irori">Irori</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>Your hours of meditation on inner perfection and the nature of strength and speed allow you to focus your thoughts to achieve things your body might not normally be able to do on its own. Select any Strength-, Constitution-, or Dexterity-based skill. You may make checks with that skill using your Wisdom modifier instead of the skill's normal ability score. That skill is always a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ln-rejected-emperor"><Link to="/trait/rejected_emperor">Rejected Emperor</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> The Eternal Emperor</p>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_ancients">Blood of the Ancients pg. 23</Link><br/>When you were young, your parents presented you to the oracles of Po Li, claiming a divine sign showed you were the reincarnation of Lung Wa's Eternal Emperor. The oracles did not support the claim, but you are not untouched by celestial influence. You may use Knowledge (nobility) or Knowledge (religion) in place of Knowledge (planes) to identify outsiders, and nonevil outsiders you encounter begin with an attitude that is one step better than normal.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_le = {title: "Religion Traits: Lawful Evil", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-deep-wounding"><Link to="/trait/deep_wounding">Deep Wounding</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/achaekek">Achaekek</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You have learned the bloody secret of striking true and deep. When you deal bleed damage with a melee weapon, a successful DC 20 Heal check is required to stop the bleed damage. Magical healing stops the damage as normal.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-frightening-speed"><Link to="/trait/frightening_speed">Frightening Speed</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/achaekek">Achaekek</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your careful study of Achaekek's kills has unlocked a divine speed in you. Once per day during a combat encounter, you can move an additional 5 feet as a part of a move action without penalty.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-contract-master"><Link to="/trait/contract_master">Contract Master</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/asmodeus">Asmodeus</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your facility with contracts makes you good at understanding dense text and obfuscating your intent. You gain a +1 trait bonus on Linguistics checks, and Linguistics is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-demon-hunter"><Link to="/trait/demon_hunter">Demon Hunter</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/asmodeus">Asmodeus</Link></p>
<p><strong>Sources</strong> <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link>, <Link to="/source/cheliax_empire_of_devils">Cheliax, Empire of Devils</Link>, <Link to="/source/ultimate_campaign">Ultimate Campaign</Link><br/>Raised in the church (whether or not you are currently a follower), you've focused your indoctrinated fervor primarily on the elimination of demons. You gain a +3 trait bonus on Knowledge (planes) checks about demons and a +2 trait bonus on Will saves against mind-affecting spells and effects from demons.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-fiendish-confidence"><Link to="/trait/fiendish_confidence">Fiendish Confidence</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/asmodeus">Asmodeus</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>You expect to be obeyed, and are rarely proven wrong. You gain a +1 trait bonus on Intimidate checks, and Intimidate is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-liars-tongue"><Link to="/trait/liars_tongue">Liar's Tongue</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/asmodeus">Asmodeus</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Thanks to your friendly mien and sly tongue, your lies are often believed. You gain a +1 trait bonus on Bluff checks, and Bluff is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-battlefield-surgeon"><Link to="/trait/battlefield_surgeon">Battlefield Surgeon</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/zon_kuthon">Zon-Kuthon</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>You're skilled at both dealing and repairing wounds. Heal is a class skill for you, and you can use the treat deadly wounds aspect of Heal 1 additional time per creature per day.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-demoralizing-presence"><Link to="/trait/demoralizing_presence">Demoralizing Presence</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/zon_kuthon">Zon-Kuthon</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Your very existence is unsettling to your foes. You gain a +2 trait bonus on Intimidate checks made to demoralize opponents.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-kuthite-caster"><Link to="/trait/kuthite_caster">Kuthite Caster</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/zon_kuthon">Zon-Kuthon</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>You gain a +4 trait bonus on <Link to="/rule/concentration">concentration</Link> checks when casting spells with the darkness, pain, or shadow descriptor.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_le-pain-is-pleasure"><Link to="/trait/pain_is_pleasure">Pain Is Pleasure</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/zon_kuthon">Zon-Kuthon</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link><br/>You have discovered a hint of the dark truths that lay hidden within blood and flesh. You gain a +1 trait bonus on Fortitude and Will saves whenever you have fewer than half your maximum number of hit points.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_ng = {title: "Religion Traits: Neutral Good", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-strengths-fanfare"><Link to="/trait/strengths_fanfare">Strength's Fanfare</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/kurgess">Kurgess</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Songs of your glory and prowess bolster your strength. When you are the subject of any sonic effect that grants a morale bonus on attack or damage rolls, you also gain a +1 trait bonus on Strength-based skill checks; on combat maneuver checks to bull rush, grapple, and reposition; and to your CMD against those combat maneuvers.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-the-flexing-arm"><Link to="/trait/the_flexing_arm">The Flexing Arm</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/kurgess">Kurgess</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You are practiced at using physical might to escape your bonds. You can use Strength instead of Dexterity as your base ability for Escape Artist skill checks to free yourself from bondage. Additionally, you gain a +1 trait bonus on such Escape Artist checks.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-ambassador"><Link to="/trait/ambassador">Ambassador</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/taldor_echoes_of_glory">Taldor, Echoes of Glory</Link><br/>Your natural abilities at mediation and compromise manifested at a young age. For as long as you can remember, you were always more able to solve disputes and carefully settle violent disagreements than others. You gain a +2 trait bonus to Diplomacy checks.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-blade-of-mercy"><Link to="/trait/blade_of_mercy">Blade of Mercy</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide</Link><br/>You know that within the heart of even the most hateful and cruel living creature exists a sliver of shame and hope for redemption. You have trained long on martial techniques to use bladed weapons not to kill, but to subdue. When striking to inflict nonlethal damage with any slashing weapon, you do not take the normal -4 penalty on your attack roll, and gain a +1 trait bonus to any nonlethal damage you inflict with a slashing weapon.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-cleansing-light"><Link to="/trait/cleansing_light">Cleansing Light</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>Your faith is pure and strong, and your positive energy purges undead. When dealing damage to undead with your channel energy ability, you can reroll any damage die roll that results in a natural 1.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-cleansing-the-twisted"><Link to="/trait/cleansing_the_twisted">Cleansing the Twisted</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide</Link><br/>You have studied well the many religious texts that chronicle Sarenrae's neverending struggle against Rovagug and his monstrous offspring. Your fighting style works particularly well when you utilize slashing weapons against aberrations. You gain a +1 trait bonus to slashing weapon damage against all aberrations.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-dawn-renewal"><Link to="/trait/dawn_renewal">Dawn Renewal</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link><br/><strong>Requirements:</strong> Halfling</p>
<p><strong>Sources</strong> <Link to="/source/halflings_of_golarion">Halflings of Golarion</Link><br/>Your morning prayers often send a welcome spark of divine vitality into your most recent patients. When you use the Heal skill to provide long-term care, your patients heal an extra 2 hit points at sunrise.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-envoy-of-healing"><Link to="/trait/envoy_of_healing">Envoy of Healing</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/healers_handbook">Healer's Handbook</Link><br/>You strive to spread the Dawnflower's message of kindness and compassion throughout the land, no matter how dangerous the road may be. Whenever you use channel energy, fervor, or lay on hands to heal a living creature, you can reroll any healing die roll that results in a natural 1 (you must use the new result).</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-flame-of-the-dawnflower"><Link to="/trait/flame_of_the_dawnflower">Flame of the Dawnflower</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/qadira_gateway_to_the_east">Qadira, Gateway to the East</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>You have been raised to view yourself as a blade in Sarenrae's service, or you have taken on that duty for yourself. Whenever you score a critical hit with a scimitar, you deal 2 additional points of fire damage to your target.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-illuminator"><Link to="/trait/illuminator">Illuminator</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>When you are filled with the light of Sarenrae, your speech takes on a fiery eloquence. You gain a +2 trait bonus on Diplomacy checks, and Diplomacy is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-light-bringer"><Link to="/trait/light_bringer">Light-Bringer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You were born with a blessing of the Dawnflower. Once per day, you can use <Link to="/spell/light">light</Link> as a spell-like ability. Your caster level is equal to your character level.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-strength-of-the-sun"><Link to="/trait/strength_of_the_sun">Strength of the Sun</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide</Link><br/>You take solace in the purifying light of the sun. During the day, you gain a +1 trait bonus on all Charisma-based checks.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-under-siege"><Link to="/trait/under_siege">Under Siege</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sarenrae">Sarenrae</Link></p>
<p><strong>Sources</strong> <Link to="/source/taldor_echoes_of_glory">Taldor, Echoes of Glory</Link><br/>In order to maintain your devotion to Sarenrae in Taldor and stay alive, you and your fellow worshipers developed a complex system of hand signs and facial gestures to identify yourselves as faithful in the Cult of the Dawnflower. You gain a +1 trait bonus on Bluff and Sense Motive checks. One of these skills (your choice) is always a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-ear-for-music"><Link to="/trait/ear_for_music">Ear for Music</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/shelyn">Shelyn</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>You spent countless hours of your youth in one of Shelyn's temples, listening to wonderful musicians and singers. You gain a +1 trait bonus on one category of Perform checks and a +2 trait bonus on Knowledge (local) checks that deal with the local art or music scene.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-inner-beauty"><Link to="/trait/inner_beauty">Inner Beauty</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/shelyn">Shelyn</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>Once per day when you manifest your faith in your goddess, you gain a +4 trait bonus on a single Bluff, Craft, Diplomacy, or Perform skill check. You must choose to use this trait immediately after rolling the skill check but before the result is revealed by the GM.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-intense-artist"><Link to="/trait/intense_artist">Intense Artist</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/shelyn">Shelyn</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>Your devotion to Shelyn has caused you to delve more deeply into your art. Choose two Perform skills; you gain a +1 trait bonus on Perform checks of the selected types, and Perform is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-self-sacrifice"><Link to="/trait/self_sacrifice">Self-Sacrifice</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/shelyn">Shelyn</Link><br/><strong>Requirements:</strong> Halfling</p>
<p><strong>Sources</strong> <Link to="/source/halflings_of_golarion">Halflings of Golarion</Link><br/>You honor your goddess through your willingness to take risks for those you care about. As a move action, you can use your own body to grant soft cover to an adjacent ally regardless of the difference in your respective sizes.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ng-unswaying-love"><Link to="/trait/unswaying_love">Unswaying Love</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/shelyn">Shelyn</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Your resolute devotion to the unadulterated purity of your goddess protects you from those who would manipulate you. You gain a +2 trait bonus on saving throws against charm or compulsion effects.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_nn = {title: "Religion Traits: True Neutral", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-brighs-insight"><Link to="/trait/brighs_insight">Brigh's Insight</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/brigh">Brigh</Link></p>
<p><strong>Sources</strong> <Link to="/source/people_of_the_wastes">People of the Wastes</Link><br/>You hear Brigh's whisper in the workings of technology, granting you better understanding of and insight into constructs. You gain a +2 trait bonus on caster level checks to overcome the spell resistance of constructs.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-nimble-fingers-keen-mind"><Link to="/trait/nimble_fingers_keen_mind">Nimble Fingers, Keen Mind</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/brigh">Brigh</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Your study of clockwork mechanisms and other mechanical wonders grants you a +1 trait bonus on Disable Device checks, and Disable Device is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-child-of-nature"><Link to="/trait/child_of_nature">Child of Nature</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gozreh">Gozreh</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link>, <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>The wild places are your home, and provide everything you need to be happy. You gain a +2 trait bonus on Survival checks, and Survival is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-gozrehs-sight"><Link to="/trait/gozrehs_sight">Gozreh's Sight</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gozreh">Gozreh</Link></p>
<p><strong>Sources</strong> <Link to="/source/people_of_the_wastes">People of the Wastes</Link><br/>Your faith in the Wind and the Waves helps you navigate through all manner of mist or haze. You can see normally up to 5 feet away in areas of nonmagical fog, mist, rain, or similar conditions (such as the spray of a waterfall). Your sight is still obscured beyond 5 feet as normal in these conditions.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-natural-philosopher"><Link to="/trait/natural_philosopher">Natural Philosopher</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gozreh">Gozreh</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You study the outdoors, and leave books for dusty libraries. You can attempt Knowledge (geography) and Knowledge (nature) checks as if you were trained.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-strong-swimmer"><Link to="/trait/strong_swimmer">Strong Swimmer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gozreh">Gozreh</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Your faith in Gozreh's grace gives you the confidence to swim without fear. You gain a +2 trait bonus on Swim checks, and can <Link to="/misc/hold_your_breath">hold your breath</Link> for an extra 2 rounds when underwater.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-eyes-of-the-wild"><Link to="/trait/eyes_of_the_wild">Eyes of the Wild</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/green_faith">Green Faith</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Having spent much time immersed in the wilderness, you're now attuned to its ways. You gain a +2 trait bonus on Perception checks in natural settings.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-know-the-land"><Link to="/trait/know_the_land">Know the Land</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/green_faith">Green Faith</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Your familiarity with the plants and animals of a variety of environments gives you a +1 trait bonus on Knowledge (nature) and Survival checks, and one of these skills is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-spirit-talker"><Link to="/trait/spirit_talker">Spirit Talker</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> Mwangi shamanistic faith</p>
<p><strong>Sources</strong> <Link to="/source/sargava_the_lost_colony">Sargava, the Lost Colony</Link><br/>You are a devotee of the shamanistic practices of the Mwangi, having little use for the deities of the colonials. You gain a +1 racial bonus on Will saves against divine spells and spell-like effects employed against you by clerics or paladins of Aroden, Abadar, Iomedae, Gozreh, and Shelyn - but you suffer a -1 penalty on Will saves against divine spells cast by devotees of Mwangi faiths.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-empty-heart-full-heart"><Link to="/trait/empty_heart_full_heart">Empty Heart, Full Heart</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/naderi">Naderi</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Because of the aching strength of your forbidden love, you gain a +1 trait bonus on saving throws against charm effects, and targets of your charm spells take a -1 penalty on their saving throws.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-arcane-depth"><Link to="/trait/arcane_depth">Arcane Depth</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/nethys">Nethys</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You have studied the great masters of spellcraft, and your knowledge is exceptional. You gain a bonus of either +1 on Spellcraft checks or +2 on Knowledge (arcana) checks. You must choose which bonus you receive when you take the trait; once chosen, it cannot be changed.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-magic-is-life"><Link to="/trait/magic_is_life">Magic Is Life</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/nethys">Nethys</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link>, <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide</Link><br/>Your faith in magic allows you to reflexively use the energy of any spell effect currently on you to save you from death. As long as you are under the effects of a spell, you gain a +2 trait bonus on saving throws against death effects. If you are reduced to negative hit points while you are under the effects of any spell, you automatically confirm stabilization checks to stop bleeding.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-thirst-for-knowledge"><Link to="/trait/thirst_for_knowledge">Thirst for Knowledge</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/nethys">Nethys</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You have a need to bring old knowledge into the light, no matter what language it's written in. You gain a +1 trait bonus on Linguistics checks, and Linguistics is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-underlying-principles"><Link to="/trait/underlying_principles">Underlying Principles</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/nethys">Nethys</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You've spent a large amount of time around magical items, and understand the similarities between many of them. You gain a +1 trait bonus on Use Magic Device checks, and Use Magic Device is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-agent-of-chance"><Link to="/trait/agent_of_chance">Agent of Chance</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/nivi_rhombodazzle">Nivi Rhombodazzle</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You can change the fortunes of others, typically for the better. Once per day, you can allow an adjacent ally to reroll a skill check as an immediate action before the result is revealed. The ally must take the second roll, even if it is worse.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-corpse-hunter"><Link to="/trait/corpse_hunter">Corpse Hunter</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/pharasma">Pharasma</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You have dedicated yourself to the destruction of undead, and gain a +1 trait bonus on attacks made against undead.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-spirit-guide"><Link to="/trait/spirit_guide">Spirit Guide</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/pharasma">Pharasma</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>As someone who has performed or observed funeral rites for a wide variety of people, you have a basic understanding of many different religions. You gain a +2 trait bonus on Knowledge (religion) checks, and Knowledge (religion) is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-stabilizing-touch"><Link to="/trait/stabilizing_touch">Stabilizing Touch</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/pharasma">Pharasma</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You were born with the ability to stop the passage to death's door. Once per day, you can use <Link to="/spell/stabilize">stabilize</Link> as a spell-like ability, but with a range of touch.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-undead-slayer-pharasma"><Link to="/trait/undead_slayer_pharasma">Undead Slayer (Pharasma)</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/pharasma">Pharasma</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>Instructed at a young age in the tenets of the faith of Pharasma, you view the undead as abominations that must be destroyed so their souls can journey beyond to be judged. You gain a +1 trait bonus on weapon damage rolls against undead.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-strip-the-veils"><Link to="/trait/strip_the_veils">Strip the Veils</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sivanah">Sivanah</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You are unusually perceptive when dealing with others. You gain a +1 trait bonus on Sense Motive checks, and Sense Motive is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_nn-veils-upon-veils"><Link to="/trait/veils_upon_veils">Veils upon Veils</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/sivanah">Sivanah</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You have learned a holy secret that makes your illusions more powerful. Once per day when casting an illusion spell, you can do so at +1 caster level.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_ne = {title: "Religion Traits: Neutral Evil", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-poisonous-slayer"><Link to="/trait/poisonous_slayer">Poisonous Slayer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/norgorber">Norgorber</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You know the secret of plunging a poisoned weapon in just the right spot. You gain a +1 trait bonus on attack rolls when you are wielding a weapon treated with poison.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-practiced-deception"><Link to="/trait/practiced_deception">Practiced Deception</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/norgorber">Norgorber</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>You gain a +1 trait bonus on Disguise checks, and you can apply and remove a disguise in half the normal time.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-secret-knowledge"><Link to="/trait/secret_knowledge">Secret Knowledge</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/norgorber">Norgorber</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>At any point after taking this trait, you may choose one Knowledge skill. You gain a permanent +2 trait bonus on checks with that skill, and it is a class skill for you. Once this skill is chosen, it cannot be changed.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-shadow-whispers"><Link to="/trait/shadow_whispers">Shadow Whispers</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/norgorber">Norgorber</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link><br/>You have a penchant for just knowing others' secrets. You gain a +1 trait bonus on Knowledge (local) checks and a +2 trait bonus on Intimidate checks made to demoralize opponents.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-venom-drenched"><Link to="/trait/venom_drenched">Venom-Drenched</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/norgorber">Norgorber</Link><br/><strong>Requirements:</strong> Halfling</p>
<p><strong>Sources</strong> <Link to="/source/halflings_of_golarion">Halflings of Golarion</Link><br/>You have nothing to fear from one sort of poison. In fact, you can actually drink the toxic brew in order to make your blood dangerous. You are immune to one specific nonmagical poison. If you ingest a dose of that poison (even if it is a contact, inhaled, or injury poison), it remains in your system for 24 hours; any creature that bites you during that time is subject to the poison's effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-corpse-cannibal"><Link to="/trait/corpse_cannibal">Corpse Cannibal</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/urgathoa">Urgathoa</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link><br/>Your faith encourages you to indulge a variety of perverse hungers, leading you to shrug at even some of the darkest taboos. You gain a +2 trait bonus on Fortitude saves against diseases and can gain sustenance from rotting flesh with no negative side effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-deathspeaker"><Link to="/trait/deathspeaker">Deathspeaker</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/urgathoa">Urgathoa</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your experience with undead creatures gives you a +2 trait bonus on Diplomacy checks when dealing with undead, as well as a +2 trait bonus on Charisma checks to influence undead (such as with the command undead spell).</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-denial-of-fate"><Link to="/trait/denial_of_fate">Denial of Fate</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/urgathoa">Urgathoa</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>The Pallid Princess has blessed you with the ability to avoid the final fate. Once per day while you are below 0 hit points, at the start of your turn you can choose to stabilize without needing to succeed at a Constitution check.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-inoculated"><Link to="/trait/inoculated">Inoculated</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/urgathoa">Urgathoa</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your regular exposure to plagues grants you a +2 trait bonus on saving throws against disease effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-accident-resistant"><Link to="/trait/accident_resistant">Accident Resistant</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/zyphus">Zyphus</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Your understanding of pointless and unexpected death grants you a special awareness. You gain a +2 trait bonus on Reflex saves when denied your Dexterity bonus or during a surprise round.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ne-fatal-trapper"><Link to="/trait/fatal_trapper">Fatal Trapper</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/zyphus">Zyphus</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your patron grants you expertise at creating or disabling traps. You gain a +1 trait bonus on Craft (traps) checks, as well as a +1 trait bonus on Disable Device checks to disable traps.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_cg = {title: "Religion Traits: Chaotic Good", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-adventurous-imbiber"><Link to="/trait/adventurous_imbiber">Adventurous Imbiber</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/cayden_cailean">Cayden Cailean</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You've never been afraid of good, strong drink, and that has prepared you for the perils of more dangerous substances. You gain a +1 trait bonus on saving throws against poison.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-fortified-drinker"><Link to="/trait/fortified_drinker">Fortified Drinker</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/cayden_cailean">Cayden Cailean</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>Cayden Cailean's holy brews invigorate your mind, making you less susceptible to mental attacks. Whenever you imbibe any alcoholic beverage, you gain a +2 trait bonus on saves against mind-affecting effects for 1 hour.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-good-natured"><Link to="/trait/good_natured">Good-Natured</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/cayden_cailean">Cayden Cailean</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You have an unusually sunny spirit, and it takes something truly intimidating to dampen your mood. You gain a +2 trait bonus on saving throws against fear effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-strong-willed"><Link to="/trait/strong_willed">Strong-Willed</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/cayden_cailean">Cayden Cailean</Link></p>
<p><strong>Sources</strong> <Link to="/source/faiths_of_purity">Faiths of Purity</Link>, <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Your fervent desire to choose your own path gives you strong willpower. You receive a +2 trait bonus on saving throws against charm and compulsion effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-faithful-artist"><Link to="/trait/faithful_artist">Faithful Artist</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/desna">Desna</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>With Desna's blessing, you have pursued an artistic path. Choose one Perform skill; you gain a +1 trait bonus on Perform checks of the selected type, and Perform is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-follower-of-the-stars"><Link to="/trait/follower_of_the_stars">Follower of the Stars</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/desna">Desna</Link></p>
<p><strong>Sources</strong> <Link to="/source/wilderness_origins">Wilderness Origins</Link><br/>You gain a +4 trait bonus when using Survival to navigate under clear skies.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-good-dreams"><Link to="/trait/good_dreams">Good Dreams</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/desna">Desna</Link><br/><strong>Requirements:</strong> Halfling</p>
<p><strong>Sources</strong> <Link to="/source/halflings_of_golarion">Halflings of Golarion</Link><br/>Your dreams often give you a hint of possible dangers you might face during your day - such as a fall, a blast of fire, or a poisonous snake - and this hint sometimes makes all the difference. Each time you sleep, the GM tells you of a dangerous dream you had. Once per day, if you have to make a saving throw against a threat related or similar to that dream, you can roll twice and take the more favorable result. If you do not encounter circumstances similar to the threat or situation you dreamed, this trait has no effect that day. If you have the Halfling Jinx alternate racial trait, you cannot select this trait, and vice versa.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-starchild"><Link to="/trait/starchild">Starchild</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/desna">Desna</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/elves_of_golarion">Elves of Golarion</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>Desna sensed your love of travel and promised you would always be able to find your way home. You can automatically determine where true north is. You gain a +4 trait bonus on Survival checks to avoid becoming lost.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-stoic-optimism"><Link to="/trait/stoic_optimism">Stoic Optimism</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/desna">Desna</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You realize that accepting the pain in life accentuates its joys by contrast, and so your hope sustains you where others despair. You receive a +2 trait bonus on saving throws against fear effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-thrill-seeker-isg"><Link to="/trait/thrill_seeker_isg">Thrill-Seeker (ISG)</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/desna">Desna</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Desna has blessed you not just with a love of taking chances, but also the fortune to come out of such risky situations unscathed. Once per day, when you attempt an Acrobatics check, you can roll twice and take the better result. You must choose to use this ability before making the check.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-split-second-defense"><Link to="/trait/split_second_defense">Split-Second Defense</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/milani">Milani</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>When you are the target of an attack by an opponent that is flanking you, as an immediate action once per day you can foil that opponent's attack. For that attack, the opponent does not gain any of the bonuses or effects that are associated with flanking.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cg-talented-organizer"><Link to="/trait/talented_organizer">Talented Organizer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/milani">Milani</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_purity">Faiths of Purity</Link><br/>You are both skilled and knowledgeable when at putting together strong resistance organizations, thanks to your keen sense of how to motivate people. You gain a +1 trait bonus on Sense Motive skill checks, and Sense Motive is a class skill for you.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_cn = {title: "Religion Traits: Chaotic Neutral", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-adherent-of-ancient-osirion"><Link to="/trait/adherent_of_ancient_osirion">Adherent of Ancient Osirion</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> Bastet<br/><strong>Region:</strong> Osirion<br/><strong>Requirements:</strong> Catfolk</p>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast</Link><br/>Although Bastet has been all but forgotten by the native Osirians, you either sojourned with or were raised in a cult dedicated to the cat-headed goddess of Ancient Osirion. You treat the tekko-kagi as a martial weapon instead of an exotic weapon. You also treat the tekko-kagi as if it were a set of claw blades when determining how it interacts with other effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-besmaras-name"><Link to="/trait/besmaras_name">Besmara's Name</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/besmara">Besmara</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Besmara sometimes answers your call. Once per day when casting a divine spell, you can speak or whisper her name in place of using a divine focus.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-besmaras-strength"><Link to="/trait/besmaras_strength">Besmara's Strength</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/besmara">Besmara</Link></p>
<p><strong>Sources</strong> <Link to="/source/people_of_the_wastes">People of the Wastes</Link><br/>The Pirate Queen sometimes answers your calls when you tread dangerous waters. Once per day when attempting a Swim check, you can treat the water as if it were one category calmer (as if stormy water were rough water or rough water were calm water).</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-cheat-death"><Link to="/trait/cheat_death">Cheat Death</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/besmara">Besmara</Link></p>
<p><strong>Sources</strong> <Link to="/source/pirates_of_the_inner_sea">Pirates of the Inner Sea</Link><br/>Even Besmara's most faithful worshipers usually call upon her only in times of greatest need. Sometimes Besmara intervenes on behalf of her faithful; other times, she turns her face away as they sink beneath the waves. Once per day, when you would be reduced to 0 or fewer hit points as a result of a failed ability check, skill check, or saving throw on your part, you may invoke this ability in order to reroll the failed check. You must take the result of the second roll, even if it is worse than the original.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-deck-fighter"><Link to="/trait/deck_fighter">Deck Fighter</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/besmara">Besmara</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>Your long experience in compensating for the pitch and yaw of ocean-going ships grants you a +1 trait bonus on attacks of opportunity when fighting aboard a ship.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-expert-boarder"><Link to="/trait/expert_boarder">Expert Boarder</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/besmara">Besmara</Link></p>
<p><strong>Sources</strong> <Link to="/source/pirates_of_the_inner_sea">Pirates of the Inner Sea</Link><br/>Besmara rewards those who board other vessels and take what they want. While fighting on the deck of a ship, you gain a +1 bonus on all attacks made with one-handed weapons.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-calistrian-courtesan"><Link to="/trait/calistrian_courtesan">Calistrian Courtesan</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/calistria">Calistria</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link>, <Link to="/source/elves_of_golarion">Elves of Golarion</Link><br/>You worked in one of Calistria's temples as a sacred courtesan, and you know how to flatter, please, and (most of all) listen. You gain a +1 trait bonus on Sense Motive checks and Diplomacy checks to gather information, and one of these skills (your choice) is always a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-enchanting-conniver"><Link to="/trait/enchanting_conniver">Enchanting Conniver</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/calistria">Calistria</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You gain a +2 trait bonus on Bluff and Diplomacy checks against creatures affected by one of your charm or compulsion effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-holy-schemer"><Link to="/trait/holy_schemer">Holy Schemer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/calistria">Calistria</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You are well versed in the arts of misdirection, plotting, and intrigue, and you know how to recognize these tactics when they're used against you. You receive a +1 trait bonus on Sense Motive checks, and Sense Motive is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-opportunistic"><Link to="/trait/opportunistic">Opportunistic</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/calistria">Calistria</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You have learned to recognize openings that your foes leave, and you know how to take advantage of them. You gain a +1 trait bonus on attacks of opportunity when using a dagger, sword, or whip.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-sacred-avenger"><Link to="/trait/sacred_avenger">Sacred Avenger</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/calistria">Calistria</Link><br/><strong>Requirements:</strong> Elf</p>
<p><strong>Sources</strong> <Link to="/source/elves_of_golarion">Elves of Golarion</Link><br/>You have a special connection between you and Calistria that enhances your ability to achieve vengeance. When a creature damages you with a weapon, on your next turn you gain a +1 trait bonus on weapon damage against that creature. If this creature is your <em>ilduliel</em> (a personal, mutual nemesis), this bonus increases to +2.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-wasp-whisperer"><Link to="/trait/wasp_whisperer">Wasp Whisperer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/calistria">Calistria</Link><br/><strong>Requirements:</strong> Elf</p>
<p><strong>Sources</strong> <Link to="/source/elves_of_golarion">Elves of Golarion</Link><br/>Your association with Calistria's church has toughened your flesh against venom and blessed you with the ability to influence wasps and similar insectile vermin. You gain a +1 trait bonus on Fortitude saving throws against poison. You may make Diplomacy checks (or <Link to="/ability/wild_empathy">wild empathy</Link> checks if you are a druid or ranger) to improve a Hostile or Unfriendly insectile vermin's attitude toward Indifferent.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-iron-grip"><Link to="/trait/iron_grip">Iron Grip</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gorum">Gorum</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You and your weapon are practically one. You receive a +2 trait bonus to your CMD against disarm attempts.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-shield-trained"><Link to="/trait/shield_trained">Shield-Trained</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gorum">Gorum</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You were trained to use shields as weapons. Heavy and light shields are considered simple weapons rather than martial weapons for you. Heavy shields are considered light weapons for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-strong-heart"><Link to="/trait/strong_heart">Strong Heart</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gorum">Gorum</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You can stand firm against even the most terrifying foes. You gain a +1 trait bonus on saves against fear effects, and the DC of Intimidate checks against you increases by 2.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-veteran-of-battle"><Link to="/trait/veteran_of_battle">Veteran of Battle</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gorum">Gorum</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide</Link><br/>You have fought in several battles, and each time felt the presence of Gorum guiding your sword-arm, making you ready to act at a moment's notice. You gain a +1 trait bonus on initiative checks, and if you are able to act during a surprise round, you may draw a weapon (but not a potion or magic item) as a free action during that round.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-broken-mind"><Link to="/trait/broken_mind">Broken Mind</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/groetus">Groetus</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>You're used to living with your own madness, and gain a +2 trait bonus on saving throws against madness and confusion effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-light-sleeper"><Link to="/trait/light_sleeper">Light Sleeper</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/hanspur">Hanspur</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Because of a blessing from your god, or worries inspired by the way he died as a mortal, you are a light sleeper. Your modifier to Perception DCs when sleeping is +5 instead of +10.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_cn-river-freedom"><Link to="/trait/river_freedom">River Freedom</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/hanspur">Hanspur</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_balance">Faiths of Balance</Link><br/>The freedom of water inspires you. While touching flowing water, you gain a +2 trait bonus on saving throws against effects that would hamper your movement.</p>
</IonLabel></IonItem></IonList>};
const _traits_religion_ce = {title: "Religion Traits: Chaotic Evil", jsx: <IonList lines="full"><MainLink to="/main/traits_religion" className="reversed" info="Back to Religion Traits" /><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-dragon-tracker"><Link to="/trait/dragon_tracker">Dragon Tracker</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/dahak">Dahak</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>You have been taught to identify the subtle and not-so-subtle signs of a dragon's passage. You gain a +2 trait bonus on Survival checks to track dragons, and you can track a dragon with Survival untrained if the check's DC is 15 or lower.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-dragonslayer"><Link to="/trait/dragonslayer">Dragonslayer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/dahak">Dahak</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>You're greatly skilled in hunting and slaying those who resemble your lord's favored prey. You gain a +1 trait bonus on attack rolls against creatures of the dragon type.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-diseased-heart"><Link to="/trait/diseased_heart">Diseased Heart</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/ghlaunder">Ghlaunder</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Your work with infections has infused your spirit with disease. Any creature that performs a blood drain or swallow whole attack on you must succeed at a Fortitude saving throw (DC = 10 + your character level + your Constitution modifier) or become infected with filth fever. This is a poison effect.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-potent-concoctions"><Link to="/trait/potent_concoctions">Potent Concoctions</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/ghlaunder">Ghlaunder</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>You have dedicated your life to honoring famine and disease. Choose any two <Link to="/main/equipment_poisons">poisons</Link>; when you attempt to inflict either of these poisons on an enemy, the DC to resist it increases by 1.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-vindictive-strike"><Link to="/trait/vindictive_strike">Vindictive Strike</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gyronna">Gyronna</Link></p>
<p><strong>Sources</strong> <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Once per day during a combat encounter, you can choose to gain a +1 trait bonus on a single attack roll against the creature that last hit you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-wronged"><Link to="/trait/wronged">Wronged</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/gyronna">Gyronna</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Somewhere in your past, you were taken advantage of because of your gender. You gain a +2 trait bonus on Sense Motive checks against male creatures of your race, and the DC for men to intimidate you increases by 2.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-deformed"><Link to="/trait/deformed">Deformed</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/lamashtu">Lamashtu</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your monstrous deformities grant you a +1 trait bonus on Intimidate checks, and Intimidate is a class skill for you.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-mothers-rage"><Link to="/trait/mothers_rage">Mother's Rage</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/lamashtu">Lamashtu</Link></p>
<p><strong>Sources</strong> <Link to="/source/orcs_of_golarion">Orcs of Golarion</Link><br/>The blood of the beast runs thick in your veins, and your appearance is bestial. You receive a +1 trait bonus on Survival checks, and you treat your caster level as +1 higher when summoning creatures.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-mothers-teeth"><Link to="/trait/mothers_teeth">Mother's Teeth</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/lamashtu">Lamashtu</Link><br/><strong>Requirements:</strong> Goblin</p>
<p><strong>Sources</strong> <Link to="/source/goblins_of_golarion">Goblins of Golarion</Link><br/>Your teeth are more jagged and pointed than normal. You can make a bite attack for 1d2 points of damage as a secondary attack.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-opportune-slayer"><Link to="/trait/opportune_slayer">Opportune Slayer</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/lamashtu">Lamashtu</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>Those who open themselves to your attacks feel your wrath. You gain a +2 trait bonus on damage rolls against those you hit with attacks of opportunity.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-unhinged-mentality"><Link to="/trait/unhinged_mentality">Unhinged Mentality</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/lamashtu">Lamashtu</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your goddess-granted madness gives you a +2 trait bonus on saving throws against confusion, insanity, and fear effects.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-voice-of-monsters"><Link to="/trait/voice_of_monsters">Voice of Monsters</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/lamashtu">Lamashtu</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link><br/>Your faith leads you to see the power and wonder in even the most horrible abominations. Once per day, you can cast speak with animals. When you cast this spell, it can affect animals (as normal) as well as aberrations and magical beasts with an Intelligence of 2 or lower.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-bestial-wrath"><Link to="/trait/bestial_wrath">Bestial Wrath</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/rovagug">Rovagug</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link><br/>When you strike hard, you strike deep. You gain a +2 trait bonus on critical confirmation rolls.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-destructive-blows"><Link to="/trait/destructive_blows">Destructive Blows</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/rovagug">Rovagug</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your faith strengthens your powers of destruction. You gain a +2 trait bonus on Strength checks to break objects, as well as on combat maneuver checks to sunder.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-fury"><Link to="/trait/fury">Fury</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/rovagug">Rovagug</Link></p>
<p><strong>Sources</strong> <Link to="/source/orcs_of_golarion">Orcs of Golarion</Link><br/>The flood of battle and destruction stirs deep within you. When wielding a greataxe, you receive a +2 trait bonus on attack rolls to confirm critical hits.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-hatred-of-the-gods"><Link to="/trait/hatred_of_the_gods">Hatred of the Gods</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/rovagug">Rovagug</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>Your god's own hatred of other deities is reflected in your ability to withstand the attacks of their followers. You gain a +1 trait bonus on saving throws made against divine spells.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-sacred-smasher"><Link to="/trait/sacred_smasher">Sacred Smasher</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/rovagug">Rovagug</Link></p>
<p><strong>Sources</strong> <Link to="/source/orcs_of_golarion">Orcs of Golarion</Link><br/>Your love of carnage extends even to the defenseless, inanimate objects around you. Whenever you make an attempt to break an object, you receive a +2 trait bonus on your Strength check.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-wrecking-wrath"><Link to="/trait/wrecking_wrath">Wrecking Wrath</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/rovagug">Rovagug</Link></p>
<p><strong>Sources</strong> <Link to="/source/ultimate_campaign">Ultimate Campaign</Link><br/>Your ferocity is devastating, sometimes even to your own weapons. Once per day, after successful hitting a foe with a melee weapon, you can add your Strength modifier to the damage roll a second time (your Strength Modifier is not doubled if you are using a two-handed weapon). Doing so has a 25% chance of giving your weapon the broken condition.</p>
</IonLabel></IonItem><IonItem className="mainItem basic"><IonLabel><h2 id="main-traits_religion_ce-serpentine-squeeze"><Link to="/trait/serpentine_squeeze">Serpentine Squeeze</Link></h2>
<p><strong>Type:</strong> Religion<br/><strong>Religion:</strong> <Link to="/faith/ydersius">Ydersius</Link></p>
<p><strong>Sources</strong> <Link to="/source/inner_sea_gods">Inner Sea Gods</Link>, <Link to="/source/faiths_of_corruption">Faiths of Corruption</Link><br/>You gain a +1 trait bonus on combat maneuver checks to grapple a foe, as well as a +1 trait bonus to your CMD whenever an opponent tries to grapple you.</p>
</IonLabel></IonItem></IonList>};
export default {traits_religion_lg:_traits_religion_lg,traits_religion_ln:_traits_religion_ln,traits_religion_le:_traits_religion_le,traits_religion_ng:_traits_religion_ng,traits_religion_nn:_traits_religion_nn,traits_religion_ne:_traits_religion_ne,traits_religion_cg:_traits_religion_cg,traits_religion_cn:_traits_religion_cn,traits_religion_ce:_traits_religion_ce}