import Link from '../../components/Link';
const _not_found = {title: "Unknown", jsx: <><h2 id="kipower-not_found-unknown">Unknown</h2>
<p>Unable to find the requested ki power.</p>
</>};
const _abundant_step = {title: "Abundant Step", jsx: <><h2 id="kipower-abundant_step-abundant-step-su">Abundant Step (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>A monk with this ki power can slip magically between spaces, as if using the spell <Link to="/spell/dimension_door">dimension door</Link>. Using this ability is a move action that consumes 2 points from his ki pool. The monk's caster level for this effect is equal to his monk level. He cannot take other creatures with him when he uses this ability. A monk must be at least 8th level before selecting this ki power.</p>
</>};
const _action_before_thought = {title: "Action Before Thought", jsx: <><h2 id="kipower-action_before_thought-action-before-thought-ex">Action Before Thought (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/martial_arts_handbook">Martial Arts Handbook pg. 20</Link><br/>A monk with this ability can spend 2 ki points as a free action as part of rolling initiative to roll twice on the initiative check and take the higher result. A monk must be at least 6th level before selecting this ki power.</p>
</>};
const _breaking_down_koan = {title: "Breaking-Down Koan", jsx: <><h2 id="kipower-breaking_down_koan-breaking-down-koan-su">Breaking-Down Koan (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/martial_arts_handbook">Martial Arts Handbook pg. 20</Link><br/>A monk with this ability can spend 1 ki point as a swift action to present a paradox, riddle, or complicated question to a creature within 30 feet. The creature must succeed at a Will save (DC = 10 + 1/2 the monk's level + his Wisdom modifier) or be <Link to="/misc/confused">confused</Link> for 1 round. This is a mind-affecting, language-dependent effect. A monk must be at least 8th level before selecting this ki power.</p>
</>};
const _building_up_koan = {title: "Building-Up Koan", jsx: <><h2 id="kipower-building_up_koan-building-up-koan-su">Building-Up Koan (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/martial_arts_handbook">Martial Arts Handbook pg. 20</Link><br/>A monk with this ability can spend 2 ki points as a swift action to ask himself a koan, which he then tries to answer. The monk must attempt a Will save (DC 15 + 1/2 the monk's level). If successful, he gains an insight bonus equal to his Wisdom modifier to AC and on attack rolls, saving throws, skill checks and until the end of the round. If he fails, the monk is instead confused for 1 round. This is a mind-affecting, language-dependent effect. A character who can't become confused can't benefit from this ability. A monk must be at least 8th level before selecting this ki power.</p>
</>};
const _master_thought_koan = {title: "Master-Thought Koan", jsx: <><h2 id="kipower-master_thought_koan-master-thought-koan-su">Master-Thought Koan (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/martial_arts_handbook">Martial Arts Handbook pg. 20</Link><br/>A monk with this ability can spend an additional 2 ki points when using either the breaking-down koan or building-up koan ki powers. When combined with master-thought koan, breaking-down koan affects a number of characters of your choice within 30 feet equal to the monk's wisdom modifier. When combined with master-thought koan, building-up koan can be used on an ally within 30 feet. A monk must be at least 12th level and have either the <Link to="/kipower/breaking_down_koan">breaking-down koan</Link> or the <Link to="/kipower/building_up_koan">building-up koan</Link> ki power before selecting this ki power.</p>
</>};
const _diamond_body = {title: "Diamond Body", jsx: <><h2 id="kipower-diamond_body-diamond-body-su">Diamond Body (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>By spending 1 point from his ki pool, a monk with this power can remove one toxin from his body as if using <Link to="/spell/neutralize_poison">neutralize poison</Link>, using his monk level as his caster level. He can remove only one poison in this way per use of this ability. A monk must be at least 8th level before selecting this ki power.</p>
</>};
const _cobra_breath = {title: "Cobra Breath", jsx: <><h2 id="kipower-cobra_breath-cobra-breath-su">Cobra Breath (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>Whenever a monk with this ki power uses diamond body to neutralize a poison, he can instead release that poison as a ranged touch attack against a single foe within 30 feet. If the attack hits, the foe must succeed at a saving throw (using the poison's original DC) or suffer the poison's effects, even if it was not originally a contact poison. A monk must be at least 12th level and must possess the <Link to="/kipower/diamond_body">diamond body</Link> ki power before selecting this ki power.</p>
</>};
const _diamond_mind = {title: "Diamond Mind", jsx: <><h2 id="kipower-diamond_mind-diamond-mind-su">Diamond Mind (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>By spending 1 point from his ki pool as a swift action, a monk with this power can suppress a fear effect affecting him as if using <Link to="/spell/remove_fear">remove fear</Link>, using his monk level as his caster level. He can spend 2 ki points to activate this ability even when frightened or panicked. A monk must be at least 6th level before selecting this ki power.</p>
</>};
const _diamond_resilience = {title: "Diamond Resilience", jsx: <><h2 id="kipower-diamond_resilience-diamond-resilience-ex">Diamond Resilience (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>By spending 1 ki point as a swift action, the monk gains DR 2/-. At 16th level, the damage reduction increases to 4/-. At 19th level, it increases to DR 6/-. This DR lasts for 1 minute. A monk must be at least 12th level before selecting this ki power.</p>
</>};
const _diamond_soul = {title: "Diamond Soul", jsx: <><h2 id="kipower-diamond_soul-diamond-soul-ex">Diamond Soul (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>A monk can spend 2 points from his ki pool as a swift action to gain spell resistance equal to his monk level + 10. This spell resistance lasts for a number of rounds equal to the monk's level. A monk must be at least 12th level before selecting this ki power.</p>
</>};
const _ki_volley = {title: "Ki Volley", jsx: <><h2 id="kipower-ki_volley-ki-volley-su">Ki Volley (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>When a targeted spell or spell-like ability fails to overcome the monk's spell resistance from diamond soul, he can spend 2 ki points as an immediate action to send that spell back at its caster as <Link to="/spell/spell_turning">spell turning</Link>. A monk must be 16th level or higher and possess the <Link to="/kipower/diamond_soul">diamond soul</Link> ki power before selecting this ki power.</p>
</>};
const _elemental_fury = {title: "Elemental Fury", jsx: <><h2 id="kipower-elemental_fury-elemental-fury-su">Elemental Fury (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>A monk who selects this ki power must select one type of energy: acid, cold, electricity, or fire. Once this choice is made, it cannot be changed. The monk can expend 1 point from his ki pool as a swift action to imbue his natural attacks with this energy, causing them to deal 1d6 points of damage of the chosen type for a number of rounds equal to 1/2 his monk level. A monk must be at least 6th level before selecting this ki power.</p>
</>};
const _elemental_burst = {title: "Elemental Burst", jsx: <><h2 id="kipower-elemental_burst-elemental-burst-su">Elemental Burst (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>A monk with this ability can spend 4 ki points to unleash a gout of energy in a 30-foot cone. Creatures within the cone take 20d6 points of damage of the same type as the monk's <Link to="/kipower/elemental_fury">elemental fury</Link> ki power. A Reflex save (DC = 10 + 1/2 the monk's level + his Wisdom modifier) halves the damage. A monk must be at least 18th level and must possess the elemental fury ki power before selecting this ki power.</p>
</>};
const _empty_body = {title: "Empty Body", jsx: <><h2 id="kipower-empty_body-empty-body-su">Empty Body (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 16</Link><br/>A monk with this ki power gains the ability to assume an ethereal state for 1 minute as though using the spell <Link to="/spell/etherealness">etherealness</Link>, using his monk level as his caster level. Using this ability is a move action that consumes 3 points from the monk's ki pool. This ability affects only the monk and cannot be used to make other creatures ethereal.</p>
</>};
const _feather_balance = {title: "Feather Balance", jsx: <><h2 id="kipower-feather_balance-feather-balance-ex">Feather Balance (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability can spend 1 ki point as a swift action to achieve perfect balance. While this is active, the monk treats any Acrobatics attempt made to balance as if he had rolled a 20. This ability lasts for 1 minute.</p>
</>};
const _light_steps = {title: "Light Steps", jsx: <><h2 id="kipower-light_steps-light-steps-ex">Light Steps (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk with this ki power can move effortlessly across nearly any surface. Whenever the monk activates his feather balance ki power, he can also ignore all <Link to="/rule/difficult_terrain">difficult terrain</Link>. In addition, while active, he can cross any solid surface, even if it would normally not support his weight. This does not allow him to walk on liquids. A monk must be at least 8th level and have the <Link to="/kipower/feather_balance">feather balance</Link> ki power before selecting this ki power.</p>
</>};
const _floating_breath = {title: "Floating Breath", jsx: <><h2 id="kipower-floating_breath-floating-breath-su">Floating Breath (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/wilderness_origins">Wilderness Origins pg. 31</Link><br/>A monk with this ki power can spend 1 point from his ki pool as a swift action to balance on the air, hovering in place, until the end of his next turn. This power does not allow the monk to fly or otherwise move into the air; he must jump or use some other ability to reach his position. This otherwise functions as <Link to="/spell/air_walk">air walk</Link>. A monk must be 8th level before selecting this power.</p>
</>};
const _formless_mastery = {title: "Formless Mastery", jsx: <><h2 id="kipower-formless_mastery-formless-mastery-ex">Formless Mastery (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability varies his styles, never repeating the same move twice and capitalizing on the weaknesses of an opponent's style. As long as he does not possess any style feat, the monk can spend 1 point from his ki pool as an immediate action to gain the following against opponents in the stance of a style feat: a +4 dodge bonus to AC, a +4 circumstance bonus on attack rolls, and a bonus equal to his monk level on damage rolls. These bonuses last until the end of the monk's next turn (or his current turn if he uses this ability on his own turn). The monk can activate this ability and the <Link to="/kipower/furious_defense">furious defense</Link> ki power with the same immediate action for a total cost of 3 ki points. A monk must be at least 7th level before selecting this ki power.</p>
</>};
const _freedom_of_movement = {title: "Freedom of Movement", jsx: <><h2 id="kipower-freedom_of_movement-freedom-of-movement-su">Freedom of Movement (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 31</Link><br/>A monk with this ability can spend 1 ki point as a swift action to gain the effects of <Link to="/spell/freedom_of_movement">freedom of movement</Link> for 1 round. The monk must be at least 8th level before selecting this ki power.</p>
</>};
const _furious_defense = {title: "Furious Defense", jsx: <><h2 id="kipower-furious_defense-furious-defense-ex">Furious Defense (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>By spending 1 point from his ki pool as an immediate action, a monk with this ki power can grant himself a +4 dodge bonus to AC until the end of his next turn. The monk can activate this ability and the <Link to="/kipower/formless_mastery">formless mastery</Link> ki power with the same immediate action for a total cost of 3 ki points. A monk must be at least 7th level before selecting this ki power.</p>
</>};
const _high_jump = {title: "High Jump", jsx: <><h2 id="kipower-high_jump-high-jump-ex">High Jump (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ki power adds his level as a bonus on all Acrobatics checks to jump, both for vertical jumps and horizontal jumps. In addition, he always counts as having a running start when attempting Acrobatics checks to jump. By spending 1 point from his ki pool as a swift action, the monk gains a +20 bonus on Acrobatics checks to jump for 1 round.</p>
</>};
const _wind_jump = {title: "Wind Jump", jsx: <><h2 id="kipower-wind_jump-wind-jump-su">Wind Jump (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk with this ki power can spend 1 point from his ki pool as a move action to grant himself a fly speed (with perfect maneuverability) equal to his base land speed. He must end his movement each round on solid ground (or some other surface that can support his weight) or fall as normal. Once activated, this ability lasts for 1 minute. A monk must be at least 8th level and have the <Link to="/kipower/high_jump">high jump</Link> ki power before selecting this ki power.</p>
</>};
const _improvised_weapon_proficiency = {title: "Improvised Weapon Proficiency", jsx: <><h2 id="kipower-improvised_weapon_proficiency-improvised-weapon-proficiency-ex-su">Improvised Weapon Proficiency (Ex, Su)</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 31</Link><br/>A monk with this ability does not take a penalty on attack rolls for using an <Link to="/misc/improvised_weapon">improvised weapon</Link>. By spending 1 ki point, the monk can fight with a <Link to="/misc/broken">broken</Link> weapon without taking any penalties on attack rolls or damage rolls for 1 round.</p>
</>};
const _insightful_wisdom = {title: "Insightful Wisdom", jsx: <><h2 id="kipower-insightful_wisdom-insightful-wisdom-su">Insightful Wisdom (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability can spend 2 ki points as an immediate action to give another ally within 30 feet just the right word of advice to prevent disaster. If the ally can hear the monk, she can reroll a single attack roll or saving throw. The ally must take the second result, even if it is worse. A monk must be at least 8th level before selecting this ki power.</p>
</>};
const _ki_blocker = {title: "Ki Blocker", jsx: <><h2 id="kipower-ki_blocker-ki-blocker-su">Ki Blocker (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability can spend 1 ki point as a free action before making an unarmed strike against a foe. If the attack hits, the monk can interrupt the target's flow of ki. If the monk successfully damages the target of his attack, that opponent's cost to activate abilities with ki increases by 1 ki point for 1 hour. If the monk spends 2 points from his ki pool, he can use this ability to affect the target's arcane pool, arcane reservoir, grit points, inspiration, or panache points instead of its ki pool. The effects of this ability do not stack, but multiple hits increase the duration by 1 hour for each hit. A monk must be at least 10th level before selecting this ki power.</p>
</>};
const _ki_guardian = {title: "Ki Guardian", jsx: <><h2 id="kipower-ki_guardian-ki-guardian-su">Ki Guardian (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>As an immediate action before he rolls a saving throw against a targeted effect that also targets other allies or an area effect whose area includes other allies, a monk with this ability can spend any number of ki points and designate a number of adjacent allies equal to the number of ki points spent. The monk rolls one saving throw for each designated ally, using his bonus instead of the ally's. For each successful saving throw, the corresponding ally treats the effect as if that ally had succeeded at the saving throw, and for each saving throw failed, the corresponding ally treats the effect as if that ally had failed the saving throw. If the monk fails any of the saving throws (including his own original saving throw), the monk treats the effect as if he had failed the saving throw. A monk must be at least 6th level before selecting this ki power.</p>
</>};
const _ki_meditation = {title: "Ki Meditation", jsx: <><h2 id="kipower-ki_meditation-ki-meditation-su">Ki Meditation (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 31</Link><br/>A monk with this ability can spend 2 ki points to meditate as a full-round action, as if using Combat Meditation. Alternatively, he can spend 4 ki points to meditate as a move action instead. Using these ki points does not count as one of the monk's daily uses of Combat Meditation, but it grants him the usual benefits he would gain from his meditation feats for doing so. The monk must have the <Link to="/feat/combat_meditation">Combat Meditation</Link> feat before selecting this ki power.</p>
</>};
const _ki_metabolism = {title: "Ki Metabolism", jsx: <><h2 id="kipower-ki_metabolism-ki-metabolism-su">Ki Metabolism (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability uses his ki to control his metabolism. As long as he has at least 1 point remaining in his ki pool, the monk needs to eat and drink only 1/4 as often as normal, needs only 2 hours of sleep each night (including to replenish his ki pool), and can <Link to="/misc/hold_his_breath">hold his breath</Link> for up to 1 hour per point of Constitution. As a move action, he can spend 1 ki point to enter a state of suspended animation, falling unconscious and appearing dead to all senses. At the time he enters this state, he indicates a preset period of time or a triggering condition, after which he awakens.</p>
</>};
const _ki_mount = {title: "Ki Mount", jsx: <><h2 id="kipower-ki_mount-ki-mount-su">Ki Mount (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability can spend 1 ki point as a standard action to grant 2 <Link to="/rule/temporary_hit_points">temporary hit points</Link> per monk level he possesses to his mount for 1 hour per monk level. As long as the monk and his mount are adjacent or the monk is mounted, the mount shares the benefits of whichever of the AC bonus, evasion, high jump, improved evasion, ki strike, perfect self, and still mind abilities the monk possesses. A monk must be at least 6th level before selecting this ki power.</p>
</>};
const _ki_range = {title: "Ki Range", jsx: <><h2 id="kipower-ki_range-ki-range-su">Ki Range (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability can spend 1 ki point as a swift action to increase the range increment of any thrown monk weapon by 20 feet. Apply this benefit before doubling the range increment with the <Link to="/feat/far_shot">Far Shot</Link> feat.</p>
</>};
const _ki_sunder = {title: "Ki Sunder", jsx: <><h2 id="kipower-ki_sunder-ki-sunder-ex">Ki Sunder (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/martial_arts_handbook">Martial Arts Handbook pg. 20</Link><br/>A monk with this ability can spend 1 ki point as a free action when attempting a sunder combat maneuver check to add his monk level as a bonus to the damage roll.</p>
</>};
const _bare_hand_block = {title: "Bare-Hand Block", jsx: <><h2 id="kipower-bare_hand_block-bare-hand-block-ex">Bare-Hand Block (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/martial_arts_handbook">Martial Arts Handbook pg. 20</Link><br/>A monk with this ability can spend 1 ki point as an immediate action when attacked with a manufactured weapon to attempt an unarmed sunder combat maneuver check against it. If he successfully sunders the weapon and grants it the broken condition, the attack deals no damage. He can spend an additional 1 ki point when using this ability to activate ki sunder as a free action. A monk must be at least 8th level and have the <Link to="/kipower/ki_sunder">ki sunder</Link> ki power before selecting this ki power.</p>
</>};
const _ki_visions = {title: "Ki Visions", jsx: <><h2 id="kipower-ki_visions-ki-visions-su">Ki Visions (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>A monk with this ability often sees visions of spirits or hears the voice of his departed mentor in his dreams. On any given night during which the monk dreams, he can use this ability to gain the benefits of a <Link to="/spell/divination">divination</Link>. If he does, he spends 2 ki points from the next day's total. A monk must be at least 10th level before selecting this ki power.</p>
</>};
const _one_touch = {title: "One Touch", jsx: <><h2 id="kipower-one_touch-one-touch-ex">One Touch (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>As long as he has at least 1 point remaining in his ki pool, as a standard action, a monk with this power can make an unarmed strike against a foe as a touch attack. He adds 1/2 his monk level as a bonus on the damage roll. He can spend 1 ki point to double this bonus for that attack. A monk must be at least 12th level before selecting this ki power.</p>
</>};
const _qinggong_power = {title: "Qinggong Power", jsx: <><h2 id="kipower-qinggong_power-qinggong-power-su">Qinggong Power (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk with this power selects any of the <Link to="/arc-monk/qinggong_monk">qinggong monk</Link> ki powers for which he qualifies based on his monk level. A monk can select this ability multiple times. Each time, he must select a different qinggong monk ki power.</p>
</>};
const _quivering_palm = {title: "Quivering Palm", jsx: <><h2 id="kipower-quivering_palm-quivering-palm-su">Quivering Palm (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk can set up vibrations within the body of another creature that can thereafter be fatal if the monk so desires. Using this ability is a standard action that costs 4 ki points, and the monk must announce his intent to use this ability (and spend the ki points) before making the attack roll. Creatures immune to critical hits cannot be affected. Otherwise, if the attack hits and the target takes damage from the blow, the quivering palm attack succeeds. Thereafter, the monk can try to slay the victim at any time within a number of days equal to his monk level. To make such an attempt, the monk merely wills the target to die (a free action); unless the target succeeds at a Fortitude saving throw (DC = 10 + 1/2 the monk's level + the monk's Wisdom modifier), it dies. If the saving throw is successful, the target is no longer in danger from that particular quivering palm attack, but it can still be affected by another one at a later time. A monk can have no more than one quivering palm in effect at one time. If a monk uses quivering palm while another is still in effect, the previous one is negated. A monk must be at least 16th level before selecting this ki power.</p>
</>};
const _racing_current = {title: "Racing Current", jsx: <><h2 id="kipower-racing_current-racing-current-su">Racing Current (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/wilderness_origins">Wilderness Origins pg. 31</Link><br/>A monk with this ki power can create a wave to help him maneuver allies upon the battlefield, as if using the spell <Link to="/spell/slipstream">slipstream</Link>. Using this ability is a move action that costs 2 ki points, and the ability remains in effect for 1 minute. A monk must be 6th level to select this ki power.</p>
</>};
const _slow_fall = {title: "Slow Fall", jsx: <><h2 id="kipower-slow_fall-slow-fall-su">Slow Fall (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk within arm's reach of a wall can use it to slow his descent by expending 1 point from his ki pool. When he uses this ability, he takes no damage from the fall (as if using <Link to="/spell/feather_fall">feather fall</Link>), but he must be adjacent to a wall for the length of the fall (although this can be used to reduce the damage from a fall if only part of it is adjacent to a wall).</p>
</>};
const _sudden_speed = {title: "Sudden Speed", jsx: <><h2 id="kipower-sudden_speed-sudden-speed-su">Sudden Speed (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk with this ki power can spend 1 point from his ki pool as a swift action to grant himself a sudden burst of speed. This increases the monk's base land speed by 30 feet for 1 minute.</p>
</>};
const _branch_runner = {title: "Branch Runner", jsx: <><h2 id="kipower-branch_runner-branch-runner-ex-su">Branch Runner (Ex, Su)</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_beast">Blood of the Beast pg. 30</Link><br/>A monk with this ability adds half the base speed bonus from his fast movement ability to his racial climb speed. In addition, when he uses the sudden speed ki power, he adds the base speed bonus from that ki power to his racial climb speed for 1 round. The monk must have the <Link to="/kipower/sudden_speed">sudden speed</Link> ki power before selecting branch runner.</p>
</>};
const _ki_hurricane = {title: "Ki Hurricane", jsx: <><h2 id="kipower-ki_hurricane-ki-hurricane-ex">Ki Hurricane (Ex)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 17</Link><br/>As a full-round action, a monk with this ability can move up to twice his speed. At any point in that movement, the monk can spend 1 ki point to make the first attack in his flurry of blows. He can later spend another ki point to make the next attack in his flurry of blows, and so on, until he either stops spending ki points or has exhausted all the attacks from his flurry of blows. A monk must be at least 10th level and possess the sudden speed ki power before selecting this ki power.</p>
</>};
const _water_sprint = {title: "Water Sprint", jsx: <><h2 id="kipower-water_sprint-water-sprint-su">Water Sprint (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk with this ki power can spend 1 point from his ki pool as a swift action to gain the ability to walk on water, as if under the effects of <Link to="/spell/water_walk">water walk</Link>. Once activated, this ability lasts for 1 minute per monk level. A monk must be fat least 6th level before selecting this ki power.</p>
</>};
const _wholeness_of_body = {title: "Wholeness of Body", jsx: <><h2 id="kipower-wholeness_of_body-wholeness-of-body-su">Wholeness of Body (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_unchained">Pathfinder Unchained pg. 18</Link><br/>A monk with this ki power can heal his own wounds as a standard action. By spending 2 points from his ki pool, he can heal an amount of damage equal to 1d8 + his monk level.</p>
</>};
const _zephyr_blow = {title: "Zephyr Blow", jsx: <><h2 id="kipower-zephyr_blow-zephyr-blow-su">Zephyr Blow (Su)</h2>
<p><strong>Sources</strong> <Link to="/source/wilderness_origins">Wilderness Origins pg. 31</Link><br/>By spending 1 ki point as a standard action, a monk with this power can disrupt the wind and create a sharp blast of air, as if using the spell <Link to="/spell/gust_of_wind">gust of wind</Link>. The monk's caster level for this effect is equal to his monk level.</p>
</>};
export default {not_found:_not_found,abundant_step:_abundant_step,action_before_thought:_action_before_thought,breaking_down_koan:_breaking_down_koan,building_up_koan:_building_up_koan,master_thought_koan:_master_thought_koan,diamond_body:_diamond_body,cobra_breath:_cobra_breath,diamond_mind:_diamond_mind,diamond_resilience:_diamond_resilience,diamond_soul:_diamond_soul,ki_volley:_ki_volley,elemental_fury:_elemental_fury,elemental_burst:_elemental_burst,empty_body:_empty_body,feather_balance:_feather_balance,light_steps:_light_steps,floating_breath:_floating_breath,formless_mastery:_formless_mastery,freedom_of_movement:_freedom_of_movement,furious_defense:_furious_defense,high_jump:_high_jump,wind_jump:_wind_jump,improvised_weapon_proficiency:_improvised_weapon_proficiency,insightful_wisdom:_insightful_wisdom,ki_blocker:_ki_blocker,ki_guardian:_ki_guardian,ki_meditation:_ki_meditation,ki_metabolism:_ki_metabolism,ki_mount:_ki_mount,ki_range:_ki_range,ki_sunder:_ki_sunder,bare_hand_block:_bare_hand_block,ki_visions:_ki_visions,one_touch:_one_touch,qinggong_power:_qinggong_power,quivering_palm:_quivering_palm,racing_current:_racing_current,slow_fall:_slow_fall,sudden_speed:_sudden_speed,branch_runner:_branch_runner,ki_hurricane:_ki_hurricane,water_sprint:_water_sprint,wholeness_of_body:_wholeness_of_body,zephyr_blow:_zephyr_blow}