import Link from '../../components/Link';
const _archmages_vestments = {title: "Archmage's Vestments", jsx: <><h2 id="magic-set-archmages_vestments-archmages-vestments">Archmage's Vestments</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 24</Link></p>
<p>Consisting of everything a truly legendary wizard might need to overcome his rivals, the Archmage's Vestments enhance the wearer's spellcasting abilities.</p>
<p><strong><Link to="/magic-armor/casters_shield_greater">Caster's Shield, Greater:</Link></strong> For each additional piece of the set you wear or wield, the maximum spell level of scroll you can inscribe on this shield increases by 1.</p>
<p><strong><Link to="/magic-wondrous/magicians_hat">Magician's Hat:</Link></strong> While you are wearing and wielding all five pieces of this set, you can use this hat's ability to shift metamagic feats two additional times per day.</p>
<p><strong><Link to="/magic-ring/ring_of_counterspells">Ring of Counterspells:</Link></strong> While you are wearing and wielding all five pieces of this set, you can store a second spell of 1st through 6th level inside this ring.</p>
<p><strong><Link to="/magic-wondrous/robe_of_the_archmagi">Robe of the Archmagi:</Link></strong> For every two additional pieces of the set you wear or wield, the spell resistance granted by these robes increases by 1.</p>
<p><strong><Link to="/magic-staff/staff_of_power">Staff of Power:</Link></strong> For every two additional pieces of this set you wear or wield, the enhancement bonus of this staff increases by 1. While you are wearing and wielding all five pieces of the set, the staff of power automatically regains 1 charge every 24 hours (to a maximum of 10 charges).</p>
<p><strong className="hl">Two-Item Benefit:</strong> While you are wearing or wielding at least two pieces of this set, your caster level for all arcane spellcasting classes you have levels in increases by 1.</p>
<p><strong className="hl">Three-Item Benefit:</strong> While you are wearing or wielding at least three pieces of this set, you gain one additional 3rd-level spell slot for one arcane spellcasting class you have levels in.</p>
<p><strong className="hl">Four-Item Benefit:</strong> While you are wearing or wielding at least four pieces of this set, you gain one additional 4th-level spell slot for one arcane spellcasting class you have levels in.</p>
<p><strong className="hl">Five-Item Benefit:</strong> While you are wearing and wielding all five pieces of this set, you gain one additional 5th-level spell slot for one arcane spellcasting class you have levels in.</p>
</>};
const _arodens_array = {title: "Aroden's Array", jsx: <><h2 id="magic-set-arodens_array-arodens-array">Aroden's Array</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 25</Link></p>
<p>While the <Link to="/magic-artifact/shield_of_aroden">Shield of Aroden</Link>, now known as the Shattered Shield of Arnisant, is famous for its role in defeating <Link to="/monster/the_whispering_tyrant">the Whispering Tyrant</Link>, it was not the only holy relic carried by General Arnisant during his fateful confrontation with Tar-Baphon. While the shield was shattered, the other relics survived, and these items or potent copies of them have protected heroic knights and paladins to this day.</p>
<p><strong><Link to="/magic-wondrous/belt_of_fallen_heroes">Belt of Fallen Heroes:</Link></strong> For every two additional pieces of this set you wear or wield, the insight bonus on saving throws granted by this belt increases by 1.</p>
<p><strong><Link to="/magic-armor/daystar_half_plate">Daystar Half-Plate:</Link></strong> For every two additional pieces of this set you wear or wield, the enhancement bonus of this suit of armor increases by 1.</p>
<p><strong><Link to="/magic-ring/ring_of_the_ecclesiarch">Ring of the Ecclesiarch:</Link></strong> For every two additional pieces of this set you wear or wield, you can use this ring to use <Link to="/spell/prayer">prayer</Link> one additional time per day.</p>
<p><strong><Link to="/magic-weapon/sun_blade">Sun Blade:</Link></strong> For every two additional pieces of this set you wear, the enhancement bonus of this weapon increases by 1; this also improves the increased enhancement bonus when using it against evil creatures.</p>
<p><strong><Link to="/magic-wondrous/winged_boots">Winged Boots:</Link></strong> For every two additional pieces of this set you wear or wield, you can use these boots to fly one additional time per day.</p>
<p><strong className="hl">Two-Item Benefit:</strong> While you are wearing or wielding at least two pieces of this set, you gain a +1 circumstance bonus on saving throws against negative energy or death effects.</p>
<p><strong className="hl">Three-Item Benefit:</strong> While you are wearing or wielding at least three pieces of this set, the circumstance bonus on saving throws against negative energy or death effects increases to +2.</p>
<p><strong className="hl">Four-Item Benefit:</strong> While you are wearing or wielding at least four pieces of this set, you gain a +4 circumstance bonus on Will saving throws against fear effects.</p>
<p><strong className="hl">Five-Item Benefit:</strong> When wearing and wielding all five pieces of this set, once per day as an immediate action you can maximize the effects of a single healing effect targeting you, treating all dice rolled as part of the effect as though they had rolled the maximum possible value.</p>
</>};
const _beastmasters_will = {title: "Beastmaster's Will", jsx: <><h2 id="magic-set-beastmasters_will-beastmasters-will">Beastmaster's Will</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 25</Link></p>
<p>At times, nature will grant its greatest champions gifts in the form of magical relics. Among these gifts, nature bestows Beastmaster's Will to those who defend animal life.</p>
<p><strong><Link to="/magic-wondrous/boots_of_the_cat">Boots of the Cat:</Link></strong> For every additional piece of this set you wear, you treat all <Link to="/rule/falling">falls</Link> as of they were 10 feet shorter.</p>
<p><strong><Link to="/magic-wondrous/cloak_of_the_bat">Cloak of the Bat:</Link></strong> For every two pieces of this set you wear, the duration you can use this cloak to fly at a given time increases by 1 minute.</p>
<p><strong><Link to="/magic-wondrous/eyes_of_the_eagle">Eyes of the Eagle:</Link></strong> For every additional piece of this set you wear, the competence bonus of these lenses increases by 2.</p>
<p><strong><Link to="/magic-wondrous/monkey_belt_greater">Monkey Belt (Greater):</Link></strong> While you are wearing all four pieces of this set, the enhancement bonus of this item increases by 2 and you gain a 20-foot climb speed.</p>
<p><strong className="hl">Two-Item Benefit:</strong> When wearing at least two pieces of this set, you gain the <Link to="/ability/wild_empathy">wild empathy</Link> class feature, treating your character level as your druid level.</p>
<p><strong className="hl">Three-Item Benefit:</strong> When wearing at least three pieces of this set, you can cast <Link to="/spell/beast_shape_ii">beast shape II</Link> once per day as a spell-like ability, treating your character level as your caster level.</p>
<p><strong className="hl">Four-Item Benefit:</strong> When wearing all four pieces of this set, you gain the <Link to="/ability/animal_focus">animal focus</Link> class feature with an effective hunter level equal to your character level - 4. You can only use this ability on yourself in 1-minute increments and not an any animal companion you may have. The animal focus class feature you gain from this equipment set is separate of that from any other source.</p>
</>};
const _besmaras_bounty = {title: "Besmara's Bounty", jsx: <><h2 id="magic-set-besmaras_bounty-besmaras-bounty">Besmara's Bounty</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 26</Link></p>
<p>The <Link to="/faith/besmara">Pirate Queen</Link> has few priests but many devoted followers. It is said that the collection of magical items collectively known as Besmara's Bounty can be completely assembled only by those graced with the Sea Banshee's favor.</p>
<p><strong><Link to="/magic-wondrous/bracelet_of_bargaining">Bracelet of Bargaining:</Link></strong> For each additional piece of this set you wear or wield, the Will saving throw DC to resist this item's ability to detect deceit increases by 1.</p>
<p><strong><Link to="/magic-weapon/disarming_blade">Disarming Blade:</Link></strong> For every two additional pieces of this set you wear or wield, the enhancement bonus of this weapon increases by 1 and you gain a +1 circumstance bonus on combat maneuver checks to disarm.</p>
<p><strong><Link to="/magic-armor/enchanted_eelskin">Enchanted Eelskin:</Link></strong> For every two additional pieces of this set you wear or wield, the enhancement bonus of this suit of armor increases by 1.</p>
<p><strong><Link to="/magic-wondrous/jellyfish_cape">Jellyfish Cape:</Link></strong> For every two additional pieces of this set you wear or wield, the electricity damage dealt by this item's tentacles increases by 1d4 and the DC to resist being sickened by their sting increases by 1.</p>
<p><strong><Link to="/magic-wondrous/sea_tyrants_patch">Sea Tyrant's Patch:</Link></strong> While you are wearing and wielding all five pieces of this set, you can use this item's ability to use <Link to="/spell/mass_charm_monster">mass charm monster</Link> one additional time per day.</p>
<p><strong className="hl">Two-Item Benefit:</strong> While you are wearing or wielding at least two pieces of this set, you gain a +1 circumstance bonus on <Link to="/skill/acrobatics">Acrobatics</Link> checks to balance and <Link to="/skill/swim">Swim</Link> checks.</p>
<p><strong className="hl">Three-Item Benefit:</strong> While you are wearing or wielding at least three pieces of this set, the circumstance bonus on Acrobatics checks to balance and Swim checks increases to +2.</p>
<p><strong className="hl">Four-Item Benefit:</strong> While you are wearing or wielding at least four pieces of this set, you gain a +10-foot enhancement bonus to your swim speed if you have one.</p>
<p><strong className="hl">Five-Item Benefit:</strong> While you are wearing and wielding all five pieces of this set, the enhancement bonus to your swim speed (if any) increases to +20.</p>
</>};
const _dread_demonic_armor = {title: "Dread Demonic Armor", jsx: <><h2 id="magic-set-dread_demonic_armor-dread-demonic-armor">Dread Demonic Armor</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 26</Link></p>
<p>As <Link to="/faith/deskari">Deskari's</Link> dread hordes surged forth from the Worldwound, many mortals joined the demon lord's forces, some willingly and some through the most wicked coercions. To the most powerful and deadly of these mortal conscripts were given sets of Dread Demoniac Armor, giving them powers akin to those wielded by the <Link to="/family/demon">demons</Link> themselves. These sets of armor are said to buzz with the sound of locusts.</p>
<p><strong><Link to="/magic-wondrous/deliquescent_gloves">Deliquescent Gloves:</Link></strong> For every two additional pieces of this set you wear, you deal an additional 1d6 points of acid damage when using these gloves to make a melee touch attack.</p>
<p><strong><Link to="/magic-armor/demon_armor">Demon Armor:</Link></strong> For every two additional pieces of this set you wear, the enhancement bonus of the claws granted by this dread suit of armor increases by 1.</p>
<p><strong><Link to="/magic-ring/ring_of_retribution">Ring of Retribution:</Link></strong> For every two additional pieces of this set you wear, the DC to resist this ring's fire damage effect increases by 1.</p>
<p><strong><Link to="/magic-wondrous/shadowform_belt">Shadowform Belt:</Link></strong> For each additional piece of this set you wear, you can use this item's ability to become incorporeal for 1 additional round per day.</p>
<p><strong><Link to="/magic-wondrous/shirt_of_immolation">Shirt of Immolation:</Link></strong> For each additional piece of this set you wear, this shirt can stay ignited for 1 additional round per day.</p>
<p><strong className="hl">Two-Item Benefit:</strong> While you are wearing at least two pieces of this set, you gain a +1 circumstance bonus on <Link to="/skill/intimidate">Intimidate</Link> checks.</p>
<p><strong className="hl">Three-Item Benefit:</strong> While you are wearing at least three pieces of this set, you gain fire resistance 5.</p>
<p><strong className="hl">Four-Item Benefit:</strong> While you are wearing at least four pieces of this set, the granted fire resistance increases to 10.</p>
<p><strong className="hl">Five-Item Benefit:</strong> While you are wearing all five pieces of this set, you gain immunity to fire damage.</p>
</>};
const _iroris_meditation = {title: "Irori's Meditation", jsx: <><h2 id="magic-set-iroris_meditation-iroris-meditation">Irori's Meditation</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 27</Link></p>
<p>As a mortal, <Link to="/faith/irori">Irori</Link> committed to a lifestyle of intense discipline and self-actualization, a dedication that persists through Irori's followers to this day. Legends state that as he approached enlightenment, Irori began to shed the need for the material, giving up many of his earthly possessions, which were then passed on through generations of students as they followed in his footsteps. Irori's Meditation is a set of simple trappings that are said to include a single thread from Irori's original belongings and help Iroran's find inner balance and aid them in their journey towards the true enlightenment they seek.</p>
<p><strong><Link to="/magic-wondrous/bodywrap_of_mighty_strikes_1">Bodywrap of Mighty Strikes +1</Link>:</strong> For every additional piece of this set you wear, you can add this item's enhancement to one additional attack and damage roll per round.</p>
<p><strong><Link to="/magic-wondrous/monks_robe">Monk's Robe</Link>:</strong> While you are wearing all three pieces of this set, the bonus to AC you gain from your effective monk levels granted by this item increases by 2, exceeding the monk's AC bonus maximum of +5 if applicable.</p>
<p><strong><Link to="/magic-wondrous/necklace_of_ki_serenity">Necklace of Ki Serenity</Link>:</strong> For every additional piece of this set you wear, you increase this item's bonus by 1.</p>
<p><strong className="hl">Two-Item Benefit:</strong> When wearing at least two pieces of this set, you gain a +4 insight bonus to CMD.</p>
<p><strong className="hl">Three-Item Benefit:</strong> When wearing all three pieces of this set, your base speed increases by 10 feet.</p>
</>};
const _pharasmas_command = {title: "Pharasma's Command", jsx: <><h2 id="magic-set-pharasmas_command-pharasmas-command">Pharasma's Command</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 27</Link></p>
<p>The Lady of Graves oversees the natural cycle of life, death, and rebirth. As such, the very existence of undead is anathema to her goals and purpose. <Link to="/faith/pharasma">Pharasma</Link> commands her faithful to destroy the undead wherever she finds them, but the Mother of Souls is not so cruel as to give her worshippers commands without providing the tools to successfully complete them. Pharasma's Command is a set of holy equipment first assembled to safeguard the most daring and adventurous of her mortal servants.</p>
<p><strong><Link to="/magic-wondrous/cassock_of_the_clergy">Cassock of the Clergy:</Link></strong> For every two additional pieces of this set you wear or wield, you can use <Link to="/spell/bless">bless</Link> and <Link to="/spell/sanctuary">sanctuary</Link> one additional time per day, and the DC for <em>sanctuary</em> spells cast in this way increases by 2.</p>
<p><strong><Link to="/magic-wondrous/deathwatch_eyes">Deathwatch Eyes:</Link></strong> For every two additional pieces of this set you wear or wield, you gain a +1 circumstance bonus on Perception checks.</p>
<p><strong><Link to="/magic-ring/ring_of_the_grasping_grave">Ring of the Grasping Grave:</Link></strong> For every two additional pieces of this set you wear or wield, the melee touch attack granted by this ring deals an additional 1d6 points of positive energy damage to undead on a successful attack.</p>
<p><strong><Link to="/magic-weapon/spirit_blade">Spirit Blade:</Link></strong> For every two additional pieces of this set you wear or wield, you can use this blade's ability to <Link to="/spell/dispel_magic">dispel magic</Link> one additional time per day.</p>
<p><strong><Link to="/magic-staff/staff_of_souls">Staff of Souls:</Link></strong> While you are wearing and wielding all five pieces of this set, you can expend 2 charges from this staff to cast <Link to="/spell/undeath_to_death">undeath to death</Link>.</p>
<p><strong className="hl">Two-Item Benefit:</strong> When wearing or wielding at least two pieces of this set, you gain a +1 circumstance on saving throws against death effects.</p>
<p><strong className="hl">Three-Item Benefit:</strong> When wearing or wielding at least three pieces of this set, you gain a +1 circumstance on saving throws to resist <Link to="/rule/energy_drain">energy drain</Link>.</p>
<p><strong className="hl">Four-Item Benefit:</strong> When wearing or wielding at least four pieces of this set, the circumstance bonuses on saving throws to resist death effects and energy drain increase to +2.</p>
<p><strong className="hl">Five-Item Benefit:</strong> When wearing and wielding all five pieces of this set, you gain immunity to death effects.</p>
</>};
const _urgathoas_gluttony = {title: "Urgathoa's Gluttony", jsx: <><h2 id="magic-set-urgathoas_gluttony-urgathoas-gluttony">Urgathoa's Gluttony</h2>
<p><strong>Sources</strong> <Link to="/source/chronicle_of_legends">Chronicle of Legends pg. 27</Link></p>
<p><Link to="/faith/urgathoa">Urgathoa</Link> is the goddess of disease, gluttony, and undeath. Worshipped by dark necromancers, the undead, and those wishing to become undead, Urgathoa bestows dark and terrible blessings on her followers. One of the greatest manifestations of Urgathoa's favor is seen when the set of magical items known as Urgathoa's Gluttony is assembled and worn by a single individual, granting him the powers of some of the greatest forms of undead and the tiniest fraction of the power utilized by Urgathoa herself. Dozens of flies and worms are said to constantly follow those wearing this equipment set.</p>
<p><strong><Link to="/magic-wondrous/haunted_shoes">Haunted Shoes:</Link></strong> For every two additional pieces of this set you wear or wield, you can use each of the abilities granted by these shoes one additional time per day.</p>
<p><strong><Link to="/magic-wondrous/mask_of_the_skull">Mask of the Skull:</Link></strong> For each additional piece of this set you wear or wield, the AC and hardness of this mask increase by 1 and it gains 5 additional hit points.</p>
<p><strong><Link to="/magic-ring/ring_of_rat_fangs">Ring of Rat Fangs:</Link></strong> For each additional piece of this set you wear or wield, the bite attack granted by this ring deals 1 additional point of <Link to="/rule/bleed">bleed</Link> damage.</p>
<p><strong><Link to="/magic-wondrous/robe_of_bones">Robe of Bones:</Link></strong> For every two additional pieces of this set you wear or wield, this robe regenerates one expended undead per hour. Creating more than two of any single type of undead with this robe destroys the first undead of that type you created.</p>
<p><strong><Link to="/magic-weapon/void_scythe">Void Scythe:</Link></strong> For every two additional pieces of this set you wear or wield, the enhancement bonus of this weapon increases by 1, and the DC to resist <Link to="/rule/negative_levels">negative levels</Link> imposed by this blade increases by 1.</p>
<p><strong className="hl">Two-Item Benefit:</strong> While you are wearing or wielding at least two pieces of this set, you begin overflowing with Urgathoa's dark power, adding 1 point of negative energy damage to each of your melee attacks. This negative energy damage cannot heal creatures that are healed by negative energy.</p>
<p><strong className="hl">Three-Item Benefit:</strong> While you are wearing or wielding at least three pieces of this set, the negative energy added to your melee attacks increases to 5 points.</p>
<p><strong className="hl">Four-Item Benefit:</strong> While you are wearing or wielding at least four pieces of this set, you gain a +1 profane bonus on attack rolls.</p>
<p><strong className="hl">Five-Item Benefit:</strong> While you are wearing and wielding all five pieces of this set, you are imbued with the powers of undeath and react to negative and positive energy as though you were undead; you are healed by negative energy and harmed by positive energy.</p>
</>};
export default {archmages_vestments:_archmages_vestments,arodens_array:_arodens_array,beastmasters_will:_beastmasters_will,besmaras_bounty:_besmaras_bounty,dread_demonic_armor:_dread_demonic_armor,iroris_meditation:_iroris_meditation,pharasmas_command:_pharasmas_command,urgathoas_gluttony:_urgathoas_gluttony}