import Link from '../../components/Link';
const _not_found = {title: "Unknown", jsx: <><h2 id="implement-not_found-error">Error</h2>
<p>Unable to find the requested implement.</p>
</>};
const _abjuration = {title: "Abjuration", jsx: <><h2 id="implement-abjuration-abjuration">Abjuration</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 50</Link><br/>Abjuration implements are objects associated with protection and wards.</p>
<p><strong>Implements:</strong> Amulet, armor, bell, bracers, brooch, cloak, holy symbol, shield.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an abjuration implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Warding Talisman (Su):</strong> The implement wards against adverse effects. Whoever wears (or holds, for bells) the implement gains a +1 resistance bonus on saving throws for every 2 points of mental focus invested in the implement, to a maximum bonus of 1 + 1 for every 4 occultist levels you possess.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use abjuration implements gain the following focus power.</p>
<blockquote>
<p><strong>Mind Barrier (Sp):</strong> As a swift action, you can expend 1 point of mental focus to create a shield of mental energy around you that protects you from harm. The shield prevents a total of 2 points of damage per occultist level you possess. It lasts until the start of your next turn or until exhausted. For example, if you are 5th level, the mind barrier protects you from 10 points of damage; if you are hit by an attack that would deal 12 points of damage, the mind barrier is exhausted and you take 2 points of damage. You can activate this ability as an immediate action, but doing so costs 2 points of mental focus instead of 1.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use abjuration implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Aegis (Su):</strong> As a standard action, you can expend 1 point of mental focus and touch a suit of armor or a shield to grant it an enhancement bonus. The bonus is equal to 1 + 1 for every 6 occultist levels you possess (to a maximum bonus of +4 at 18th level). Enhancement bonuses gained via this ability stack with those of the armor or shield, to a maximum total enhancement bonus of +5. You can also imbue the armor or shield with any one armor or shield <Link to="/main/magic_enhancements">special ability</Link> that has an equivalent enhancement bonus less than or equal to your maximum bonus granted by this ability by reducing the granted enhancement bonus by the appropriate amount. The item must have an enhancement bonus of at least +1 (from the item itself or from aegis) to gain an armor or shield special ability. In either case, these bonuses last for 1 minute.</p>
<p><strong>Energy Shield (Sp):</strong> As a swift action, you can expend 1 point of mental focus to surround yourself with a shield that protects you from energy damage. Whenever you take acid, cold, electricity, or fire damage, the shield absorbs the damage (as <Link to="/spell/protection_from_energy">protection from energy</Link>). The energy shield can absorb up to 5 points of energy damage per occultist level you possess. This shield lasts for 1 minute or until its power is exhausted. Its effect doesn't stack with itself, with <em>protection from energy,</em> or with <Link to="/spell/resist_energy">resist energy</Link>. You can activate the energy shield as an immediate action by expending 2 points of mental focus instead of 1. You must be at least 3rd level to select this focus power.</p>
<p><strong>Globe of Negation (Sp):</strong> As a standard action, you can expend 3 points of mental focus to create a stationary globe of negation. This globe is 10 feet in diameter and cancels any spell effect that is cast into or through its area. This functions as <Link to="/spell/globe_of_invulnerability">globe of invulnerability</Link>, but it affects spells of any level. The globe can negate a total number of spell levels equal to your occultist level, after which the globe collapses. Spells that exceed the number of remaining levels remove all remaining levels, but are weakened; any creatures targeted by such spells receive a +4 circumstance bonus on any saving throws against the spells' effects. The globe lasts for a number of rounds equal to your occultist level. It has no effect on spells originating within the globe - only on those that enter its area as or after they are cast. You must be at least 11th level to select this focus power.</p>
<p><strong>Loci Sentry (Sp):</strong> As a standard action, you can expend 1 point of mental focus to set a ward about an area. This area has a maximum radius of 10 feet + 5 feet per occultist level you possess. Whenever a creature enters the area, a sentry manifested by your psyche appears and strikes out at the intruder. The affected creature must succeed at a Will save or be <Link to="/misc/dazed">dazed</Link> for 1 round. You are immediately aware of the sentry's activation. The sentry lasts for up to 1 hour per occultist level you possess, or until triggered. When you set the sentry, you can set any number of specific creatures to be immune to the sentry and thus avoid triggering it.</p>
<p><strong>Planar Ward (Sp):</strong> As a standard action, you can expend 2 points of mental focus to surround yourself with a planar ward. Creatures not native to the plane that you are currently on take a -4 penalty on attacks against you, and you receive a +4 circumstance bonus on saving throws against the spells, spell-like abilities, and supernatural abilities of such creatures. This ward lasts for 1 minute.</p>
<p><strong>Unraveling (Sp):</strong> As a standard action, you can expend 1 point of mental focus to unravel a magical effect. This functions as a targeted <Link to="/spell/dispel_magic">dispel magic</Link> spell, but you must be adjacent to the effect to unravel it. If the effect is created by psychic magic, you receive a +5 bonus on your caster level check to unravel it. If the effect targets an object in your possession, you automatically succeed at the check. You must be at least 5th level to select this focus power.</p>
<h3 id="implement-abjuration-sacred-implement">Sacred Implement</h3>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 15</Link></p>
<p><strong>Deity</strong> <Link to="/faith/pharasma">Pharasma</Link>; <strong>Implement</strong> brooch; <strong>Opposition School</strong> necromancy</p>
<p><strong>Grandmother's Ward (Su):</strong> As a standard action, you can expend 3 points of psychic focus to create a 5-foot-radius ward centered on you for 1 round per occultist level. This ward burns undead creatures, dealing an amount of damage equal to 1d4 + 1d4 per 2 occultist levels you have when the undead enter the ward and each round they begin their turns within this area of effect. The warded area moves with you and can be used only defensively. Any attempt to force the ward against an undead creature immediately ends the effect.</p>
</blockquote>
</>};
const _conjuration = {title: "Conjuration", jsx: <><h2 id="implement-conjuration-conjuration">Conjuration</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 51</Link><br/>Implements used in conjuration allow the occultist to perform magic that transports or calls creatures.</p>
<p><strong>Implements:</strong> Bowl, brazier, compass, figurine, lantern, mirror.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an conjuration implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Casting Focus (Su):</strong> The implement empowers the bearer's ties to the worlds beyond, allowing his spells to maintain their power for a longer period of time. The bearer can add the implement as an additional focus component to any conjuration spell he casts that has a duration measured in rounds per level. If he does so, he adds 1 to his caster level for every 2 points of mental focus stored in the implement (to a maximum bonus equal to your occultist level). This increase applies only when determining the duration of the spell. Apply this increase after other effects that adjust a spell's duration, such as <Link to="/feat/extend_spell">Extend Spell</Link>.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use conjuration implements gain the following focus power.</p>
<blockquote>
<p><strong>Servitor (Sp):</strong> As a standard action, you can expend 1 point of mental focus to summon a servitor. This ability functions as <Link to="/spell/summon_monster_i">summon monster I</Link>, but you can use it only to summon a single creature, and the effect lasts for 1 minute. At 4th level and every 3 levels thereafter, the level of the summon monster spell increases by 1, to a maximum of <Link to="/spell/summon_monster_vii">summon monster VII</Link> at 19th level. You can't have more than one servitor in effect at a time. At any time, you can expend 1 point of mental focus as a free action to extend the duration of an active servitor by 1 minute.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use conjuration implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Conjure Implement (Sp):</strong> You can expend 1 point of mental focus to conjure any item that qualifies as an implement that you know how to use. This implement can be used as the item in question, functioning as a masterwork version of that item, and can also be used to cast your psychic spells, even though you did not select it at the beginning of the day. If you have more than one implement for the same school, decide which set of spells the conjured implement will grant when you first conjure it. The implement can't be used to store mental focus or create any effects that require mental focus. The implement lasts for 10 minutes per occultist level you possess.</p>
<p><strong>Flesh Mend (Sp):</strong> As a standard action, you can expend 1 point of mental focus to heal a living creature with a touch. The creature is healed an amount of damage equal to 1d8 + your occultist level. For every 4 occultist levels you possess beyond 3rd, the creature is healed an additional 1d8 points of damage, to a maximum of 5d8+19 at 19th level. This has no effect on undead creatures. You must be at least 3rd level to select this focus power.</p>
<p><strong>Mind Steed (Sp):</strong> As a standard action, you can expend 1 point of mental focus to conjure a spectral horse. This horse can be either Medium or Large, but it otherwise functions as <Link to="/spell/mount">mount</Link>. The horse lasts for 10 minutes per occultist level you possess. If you are at least 5th level, the mount's base land speed increases by 20 feet. If you are at least 9th level and you expend 1 additional point of mental focus, the mount can fly at a speed of 60 feet with good maneuverability, but doing so reduces the mount's duration to 1 minute per occultist level you possess.</p>
<p><strong>Psychic Fog (Sp):</strong> As a standard action, you can expend 1 point of mental focus to create a cloud of fog. This fog lasts for 1 minute per occultist level you possess. It functions as <Link to="/spell/fog_cloud">fog cloud</Link>, except it can't be dispersed by wind. At 7th level, you can expend 1 additional point of mental focus when creating this fog, causing it to become more tangible and function as <Link to="/spell/solid_fog">solid fog</Link>, except it doesn't slow down any creature that has psychic powers or that can cast psychic spells. When you create a solid fog in this way, its duration is reduced to 1 round per occultist level you possess. You must be at least 3rd level to select this focus power.</p>
<p><strong>Purge Corruption (Sp):</strong> As a standard action, you can expend 1 point of mental focus to draw out the corruption from a creature. You must touch the target with your implement to use this power. This ability functions as either <Link to="/spell/neutralize_poison">neutralize poison</Link> or <Link to="/spell/remove_disease">remove disease</Link>, using your occultist level as the caster level. Each use of this ability can cure only one poison or one disease. You must be at least 5th level to select this focus power.</p>
<p><strong>Side Step (Sp):</strong> You can create a temporary fissure in space by expending 1 point of mental focus. You can use this ability as part of a move action taken to move. The fissure begins in any square you designate and allows you to teleport to any other square you can see within 10 feet per occultist level. Stepping between these locations requires you to expend 5 feet of movement, and the movement through the rift does not provoke attacks of opportunity. This otherwise functions as <Link to="/spell/teleport">teleport</Link>. You must be at least 7th level to select this focus power.</p>
<h3 id="implement-conjuration-sacred-implement">Sacred Implement</h3>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 15</Link></p>
<p><strong>Deity</strong> <Link to="/faith/asmodeus">Asmodeus</Link>; <strong>Implement</strong> bowl; <strong>Opposition School</strong> transmutation</p>
<p><strong>Amber Prison (Su):</strong> You can expend 3 points of mental focus to entomb a creature within 40 feet in an amber-like prison, rendering it <Link to="/rule/paralyzed">paralyzed</Link> and <Link to="/misc/unconscious">unconscious</Link> for 1 minute per occultist level you have. The amber prison has 20 hit points; destroying the prison frees the creature. A successful Reflex save negates this entombment. Whether or not the saving throw is successful, the creature can't be the target of this focus power again for 1 day.</p>
</blockquote>
</>};
const _divination = {title: "Divination", jsx: <><h2 id="implement-divination-divination">Divination</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 52</Link><br/>Implements of the divination school grant powers related to foresight and remote viewing.</p>
<p><strong>Implements:</strong> Book, crystal ball, goggles, harrow deck, headband, lenses, planchette.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an divination implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Third Eye (Su):</strong> The implement allows its bearer to notice that which can't easily be seen. The implement grants a +1 insight bonus on Perception checks per 2 points of mental focus stored in it, to a maximum bonus equal to the occultist's level. If the occultist is 3rd level or higher and stores at least 3 points of mental focus in it, the implement also grants low-light vision. If the occultist is 5th level or higher and stores at least 6 points of mental focus in it, the implement also grants darkvision 60 feet. (If the bearer already has darkvision, the implement increases the range of the darkvision by 30 feet.) If the occultist is 7th level or higher and stores at least 9 points of mental focus in it, the implement also grants the effects of <Link to="/spell/see_invisibility">see invisibility</Link>. If the occultist is 13th level or higher and stores at least 12 points of mental focus in it, the implement also grants <Link to="/umr/blindsense">blindsense</Link> 60 feet. If the occultist is 19th level or higher and stores at least 15 points of mental focus in it, the implement also grants <Link to="/umr/blindsight">blindsight</Link> 30 feet.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use divination implements gain the following focus power.</p>
<blockquote>
<p><strong>Sudden Insight (Sp):</strong> As a swift action, you can expend 1 point of mental focus to gain an insight into your immediate future. You can use this foreknowledge as a free action before you roll any ability check, attack roll, or skill check to gain an insight bonus on that roll equal to 1/2 your occultist level (minimum +1). You can use your foreknowledge only once per turn, and if it's not used by the end of your turn, the insight fades and you gain no benefit.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use divination implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Danger Sight (Sp):</strong> As an immediate action, you can protect yourself from harm by expending 1 point of mental focus. You can use this ability whenever you are the target of an attack or are required to attempt a saving throw against a special ability, spell, or trap. Doing so grants you an insight bonus to your AC or on your saving throw equal to 1/2 your occultist level. This bonus applies only to the next attack against you or saving throw you attempt, and if not applied by the end of the round, the protection fades and you gain no benefit. You must be at least 3rd level to select this focus power.</p>
<p><strong>Future Gaze (Sp):</strong> As a standard action, you can gain an insight into the future by expending 1 point of mental focus. This functions as <Link to="/spell/augury">augury</Link>, using your occultist level as the caster level.</p>
<p><strong>Mind Eye (Sp):</strong> As a standard action, you can expend 1 point of mental focus to create a mind eye - a magical sensor through which you can see and hear. The mind eye is invisible and its size is Fine, giving it an AC of 18. Any amount of damage to the eye destroys it, but it can be harmed by only spells or magic weapons. The eye moves with a fly speed of 60 feet with perfect maneuverability and can travel up to 1 mile away from you. You must concentrate as a standard action to direct the eye and receive sensory images through it. The mind eye sees as your eyes see, including any additional senses you possess (such as darkvision or <em>see invisibility</em>). The mind eye lasts for 1 minute per occultist level you possess. You must be at least 5th level to select this focus power.</p>
<p><strong>Object Seer (Sp):</strong> As a full-round action, you can expend 1 point of mental focus to gain insight into an object in your possession. You can ask one question, but that question must be tied in some way to the object, such as the nature of its power, the identity of the creature that last possessed it, or even where the object was when a certain event took place. You always receive an answer from the psychic impressions imprinted upon the item, but they are sometimes cryptic or misleading. This ability otherwise functions as <Link to="/spell/commune">commune</Link>. You must be at least 7th level to select this focus power.</p>
<p><strong>Powerful Connection (Su):</strong> When casting a divination spell (such as <Link to="/spell/scrying">scrying</Link>) that imposes a penalty on saving throws based on the physical connection you have to the target, you can expend 1 point of mental focus to double the penalty from a possession, garment, or body part. In addition, when casting any other divination spell that allows a saving throw, you can increase the DC of that save by 2 by adding an object, garment, or body part that belonged to the target as a focus component for the spell and expending 1 point of mental focus.</p>
<p><strong>Watchful Eye (Sp):</strong> You can expend 1 point of mental focus as a standard action to create an invisible sensor within 30 feet that watches a 5-foot-square area. Whenever any creature enters that square, you receive a mental image of the creature as long as you are on the same plane as the sensor. The sensor remains active for 10 minutes per occultist level you possess. The image will not wake you from slumber, although you do receive all of the images the sensor collected once you wake up. The sensor can be deceived by <Link to="/spell/invisibility">invisibility</Link> and similar magic. You can expend additional points of mental focus when creating the eye to increase the size of the square by 5 feet per additional point spent (to 10 feet square, 15 feet square, and so on).</p>
</blockquote>
</>};
const _enchantment = {title: "Enchantment", jsx: <><h2 id="implement-enchantment-enchantment">Enchantment</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 53</Link><br/>Enchantment implements allow the occultist to befuddle the mind and charm his foes.</p>
<p><strong>Implements:</strong> Censer, crown, helm, musical instrument, necklace.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an enchantment implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Glorious Presence (Su):</strong> The implement invokes the presence of those who have worn it in the past. The implement's wearer gains a +1 competence bonus on all Charisma-based skill checks and ability checks for every 2 points of mental focus invested in the implement, to a maximum bonus of 1 + 1 for every 4 occultist levels you possess.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use enchantment implements gain the following focus power.</p>
<blockquote>
<p><strong>Cloud Mind (Su):</strong> As a standard action, you can expend 1 point of mental focus to cloud the mind of one foe within 30 feet. That foe is <Link to="/misc/dazed">dazed</Link> for 1 round if the number of Hit Dice it possesses is less than or equal to or your occultist level. If it has more Hit Dice than your occultist level, it is <Link to="/misc/staggered">staggered</Link> for 1 round instead. The foe can attempt a Will saving throw to negate the effect. Whether or not it succeeds at the save, the target is then immune to this effect for 1 day. This is a mind-affecting effect.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use enchantment implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Binding Pattern (Sp):</strong> As a standard action, you can expend 1 point of mental focus to create a binding pattern of psychic energy that causes a living creature to become <Link to="/rule/paralyzed">paralyzed</Link>. The target must be within 30 feet of you, and it can attempt a Will saving throw to negate the effect. If it fails the save, it is paralyzed for 1 round for every 2 occultist levels you possess. At the end of each of its turns, it can attempt another Will save to end the paralyzed effect and instead be staggered for the remaining duration. This is a mind-affecting compulsion effect. You must be at least 7th level to select this focus power.</p>
<p><strong>Forced Alliance (Sp):</strong> As a standard action, you can alter a living creature's mind, causing it to see you as a friend and ally. If the creature is the same creature type as you, this power requires you to expend 1 point of mental focus; if it's is not, you must expend 2 points instead. The creature can attempt a Will save to negate this effect. If it fails the saving throw, the creature treats you as an ally and doesn't attempt to harm you (although your allies are not protected). You can call on the creature to aid you directly, but while doing so the creature can attempt a new Will save at the end of each round to end the effect. This effect otherwise lasts 1 round per occultist level you possess. This is a mind-affecting charm effect. You must be at least 5th level to select this focus power.</p>
<p><strong>Inspired Assault (Sp):</strong> As a standard action, you can inspire a living creature with a touch by expending 1 point of mental focus. The creature receives a morale bonus on attack rolls equal to 1 + 1 for every 6 occultist levels you possess (to a maximum bonus of +4 at 18th level). This bonus also applies on saving throws against fear effects. This bonus lasts for 1 minute.</p>
<p><strong>Mental Discord (Sp):</strong> As a standard action, you can expend 1 point of mental focus to disrupt the mind of one living creature within 30 feet. The creature can attempt a Will saving throw to negate the effect. If it fails the save, the creature can't concentrate on any spell effects and must succeed at a <Link to="/rule/concentration">concentration</Link> check to cast any spell (DC = 15 + double the spell level). The affected creature takes a -4 penalty on this check if the spell includes a thought component. The creature takes a -2 penalty on all Will saving throws while under this effect. This effect lasts for 1 round per occultist level you possess.</p>
<p><strong>Mind Slumber (Sp):</strong> By expending 1 point of mental focus as a standard action, you can lull a living creature into a deep mental slumber, forcing it to view the world as a dream. The target must be within 30 feet of you, and it can attempt a Will saving throw to negate the effect. If it fails the save, the creature falls asleep, although it still perceives the world around it as a dream. This doesn't cause the creature to fall prone, but it does drop whatever it is holding. The creature can't take any actions while in this state, but it isn't helpless - it perceives danger as part of its dream. The creature remains asleep for a number of rounds equal to your occultist level or until it takes any amount of damage, which immediately wakes it. At the end of each of its turns, it receives another Will saving throw to end the effect. The creature can be manipulated or examined without waking it, but it can't be moved from its square without waking it. This is a mind-affecting compulsion effect. Regardless of whether it succeeds at the save, the target is then immune to this effect for 24 hours. You must be at least 3rd level to select this focus power.</p>
<p><strong>Obey (Sp):</strong> As a standard action, you can issue a command to one living creature by expending 1 point of mental focus. This functions as <Link to="/spell/command">command</Link>. The target must be within 30 feet and capable of understanding your order. The target can attempt a Will save to negate this effect. If the creature is the same creature type as you, it takes a -2 penalty on this saving throw.</p>
</blockquote>
<h3 id="implement-enchantment-sacred-implement">Sacred Implement</h3>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 15</Link></p>
<p><strong>Deity</strong> <Link to="/faith/aroden">Aroden</Link>; <strong>Implement</strong> necklace; <strong>Opposition School</strong> illusion</p>
<p><strong>Forgotten (Sp):</strong> As a standard action, you can expend 3 points of mental focus to target a single creature within 30 feet using <Link to="/spell/modify_memory">modify memory</Link>. This ability can be used only to cause the target to forget the last 5 minutes of interaction with you.</p>
</>};
const _evocation = {title: "Evocation", jsx: <><h2 id="implement-evocation-evocation">Evocation</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 54</Link><br/>Implements focused on evocation grant the ability to create and direct energy to protect and to destroy.</p>
<p><strong>Implements:</strong> Gloves, rod, staff, wand.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an evocation implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Intense Focus (Su):</strong> The implement channels and enhances the effects of damaging evocations. A spellcaster who bears the implement can add the implement as an additional focus component for any of his damaging evocation spells that have an instantaneous duration or focus powers with an instantaneous duration. If he does so, the spell or focus power deals 1 additional point of damage of the same type to each creature for every 2 points of mental focus invested in the implement, to a maximum of 1 + 1 for every 2 occultist levels you possess.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use evocation implements gain the following focus power.</p>
<blockquote>
<p><strong>Energy Ray (Sp):</strong> As a standard action that provokes attacks of opportunity, you can expend 1 point of mental focus to unleash a ray of pure energy as a ranged touch attack. This ray has a range of 30 feet. The ray deals an amount of energy damage equal to 1d6 points + 1d6 points for every 2 occultist levels you possess beyond 1st (2d6 at 3rd level, 3d6 at 5th, and so on, to a maximum of 10d6 at 19th level). When you unleash an energy ray, you must decide what type of damage it deals (acid, cold, electricity, or fire).</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use evocation implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Energy Blast (Sp):</strong> As a standard action that provokes attacks of opportunity, you can expend 2 points of mental focus to unleash a blast of energy. This blast has a range of 100 feet, and deals 5d6 points of energy damage, plus an additional 1d6 points for every 2 occultist levels you possess beyond 5th (6d6 at 7th, 7d6 at 9th, and so on, to a maximum of 12d6 at 19th level). The blast deals damage to each creature in a 20-foot-radius <Link to="/misc/burst">burst</Link>, but each affected creature can attempt a Reflex save to halve the damage. When you unleash an energy blast, you must decide what type of damage it deals (acid, cold, electricity, or fire). You must be at least 5th level to select this focus power.</p>
<p><strong>Energy Ward (Sp):</strong> As a standard action, you can expend 1 point of mental focus to surround yourself in a swirling ward of energy. When you activate this power, you must select acid, cold, electricity, or fire. You gain resistance 10 against that energy type, and whenever a creature hits you with a melee weapon or natural weapon, that creature takes 1d6 points of energy damage of the chosen type. Attacks made with melee weapons with reach don't cause the attacker to take this damage. At 13th and 19th levels, the resistance granted by this ward increases by 5, to a maximum of resistance 20 at 19th level. The energy ward lasts for 1 round per occultist level. You must be at least 7th level to select this focus power.</p>
<p><strong>Light Matrix (Sp):</strong> As a standard action, you can expend 1 point of mental focus to create a glowing orb of swirling lights that obeys your commands. This orb illuminates the area like the <Link to="/spell/light">light</Link> spell. The orb can be commanded to hover over your shoulder, moving with you. As a move action, you can direct it to move up to 30 feet away from you. If the light matrix is ever more than 30 feet away from you, it returns to hover over your shoulder. If you are at least 5th level, you can direct the light matrix to make a melee touch attack against one foe within 30 feet. If the attack hits, the target must succeed at a Fortitude save or be <Link to="/misc/blinded">blinded</Link> for 1d4 rounds by a flash of light. If the attack hits, regardless of whether the target succeeds at the save, the light matrix immediately ends. The light matrix otherwise has a duration of 1 hour per occultist level you possess. You can't have more than one light matrix in existence at one time. If you use this power again, any previous light matrices immediately end.</p>
<p><strong>Radiance (Sp):</strong> As a standard action, you can touch a weapon to cause it to glow with light by expending 1 point of mental focus. The weapon produces light like a torch. For the purpose of <Link to="/spelldef/darkness">darkness</Link> spells and abilities, this effect counts as a light spell of level 0, plus 1 additional spell level for every 2 occultist levels you possess. This light lasts for 1 minute per occultist level you possess. In addition, whenever the weapon scores a critical hit against a foe, the wielder can choose to end the effect, causing the foe to be surrounded by the radiance for 1d4 rounds. While illuminated in this way, the target can't benefit from <Link to="/rule/concealment">concealment</Link> or <Link to="/spell/invisibility">invisibility</Link>, nor can it attempt Stealth checks to avoid being seen. All attack rolls made against an illuminated foe receive a +2 circumstance bonus.</p>
<p><strong>Shape Mastery (Su):</strong> As part of casting an evocation spell with an area of effect, you can expend a number of points of mental focus up to your Intelligence modifier to exclude an equal number of squares from the area.</p>
<p><strong>Wall of Power (Sp):</strong> By expending 1 point of mental focus as a standard action, you can create a wall of pure energy with a length of up to 5 feet per occultist level you possess. This wall is 10 feet high and 1 foot thick. It doesn't block passage, line of sight, or line of effect, but does deal damage to anyone passing through it. The wall deals 2d6 points of energy damage + 1 point of energy damage per occultist level you possess. You must select acid, cold, electricity, or fire when you create the wall to determine the type of damage it deals. The wall must be straight, and can't pass through a creature's space when created. The wall lasts for 1 round per occultist level you possess. You must be at least 9th level to select this focus power.</p>
</blockquote>
<h3 id="implement-evocation-sacred-implement">Sacred Implement</h3>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 15</Link></p>
<p><strong>Deity</strong> <Link to="/faith/rovagug">Rovagug</Link>; <strong>Implement</strong> figurine; <strong>Opposition School</strong> abjuration</p>
<p><strong>Footsteps of the Rough Beast (Su):</strong> You can expend 1 point of mental focus as a move action to cause the ground in a 5-foot-radius burst centered on you to crumble and rupture, becoming <Link to="/rule/difficult_terrain">difficult terrain</Link>. If you remain stationary, in subsequent rounds you can <Link to="/rule/concentration">concentrate</Link> on this area as though concentrating on a spell by expending 1 additional mental focus each round. As long as you maintain concentration, the radius of the difficult terrain increases by 5 feet (maximum 30-foot radius) each round. You immediately cease concentrating if you move from your originating location. Difficult terrain created this way remains for 24 hours before returning to its original state.</p>
</>};
const _illusion = {title: "Illusion", jsx: <><h2 id="implement-illusion-illusion">Illusion</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 55</Link><br/>Illusion implements allow the occultist to distort the senses and cloak creatures from sight.</p>
<p><strong>Implements:</strong> Crystal, hat, mask, prism, ring.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an illusion implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Distortion (Sp):</strong> The implement allows its bearer to distort his form and location, protecting him from harm. As a standard action, the bearer can gain a <Link to="/rule/concealment">concealment</Link> miss chance equal to 5% for every point of mental focus invested in the implement (to a maximum of 5% + 5% for every 2 occultist levels you possess) until the next time the bearer makes an attack. If this miss chance reaches 50%, it doesn't increase further, but the bearer gains all the benefits of <Link to="/spell/invisibility">invisibility</Link>. Creatures with <Link to="/spell/see_invisibility">see invisibility</Link>, <Link to="/spell/true_seeing">true seeing</Link>, or similar abilities ignore the miss chance from this ability.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use illusion implements gain the following focus power.</p>
<blockquote>
<p><strong>Minor Figment (Sp):</strong> As a standard action, you can expend 1 point of mental focus to create a minor figment. This can function as either <Link to="/spell/ghost_sound">ghost sound</Link> or <Link to="/spell/minor_image">minor image</Link>. In either case, the effect lasts for a number of rounds equal to your occultist level. If you are 7th level or higher, the figment lasts for a number of minutes equal to your occultist level, and you can cause the figment to change once during its duration when a specified condition occurs.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use illusion implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Cloak Image (Sp):</strong> As a standard action, you can expend 1 point of mental focus to hide your appearance behind an illusion, as <Link to="/spell/disguise_self">disguise self</Link>. The effect lasts for 1 minute per occultist level you possess. At 5th level, you can instead expend 2 points of mental focus to appear as a creature of a different type, but you must remain the same size. At 7th level, you can expend 1 additional point of mental focus to target a willing creature other than yourself with this ability.</p>
<p><strong>Color Beam (Sp):</strong> As a standard action, you can expend 1 point of mental focus to unleash a beam of cascading colors at any one target within 30 feet. Doing so requires a ranged touch attack. If the beam hits, the target is <Link to="/misc/blinded">blinded</Link> for 1 round if it has a number of Hit Dice equal to or lower than your occultist level. A foe with a number of Hit Dice greater than your occultist level is instead dazzled for 1 round. The foe can attempt a Will save to negate the effect. Regardless of whether it succeeds at its save, the target is then immune to this effect for 1 day. This is a mind-affecting illusion effect.</p>
<p><strong>Masquerade (Sp):</strong> As a standard action, you can expend 1 point of mental focus to take on the appearance of another creature that you touch. If the creature is not friendly to you, this requires a melee touch attack, but the target doesn't receive a saving throw to negate the effect. You gain a circumstance bonus on Disguise checks equal to your occultist level + 10, but only to look like the creature touched. This bonus doesn't stack with the bonuses from polymorph spells or spells like <em>disguise self.</em> While using this ability, you can change your disguise as a standard action by touching a different creature and assuming its appearance. You can end this effect at any time. This effect lasts for 10 minutes per occultist level you possess, but you can renew the duration at any time by expending 1 additional point of mental focus. You must be at least 7th level to select this focus power.</p>
<p><strong>Mirage (Sp):</strong> As a standard action, you can expend 1 point of mental focus to cloak an area in illusion, allowing you to change the area's appearance. You can affect up to one 5-foot-cube area for every occultist level you posses, changing the appearance in a way that seems natural to the surroundings, subject to GM discretion. You could, for example, hide a door or passageway, make a table appear to be covered in food, or even create the illusion of a pit. You can't make creatures or objects invisible with this power, but you can change the appearance of an object or create an illusion for creatures to hide behind. This functions as <Link to="/spell/major_image">major image</Link>, and creatures that physically interact with the illusion in any way can attempt a Will save to see through the mirage. You must be at least 5th level to select this focus power.</p>
<p><strong>Shadow Beast (Sp):</strong> As a standard action, you can call forth one or more beasts made of shadow by expending 1 point of mental focus. This functions as <Link to="/spell/shadow_conjuration">shadow conjuration</Link>, but it can be used to duplicate only the effects of summon monster spells. Creatures created with this spell deal 50% of the normal damage to those that disbelieve the illusion, and their non-damaging effects have only a 50% chance of affecting disbelieving targets. This can be used to duplicate any summon monster spell up to <Link to="/spell/summon_monster_v">summon monster V</Link>. For every 2 additional levels you possess beyond 9th, the maximum spell level you can duplicate with this ability increases by 1 (to a maximum of <Link to="/spell/summon_monster_ix">summon monster IX</Link> at 17th level). Regardless of the spell duplicated, the creatures remain for 1 round per occultist level you possess. You must be at least 9th level to select this focus power.</p>
<p><strong>Unseen (Sp):</strong> As a standard action, you can expend 1 point of mental focus to become invisible, as <em>invisibility.</em> This effect lasts for 1 minute per occultist level you possess. You can expend 2 points of mental focus instead of 1 to use this power on a willing adjacent creature instead of yourself. You can still see creatures you make invisible with this power. If the invisible creature makes an attack or otherwise takes an action that would cause the invisibility to end, you can immediately expend 1 additional point of mental focus to allow the creature to remain invisible if the creature is within 30 feet of you. You must be at least 3rd level to select this focus power.</p>
</blockquote>
<h3 id="implement-illusion-sacred-implement">Sacred Implement</h3>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 15</Link></p>
<p><strong>Deity</strong> <Link to="/faith/norgorber">Norgorber</Link>; <strong>Implement</strong> mask; <strong>Opposition School</strong> conjuration</p>
<p><strong>Psychic Mirage (Sp):</strong> You can expend 1 point of mental focus to become invisible to a single target within 30 feet, as per <em>invisibility,</em> and remain so for 1 minute per occultist level you have. This invisibility doesn't affect other creatures. While within 30 feet of the target, you can expend 1 point of mental focus to read the target's surface thoughts as per <Link to="/spell/detect_thoughts">detect thoughts</Link>.</p>
</>};
const _necromancy = {title: "Necromancy", jsx: <><h2 id="implement-necromancy-necromancy">Necromancy</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 56</Link><br/>Implements that draw power from necromancy can control undead and harm the living.</p>
<p><strong>Implements:</strong> Bone, coin, doll, drum, robe, skull.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an necromancy implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Necromantic Focus (Su):</strong> The implement grants its possessor greater power over the undead. Whoever possesses the implement can control an additional 2 Hit Dice of undead for every point of mental focus invested in the item (to a maximum number of Hit Dice equal to 4 &times; your occultist level). Any spellcaster who bears the implement can add it as an additional focus component for a necromancy spell he casts to create undead. If he does so, he can create an additional number of HD of undead equal to the additional HD the implement allows him to control (apply this effect after doubling the HD of undead for desecrate, if applicable). Undead creatures take a -1 penalty on saving throws against spells cast by the bearer of this implement for every 4 points of mental focus invested in this implement.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use necromancy implements gain the following focus power.</p>
<blockquote>
<p><strong>Mind Fear (Sp):</strong> As a standard action, you can expend 1 point of mental focus to cause a living creature to succumb to fear. The target must be within 30 feet of you, and it can attempt a Will saving throw to negate the effect. If the target fails the save and has a number of Hit Dice less than or equal to yours, it is <Link to="/misc/frightened">frightened</Link> for 1d4 rounds. If the target fails the saving throw and has a number of Hit Dice greater than yours, it is instead shaken for 1d4 rounds. This is a mind-affecting fear effect.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use necromancy implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Flesh Rot (Sp):</strong> As a standard action, you can make a melee touch attack and expend 1 point of mental focus to cause the flesh of a living creature to rot and wither. If the attack hits, the target takes 1d8 points of damage + 1 point per occultist level you possess. For every 4 occultist levels you possess beyond 3rd, the target takes an additional 1d8 points of damage (to a maximum of 5d8 at 19th level). If you miss with the melee touch attack, this power is wasted with no effect. You must be at least 3rd level to select this focus power.</p>
<p><strong>Necromantic Servant (Sp):</strong> As a standard action, you can expend 1 point of mental focus to raise a single human <Link to="/template/skeleton">skeleton</Link> or human <Link to="/template/zombie">zombie</Link> from the ground to serve you for 10 minutes per occultist level you possess or until it is destroyed, whichever comes first. This servant has a number of hit points equal to 1/2 your maximum hit point total (not adjusted for temporary hit points or other temporary increases). It also uses your base attack bonus and gains a bonus on damage rolls equal to 1/2 your occultist level. At 5th level, whenever the necromantic servant would be destroyed, if you are within medium range (100 feet + 10 feet per level) of the servant, you can expend 1 point of mental focus as an immediate action to cause the servant to return to full hit points. At 9th level, you can choose to give the servant the bloody or burning simple template (if it's a skeleton) or the fast simple template (if it's a zombie). At 13th level, when you take an immediate action to restore your servant, it splits into two servants. You can have a maximum number of servants in existence equal to 1/2 your occultist level. At 17th level, the servant gains a <Link to="/main/teamwork_feat">teamwork feat</Link> of your choice.</p>
<p><strong>Pain Wave (Sp):</strong> As a standard action, you can expend 1 point of mental focus to unleash a wave of pain. This wave hits all creatures other than you in a 20-foot-radius <Link to="/misc/burst">burst</Link> centered on a point that you designate within 100 feet. All living creatures in this area are wracked with pain, gaining the <Link to="/misc/sickened">sickened</Link> condition for 1 round per occultist level you possess. Affected creatures can attempt a Will save to reduce the duration to just 1 round. This is a mind-affecting pain effect. You must be at least 7th level to select this focus power.</p>
<p><strong>Psychic Curse (Sp):</strong> As a standard action, you can expend 1 point of mental focus to curse a living creature within 30 feet with your psychic magic. You can choose one of the following effects: memory lapse, mental block, or pain confusion. If you choose memory lapse, the target loses its memory of the past 1 hour per occultist level you possess. If you choose mental block, you can proscribe one specific action, such as attacking with a type of weapon, casting a specific spell, or something else suitably specific (subject to the GM's discretion). The target can't take that action without first succeeding at a Will save. If it fails, it can take other actions instead. If it attempts the prohibited action again on subsequent rounds, it gains a cumulative +2 bonus on the save until it succeeds. If you select pain confusion, the creature is <Link to="/misc/confused">confused</Link> for 1d4 rounds whenever it is damaged by a critical hit. The target can attempt a Will save to negate this effect. This effect lasts for 1 day per occultist level you possess. A creature can't be under the effects of more than one psychic curse at a time. This is a mind-affecting curse effect. You must be at least 5th level to select this focus power.</p>
<p><strong>Soulbound Puppet (Su):</strong> As a full-round action, you can expend 1 point of mental focus to create a soulbound puppet from a bone, doll, or skull. If you use a bone or a skull, your power builds a Tiny or Small flesh puppet around it that vaguely resembles the original creature from which the bones were taken. If the implement is a doll, the doll comes to life. Treat this as a <Link to="/sidekick/familiar">familiar</Link>, using your occultist level as your wizard level to determine its powers and abilities. By using a bone or skull from the appropriate creature or a doll shaped like that creature, you can select any of the <Link to="/ability/familiar">familiar</Link> choices available to a wizard. You can instead use a humanoid bone, doll, or skull, to give the puppet the base statistics of a <Link to="/monster/homunculus">homunculus</Link>, but without a fly speed or the poison bite or telepathic link abilities. No matter the form, this creature is a construct with an alignment matching your own. You can have no more than one soulbound puppet active at any given time. The soulbound puppet remains animated for 10 minutes per occultist level you possess.</p>
<p><strong>Spirit Shroud (Su):</strong> As a standard action, you can expend 1 point of mental focus to surround yourself with a shroud of spirit energy. You gain a number of <Link to="/rule/temporary_hit_points">temporary hit points</Link> equal to 1d6 + your occultist level. This shroud lasts for 1 minute per occultist level or until the temporary hit points are expended, whichever comes first. These temporary hit points stack with those from other sources, but not with those gained through multiple uses of this ability. At 4th level, as long as the shroud remains, you also gain a resistance bonus on all saving throws against death effects, fear effects, and any spells or effects that bestow negative levels or deal negative energy damage (if the spells or effects allow a save). This bonus is equal to 1 + 1 for every 4 occultist levels you possess beyond 4th. You must be at least 3rd level to select this focus power.</p>
</blockquote>
<h3 id="implement-necromancy-sacred-implement">Sacred Implement</h3>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 15</Link></p>
<p><strong>Deity</strong> <Link to="/faith/urgathoa">Urgathoa</Link>; <strong>Implement</strong> coin; <strong>Opposition School</strong> evocation</p>
<p><strong>Wake (Su):</strong> As a standard action, you can expend 1 point of mental focus to inspire fits of grief in a single creature within 30 feet that can see and hear you. You fill the target with haunting visions of the deaths of loved ones and the brevity of life, and for 1 minute, the target's emotional vulnerability grants you a circumstance bonus equal to your occultist level on Diplomacy and Intimidate checks attempted against the target. If this implement is used in combat, these emotions instead distract your target, leaving it <Link to="/misc/dazzled">dazzled</Link> for 1 round per occultist level you have.</p>
</>};
const _transmutation = {title: "Transmutation", jsx: <><h2 id="implement-transmutation-transmutation">Transmutation</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 57</Link><br/>Transmutation implements can alter the properties of both objects and creatures.</p>
<p><strong>Implements:</strong> Belt, boots, sandals, vest, weapon.</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into an transmutation implement, the implement grants the following resonant power. The implement's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Physical Enhancement (Su):</strong> The implement enhances its bearer's body. When you invest mental focus in the implement, select a physical ability score. The implement grants a +2 temporary enhancement bonus to that physical ability score for every 3 points of mental focus invested in the implement (to a maximum of +2 at 1st level, plus an additional 2 for every 6 occultist levels you possess).</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use transmutation implements gain the following focus power.</p>
<blockquote>
<p><strong>Legacy Weapon (Su):</strong> As a standard action, you can expend 1 point of mental focus and touch a weapon to grant it an enhancement bonus. The bonus is equal to 1 + 1 for every 6 occultist levels you possess (to a maximum of +4 at 18th level). Enhancement bonuses gained by this ability stack with those of the weapon, to a maximum of +5. You can also imbue the weapon with any one weapon <Link to="/main/magic_enhancements">special ability</Link> with an equivalent enhancement bonus less than or equal to your maximum bonus by reducing the granted enhancement bonus by the appropriate amount. The item must have an enhancement bonus of at least +1 (from the item itself or from legacy weapon) to gain a weapon special ability. In either case, these bonuses last for 1 minute.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to gaining the base focus power, occultists who learn to use transmutation implements can select from the following focus powers when choosing the powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Mind Over Gravity (Sp):</strong> As a standard action, you can expend 1 point of mental focus to give yourself a fly speed of 60 feet with perfect maneuverability. This effect lasts for 1 minute per occultist level you possess. You must be at least 7th level to select this focus power.</p>
<p><strong>Philosopher's Touch (Su):</strong> As a standard action, you can expend 1 point of mental focus and touch a weapon, causing it to gain the properties of a special material. You can cause the weapon to be treated as cold iron or silver for the purposes of overcoming damage reduction for 1 minute per occultist level you possess. At 4th level and every 4 levels thereafter, you can touch an additional weapon as part of using this ability to grant that weapon the same benefit (still expending only 1 point of mental focus). At 11th level, you can cause any weapon affected by this ability to act as if it were <Link to="/eq-material/adamantine">adamantine</Link> instead (but only for the purposes of overcoming damage reduction, not for overcoming hardness).</p>
<p><strong>Quickness (Sp):</strong> As a standard action, you can expend 1 point of mental focus to grant supernatural quickness and reflexes to yourself or a willing living creature you touch. This functions as <Link to="/spell/haste">haste</Link>, but the bonus to AC and on Reflex saving throws increases to +2. This effect lasts for 1 round per occultist level you possess. You must be at least 5th level to select this focus power.</p>
<p><strong>Size Alteration (Sp):</strong> As a standard action, you can expend 1 point of mental focus and touch a creature to alter its size. You can increase or decrease the creature's size by one step, as <Link to="/spell/enlarge_person">enlarge person</Link> or <Link to="/spell/reduce_person">reduce person</Link> but not limited by the creature's type. If the creature is hostile toward you, using this ability requires a successful melee touch attack, and the creature can attempt a Fortitude save to negate the effect. This effect lasts for 1 round per occultist level you possess. You can't use this ability on a creature that is already subject to an effect that alters its size.</p>
<p><strong>Sudden Speed (Sp):</strong> As a swift action, you can expend 1 point of mental focus to grant yourself a burst of speed. This increases your land speed by 30 feet for 1 minute. This ability does not stack with itself.</p>
<p><strong>Telekinetic Mastery (Sp):</strong> As a standard action, you can expend 1 point of mental focus to grant yourself telekinetic power. This functions as <Link to="/spell/telekinesis">telekinesis</Link>, except you don't need to concentrate on the effect to maintain it, and using any one of its effects is a standard action. This effect lasts for 1 round per occultist level you possess. You must be at least 9th level to select this focus power.</p>
</blockquote>
<h3 id="implement-transmutation-sacred-implement">Sacred Implement</h3>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 15</Link></p>
<p><strong>Deity</strong> <Link to="/faith/nethys">Nethys</Link>; <strong>Implement</strong> vest; <strong>Opposition School</strong> divination</p>
<p><strong>Parity (Su):</strong> While casting a transmutation spell that provides you an enhancement bonus to a single mental or physical attribute, you can expend 1 point of mental focus as an immediate action to divide the bonus the spell provides, granting half to the original attribute affected by the spell and half to a corresponding attribute. Strength corresponds with Intelligence, Dexterity corresponds with Wisdom, and Constitution corresponds with Charisma. You can also use this ability to divide an ability score bonus granted by a magic item, but you must immediately expend 1 point of mental focus each day when you allocate mental focus to your implements to maintain the parity, or else the bonus immediately reverts to normal.</p>
</>};
const _mages_paraphernalia = {title: "Mage's Paraphernalia (Panoply)", jsx: <><h2 id="implement-mages_paraphernalia-mages-paraphernalia">Mage's Paraphernalia</h2>
<p><strong>Sources</strong> <Link to="/source/psychic_anthology">Psychic Anthology pg. 26</Link><br/>This panoply is associated with the arcane arts and the masters of manipulating magic.</p>
<p><strong>Implements:</strong> Crystal ball (divination), robe (necromancy), and wand (evocation).</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into all of the associated implements, the panoply grants the following resonant power. The panoply's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Scholarly Knowledge (Su):</strong> The panoply grants a +1 bonus on all Knowledge checks for every 4 points of total mental focus invested in all of the associated implements, to a maximum bonus equal to half the occultist's level. Additionally, the bearer is treated as being trained in all Knowledge checks for the purpose of determining whether or not he can succeed at Knowledge checks with a DC higher than 10. If the occultist is at least 5th level, the panoply's bearer can cast <Link to="/spell/augury">augury</Link> as a spell-like ability a total number of times per day equal to the greatest number of points of mental focus stored in any one of the associated implements.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use this panoply gain the following focus power.</p>
<blockquote>
<p><strong>Arcane Inspiration (Sp):</strong> By consulting a spellbook for 15 minutes, you can expend 1 or more points of mental focus to prepare a divination, evocation, or necromancy spell from the <Link to="/main/spells_wizard">sorcerer/wizard spell list</Link> that is contained in that spellbook. You must choose an unused spell slot for the prepared spell to occupy, and the chosen spell must be of a spell level equal to or lower than that spell slot. The number of points of mental focus you must expend is equal to the level of the spell slot used. You can apply metamagic effects to the prepared spell, if desired, and they increase the level of the spell slot the spell occupies as normal. Once the spell is prepared, you can cast it normally, using the prepared spell slot (you cannot use any of your other spell slots to cast it, restricting you to casting it only once per use of this ability). The spell is treated as a psychic spell.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to the base focus power, occultists who learn to use this panoply can select the following focus powers when choosing powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Metamagic Knowledge (Su):</strong> As a standard action, you can expend 3 points of mental focus and choose a single metamagic feat you qualify for but do not know. You gain that metamagic feat until the next time you refresh your mental focus.</p>
<p><strong>Metamagic Master (Su):</strong> As a free action while casting a spell, you can expend 1 or more points of mental focus to apply a metamagic feat you know to that spell without increasing the spell's casting time or the spell level of the spell slot it occupies. The number of points of mental focus you must expend to use this power is equal to the increase in spell levels the metamagic feat would normally require (minimum 1).</p>
<p><strong>Spell Power (Su):</strong> As a free action while casting a spell, you can expend 2 points of mental focus to increase that spell's caster level by 2. At 12th and 18th levels, whenever you use this ability, you can spend an additional point of mental focus in order to increase the spell's caster level by an additional 1.</p>
</blockquote>
</>};
const _performers_accoutrements = {title: "Performer's Accoutrements (Panoply)", jsx: <><h2 id="implement-performers_accoutrements-performers-accoutrements">Performer's Accoutrements</h2>
<p><strong>Sources</strong> <Link to="/source/psychic_anthology">Psychic Anthology pg. 27</Link><br/>This panoply is associated with those who deceive as well as those who entertain.</p>
<p><strong>Implements:</strong> Mask (illusion) and musical instrument (enchantment).</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into all of the associated implements, the panoply grants the following resonant power. The panoply's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Actor's Skill (Su):</strong> The panoply grants a +1 bonus on Bluff, Disguise, and Perform checks for every 3 points of total mental focus invested in all of the associated implements, to a maximum bonus equal to half the occultist's level. The panoply also grants an equal bonus on saving throws against divination effects.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use this panoply gain the following focus power.</p>
<blockquote>
<p><strong>False Persona (Su):</strong> By spending 1 minute in meditation and expending 2 points of mental focus, you can create a psychic mask that obscures your identity. When you create this false persona, you choose the nature of the persona's alignment and magical auras, and can create a simple background of up to four basic facts about the persona. All divination spells that reveal information about you instead reveal information based on the false persona's background and aura information. Additionally, attempts to scry or magically locate you work only if the creature making such attempts knows that you and your current false persona are the same individual. Otherwise, the spell has no effect, revealing nothing but darkness, as if you did not exist. This effect lasts up to 24 hours or until you next refresh your mental focus (whichever occurs first), though you can dismiss this false persona at any time before then as a full-round action. This effect fools only magical attempts to discern your identity or background, and has no effect on mundane means of gathering information about you.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to the base focus power, occultists who learn to use this panoply can select the following focus powers when choosing powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>False Confidence (Sp):</strong> By taking a standard action and expending 1 point of mental focus, you can instill incredible, boundless confidence in a single living creature with an Intelligence score of 3 or higher within 60 feet, granting that creature a +2 morale bonus on ability checks, attack rolls, saving throws, and skill checks for 10 minutes. As a move action, you can shatter the feeling of confidence, leaving the target feeling hopeless and distraught. If you do, the target can immediately attempt a Will save to negate the effect, with a cumulative -1 penalty for every 2 minutes the creature benefited from the morale bonus. If the target fails this save, it takes a -2 penalty on ability checks, attack rolls, saving throws, and skill checks for the remainder of the effect's duration. If the creature then fails an ability check, attack roll, saving throw, or skill check by 10 or more while subject to this penalty, the penalty changes to -4.</p>
<p><strong>Hypnotic Gaze (Sp):</strong> By taking a standard action and expending 1 point of mental focus, you can hypnotize a single creature within 60 feet that can see you. The target must succeed at a Will save or become <Link to="/misc/fascinated">fascinated</Link> for as long as you maintain the effect (a move action), plus 1 additional round. Fascinated creatures take a -1 penalty on Will saving throws. For every 3 rounds that you maintain the effect, this penalty increases by 1 to a maximum penalty of -4. Anything that ends the fascination effect also ends the penalty. A creature that succeeds at its saving throw to resist this effect is immune to that occultist's hypnotic gaze for 24 hours.</p>
<p><strong>Puppet Master (Sp):</strong> By taking a standard action and expending 2 points of mental focus, you can implant a hypnotic suggestion in a creature. This functions as per <Link to="/spell/suggestion">suggestion</Link> (using your occultist level as the caster level), except that the saving throw DC is equal to 10 + half your occultist level + your Intelligence modifier, and if the target fails its saving throw, you can choose to have it forget everything that occurs while it is under the spell's effects, as well as any recollection of you using this ability on it. Memories forgotten in this way can be recovered with restoration or spells or effects that can restore lost memories (such as <Link to="/spell/modify_memory">modify memory</Link>).</p>
</blockquote>
</>};
const _saints_holy_regalia = {title: "Saint's Holy Regalia (Panoply)", jsx: <><h2 id="implement-saints_holy_regalia-saints-holy-regalia">Saint's Holy Regalia</h2>
<p><strong>Sources</strong> <Link to="/source/psychic_anthology">Psychic Anthology pg. 27</Link><br/>This panoply is associated with devoted members of a good-aligned faith and the power of belief.</p>
<p><strong>Implements:</strong> Censer (conjuration) and holy symbol (abjuration).</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into all of the associated implements, the panoply grants the following resonant power. The panoply's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Font of Healing (Su):</strong> The panoply grants you mastery over healing magic. When you cast a <Link to="/main/cure_spells">cure spell</Link> (a spell with "cure" in its name), you restore 1 additional hit point for every 3 points of total mental focus invested in all of the associated implements, to a maximum bonus equal to half the occultist's level. This doesn't apply to damage dealt to undead with the spell.</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use this panoply gain the following focus power.</p>
<blockquote>
<p><strong>Restoring Touch (Sp):</strong> As a standard action, you can expend 2 points of mental focus to cure a living creature you touch of temporary ability damage. You cure 1 point of temporary ability damage to a single ability score for every 3 occultist levels you have. At 10th level, you can expend an additional point of mental focus to instead restore the same amount of permanent ability drain.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to the base focus power, occultists who learn to use this panoply can select the following focus powers when choosing powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Guardian Aura (Sp):</strong> As a full-round action, you can expend 3 points of mental focus to emit a 20-foot-radius aura of protection that lasts for 1 minute. You and your allies within the aura gain a sacred bonus to AC equal to 1/4 of your occultist level (minimum +1). Your speed is reduced to 10 feet while this power is active, but you can dismiss it as a free action.</p>
<p><strong>Martyr's Benediction (Sp):</strong> As an immediate action when you would be reduced to fewer than 0 hit points or killed (including by effects that kill without dealing damage, such as <Link to="/spell/phantasmal_killer">phantasmal killer</Link> and <Link to="/spell/power_word_kill">power word kill</Link>), you can expend 1 point of mental focus to restore a number of hit points equal to 1d8 + your occultist level all allies (other than you) within 30 feet. In addition, if any healed ally is under a fear effect, she can immediately attempt a new saving throw to end it.</p>
<p><strong>Rebuke Anathema (Sp):</strong> As a standard action, you can present the holy symbol used as the panoply's associated implement and expend 2 points of mental focus to keep a single creature at bay. Your alignment must be within one step of that of the holy symbol's deity, and the creature's alignment must be more than one step away from both your alignment and the deity's alignment. If neither is the case, this power is ineffective and the spent mental focus is wasted. If the target creature fails a Will save, it can't move toward you for a number of rounds equal to your occultist level.</p>
</blockquote>
</>};
const _trappings_of_the_warrior = {title: "Trappings of the Warrior (Panoply)", jsx: <><h2 id="implement-trappings_of_the_warrior-trappings-of-the-warrior">Trappings of the Warrior</h2>
<p><strong>Sources</strong> <Link to="/source/psychic_anthology">Psychic Anthology pg. 28</Link><br/>This panoply is associated with brave and stalwart warriors, martial skill, and the defense of one's allies.</p>
<p><strong>Implements:</strong> Shield (abjuration) and weapon (transmutation).</p>
<p><strong>Resonant Power:</strong> Each time the occultist invests mental focus into all of the associated implements, the panoply grants the following resonant power. The panoply's bearer gains the benefits of this power until the occultist refreshes his focus.</p>
<blockquote>
<p><strong>Martial Skill (Ex):</strong> When wielding the weapon used as the panoply's associated implement, you treat your base attack bonus as though it were 1 point higher for every 4 points of total mental focus invested in all of the associated implements, to a maximum base attack bonus equal to your occultist level. This increase can grant you additional attacks when using the full attack action (for example, a 12th-level occultist with 12 points of mental focus invested among the associated implements would be treated as having a base attack bonus of +11, with iterative attacks at a base attack bonus of +6 and +1).</p>
</blockquote>
<p><strong>Base Focus Power:</strong> All occultists who learn to use this panoply gain the following focus power.</p>
<blockquote>
<p><strong>Combat Trick (Ex):</strong> As a move action, you can expend 3 points of mental focus to gain a single <Link to="/main/combat_feat">combat feat</Link> for which you qualify. This benefit lasts for 1 minute.</p>
</blockquote>
<p><strong>Focus Powers:</strong> In addition to the base focus power, occultists who learn to use this panoply can select the following focus powers when choosing powers gained from their focus powers class feature.</p>
<blockquote>
<p><strong>Counterstrike (Ex):</strong> As an immediate action when you are damaged by a melee attack, you can expend 1 point of mental focus to immediately make a single attack at your highest base attack bonus against the creature that hit you, provided that you threaten that creature. If the attack hits, you gain a bonus on the damage roll equal to 1/3 your occultist level (rounded down, minimum +1). This attack counts as an attack of opportunity.</p>
<p><strong>Shield Ally (Ex):</strong> As an immediate action when an adjacent ally is the target of a spell or attack, you can expend 2 points of mental focus to redirect that spell or attack to yourself instead. You must declare that you are using this ability before the result of any attack roll is known or before any saving throws are attempted.</p>
<p><strong>Warrior's Resilience (Su):</strong> As an immediate action when you would be reduced to fewer than 0 hit points, you can expend 1 or more points of mental focus to remain at 0 hit points instead. Using this focus power costs 1 point of mental focus for every 5 points of damage below 0 that you would otherwise be reduced to (rounded up, minimum 1 point of mental focus). This has no effect on anything that would kill you without reducing your hit points below 0, such as a failed saving throw against a death effect.</p>
</blockquote>
</>};
export default {not_found:_not_found,abjuration:_abjuration,conjuration:_conjuration,divination:_divination,enchantment:_enchantment,evocation:_evocation,illusion:_illusion,necromancy:_necromancy,transmutation:_transmutation,mages_paraphernalia:_mages_paraphernalia,performers_accoutrements:_performers_accoutrements,saints_holy_regalia:_saints_holy_regalia,trappings_of_the_warrior:_trappings_of_the_warrior}