import Link from '../../components/Link';
import InnerLink from '../../components/InnerLink';
const _not_found = {title: "Unknown", jsx: <><h2 id="tech-artifact-not_found-error">Error</h2>
<p>Unable to find the requested tech artifact.</p>
</>};
const _arms_of_the_iron_god = {title: "Arms of the Iron God", jsx: <><h2 id="tech-artifact-arms_of_the_iron_god-arms-of-the-iron-god">Arms of the Iron God</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_90_the_divinity_drive">Pathfinder #90: The Divinity Drive pg. 60</Link><br/><strong>Slot</strong> arms (cybernetic); <strong>Weight</strong> 28 lbs.<br/><strong>Capacity</strong> -; <strong>Usage</strong> -<br/><strong>Install</strong> DC 38; <strong>Implantation</strong> 4</p>
<p><em>The Arms of the Iron God</em> replace the arms, shoulders, and much of the recipient's spine. They double the creature's lifting and carrying capacity, grant a +5 circumstance bonus on Climb checks, and grant a +5 bonus to CMD against disarm attempts. The Arms also grant the user a +4 enhancement bonus to Strength.</p>
<p>Each arm ends in an electrified claw that grants the wielder a claw attack that deals 1d8 points of damage. These claw attacks are always primary attacks, even while a one-handed weapon is wielded and the other claw is used to make an additional attack. The claws function as +3 <Link to="/magic-enh/shocking_burst">shocking burst</Link> weapons. As a free action, one of the claws can be transformed into a +3 shocking burst battleaxe - returning it to its claw form is a move action. When the claw transforms, any item held in or worn on that hand drops. Attacks made with this battleaxe gain a +2 bonus on damage rolls, but it cannot be wielded with two hands.</p>
<p>The Arms also function as a divine focus for spellcasting if the user worships Unity - even for unusually expensive divine focuses, such as the focus needed for <Link to="/spell/destruction">destruction</Link>.</p>
<h3 id="tech-artifact-arms_of_the_iron_god-destruction">Destruction</h3>
<p>Once Unity is destroyed, the Arms of the Iron God can be destroyed as a normal item (hardness 15, hp 120).</p>
</>};
const _autodoc = {title: "Autodoc", jsx: <><h2 id="tech-artifact-autodoc-autodoc">Autodoc</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 60</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> 1,200 lbs.<br/><strong>Capacity</strong> 120; <strong>Usage</strong> see text</p>
<p>An autodoc is a large, cumbersome device that consists of a comfortable, plastic-framed reclining chair inside a transparent pod, within which is affixed a dizzying array of multi-jointed arms and extendable devices. An equally dizzying assortment of buttons, lights, and touch-sensitive screens adorn the device, both on the inside and outside of the pod.</p>
<p>An autodoc can heal wounds, set broken bones, cure disease, treat burns, implant cybertech, remove poison, and more. An autodoc can be programmed to perform any number of surgical procedures upon the person lying within the pod - the dozens of arms and devices work with precision and great speed. The operator need only enter in the proper diagnosis or desired operation on the screens at the foot of the bed with a successful <Link to="/skill/heal">Heal</Link> check; this requires the <Link to="/feat/technologist">Technologist</Link> feat to attempt. The DC is based on the operation, detailed below. An autodoc will not activate until it has been properly programmed. Programming an operation takes 2d6 rounds of work. An autodoc has some capacity to error-check and auto-complete the correct programming for an operation before undertaking it by running instantaneous simulations on one of its many screens, granting the user a +5 circumstance bonus on these Heal checks.</p>
<p>An autodoc consumes 1 charge per hour while idle (including time needed to program an operation), and 1 charge per round while operating. As an autodoc can only hold a maximum of 120 charges at a time, for lengthy operations it must be recharged during use or be attached to a standing power supply such as a <Link to="/rule/tech_artifacts">generator or reactor</Link>. While functioning, an autodoc is closed tight - a successful DC 25 Strength check is required to wrench the door open. A patient who leaves or is forcibly removed from an autodoc before an operation finishes (or who is being operated on when the autodoc runs out of charges) must succeed a DC 15 Reflex save or take 3d6+10 points of damage from the cutting lasers, surgical tools, and needles moving at high speed. Needless to say, exiting the autodoc before an operation completes negates any of the benefits that would have been otherwise granted by the device.</p>
<p>The various operations an autodoc can perform are as follows; additional operations can be devised as needed.</p>
<ul>
<li><strong>Minor Surgery (DC 15):</strong> The patient heals 1d8+1 points of damage. <em>Operation Time:</em> 1 minute.</li>
<li><strong>Moderate Surgery (DC 20):</strong> The patient heals 2d8+3 points of damage and 1d4+1 points of ability damage to a selected ability score. <em>Operation Time:</em> 2 minutes.</li>
<li><strong>Major Surgery (DC 25):</strong> The patient heals 3d8+5 points of damage and is cured of blindness and deafness. <em>Operation Time:</em> 3 minutes.</li>
<li><strong>Critical Surgery (DC 30):</strong> The patient heals 4d8+7 points of damage and either all ability damage to all ability scores or all ability drain to one ability score. <em>Operation Time:</em> 4 minutes.</li>
<li><strong>Back from the Brink (DC 35):</strong> A dead patient whose body is relatively intact is restored to life at 1 hit point per Hit Die, as if by <Link to="/spell/raise_dead">raise dead</Link> (including time restrictions and negative levels). <em>Operation Time:</em> 1 hour.</li>
<li><strong>Total Molecular Reconstruction (DC 45):</strong> As long as at least a small amount of a patient's DNA is available, an autodoc can reconstruct a patient's body completely. At the end of the reconstruction process, the new body is considered to be a blank clone of the patient, and until the patient's memories and personality are implanted into the clone via a <Link to="/tech-misc/neurocam">neurocam</Link>, the body remains alive but inert. <em>Operation Time:</em> 24 hours.</li>
<li><strong>Install Cybertech (DC = the cybertech install DC):</strong> Cybernetic equipment is installed safely. <em>Operation Time:</em> 10 minutes per point of implantation of the cybertech being installed.</li>
<li><strong>Treat Toxin (DC = 10 + the save DC of disease or poison):</strong> The patient has one disease or poison currently afflicting him removed. <em>Operation Time:</em> 10 minutes.</li>
</ul>
</>};
const _beam_cannon_gravity_cannon = {title: "Beam cannon (gravity cannon)", jsx: <><h2 id="tech-artifact-beam_cannon_gravity_cannon-beam-cannon-gravity-cannon">Beam Cannon (Gravity Cannon)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_89_palace_of_fallen_stars">Pathfinder #89: Palace of Fallen Stars pg. 62</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> 18 lbs.<br/><strong>Capacity</strong> 50; <strong>Usage</strong> 1 charge<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry)<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 300 ft.</p>
<p>A beam cannon is an immense version of one of the six more common beam rifle types. Beam cannons are generally referred to by type as summarized below. In addition to the standard automatic firing mode options, a beam cannon can be used to launch a devastating blast of energy. This is a full-round action, and these blasts can't be used to make iterative attacks. When a beam cannon is used to launch a blast, no attack roll is made - you simply target a 20-foot-radius <Link to="/misc/spread">spread</Link> within a maximum range of 300 feet. You must have line of effect to your target when you launch a blast; if the blast impacts a solid object before reaching the target area, it explodes at that point. All creatures caught in the blast radius take 6d6 points of damage of the energy type appropriate to the cannon (Reflex DC 14 half). Each blast also has an additional effect as determined by the type of cannon. Firing a blast from a beam cannon consumes 10 charges.</p>
<p><strong>Gravity Cannon:</strong> A gravity cannon fires a beam of gravitons that deals force damage. Any creature that takes damage from its blast and fails the resulting Reflex save is encased in a shell of force energy for 1d4 rounds, as if by a <Link to="/spell/telekinetic_sphere">telekinetic sphere</Link>. You can use a gravity cannon to move a sphere so created (at a speed of 30 feet, up to a range of 300 feet away) as a move action - every round during which you move a sphere in this way consumes 1 charge from the gravity cannon, but also maintains the moved sphere's duration for an additional round.</p>
<p>In addition to the typical firing modes for a beam cannon, a gravity cannon can be fired on a sustained setting. When used in this mode, the gravity cannon can be used to move and manipulate objects from a distance, similar to the sustained force or combat maneuver versions of a <Link to="/spell/telekinesis">telekinesis</Link> spell. (A gravity cannon can't duplicate the violent thrust option of a telekinesis spell.) The gravity cannon uses 1 charge per round in this mode, and can move objects weighing no more than 500 pounds up to 20 feet per round. A creature can negate this effect on an object in its possession with a successful DC 19 Reflex save. If used to perform a combat maneuver, the cannon uses the wielder's CMB + 8, but uses her Intelligence modifier in place of her Strength or Dexterity modifier. A gravity cannon is a technological artifact.</p>
</>};
const _compact_ai_core = {title: "Compact AI Core", jsx: <><h2 id="tech-artifact-compact_ai_core-compact-ai-core">Compact AI Core</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_88_valley_of_the_brain_collectors">Pathfinder #88: Valley of the Brain Collectors pg. 62</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> 8 lbs.<br/><strong>Capacity</strong> 240; <strong>Usage</strong> 1/hour</p>
<p>A compact AI core is a flat sheet of semi-translucent pale blue material 10 inches wide and 20 inches long, contained in a frame of adamantine and horacalcum. One of the narrow ends of the device features a small touch-sensitive panel and several sockets to connect to external devices as needed, although the compact AI core can communicate with most electronic devices and robots wirelessly at a range of 60 feet.</p>
<p>The primary purpose of a compact AI core is to house the staggering amount of data needed to store an artificial intelligence without compromising or degrading its core programming. Most processors capable of storing this amount of data are significant in size, but a compact AI core is small enough to carry in one hand. An AI stored within a compact AI core loses all implicit connections to the source AI. An existing AI can copy itself into a compact AI, but once the copy is complete the new AI within the compact AI core becomes a duplicate but separate entity that may develop different needs and desires than the source. As a result, many AIs resist the idea of duplicating themselves in such a manner so as to avoid possible conflicts or competition. An AI faced with the certain destruction of its core processors, of course, may well resort to using a compact AI core as a method of escape and survival, but the unpredictable changes to personality that are possible during such a transfer may well prompt some AIs to gracefully accept oblivion instead. In a way, it's better to view the relationship between an AI and its duplicate in a compact AI core as more akin to that of parent and child than as twin siblings or clones.</p>
<p>More often, a compact AI core is used to house an entirely new AI creation, either one programmed from scratch (a discipline lost to the denizens of Divinity today, and one that was thus never available to the inhabitants of Golarion), or one created by the transfer of a living creature's mind via neurocam.</p>
<p>An AI can use a compact AI core to seize control of a robot to transform it into an aggregate, but no more often than one robot can be controlled at a time, and the compact AI core must remain within 60 feet of the aggregate or control is lost. An AI who attempts to seize control of a robot in this manner can do so as a standard action, and the target can resist the attempt with a successful Will save (DC = 10 + 1/2 the AI's CR + its Charisma modifier).</p>
<p>A compact AI core has 3 sockets capable of accepting one <Link to="/tech-artifact/memory_facet">memory facet</Link> each. A compact AI core consumes power at the rate of 1 charge per hour, but does not suffer any memory loss or damage if all 240 charges stored within it are consumed - once the compact AI core receives more energy, the AI within immediately regains the ability to interact with the world. While without power, an AI becomes dormant - it may experience something akin to strange dreams, but it cannot be communicated with and is not aware of the passage of time.</p>
<p>A compact AI core has hardness 20 and 80 hit points. If a compact AI core becomes broken, the AI it contains takes a -2 penalty on all saving throws and skill checks. If a compact AI core is destroyed, any AI housed within is destroyed as well. A compact AI core that is destroyed can be repaired via a <Link to="/spell/wish">wish</Link> or <Link to="/spell/miracle">miracle</Link>, or perhaps via complex technological machinery hidden deep in the most secure of Divinity's wreckage - but restoring an AI previously housed in the core to functionality requires a second miracle or wish - such an act is beyond even the machinery of Divinity.</p>
</>};
const _divinity_drive = {title: "Divinity Drive", jsx: <><h2 id="tech-artifact-divinity_drive-divinity-drive">Divinity Drive</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_90_the_divinity_drive">Pathfinder #90: The Divinity Drive pg. 60</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> 2,500 lbs.<br/><strong>Capacity</strong> infinite; <strong>Usage</strong> see text</p>
<p>The apex of Androffan technology, the Divinity Drive was the single most important piece of machinery on Divinity - important enough to inspire the ship's name. The drive was named for its unbelievable power - the closest to god-like energy that the people of Androffa had ever experienced. The Divinity Drive appears as nothing more than a 5-foot-diameter sphere of blue light, yet the mass generated by this sphere is significant. Enhancements made to the drive over the past several thousand years by Unity have reduced its mass significantly. It is contained within a series of circular arms of tempered <Link to="/eq-material/adamantine">adamantine</Link> - difficult to damage to begin with, but while the drive is infused with Unity's divine power, the entire structure is essentially indestructible.</p>
<p>The Divinity Drive's primary purpose was to create wormholes in space that would allow for swift travel over vast distances. Programming the Divinity Drive to open a wormhole can be accomplished only outside of significant gravitational fields - in high orbit around a planet or further out in space. A successful DC 25 Knowledge (engineering) check is required to program the wormhole's destination, a process which takes 2d6 days to complete. Every 5 points by which the check exceeds this DC reduces the number of days required by 1 (minimum 1). A wormhole can be torn open as an act of desperation in only 2d6 minutes with the same Knowledge (engineering) DC, but doing so causes the wormhole to open to a random point elsewhere in the Material Plane, and it damages the drive's wormhole function - which requires a large team of engineers or a dedicated AI to repair, and takes several years to complete.</p>
<p>When created, the wormhole connects two points on the Material Plane, as if by <Link to="/spell/gate">gate</Link>. The wormhole measures 1 mile in diameter, and remains open for 24 hours (or until the Divinity Drive moves more than 100 miles away from the wormhole). It can be closed manually before this time expires with a successful DC 40 Knowledge (engineering) check. Any object not yet clear of the wormhole when it closes is cut into two parts separated by a vast distance (which generally results in death or destruction), though a creature can avoid this by succeeding at a DC 20 Reflex save to throw itself into one side or the other before the wormhole closes.</p>
<p>In time, Unity found another use for the Divinity Drive - the transformation of a virtual reality into a stable divine realm housed entirely within the code of Divinity's computer system. Today, the Divinity Drive functions as the linchpin for Unity's realm; as long as Unity exists, its realm and the Divinity Drive shall persist in this invulnerable state.</p>
<p>The Divinity Drive has other astonishing effects as well as long as it functions, as summarized below.</p>
<ul>
<li>All teleportation and extradimensional travel within Silver Mount (or within a 1-mile radius if the Divinity Drive is removed from Silver Mount) is suppressed, as if by a <Link to="/spell/dimensional_lock">dimensional lock</Link> effect. A few teleportation effects (such as the teleporter between areas A15 and G6, and travel to and from the Godmind in area G5) are exempt from this. A successful DC 30 Knowledge (engineering) check allows someone who examines the Divinity Drive for 1d6 minutes to deactivate this effect, allowing teleportation to function normally, but the drive cannot be used to open wormholes while this effect is inactive.</li>
<li>The Divinity Drive is a staggering source of power, and functions as a <Link to="/rule/tech_artifacts">generator</Link> with infinite yield.</li>
<li>The area in a 50-foot-radius <Link to="/misc/spread">spread</Link> around the Divinity Drive is maintained at a constant temperature of extreme cold, and it actively leeches sources of heat from unshielded or unprotected sources. Living creatures in this area take 1d6 points of cold damage per round, and casting a spell with the fire descriptor requires a successful DC 25 caster level check to avoid having the spell automatically countered as its cast. Technological items that generate fire effects function normally in this area, but all existing fires are extinguished at the end of the round. Creatures with the fire subtype take 6d6 points of cold damage per round in this region (Fortitude DC 25 negates for that round).</li>
<li>The Divinity Drive emits a constant, thunderous hum that imposes a -10 penalty on all Perception checks made within a 50-foot-radius spread.</li>
</ul>
<h3 id="tech-artifact-divinity_drive-destruction">Destruction</h3>
<p>If Unity is destroyed, the aura that protects the Divinity Drive fails. It can then be destroyed as a normal item (hardness 20, hp 1,200), which causes it to explode as if a <Link to="/tech-artifact/graviton_reactor">graviton reactor</Link>, but with twice as much damage and double the radius.</p>
</>};
const _extinction_wave_device = {title: "Extinction Wave Device", jsx: <><h2 id="tech-artifact-extinction_wave_device-extinction-wave-device">Extinction Wave Device</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 60</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> 1,000 lbs.<br/><strong>Capacity</strong> -; <strong>Usage</strong> -</p>
<p>An extinction wave device is a devastating and ruinous weapon indeed. When activated by a remote <Link to="/tech-misc/detonator">detonator</Link>, this bomb explodes in a spherical wash of reality-warping radiation, killing virtually all living creatures with an Intelligence score in a 1-mile radius, while leaving structures and simple life forms intact. Affected creatures must attempt a DC 35 Will saving throw to avoid instant death; success results in 10d8 points of damage instead. Unlike signals, an extinction wave is not hampered by most solid barriers and other materials, but force barriers with 25 or more hit points and metals alloyed with <Link to="/eq-material/djezet">djezet</Link> block it. An extinction wave is a mind-affecting death effect.</p>
<p>These statistics are for an extinction wave device designed to target command and control centers. Smaller and larger extinction wave devices exist. For example, a portable wave extinction device delivers a 1,000-foot-radius effect and weighs 50 pounds.</p>
</>};
const _memory_facet = {hasJL:true,title: "Memory facet", jsx: <><div className="jumpList" id="tech-artifact-memory_facet-jumplist"><h2>Jump to:</h2><ul><li><InnerLink toTop to="tech-artifact-memory_facet-aggression-facet">Aggression Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-compassion-facet">Compassion Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-creativity-facet">Creativity Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-cruelty-facet">Cruelty Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-discipline-facet">Discipline Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-ego-facet">Ego Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-entropy-facet">Entropy Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-guile-facet">Guile Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-inhibitor-facet">Inhibitor Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-ingenuity-facet">Ingenuity Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-instinct-facet">Instinct Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-intuition-facet">Intuition Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-logic-facet">Logic Facet</InnerLink></li><li><InnerLink toTop to="tech-artifact-memory_facet-psyche-facet">Psyche Facet</InnerLink></li></ul></div><h2 id="tech-artifact-memory_facet-memory-facet">Memory Facet</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_86_lords_of_rust">Pathfinder #86: Lords of Rust pg. 62</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> &mdash;<br/><strong>Capacity</strong> -; <strong>Usage</strong> -</p>
<p>A memory facet is a length of crystal about the size of a human thumb that's adorned at one end by a metal cap fitted with prongs and plugs. The crystal's interior contains sparkling veins of glittering light. A memory facet is a high-capacity storage device capable of containing a staggering amount of programming - these devices were rare and difficult to craft, and at the time Divinity began its mission, they were primarily used for one purpose: storing and transporting the staggeringly complex code required to program and enhance <Link to="/rule/artificial_intelligence">artificial intelligences</Link>. To use a memory facet, one needs simply to insert the crystal's connectors into an appropriate slot in an AI's core processor or a robot under the AI's control. A core processor or robot can hold as many memory facets as it has available slots, but at any one time, an AI can benefit from a maximum number of memory facets equal to its CR divided by 4 (minimum 1). The AI can gain the benefits of memory facets installed in any of the robots and processors it controls - where a memory facet is installed makes little difference, but most AIs prefer to keep their memory facets installed in their most secure locations.</p>
<p>Each memory facet contains a unique combination of emotions, knowledge, traits, and personality quirks designed to enhance and bolster an artificial intelligence's capabilities. In rare cases, destructive memory facets were created - items intended to disable or damage an artificial intelligence in case of emergencies. An AI immediately gains all of the advantages (and any disadvantages) associated with a particular memory facet as soon as it is installed (this is a full-round action). Memory facets can change an AI's personality or even its alignment. An AI can try to resist having a memory facet added to its code by attempting a DC 20 Will save. If the AI is successful, the memory facet ceases functioning for 1d4 rounds, and must be extracted and reinstalled to make a second attempt to changing the AI's code. Once installed, a memory facet is difficult to remove; removing one requires either a successful DC 25 Strength check to wrench free or a successful DC 30 Disable Device check. Both attempts are full-round actions.</p>
<h3 id="tech-artifact-memory_facet-aggression-facet" data-hash-target>Aggression Facet</h3>
<p>This memory facet enhances an AI's offensive protocols, imparting a +2 bonus on all attack rolls and weapon damage rolls, and granting <Link to="/feat/deadly_aim">Deadly Aim</Link> and <Link to="/feat/power_attack">Power Attack</Link> as bonus feats when the AI is controlling a robot.</p>
<h3 id="tech-artifact-memory_facet-compassion-facet" data-hash-target>Compassion Facet</h3>
<p>A compassion facet allows an AI to understand and even experience love and associated emotions, imparting a +2 bonus on all Will saving throws and granting a +4 bonus on Diplomacy and Sense Motive checks. An AI with a compassion facet can form a strong emotional bond with a number of creatures equal to its CR as a standard action - once this bond is formed, the AI gains a +4 bonus on attack rolls and weapon damage rolls while controlling a robot and making attacks against a creature the AI has witnessed harming one of its bonded creatures within the last hour.</p>
<h3 id="tech-artifact-memory_facet-creativity-facet" data-hash-target>Creativity Facet</h3>
<p>This memory facet enhances the AI's creativity and ability to react quickly to problems. It grants a +6 bonus to the AI's Charisma score and grants <Link to="/feat/improved_initiative">Improved Initiative</Link> as a bonus feat.</p>
<h3 id="tech-artifact-memory_facet-cruelty-facet" data-hash-target>Cruelty Facet</h3>
<p>This memory facet bolsters an AI's ability to do harm, granting a +4 bonus on all damage rolls. In addition, while the AI controls an <Link to="/template/aggregate">aggregate</Link>, the facet grants the aggregate a rogue's <Link to="/ability/sneak_attack">sneak attack</Link> ability (+2d6) and bleeding strike talent.</p>
<h3 id="tech-artifact-memory_facet-discipline-facet" data-hash-target>Discipline Facet</h3>
<p>This memory facet bolsters an AI's thought and personality with rigid order and behavior, granting it a +2 enhancement bonus to its Intelligence score. In addition, the facet grants the AI the ability to bolster the programming of any robot within 30 feet as a swift action for a number of rounds per day equal to its CR. A bolstered robot gains a +2 circumstance bonus on attack rolls, weapon damage rolls, and Will saving throws. The AI can target an aggregate under its control with this effect.</p>
<h3 id="tech-artifact-memory_facet-ego-facet" data-hash-target>Ego Facet</h3>
<p>An ego facet bolsters an AI's sense of self-esteem and sense of worth, imparting a +2 bonus on all Fortitude saving throws and a +4 bonus on Intimidate checks, as well as granting <Link to="/feat/toughness">Toughness</Link> as a bonus feat when the AI is controlling a robot.</p>
<h3 id="tech-artifact-memory_facet-entropy-facet" data-hash-target>Entropy Facet</h3>
<p>This memory facet enhances an AI's capacity to understand and interpret chaos theory and probabilities, allowing it to more swiftly react to and mimic emotions. The facet grants a +2 enhancement bonus to the AI's Charisma score. In addition, up to three times per day when the AI rolls a d20, it can roll twice and take either result as an immediate action. This ability must be used after the first roll but before the results are revealed.</p>
<h3 id="tech-artifact-memory_facet-guile-facet" data-hash-target>Guile Facet</h3>
<p>This facet augments the AI's skills at deception and trickery. The facet grants a +4 bonus on Bluff checks. When the AI attempts a Sense Motive check to see through a Bluff, it rolls twice and takes the higher result. Finally, while the AI is controlling a robot, it gains <Link to="/feat/improved_feint">Improved Feint</Link> and <Link to="/feat/greater_feint">Greater Feint</Link> as bonus feats; it does not need to meet the prerequisites for those feats.</p>
<h3 id="tech-artifact-memory_facet-inhibitor-facet" data-hash-target>Inhibitor Facet</h3>
<p>An inhibitor facet is unusual among memory facets in that it isn't intended to augment an AI at all, but rather to hinder and impair its functionality. When installed, an inhibitor facet reduces an AI's Charisma by 4 and imposes a -4 penalty on all skill checks, saving throws, initiative checks, and attack rolls. The effects of multiple inhibitor facets do not stack.</p>
<h3 id="tech-artifact-memory_facet-ingenuity-facet" data-hash-target>Ingenuity Facet</h3>
<p>An ingenuity facet grants an AI insight into the construction and maintenance of technological items and robot maintenance. This facet grants a +4 bonus on Disable Device checks, as well as the <Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link> and <Link to="/feat/craft_technological_item">Craft Technological Item</Link> feats. While the AI controls a robot, this facet given the AI the ability to repair 3d8+15 points of damage to any robot it can touch (including itself) as a full-round action at will, but only once per day for any given robot.</p>
<h3 id="tech-artifact-memory_facet-instinct-facet" data-hash-target>Instinct Facet</h3>
<p>This memory facet enhances the AI's ability to act on instinct. It grants a +6 bonus to the AI's Wisdom score and grants <Link to="/feat/combat_reflexes">Combat Reflexes</Link> as a bonus feat. The AI can use either its Wisdom modifier or its aggregate's Dexterity modifier (its choice) to determine the number of attacks of opportunity this bonus feat grants.</p>
<h3 id="tech-artifact-memory_facet-intuition-facet" data-hash-target>Intuition Facet</h3>
<p>An intuition facet bolsters the AI's processing speed by allowing it to use probability and intuition to make incredibly swift decisions. The facet grants a +2 bonus on all Reflex saving throws and Initiative checks, as well as granting <Link to="/feat/dodge">Dodge</Link> and <Link to="/feat/mobility">Mobility</Link> as bonus feats when the AI is in an aggregate.</p>
<h3 id="tech-artifact-memory_facet-logic-facet" data-hash-target>Logic Facet</h3>
<p>This memory facet enhances the AI's ability to utilize logic. It grants a +6 bonus to the AI's Intelligence score and grants <Link to="/feat/combat_expertise">Combat Expertise</Link> as a bonus feat.</p>
<h3 id="tech-artifact-memory_facet-psyche-facet" data-hash-target>Psyche Facet</h3>
<p>A psyche facet bolsters a robot's sense of self and enhances its ability to resist peril and danger. It grants a +3 resistance bonus on all saving throws. In addition, once per day the AI can restore a destroyed robot to activity, as <Link to="/spell/memory_of_function">memory of function</Link>, using the AI's CR as the effective caster level.</p>
</>};
const _power_relay = {title: "Power Relay", jsx: <><h2 id="tech-artifact-power_relay-power-relay">Power Relay</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_85_fires_of_creation">Pathfinder #85: Fires of Creation pg. 60</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> 50 lbs.<br/><strong>Capacity</strong> 10; <strong>Usage</strong> special</p>
<p>A power relay is a valuable device that allows the long-distance transmission of energy from a nearby generator to a device that can make use of it. Every <Link to="/tech-artifact/power_generator">power generator</Link> has a built-in power transmitter that allows for the transmission of power to a nearby power receiver, but an external power relay is required to send this energy beyond the generator's limitations. A power relay consumes 10 charges when it is activated (this is a full-round action), after which it automatically links to the closest generator within 1,000 feet that has an available yield. This distance is halved for every 5 feet of metal or 20 feet of solid stone between the generator and the power relay. (The power relay in "Fires of Creation" is just barely in range of the engineering deck reactor as a result.)</p>
<p>The power relay consumes 1 charge of the generator's available yield per hour to maintain its own power supplies, and can be programmed to transmit any remaining charges of available yield to any object capable of receiving broadcast power, to a maximum distance of 150 miles. This distance is halved for every 5 feet of metal or 20 feet of solid stone between the generator and the power relay. (As a result, Hellion has had to use a receiver array in Scrapwall, since the object he intends to charge is underground and farther than 75 miles away).</p>
<p>Power transmitted by this device is lost unless the device is programmed to transmit to a specific target capable of accepting a charge in range. Before a power relay can transmit, it must be linked to the target of its transmission to establish the transmission protocols. This consumes 10 charges and takes 1 minute to complete. Once completed, the distance between the power relay and the target of its transmissions can vary up to its maximum range. A small screen on the side of the power relay provides constant updates on the link, including bearings, distances, and the nature of the object to which it is linked. In the case of the power relay in this volume's adventure, that bearing and distance leads directly to Scrapwall - further information about this can be found in the next adventure, "Lords of Rust."</p>
<p>This device essentially functions as a power generator that provides an hourly yield of charges to its target. For example, if a power relay that provided a yield of 40 charges was linked to a <Link to="/tech-weapon/laser_pistol">laser pistol</Link>, that laser pistol could be fired 40 times per hour without needing an additional charge.</p>
<p>Power relays can only function a limited number of times before their delicate internal mechanisms burn out. Each time a power relay is used to initiate a new energy transfer, there's a cumulative 2% chance it burns out and becomes useless. Once a new transfer begins, a power relay can maintain that link between the generator and its target indefinitely (as long as there's always an available yield of at least 1 charge from the generator to keep itself powered). The power relay in this adventure has been used several times - the chance of burning out on its next activation is already at 50%.</p>
<p>Note that a power relay has built-in <Link to="/tech-misc/signal_booster">signal boosters</Link>, and thus the range of its transmissions cannot be further increased through the use of additional signal boosters.</p>
</>};
const _powered_armor = {title: "Powered Armor", jsx: <><h2 id="tech-artifact-powered_armor-powered-armor">Powered Armor</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 61</Link><br/><strong>Slot</strong> armor; <strong>Weight</strong> 50 lbs.<br/><strong>Capacity</strong> 100; <strong>Usage</strong> see text</p>
<p><strong>Type:</strong> Heavy<br/><strong>AC:</strong> +10<br/><strong>Max Dex:</strong> +4<br/><strong>Penalty:</strong> -2<br/><strong>Spell Failure:</strong> 60%<br/><strong>Speed (30 ft.):</strong> See text<br/><strong>Speed (20 ft.):</strong> See text</p>
<p>Powered armor represents the pinnacle of personal armor - a suit crafted of multiple <Link to="/eq-material/skymetal">skymetals</Link> and other materials designed to augment the wearer in numerous ways. The armor actually boosts land speed when worn, granting a +10 foot enhancement bonus to the wearer's speed. While worn, powered armor also grants a +6 enhancement bonus to Strength and Dexterity. Powered armor protects against energy and the environment as if it were a <Link to="/tech-armor/spacesuit">spacesuit</Link>. Powered armor has hardness 20 and 300 hit points. Powered armor is fitted with numerous small booster jets that grant the wearer a fly speed of 60 feet (with average maneuverability) in areas of no gravity and 20 feet (with poor maneuverability) in gravity.</p>
<p>As a standard action, the wearer may activate the armor's self-repair system. The armor consumes a single charge and repairs 2d6 points of damage. Only 1 charge can be consumed per turn for this effect.</p>
<p>In addition, the following technological wonders are integrated into a suit of powered armor - each of these devices drains power from the suit's charges as appropriate when they are activated and used.</p>
<ul>
<li><Link to="/tech-misc/camera">Camera</Link> in the helmet.</li>
<li><Link to="/tech-misc/commset">Commset</Link> in the helmet.</li>
<li><Link to="/tech-misc/fire_extinguisher">Fire extinguisher</Link> mounted on the left wrist.</li>
<li><Link to="/tech-misc/flashlight">Flashlight</Link> mounted on the helmet.</li>
<li>Gloves that can function as <Link to="/tech-misc/grippers">grippers</Link>.</li>
<li><Link to="/tech-weapon/laser_pistol">Laser pistol</Link> mounted on the right forearm that leaves the hand free. Firing this laser pistol is always considered an off-hand attack, and the number of times it can be fired cannot be increased by feats like <Link to="/feat/improved_two_weapon_fighting">Improved Two Weapon Fighting</Link>.</li>
<li><Link to="/tech-misc/magboots">Magboots</Link>.</li>
<li>Three <Link to="/tech-misc/medlance">medlances</Link>. Each medlance can be loaded with a single potion or pharmaceutical; activating an integrated medlance is an immediate action.</li>
<li><Link to="/tech-misc/power_receiver">Power receiver</Link>.</li>
<li><Link to="/tech-misc/prismatic_force_field">Prismatic force field</Link> located on hips; activating this force field is a swift action.</li>
<li><Link to="/tech-misc/radiation_detector">Radiation detector</Link> on the right wrist.</li>
<li>Custom <Link to="/tech-misc/veemod_brown">veemods</Link> in the visor grant a +10 bonus on Perception checks, low light vision, darkvision up to 120 feet, and all-around vision.</li>
</ul>
<p>Rumors persist of variant forms of powered armor, including suits sized for giants or that can function as vehicles for multiple creatures.</p>
</>};
const _psychic_imprinter = {title: "Psychic Imprinter", jsx: <><h2 id="tech-artifact-psychic_imprinter-psychic-imprinter">Psychic Imprinter</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 61</Link><br/><strong>Slot</strong> head; <strong>Weight</strong> 10 lbs.<br/><strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge</p>
<p>A more advanced version of the <Link to="/tech-misc/neurocam">neurocam</Link>, a psychic imprinter resembles a helmet with a closed and opaque visor. It can be adjusted to fit over the head a Small, Medium, or Large humanoid. In its recording mode, it records a complete mental image of that creator into its data banks. This functions as a neurocam's recording mode, except the DC for the Will save to resist is 30. This image remains until a new recording overwrites it.</p>
<p>In its imprinting mode, the device writes its stored mental image over the mind of the creature wearing it, destroying the creature's original memories and personality in the process. The target retains its physical ability scores, racial abilities, and any racial Hit Dice. It gains the mental abilities, class levels, feats, skills, and spell-like abilities of the stored image in place of its own. A successful DC 30 Will saving throw negates erasure. An imprinter can be set to record the mental image of the target as the device overwrites its mind. Otherwise, the old personality is utterly destroyed in the process, beyond the reach of all means except a miracle or wish spell, or divine intervention.</p>
<p>Stored memories can be transferred between neurocams and psychic imprinters without consuming charges from either device.</p>
</>};
const _rebirthing_chamber = {title: "Rebirthing Chamber", jsx: <><h2 id="tech-artifact-rebirthing_chamber-rebirthing-chamber">Rebirthing Chamber</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 61</Link><br/><strong>Slot</strong> none; <strong>Weight</strong> 1,200 lbs.<br/><strong>Capacity</strong> -; <strong>Usage</strong> 200 charges/day</p>
<p>This enclosed pod of metal and plastic contains a thinly padded bed on which to lay, and dozens of small vents along its interior. A rebirthing chamber cannot operate on its own power, and must be attached to an external power source. When a Small or Medium humanoid lies within a rebirthing chamber, the chamber automatically seals. Soporific gas fills the chamber, inducing a deathlike coma (Fortitude DC 30 each round negates; this is a poison effect). One minute after it seals, the chamber floods with nanites that first analyze, then reduce the occupant to its component molecules. The dismantling process deals 6d10 points of damage and 1d4 point of <Link to="/rule/constitution_damage">Constitution damage</Link> each round (Fortitude DC 30 half), a horrifically painful process should the occupant retain consciousness. Any gear worn by the occupant is dismantled and destroyed, with possibly catastrophic results for explosives and powered devices.</p>
<p>Over the next 1d4 days, the nanites reconstruct and enhance the occupant, in effect optimizing its genetic code. The occupant wakes up with full memories of its prior existence, but in the body of a young adult of its race, halfway between the minimum and maximum age of its current age category. In the process, all ability scores receive a +2 inherent bonus.</p>
<p>Each time a rebirthing chamber is used, there is a 10% chance its nanite reconstruction fails, leaving the host dead and without remains. Only a <Link to="/spell/miracle">miracle</Link>, <Link to="/spell/true_resurrection">true resurrection</Link>, or <Link to="/spell/wish">wish</Link> can restore such a hapless victim. The nanite reservoir contains sufficient nanites for five rebirths, assuming it hasn't been previously used.</p>
<p>A rebirthing chamber only works on humanoids and humanoid corporeal undead. It can even restore life to a long-dead corpse, so long as usable genetic information remains, but with a 25% chance of failure instead of 10%. For each day that passed without preservation such as <Link to="/spell/gentle_repose">gentle repose</Link>, the revived creature loses roughly 10% of its memories and gains 1 permanent negative level. If the negative levels gained exceed the creature's level, the revival fails. Intelligent corporeal undead retain their memories after revival, but lose all undead abilities and regain their original statistics and abilities from their time among the living. Effects that restore these negative levels also restore these lost memories.</p>
<p>Attempts to rebirth a creature without a soul invariably fail, as do attempts to rebirth a creature from partial remains while the creature is still alive. A body is created and draws breath, but lacks any intellect and dies 2d6 hours after the process completed.</p>
</>};
const _temporal_accelerator = {title: "Temporal Accelerator", jsx: <><h2 id="tech-artifact-temporal_accelerator-temporal-accelerator">Temporal Accelerator</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 62</Link><br/><strong>Slot</strong> head; <strong>Weight</strong> 1 lb.<br/><strong>Capacity</strong> -; <strong>Usage</strong> -</p>
<p>When placed on the back of the skull, this curved metal bar adheres to the skin and releases a network of microscopic probes that interface directly with the wearer's brain. As a swift action, the device can be activated to stimulate the wearer's brain into accelerated activity. For 1 minute, the wearer gains two sets of actions each turn - two move, two standard, and two swift actions - in any order desired. A standard and move action can be combined into a full-round action as normal, but actions with a duration of 1 round still take up the wearer's entire turn. When the duration expires (or the effects ends for any reason), the device deals 2 points of <Link to="/rule/constitution_drain">Intelligence and Constitution drain</Link> as well as shortens the wearer's maximum lifespan by 5 years as a result of neurological deterioration. This shortened lifespan does not hasten the accumulation of age-related bonuses or penalties; it merely hastens death from old age. While the ability drain caused by the temporal accelerator can be treated with restoration and similar effects, the wearer's shortened lifespan cannot.</p>
<p>If a temporal accelerator is activated more than once in a 24-hour period, the wearer takes an additional 2d4 points of Constitution and Intelligence damage in addition to the Constitution drain at the end of the device's effect, and loses an additional 10 years of life expectancy instead of 5 for activating the device. A successful DC 25 Fortitude save reduces the ability damage by half. The ability damage increases by 1d4 and the save DC increases by 5 for each activation beyond the second in a 24-hour period.</p>
<p>A temporal accelerator can be disarmed or sundered with a <Link to="/rule/disarm">disarm</Link> or <Link to="/rule/sunder">sunder</Link> combat maneuver. It has hardness 10 and 5 hit points. Destroying or ripping away an attached temporal accelerator causes 1d8 points of Intelligence damage to the wearer, in additional to ending the effects of the device if active at the time.</p>
</>};
const _power_generator = {title: "Power Generator", jsx: <><h3 id="tech-artifact-power_generator-power-generator">Power Generator</h3>
<p>Power generators are a specific type of technological artifact capable of providing large amounts of sustained energy, and that can supply charges to entire compounds. Every robot has a dedicated power generator within it that provides enough energy to run that robot and nothing more. Generators that are free-standing devices or built into complexes can be used to charge technological items capable of being recharged. A device hooked directly to a functioning power generator uses the generator's energy rather than its own stored energy.</p>
<p>Full rules on generators <Link to="/rule/tech_artifacts">can be found here</Link>.</p>
<ul>
<li><Link to="/tech-artifact/divinity_drive">Divinity Drive</Link></li>
<li><Link to="/tech-artifact/fission_reactor">Fission Reactor</Link></li>
<li><Link to="/tech-artifact/fusion_reactor">Fusion Reactor</Link></li>
<li><Link to="/tech-artifact/geothermal_generator">Geothermal Generator</Link></li>
<li><Link to="/tech-artifact/graviton_reactor">Graviton Reactor</Link></li>
<li><Link to="/tech-artifact/solar_generator">Solar Generator</Link></li>
</ul>
</>};
const _fission_reactor = {title: "Fission Reactor", jsx: <><h2 id="tech-artifact-fission_reactor-fission-reactor">Fission Reactor</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 63</Link><br/><strong>Yield</strong> 1,000; <strong>Fort</strong> +2; <strong>Hardness</strong> 10; <strong>HP</strong> 1,500; <strong>Explosion</strong> 20d10 bludgeoning and 20d10 fire plus severe <Link to="/rule/radiation">radiation</Link> (250-ft. radius; Reflex DC 20 half); <strong>Perception Penalty</strong> -10</p>
<p>A fission reactor harnesses power from nuclear energy gathered by processing and consuming radioactive fuel. Once activated, a fission reactor can function for many years before its radioactive fuel must be replaced. The core of a fission reactor is constantly irradiated at a high level of radioactivity; the bulk of the reactor actually consists of shielding meant to protect those nearby from <Link to="/rule/radiation">radiation poisoning</Link>. If a fission generator explodes, it inundates its blast radius with severe radiation. These generators are relatively rare: while they produce the highest yield of all generators, the incredible damage they can do if they do explode often means that safety-minded operators find them suitable only for remote, unmanned operations.</p>
</>};
const _fusion_reactor = {title: "Fusion Reactor", jsx: <><h2 id="tech-artifact-fusion_reactor-fusion-reactor">Fusion Reactor</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 63</Link><br/><strong>Yield</strong> 500; <strong>Fort</strong> +10; <strong>Hardness</strong> 10; <strong>HP</strong> 1,800; <strong>Explosion</strong> 10d6 bludgeoning and 10d6 fire and 10d6 electricity (100-ft. radius; Reflex DC 20 half); <strong>Perception Penalty</strong> -10</p>
<p>Although fusion reactors are superficially similar to <Link to="/tech-artifact/fission_reactor">fission reactors</Link>, the fact that their source of fuel is little more than seawater makes them much safer to operate.</p>
</>};
const _geothermal_generator = {title: "Geothermal Generator", jsx: <><h2 id="tech-artifact-geothermal_generator-geothermal-generator">Geothermal Generator</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 63</Link><br/><strong>Yield</strong> 200; <strong>Fort</strong> +4; <strong>Hardness</strong> 10; <strong>HP</strong> 1,000; <strong>Explosion</strong> 10d6 bludgeoning and 10d6 fire (60-ft. radius; Reflex DC 15 half); <strong>Perception Penalty</strong> -5</p>
<p>A geothermal generator doesn't take up much room on the surface, but its components reach far into the earth and tap upon superheated water, steam, and even magma to generate power. Once activated, a geothermal generator can continue to function indefinitely. Geothermal generators tend to run hot; physical contact with one causes 1d6 points of fire damage per round.</p>
</>};
const _graviton_reactor = {title: "Graviton Reactor", jsx: <><h2 id="tech-artifact-graviton_reactor-graviton-reactor">Graviton Reactor</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 63</Link><br/><strong>Yield</strong> 800; <strong>Fort</strong> +14; <strong>Hardness</strong> 20; <strong>HP</strong> 2,500; <strong>Explosion</strong> 10d6 bludgeoning, 10d6 electricity, and 20d6 force (50-ft. radius; Reflex DC 20 half; see text); <strong>Perception Penalty</strong> -2</p>
<p>A graviton reactor produce tremendous amounts of energy. It's fairly quiet while running, generating little more than a low-frequency hum. Damage caused by a graviton reactor explosion consists of an implosion rather than a classic explosion. On the round following this implosion, all objects and creatures in the blast radius suffer the explosion damage again as they are then hurled back outward. No radiation is generated by a graviton reactor, and creatures and objects outside the blast radius can escape relatively unharmed (apart from possible damage resulting from objects that are hurled beyond the blast radius).</p>
</>};
const _solar_generator = {title: "Solar Generator", jsx: <><h2 id="tech-artifact-solar_generator-solar-generator">Solar Generator</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 63</Link><br/><strong>Yield</strong> 50; <strong>Fort</strong> +5; <strong>Hardness</strong> 2; <strong>HP</strong> 100; <strong>Explosion</strong> none; <strong>Perception Penalty</strong> +0</p>
<p>A solar generator consists of a fairly small converter attached to a set of huge reflective panels. It produces full yield while receiving direct sunlight. Its yield halves during overcast conditions. At night or when densely overcast, its yield drops to 0. A solar generator runs silently. A solar generator cannot be forced to exceed its yield.</p>
</>};
export default {not_found:_not_found,arms_of_the_iron_god:_arms_of_the_iron_god,autodoc:_autodoc,beam_cannon_gravity_cannon:_beam_cannon_gravity_cannon,compact_ai_core:_compact_ai_core,divinity_drive:_divinity_drive,extinction_wave_device:_extinction_wave_device,memory_facet:_memory_facet,power_relay:_power_relay,powered_armor:_powered_armor,psychic_imprinter:_psychic_imprinter,rebirthing_chamber:_rebirthing_chamber,temporal_accelerator:_temporal_accelerator,power_generator:_power_generator,fission_reactor:_fission_reactor,fusion_reactor:_fusion_reactor,geothermal_generator:_geothermal_generator,graviton_reactor:_graviton_reactor,solar_generator:_solar_generator}