import Link from '../../components/Link';
const _not_found = {title: "Unknown", jsx: <><h2 id="emotionalfocus-not_found-unknown">Unknown</h2>
<p>Unable to find the requested emotional focus.</p>
</>};
const _anger = {title: "Anger", jsx: <><h2 id="emotionalfocus-anger-anger">Anger</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 80</Link><br/>Phantoms with this emotional focus are filled with seething anger from events in their past lives. Phantoms with this focus often take the form of hulking brutes with furrowed brows or of frenzied creatures that always seem ready to strike down those who come too near. Many times, these phantoms exude a bright red aura, especially when they are engaged in combat, or they seem to breathe a red mist in shallow pants from behind clenched, phantasmal teeth.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Intimidate and Survival equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Will.</p>
<p><strong>Strength Focus:</strong> The phantom gains a +2 bonus to Strength and a -2 penalty to Dexterity. Instead of the phantom gaining a bonus to Dexterity as the spiritualist gains levels, an anger-focused phantom gains a bonus to Strength instead.</p>
<p><strong>Powerful Strike (Ex):</strong> A phantom with this focus deals more damage with its slam attacks. It deals slam damage as a creature one size category larger than its current size. The phantom also gains <Link to="/feat/power_attack">Power Attack</Link> as a bonus feat.</p>
<p><strong>Aura of Fury (Su):</strong> When the spiritualist reaches 7th level, as a swift action, the phantom can emit a 20-foot-radius aura of fury. Creatures within the aura gain a +2 bonus on melee attack rolls but take a -2 penalty to AC. Ending the aura is a free action. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Ferocious Mien (Su):</strong> When the spiritualist reaches 12th level, once per day as a swift action, a phantom in ectoplasmic form can grow more ferocious and frightening. It becomes one size category larger than its current size, as affected by an <Link to="/spell/enlarge_person">enlarge person</Link> spell, and grows fiercer in combat, as if affected by a <Link to="/spell/rage">rage</Link> spell. This effect lasts for 1 round per class level of the spiritualist. When the spiritualist reaches 18th level, a phantom using ferocious mien also gains the <Link to="/umr/frightful_presence">frightful presence</Link> extraordinary ability (range 30 feet, duration 5d6 rounds).</p>
<p><strong>Furious Wail (Su):</strong> When the spiritualist reaches 17th level, once per day as a standard action, the phantom can emit a single angry wail that acts as <Link to="/spell/wail_of_the_banshee">wail of the banshee</Link>. The phantom uses its Hit Dice as its caster level for the effect, and the DC of the effect is 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
</>};
const _dedication = {title: "Dedication", jsx: <><h2 id="emotionalfocus-dedication-dedication">Dedication</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 80</Link><br/>Either through a sense of love or the desire to finish some unfinished task, a phantom with this emotional focus has an undying devotion to something or someone in the world. It's often the case that a phantom with this emotional focus has a strong familial tie with its spiritualist master. A dedication phantom most often appears as a strong and stern protector with a watchful gaze, and its service to its spiritualist is unwavering. These spirits exude auras of blue, or sometimes rose if their love for their spiritualist masters in life was great. Many times these auras manifest as a halo, giving these phantoms a divine appearance, no matter their actual alignment or opinions on matters of religion.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Diplomacy and Sense Motive equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Reflex and Will.</p>
<p><strong>Iron Will:</strong> The phantom gains <Link to="/feat/iron_will">Iron Will</Link> as a bonus feat. Furthermore, when the phantom is within its master's consciousness, it grants the benefits of Iron Will to its master if its master doesn't have that feat.</p>
<p><strong>Dutiful Strike (Su):</strong> When a creature makes an attack against the phantom's master, the phantom gains a +2 bonus on attack rolls against that target, and deals damage against that target as if the phantom were one size category larger. For the purposes of this ability, an attack includes any harmful spell targeting the spiritualist master of whose area or effect includes the spiritualist master. Dutiful strike lasts for 1 minute, until another creature attacks the phantom's spiritualist master (at which point this effect transfers to the new attacker), or until the attacking creature is reduced to fewer than 0 hit points, whichever occurs first.</p>
<p><strong>Defending Aura (Su):</strong> When the spiritualist reaches 7th level, the phantom can emit a 10-foot-radius aura that grants protection to nearby allies. It can activate this aura at will as a swift action. Allies within the aura gain a +2 deflection bonus to AC and a +2 bonus to CMD and on all saving throws. Deactivating the aura is a free action.</p>
<p><strong>Devoted Servant (Su):</strong> When the spiritualist reaches 12th level and is caught unawares by an attack (such as an attack made in a surprise round or while the spiritualist is asleep or an attack by a creature using Stealth), if the phantom is not fully manifested, it automatically fully manifests from the spiritualist's consciousness to protect its master. The phantom stays manifested as long as the spiritualist is unaware and in danger. This ability requires no action from the spiritualist.</p>
<p><strong>Steadfast Devotion (Su):</strong> When the spiritualist reaches 17th level, the phantom becomes immune to detrimental mind-affecting effects and all forms of possession, such as <Link to="/spell/magic_jar">magic jar</Link> and <Link to="/spell/possession">possession</Link>. Furthermore, the phantom is immune to <Link to="/spell/banishment">banishment</Link>, <Link to="/spell/dismissal">dismissal</Link>, and similar effects.</p>
</>};
const _despair = {title: "Despair", jsx: <><h2 id="emotionalfocus-despair-despair">Despair</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 81</Link><br/>Some creatures die in such horrific ways, or live such pointless and senseless lives, that despair grips their very beings. Phantoms with this focus use misery as a weapon, inflicting the living with the gloom of the phantoms' continued existence. Despair phantoms often appear twisted or wounded, showing the grisly circumstances of their demise. Their coloration tends to have a grayish or sickly green cast. When they speak, they do so in terrifying whispers or high-pitched screeches.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Intimidate and Stealth equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Will.</p>
<p><strong>Power from Despair:</strong> The phantom gains a +2 bonus on attack and damage rolls against creatures that are shaken, frightened, panicked, cowering, or subject to effects such as <em>aura of despair</em> or <em>crushing despair.</em></p>
<p><strong>Miserable Strike (Su):</strong> If the phantom hits a creature with a slam attack, that creature must succeed at a Will saving throw (DC = 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier) or take a -2 penalty on attack and damage rolls for 1 round. This is a mind-affecting fear and emotion effect. Penalties from multiple hits don't stack with themselves.</p>
<p><strong>Aura of Despair (Su):</strong> When the spiritualist reaches 7th level, as a swift action, the phantom can emit a 10-foot aura of despair. Enemies within the aura take a -2 penalty on all saving throws. This is a fear effect. Deactivating the aura is a free action.</p>
<p><strong>Despairing Shout (Su):</strong> When the spiritualist reaches 12th level, three times per day as a standard action, the phantom can emit a shout that acts as <Link to="/spell/crushing_despair">crushing despair</Link>. The phantom uses its Hit Dice as its caster level for the effect, and the DC of the effect equals 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Inescapable Despair (Su):</strong> When the spiritualist reaches 17th level, if the phantom hits with its slam attack, the creature hit doesn't get a save to resist the effects of miserable strike.</p>
</>};
const _desperation = {title: "Desperation", jsx: <><h2 id="emotionalfocus-desperation-desperation">Desperation</h2>
<p><strong>Sources</strong> <Link to="/source/elemental_masters_handbook">Elemental Master's Handbook pg. 13</Link><br/>A phantom with this emotional focus died desperate and panicking - a victim of drowning, suffocation, or some other inexorable and traumatic death. The phantom relives its horrific demise over and over, futilely clawing at its foes to save itself and dragging them down with it. Desperation phantoms often hold power over water, though a phantom that died in a cave-in might display powers that are reminiscent of pressing rock instead. Desperation phantoms eschew coherent forms, usually appearing as a cloud of grasping hands and screaming faces. A blue-gray aura tends to surround these phantoms when they manifest.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Acrobatics and Escape Artist equal to its number of Hit Dice. While confined in the spiritualist's consciousness, such a phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Reflex and Will.</p>
<p><strong>Combat Reflexes:</strong> The phantom gains <Link to="/feat/combat_reflexes">Combat Reflexes</Link> as a bonus feat. Furthermore, when the phantom is within its master's consciousness, it grants the benefits of Combat Reflexes to its master (if its master doesn't have that feat).</p>
<p><strong>Frantic Grip (Ex):</strong> The phantom can add its Dexterity modifier instead of its Strength modifier to its combat maneuver bonus when attempting to grapple. When the phantom is below half its total hit points, it gains a +4 bonus on grapple attempts and to its CMD against grapple combat maneuvers.</p>
<p><strong>Aura of Desperation (Su):</strong> When the spiritualist reaches 7th level, the phantom can emit a 10-foot-radius aura that fills its foes with the sensation of drowning, suffocation, or another terrible impending death. It can activate this aura as a swift action. Enemies attempting to cast a spell with a verbal component within the aura must succeed at a <Link to="/rule/concentration">concentration</Link> check (DC = 10 + half the phantom's Hit Dice + the level of the spell being cast) or lose the spell. This is a mind-affecting effect. Deactivating the aura is a free action.</p>
<p><strong>Clutch of Terror (Su):</strong> When the spiritualist reaches 12th level, the phantom can summon a mass of hands to grapple an enemy within 60 feet as a standard action. The hands immediately attempt a grapple combat maneuver against the target using the phantom's statistics (including the phantom's CMB), except the hands are collectively considered to be the same size as the target. On following rounds, the hands attempt to maintain the grapple (the hands cannot pin the target, however). Each round that the hands successfully grapple a target, the hands also deal the phantom's normal slam damage to the target. The hands immediately disappear and the effect ends if the hands fail to grapple their target, if the target escapes the grapple or dies, or if the phantom ceases to be manifested. The effect also ends if the phantom uses this ability against a different target. The phantom can use this ability three times per day.</p>
<p><strong>Burst of Desperation (Sp):</strong> When the spiritualist reaches 17th level, once per day as a standard action, the phantom can affect itself and the spiritualist with the effects of <Link to="/spell/haste">haste</Link>. The caster level of this effect is equal to the spiritualist's caster level. The phantom or the spiritualist can dismiss this effect as a free action. The duration of this ability must be used all at once, and any of the effect's remaining rounds per day are lost after this ability is dismissed.</p>
</>};
const _fear = {title: "Fear", jsx: <><h2 id="emotionalfocus-fear-fear">Fear</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 82</Link><br/>A phantom with this emotional focus suffered from overwhelming fear in life. As a phantom, it is able to channel that fear into a terrifying weapon. Fear phantoms are often horrifying to behold. Sometimes they appear as ghostly figures in tattered funeral garb or wrapped in chains or other bindings. Their features may be distorted into gaunt and haunting forms, making them seem more like ghosts or spectres. A miasma of livid gray swirling motes often surrounds their forms as they stalk their surroundings, seeking to bestow their terror on others.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Intimidate and Stealth equal to its number of Hit Dice. While confined in the spiritualist's consciousness, such a phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Reflex and Will.</p>
<p><strong>Stealthy:</strong> The phantom gains <Link to="/feat/stealthy">Stealthy</Link> as a bonus feat.</p>
<p><strong>Horrifying Strike (Ex):</strong> If the phantom hits a creature with a slam attack, that creature must succeed at a Will saving throw (DC = 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier) or be shaken for 1d4 rounds. Multiple attacks against the same creature do not cause the creature to become frightened. This is a mind-affecting fear effect.</p>
<p><strong>Increase Fear (Su):</strong> When the spiritualist reaches 7th level, as a swift action, the phantom can emit a 20-foot-radius aura that amplifies the fear conditions of enemies within it if they fail their Will saving throws (DC = 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier). A <Link to="/misc/shaken">shaken</Link> enemy in the aura becomes <Link to="/misc/frightened">frightened</Link>, a frightened creature becomes <Link to="/misc/panicked">panicked</Link>, and a panicked creature <Link to="/misc/cowering">cowers</Link>. This effect lasts either as long as the enemy stays within the aura and is under the condition of the initial fear effect, or for a number of rounds after it leaves the aura equal to 1/2 the phantom's Hit Dice, or until the end of the original fear effect's duration, whichever comes first. A creature that succeeds at the saving throw is immune to this effect from the same phantom for 24 hours. This is a mind-affecting fear effect. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Frightful Attack (Su):</strong> When the spiritualist reaches 12th level, if the phantom hits with a slam attack, it can frighten those it hits instead of causing them to be shaken (the phantom chooses when it makes the attack). This is a mind-affecting fear effect.</p>
<p><strong>Shelter Allies (Su):</strong> When the spiritualist reaches 17th level, the phantom protects its allies from terror. Allies within the phantom's increase fear aura are immune to fear as long as they are within the aura. This ability also grants the phantom's spiritualist master immunity to fear as long as the phantom is not banished to the Ethereal Plane.</p>
</>};
const _greed = {title: "Greed", jsx: <><h2 id="emotionalfocus-greed-greed">Greed</h2>
<p><strong>Sources</strong> <Link to="/source/occult_realms">Occult Realms pg. 14</Link><br/>A phantom with this focus voraciously coveted gold, gems, and hedonistic possessions in life. Such phantoms are still obsessed with hoarding wealth and project that avarice onto the spiritualists to whom they are bonded. Their coloration tends toward yellow, and the sound of jangling coins sometime manifests when they attack.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Appraise and Sleight of Hand equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Reflex.</p>
<p><strong>Eye of Avarice:</strong> The phantom adds half its number of Hit Dice (minimum 1) as a bonus on its Appraise checks. While it is confined to the spiritualist's consciousness, when the spiritualist attempts to identify the properties of a magic item using detect magic, the phantom grants the spiritualist this bonus on Spellcraft check.</p>
<p><strong>Ruthless Combatant (Su):</strong> A phantom with this focus threatens a critical hit with its slam attacks on a result of 19-20. At 11th level, its critical multiplier with slam attacks increases to &times;3.</p>
<p><strong>Assume Effect (Su):</strong> When the spiritualist reaches 7th level, when she casts a spell on herself with a range other than personal, the spell can also affect her phantom. The phantom can benefit from this ability once per day, plus one additional time per day when the spiritualist reaches 12th level and a third time when the spiritualist reaches 19th level.</p>
<p><strong>Covetous Aura (Su):</strong> When the spiritualist reaches 12th level, as a swift action the phantom can emit a 20-foot-radius aura that exemplifies its covetous nature. The aura lasts for a number of rounds per day equal to the phantom's Hit Dice. These rounds need not be used consecutively, and the phantom can dismiss its covetous aura as a free action. Whenever a harmless (so noted by a spell's saving throw description) spell of 2nd level or lower is cast by a creature within the covetous aura, the phantom can immediately gain the benefit of that spell as if the spell had also targeted it. The intended target still gains the effect of the spell.</p>
<p><strong>Take It with You (Su):</strong> When the spiritualist reaches 17th level, whenever the phantom is reduced to 0 hit points, a number of harmless spells affecting the phantom equal to the phantom's Charisma modifier are immediately transferred to the spiritualist for the remainder of their duration. If desired, the spiritualist can transfer only some (or none) of the spells affecting the phantom.</p>
</>};
const _hatred = {title: "Hatred", jsx: <><h2 id="emotionalfocus-hatred-hatred">Hatred</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 82</Link><br/>Few things draw a spirit toward the Negative Material Plane like the emotion of hatred. Phantoms with this focus often are blinded by - and blind others with - this powerful emotion. These phantoms are frequently darker and more foreboding than all but those phantoms with the fear emotional focus. Many of them manifest as dark and dreadful knights, their armor bristling with spikes and their hands seeming to grasp barbed and terrible weapons. Other times they appear as tall, gaunt figures staring down arrogantly at those who approach. These phantoms typically spew a string of curses at their foes, often profane, sometimes poetic. Their auras are pulsating and pitch black, and thrum violently when these horrible phantoms attack.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Acrobatics and Perception equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Reflex.</p>
<p><strong>Weapon Finesse:</strong> The phantom gains <Link to="/feat/weapon_finesse">Weapon Finesse</Link> as a bonus feat.</p>
<p><strong>Hated Target (Su):</strong> The phantom can take a move action to designate one creature within its line of sight as a hated target. The phantom gains a +2 bonus on attack rolls against its hated target, and a bonus on damage rolls equal to 1/2 the phantom's Hit Dice (minimum 1). The phantom is so focused on this hated target that it takes a -2 penalty on attack rolls against all other creatures. The phantom can maintain these bonuses against only one target at a time, and these bonuses remain in effect until either the hated opponent is dead or it has been out of the phantom's line of sight for at least 1 minute. When the spiritualist reaches 7th level, the phantom can use this ability as a swift action, and takes no penalty when attacking creatures that are not designated as its hated enemy. The phantom must be manifested in ectoplasmic form to use this ability (unless the spiritualist is 17th level or higher; see Shared Hatred below).</p>
<p><strong>Hateful Aura (Su):</strong> When the spiritualist reaches 7th level, as a swift action, the phantom can emit a 10-foot-radius aura that inflicts pain upon the minds of those who dare damage it or its master. Enemies within the aura that deal damage to the spiritualist or the phantom take an amount of damage equal to the phantom's Charisma bonus. This is a mind-affecting pain effect. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Sneak Attack (Su):</strong> When the spiritualist reaches 12th level, the phantom gains <Link to="/ability/sneak_attack">sneak attack</Link> +3d6, but only against its hated enemy. At 18th level, the sneak attack damage increases to +5d6.</p>
<p><strong>Shared Hatred (Su):</strong> When the spiritualist reaches 17th level, the phantom can grant its hatred to others. When the phantom designates a hated enemy, its allies also gain a +2 bonus on attack rolls and a +4 bonus on damage rolls against that enemy. Furthermore, the phantom can use its hated target ability even when in incorporeal form; when it does, it can make slam attacks against a corporeal creature, but only if that corporeal creature is its hated target.</p>
</>};
const _jealousy = {title: "Jealousy", jsx: <><h2 id="emotionalfocus-jealousy-jealousy">Jealousy</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 83</Link><br/>A phantom with this emotional focus is covetous of everything - its master, those who wish to do it harm, and any who do not pay attention to it. It demands to be the center of attention at all times. The forms these phantoms take are as diverse as the forms of jealousy in life. Often they take pleasing forms, wishing to draw others in. Other times they take the form of crawling and lurching things, grasping at all they covet when they come within reach. The auras of these needy phantoms quickly change in color, going from an oily green to orange, to brownish red as they swirl through emotions in their efforts to gain the objects of their dark desires.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Appraise and Bluff equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Reflex and Will.</p>
<p><strong>Deceitful:</strong> The phantom gains <Link to="/feat/deceitful">Deceitful</Link> as a bonus feat.</p>
<p><strong>Jealous Combatant (Su):</strong> Each time the phantom hits a creature with a melee attack, for 1 round that creature takes a -2 penalty on all attack rolls made against anyone other than the phantom. This effect does not stack with itself.</p>
<p><strong>Resentful Aura (Su):</strong> When the spiritualist reaches 7th level, as a swift action, the phantom can emit a 20-foot-radius aura that forces enemies within the aura who make an attack or cast a spell that does not include the phantom in its effect to succeed at a Will saving throw (DC = 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier) or become <Link to="/misc/staggered">staggered</Link> until the end of the enemy's next turn. Ending the aura is a free action. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Retribution (Su):</strong> When the spiritualist reaches 12th level, each time a creature attacks the phantom's master, whether that attack hits or misses, it enrages the phantom. Until the end of the phantom's next turn, any attack the phantom makes that hits the creature that has attacked her deals 2d8 extra points of damage. This extra damage is <Link to="/misc/precision_damage">precision damage</Link>.</p>
<p><strong>Mine to Take (Su):</strong> When the spiritualist reaches 17th level, once per day as an immediate action, just before the phantom's master is about to attempt a saving throw or be targeted by an attack roll, the phantom and the spiritualist can swap places as long as both are on the same plane and the phantom is aware of the attack or effect. After the swap occurs, the phantom is targeted by the attack or effect that triggered this ability, though the phantom may be immune or resistant to the effect. This is a teleportation effect. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
</>};
const _kindness = {title: "Kindness", jsx: <><h2 id="emotionalfocus-kindness-kindness">Kindness</h2>
<p><strong>Sources</strong> <Link to="/source/psychic_anthology">Psychic Anthology pg. 4</Link><br/>A phantom with this emotional focus was a being with a generous heart in life and continues to remain that way well after death. The phantom's intense generosity compels it to remain a phantom and continue assisting the living, especially relatives or those who had been its good friends during its living years. Kindness phantoms have pleasant and gentle demeanors and speak with a melodic cadence, putting most who see them at ease. Their auras are bright emerald green with occasional fluctuating scarlet or golden hues.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Diplomacy and Heal equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Will.</p>
<p><strong>Benevolent:</strong> When the phantom uses the <Link to="/rule/aid_another">aid another</Link> action, the bonus granted by a successful check increases by 1. If the phantom aids the spiritualist this way, the bonus instead increases by 2.</p>
<p><strong>Opening Strike (Su):</strong> As a standard action, the phantom can make a melee attack against a foe. If this attack hits, the spiritualist designates one ally threatening that enemy. This ally can make a single attack at his full base attack bonus against that enemy as an immediate action.</p>
<p><strong>Etheric Healing (Su):</strong> When the spiritualist reaches 7th level, the phantom gains the <Link to="/ability/lay_on_hands">lay on hands</Link> ability with an effective paladin level equal to its Hit Dice. The phantom can use this ability on the spiritualist as a swift action.</p>
<p><strong>Expanded Aid (Su):</strong> When the spiritualist reaches 12th level, the phantom can use the aid another action as a move action. Additionally, the phantom selects four <Link to="/ability/mercies">mercies</Link> available to a 12th-level paladin that it adds to its lay on hands ability.</p>
<p><strong>Exceptional Aid (Su):</strong> When the spiritualist reaches 17th level, the phantom can use the aid another action as a swift action. Additionally, when designating an ally for an opening strike, that ally gains a bonus equal to the phantom's Charisma modifier on damage rolls for the attack granted to him.</p>
</>};
const _lust = {title: "Lust", jsx: <><h2 id="emotionalfocus-lust-lust">Lust</h2>
<p><strong>Sources</strong> <Link to="/source/occult_realms">Occult Realms pg. 14</Link><br/>A phantom with this focus aches for the intoxicating pleasures it experienced during life. These phantoms often writhe sensuously and whisper promises of unadulterated bliss to those they fight. Lust phantoms are typically deep rose in color, and they sometimes emit musky, exotic scents when they move.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Bluff and Diplomacy equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Will.</p>
<p><strong>Constitution Focus:</strong> A phantom with this focus gains a +2 bonus to Constitution and a -2 penalty to Dexterity. Instead of gaining a bonus to Dexterity as the spiritualist gains levels, a lust-focused phantom gains a bonus to Constitution instead.</p>
<p><strong>Alluring Presence (Su):</strong> A phantom with this focus can coerce enemies to attack it. As an immediate action, the phantom attempts a Diplomacy check against a creature targeting the spiritualist with an attack or harmful spell, provided the phantom is within the target creature's reach (or range, if the creature is attacking with a ranged weapon or spell). The DC for this check equals 10 + 1/2 the attacking creature's HD + the attacking creature's Wisdom modifier. If successful, the phantom becomes the target of all the creature's attacks for 1 round. This is a mind-affecting compulsion emotion effect.</p>
<p><strong>Mine Alone (Su):</strong> When the spiritualist reaches 7th level, whenever the spiritualist or the phantom is subject to a charm or compulsion effect, the target of the effect can roll twice for its save - once using the spiritualist's Will save modifier and once using the phantom's - and take the better result.</p>
<p><strong>Aura of Ecstasy (Su):</strong> When the spiritualist reaches 12th level, the lust phantom emanates an aura of ecstasy. All creatures adjacent to the phantom must succeed at a Will save (DC = 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier) or be <Link to="/misc/shaken">shaken</Link> and <Link to="/misc/staggered">staggered</Link> each round that they remain within the aura of ecstasy. Creatures that succeed at this save are immune to this phantom's aura of ecstasy for 24 hours.</p>
<p><strong>Sinful Command (Su):</strong> When the spiritualist reaches 17th level, once per day as a standard action, the phantom can attempt to assume control of another creature's mind as per the <Link to="/spell/dominate_monster">dominate monster</Link> spell. The DC of the effect is equal to 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier.</p>
</>};
const _pride = {title: "Pride", jsx: <><h2 id="emotionalfocus-pride-pride">Pride</h2>
<p><strong>Sources</strong> <Link to="/source/occult_realms">Occult Realms pg. 15</Link><br/>No phantom is as arrogant as a pride phantom, which in life was an insufferable braggart and egotist. These phantoms often puff and posture while fighting, shouting brash taunts and paeans to their own supposed skill in all things. Pride phantoms are often a roiling green in color.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Intimidate and in Perception equal to its number of Hit Dice. While the phantom is confined within the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Reflex and Will.</p>
<p><strong>Resolve:</strong> A phantom that has this emotional focus is immune to fear effects. However, when the phantom fails an ability check, skill check, or attack roll, it loses this immunity for 1 hour. Multiple failed checks or rolls are not cumulative. Instead, they simply reset the hour of lost immunity.</p>
<p><strong>Flagrant Disregard (Ex):</strong> As a swift action, the phantom can gain a +2 bonus on all attack rolls while taking a -1 penalty to AC for 1 round. For every 4 points of base attack bonus the phantom has, this bonus on attack rolls increases by 1 and the penalty to AC increases by 1.</p>
<p><strong>Vainglorious Oration (Su):</strong> When the spiritualist reaches 7th level, the phantom can espouse bold lies about its own prowess as a swift action to cause enemies to become <Link to="/misc/shaken">shaken</Link>. To be affected, an enemy must be within 30 feet of the phantom and able to hear it. This effect persists as long as the enemy is within 30 feet (the phantom can end the oration as a free action). This ability cannot cause a creature to become frightened or panicked, even if the target was already shaken from another effect. This is a mind-affecting fear effect that relies on audible components.</p>
<p><strong>Overwhelming Confidence (Su):</strong> When the spiritualist reaches 12th level, as long as the phantom is immune to fear effects from its resolve ability, any morale bonuses affecting the phantom are doubled. If the phantom loses its immunity to fear, all doubled morale bonuses that are affecting the phantom are instead applied as penalties for the remainder of their duration or until the phantom regains its immunity to fear (whichever comes first).</p>
<p><strong>Illusion of Perfection (Su):</strong> When the spiritualist reaches 17th level, the greed phantom can shroud itself in an illusion as a swift action, appearing as a model of absolute physical perfection - its idealized image of itself. The phantom gains a bonus on melee damage rolls equal to its Charisma modifier. However, whenever the phantom deals damage to a creature, the creature can attempt a Will save (DC = 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier) to disbelieve the effect, reducing the bonus on damage rolls by half if successful. The phantom can use illusion of perfection for a number of minutes per day equal to its Hit Dice. This duration need not be used all at once, but must be expended in 1-minute intervals. This ability is a mind-affecting illusion effect.</p>
</>};
const _remorse = {title: "Remorse", jsx: <><h2 id="emotionalfocus-remorse-remorse">Remorse</h2>
<p><strong>Sources</strong> <Link to="/source/occult_origins">Occult Origins pg. 19</Link><br/>Spirits of creatures that died with heavy weights upon their consciences manifest with the remorse emotional focus. These phantoms, whose forms are often darkened by shadows, force foes to experience their regret and self-loathing. A spiritualist with the <Link to="/arc-spiritualist/fated_guide">fated guide</Link> archetype must choose remorse as her phantom's emotional focus, but other spiritualists can also select this emotional focus for their phantoms.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Perception and Sense Motive equal to its Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Will.</p>
<p><strong>Antagonistic:</strong> The phantom gains <Link to="/feat/antagonize">Antagonize</Link> as a bonus feat.</p>
<p><strong>Long-Suffering Strike (Su):</strong> When a phantom with this focus hits a creature with its slam attack, that creature must succeed at a Will saving throw (DC = 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier) or any attacks targeting the creature gain a +1 bonus on their attack rolls and damage rolls until the beginning of the phantom's next turn. Penalties from multiple hits don't stack with themselves.</p>
<p><strong>Aura of Regret (Su):</strong> When the spiritualist reaches 7th level, her phantom can emit a 10-foot-radius aura of regret as a swift action. Enemies within the aura take a -2 penalty on skill checks, on caster level checks, on combat maneuver checks, and to CMD. Ending the aura is a free action. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Keening (Su):</strong> When the spiritualist reaches 12th level, her phantom can wail about its misdeeds once per day as a standard action, affecting all creatures within a 30-foot cone with the <Link to="/spell/terrible_remorse">terrible remorse</Link> spell. The phantom uses its Hit Dice as its caster level for the effect, and the DC equals 10 + 1/2 the phantom's Hit Dice + the phantom's Charisma modifier. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Utter Misery (Su):</strong> When the spiritualist reaches 17th level, her phantom's long-suffering strike also causes a creature that fails its save to become <Link to="/misc/stunned">stunned</Link> until the beginning of the phantom's next turn.</p>
</>};
const _suffering = {title: "Suffering", jsx: <><h2 id="emotionalfocus-suffering-suffering">Suffering</h2>
<p><strong>Sources</strong> <Link to="/source/antiheros_handbook">Antihero's Handbook pg. 18</Link><br/>Phantoms with this focus stand on trembling legs, with hands quivering and tears constantly streaming from their eyes. Their auras are typically a blue or purple, but the phantoms have vividly glowing scars and bruises that pulse and throb with their motion. When addressed, they tend to respond with only slight nods and other subtle gestures, rarely speaking beyond soft-spoken apologies and self-recriminations.</p>
<p>While clearly in a state of constant pain, they show no concern for their own well-being, focusing entirely on protecting their masters and their masters' allies. Each time one of these phantoms uses its abilities to protect its allies from harm, new injuries manifest visibly upon it, which these phantoms wear like badges of honor.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Climb and Heal equal to its number of Hit Dice. When confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Will.</p>
<p><strong>Endurance:</strong> The phantom gains <Link to="/feat/endurance">Endurance</Link> as a bonus feat. Furthermore, when the phantom is confined in its master's consciousness, it grants the benefits of Endurance to its master if its master doesn't have that feat.</p>
<p><strong>Repelling Strike (Ex):</strong> When the phantom deals damage with a melee attack, it can attempt to <Link to="/rule/bull_rush">bull rush</Link> the target as a swift action without provoking attacks of opportunity, using the result of its attack roll for the combat maneuver check. The phantom can push a creature back only 5 feet with this ability, regardless of the result of its combat maneuver check.</p>
<p><strong>Numbing Aura (Su):</strong> When the spiritualist reaches 7th level, as a swift action, the phantom can emit a 20-foot aura of protection. Allies within this aura gain a +4 bonus on saving throws against curse, disease, evil, fear, pain, and poison effects. Deactivating the aura is a free action. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Suffer in Stead (Su):</strong> When the spiritualist reaches 12th level, as an immediate action when her phantom is fully manifested and within 30 feet of her, she can transfer any of the following conditions to the phantom that would afflict her: blinded, deafened, exhausted, fatigued, nauseated, paralyzed, sickened, staggered, or stunned. The spiritualist must choose to do this before the condition's duration begins. The spiritualist can't use this ability if any of the listed conditions are already affecting the phantom. Using this ability does not affect the duration of the transferred condition; it simply makes the condition affect the phantom instead of the spiritualist.</p>
<p>When the spiritualist reaches 18th level, as an immediate action when fully manifested, the phantom can use this ability to transfer any of the listed conditions to itself when the condition would afflict any ally within 30 feet. Using the ability in this way requires no additional action from the spiritualist.</p>
<p><strong>Willing Martyr (Su):</strong> When the spiritualist reaches 17th level, the phantom begins to anticipate when the spiritualist or her allies would fall into grave bodily danger and can take those wounds itself. Whenever the phantom is fully manifested and the spiritualist or an ally is reduced to one-quarter or fewer hit points, as long as the phantom is within 30 feet, it must take any hit point damage or ability score damage in place of the injured spiritualist or ally. This hit point damage or ability score damage bypasses the phantom's defensive abilities (although it is still subject to the defensive abilities of the originally targeted spiritualist or ally) and afflicts the phantom as it would the spiritualist or ally. After the phantom becomes the target of one attack or effect in place of the injured spiritualist or ally, the spiritualist can command the phantom to suppress this ability as a free action. Reactivating this ability is a swift action.</p>
</>};
const _whimsey = {title: "Whimsey", jsx: <><h2 id="emotionalfocus-whimsey-whimsey">Whimsey</h2>
<p><strong>Sources</strong> <Link to="/source/heroes_from_the_fringe">Heroes from the Fringe pg. 17</Link><br/>Phantoms with this emotional focus carry a simplistic, childlike wonder and are fond of games and playing tricks. Whimsical phantoms are often the ghosts of <Link to="/race/gnome">gnomes</Link>; in the case of bleachling spiritualists, the phantom may even be a psychic vestige of the bleachling's own lost childlike nature. Among other races, most phantoms with the whimsy focus are the spirits of those who died as children and carried their childlike nature into the afterlife.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Acrobatics and Perception equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Reflex and Will</p>
<p><strong>Tricky Combatant:</strong> A phantom with the whimsy focus gains <Link to="/feat/improved_dirty_trick">Improved Dirty Trick</Link> as a bonus feat, even if it does not meet the prerequisites.</p>
<p><strong>Colorful Burst (Sp):</strong> Once per day, a phantom with this focus can produce an explosion of bright colors in a 15-foot cone. This functions as the spell <Link to="/spell/color_spray">color spray</Link>, except that creatures with fewer HD than the phantom are treated as if they had 2 HD or less, creatures with HD equal to that of the phantom are treated as if they had 3 or 4 HD, and creatures with more HD than the phantom are treated as if they had 5 or more HD. A creature can negate this effect with a successful Will saving throw (DC = 10 + half the phantom's Hit Dice + the phantom's Charisma modifier).</p>
<p><strong>Aura of Laughter (Sp):</strong> When the spiritualist reaches 7th level, the phantom can emit a 10-foot aura of childish laughter as a swift action. Enemies within the aura are distracted by the laughter, taking a -2 penalty on attack and damage rolls and a -5 penalty on Perception checks. This ability has no effect on creatures that cannot hear.</p>
<p><strong>Telekinetic Prankster (Sp):</strong> When the spiritualist reaches 12th level, the phantom gains the ability to use limited telekinesis to trip up its foes. It can perform combat maneuvers against creatures up to 15 feet away. When doing so, it can use its Charisma modifier in place of its Strength modifier on its combat maneuver checks.</p>
<p><strong>Invoke Laughter (Sp):</strong> When the spiritualist reaches 17th level, once per day as a standard action, the phantom can cause nearby creatures to fall into fits of uncontrollable laughter. Each creature in a 30-foot-radius <Link to="/misc/burst">burst</Link> centered on the phantom must succeed at a Will save (DC = 10 + half the phantom's Hit Dice + the phantom's Charisma modifier) or begin laughing uncontrollably, as the spell <Link to="/spell/hideous_laughter">hideous laughter</Link>. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
</>};
const _zeal = {title: "Zeal", jsx: <><h2 id="emotionalfocus-zeal-zeal">Zeal</h2>
<p><strong>Sources</strong> <Link to="/source/occult_adventures">Occult Adventures pg. 83</Link><br/>A phantom with this emotional focus fixates on every task given as if it were the phantom's last. The most basic commands are treated as life-and-death situations, and the truly dangerous ones are faced with a resolve and tenacity that sometimes defies common sense. Zeal phantoms take the form of steadfast protectors or daring and manic creatures looking for the next challenge or opportunity to prove itself to either its master or itself. Often very prideful creatures, these phantoms display an orange aura upon completing their tasks. They are prone to boast about their accomplishments and chastise those around them for not accomplishing more.</p>
<p><strong>Skills:</strong> The phantom gains a number of ranks in Acrobatics and Survival equal to its number of Hit Dice. While confined in the spiritualist's consciousness, the phantom grants the spiritualist <Link to="/feat/skill_focus">Skill Focus</Link> in each of these skills.</p>
<p><strong>Good Saves:</strong> Fortitude and Reflex.</p>
<p><strong>Tracking:</strong> The phantom adds half its number of Hit Dice (minimum 1) to Survival skill checks to follow tracks.</p>
<p><strong>Ruthless Combatant (Su):</strong> The phantom threatens a critical hit with its slam attacks on a roll of 19-20. When the spiritualist reaches 11th level, the phantom's critical modifier with slam attacks increases to &times;3. This doesn't stack with <Link to="/feat/improved_critical">Improved Critical</Link> or similar effects.</p>
<p><strong>Determination Aura (Su):</strong> When the spiritualist reaches 7th level, as a swift action, the phantom can emit a 20-foot-radius aura that grants its zeal to nearby allies. Allies within the aura gain a +2 competence bonus on attack rolls and saving throws. The phantom can use this ability in either ectoplasmic or incorporeal form.</p>
<p><strong>Steadfast Servant (Su):</strong> When the spiritualist reaches 12th level, the phantom can stay manifested even when its spiritualist master is unconscious or asleep.</p>
<p><strong>Zeal's Resolve (Su):</strong> When the spiritualist reaches 17th level, three times per day as a free action, when the phantom misses with an attack roll or fails a saving throw, it can reroll the failed attack or saving throw. It must take the new result, even if that result is worse.</p>
</>};
export default {not_found:_not_found,anger:_anger,dedication:_dedication,despair:_despair,desperation:_desperation,fear:_fear,greed:_greed,hatred:_hatred,jealousy:_jealousy,kindness:_kindness,lust:_lust,pride:_pride,remorse:_remorse,suffering:_suffering,whimsey:_whimsey,zeal:_zeal}