import Link from '../../components/Link';
const _not_found = {title: "Unknown", jsx: <><h2 id="tech-weapon-not_found-error">Error</h2>
<p>Unable to find the requested tech weapon.</p>
</>};
const _monowhip = {title: "Monowhip", jsx: <><h2 id="tech-weapon-monowhip-monowhip">Monowhip</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 20</Link></p>
<p><strong>Cost</strong> 70,000 gp<br/><strong>Type</strong> light melee; <strong>Proficiency</strong> exotic; <strong>Weight</strong> 1 lb.<br/><strong>Damage</strong> 1d10 (small), 2d6 (medium); <strong>Damage Type</strong> S; <strong>Critical</strong> 18-20/&times;3<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge/round; <strong>Special</strong> <Link to="/misc/performance">Performance</Link>, <Link to="/misc/reach">reach</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-monowhip-construction">Construction</h3>
<p><strong>Craft DC</strong> 32; <strong>Cost</strong> 35,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">graviton lab</Link></p>
<p>A monowhip is a deadly melee weapon capable of inflicting horrible wounds, even in the hands of the weak. An inactive monowhip looks like a short metal baton, but when it's activated, a small weight detaches, revealing a 15-foot-long monofilament length. Wielded like a whip, a monowhip slices deeply into targets and can inflict grievous critical hits with shocking ease. Attacks made with a monowhip resolve as touch attacks, and they ignore hardness as if the monofilament were made of <Link to="/eq-material/adamantine">adamantine</Link>. A monowhip's damage cannot be enhanced by strength, as the monofilament slices with equal ease regardless of the force applied. Activating a monowhip is a move action; once activated, the whip consumes power incredibly quickly, at the rate of 1 charge per round.</p>
</>};
const _null_blade = {title: "Null blade", jsx: <><h2 id="tech-weapon-null_blade-null-blade">Null blade</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 20</Link></p>
<p><strong>Cost</strong> 58,835 gp<br/><strong>Type</strong> one-handed melee; <strong>Proficiency</strong> exotic; <strong>Weight</strong> 4 lbs.<br/><strong>Damage</strong> 1d8 (small), 1d10 (medium); <strong>Damage Type</strong> S; <strong>Critical</strong> 19-20/&times;2<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge/round; <strong>Special</strong> -</p>
<h3 id="tech-weapon-null_blade-construction">Construction</h3>
<p><strong>Craft DC</strong> 30; <strong>Cost</strong> 33,835 gp<br/><Link to="/feat/craft_magic_arms_and_armor">Craft Magic Arms and Armor</Link>, <Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link>, <Link to="/spell/discharge">discharge</Link>, <Link to="/spell/dispel_magic">dispel magic</Link>, <Link to="/spell/summon_monster_i">summon monster I</Link></p>
<p>A potent fusion of magic, advanced science, and masterful weaponsmithing, null blades were devised by the Technic League as weapons against both magic and machine. Null blades incorporate an <Link to="/eq-material/adamantine">adamantine</Link>-<Link to="/eq-material/noqual">noqual</Link> alloy in their blades, a closely guarded metallurgical secret of the Technic League. The League guards these weapons closely, and when one falls into another's hands, they spare no expense in their efforts to recover it.</p>
<p>A null blade is a +1 construct-<Link to="/magic-enh/bane">bane</Link> <Link to="/eq-weapon/bastard_sword">bastard sword</Link>; using it in this capacity does not consume any charges. The blade's strange alloy penetrates hardness as if it were made of adamantine. The blade can be activated as a swift action. While it's active, a shimmering field of green energy wraps around the blade, disrupting magic and technology alike, and the weapon's enhancement bonus increases to +2. In addition, the first time in a round that an activated null blade strikes a creature or object, it consumes an additional charge and targets the creature or object struck with <em>dispel magic</em> and <em>discharge.</em> If a technological item damaged by a null blade is used in the same round it took damage, it glitches as if it were <Link to="/rule/timeworn_technology">timeworn</Link>.</p>
</>};
const _plasma_blade = {title: "Plasma blade", jsx: <><h2 id="tech-weapon-plasma_blade-plasma-blade">Plasma blade</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_100_a_song_of_silver">Pathfinder #100: A Song of Silver pg. 105</Link></p>
<p><strong>Cost</strong> 12,000 gp<br/><strong>Type</strong> one-handed melee; <strong>Proficiency</strong> exotic; <strong>Weight</strong> 3 lbs.<br/><strong>Damage</strong> 1d8 (small), 1d10 (medium); <strong>Damage Type</strong> electricity and fire; <strong>Critical</strong> 19-20/&times;3<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge/minute; <strong>Special</strong> <Link to="/misc/touch">Touch</Link></p>
<h3 id="tech-weapon-plasma_blade-construction">Construction</h3>
<p><strong>Craft DC</strong> 0; <strong>Cost</strong> 6,000 gp</p>
<p>When activated, a plasma blade's heavy, ornate handle projects a quantum field that contains energized plasma in a 2- to 3-foot-long "blade." Attacks made with a plasma blade resolve as touch attacks. Half the damage it deals is electricity and the other half is fire. When the wielder attacks an object, damage from a plasma blade ignores the first 20 points of hardness and its damage is not halved (even though energy damage is usually halved when applied to objects). Thanks to its quantum containment, a plasma blade deals half damage against incorporeal creatures, despite not being a magical weapon.</p>
</>};
const _chainsaw = {title: "Chainsaw", jsx: <><h2 id="tech-weapon-chainsaw-chainsaw">Chainsaw</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 2,700 gp<br/><strong>Type</strong> two-handed melee; <strong>Proficiency</strong> exotic; <strong>Weight</strong> 10 lbs.<br/><strong>Damage</strong> 1d12 (small), 3d6 (medium); <strong>Damage Type</strong> S; <strong>Critical</strong> 18-20/&times;2<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge/hour; <strong>Special</strong> <Link to="/misc/deadly">Deadly</Link>, <Link to="/misc/distracting">distracting</Link></p>
<h3 id="tech-weapon-chainsaw-construction">Construction</h3>
<p><strong>Craft DC</strong> 20; <strong>Cost</strong> 1,350 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>Originally developed for use as tools, chainsaws work remarkably well as weapons and are often used by lunatics or those who want to intimidate their enemies. A Numerian chainsaw consists of a weighty housing for the engine and power source that is fitted with two handles, and a 2- to 3-foot-long blade extending from the front, around which a whirling, buzzing chain of razor-sharp cutting links spins at blinding speed when the weapon is activated. It's a standard action to activate a chainsaw, and doing so consumes a charge of power. The chainsaw continues to run constantly after activation, draining an additional charge each hour. A dropped chainsaw automatically turns off unless it is set down carefully as a move action. The buzzing of a chainsaw's blade is loud and distracting (but not deafening), causing anyone carrying an activated chainsaw to take a -10 penalty on Stealth checks. An activated chainsaw grants a proficient user a +2 morale bonus on Intimidate checks.</p>
</>};
const _neural_inhibitor = {title: "Neural inhibitor", jsx: <><h2 id="tech-weapon-neural_inhibitor-neural-inhibitor">Neural inhibitor</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_85_fires_of_creation">Pathfinder #85: Fires of Creation pg. 60</Link></p>
<p><strong>Cost</strong> 2,400 gp<br/><strong>Type</strong> light melee; <strong>Proficiency</strong> simple; <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d6 (small), 1d6 (medium); <strong>Damage Type</strong> B; <strong>Critical</strong> &times;2<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> see text; <strong>Special</strong> -</p>
<h3 id="tech-weapon-neural_inhibitor-construction">Construction</h3>
<p><strong>Craft DC</strong> 20; <strong>Cost</strong> 1,200 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>While powered down, this sturdy, 2-foot truncheon functions as a <Link to="/eq-weapon/light_mace">light mace</Link>. Once it is activated (this is a swift action that consumes 1 charge), a high-density power core housed in the weapon's head generates a high-pitched whine that causes momentary disorientation in a creature struck. Each time the weapon hits a target, it consumes 1 charge and the creature struck must succeed at a DC 12 Fortitude save or suffer trauma to its central nervous system. For 1 round, a creature that fails its saving throw takes a -1 penalty on attack rolls, skill checks, and Will saving throws, as well as a -4 penalty on <Link to="/rule/concentration">concentration</Link> checks. The duration of this effect stacks with multiple hits from the neural inhibitor. This is a mind-affecting effect.</p>
</>};
const _laser_torch = {title: "Laser torch", jsx: <><h2 id="tech-weapon-laser_torch-laser-torch">Laser torch</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 20</Link></p>
<p><strong>Cost</strong> 6,000 gp<br/><strong>Type</strong> one-handed melee; <strong>Proficiency</strong> martial; <strong>Weight</strong> 4 lbs.<br/><strong>Damage</strong> 1d8 (small), 1d10 (medium); <strong>Damage Type</strong> fire; <strong>Critical</strong> &times;3<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/touch">Touch</Link></p>
<h3 id="tech-weapon-laser_torch-construction">Construction</h3>
<p><strong>Craft DC</strong> 26; <strong>Cost</strong> 3,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">production lab</Link></p>
<p>A laser torch is a handheld tool intended to cut through objects with great speed. When activated, a laser torch emits a beam of highly focused light, cutting and burning through surfaces up to 6 inches away. Attacks from a laser torch resolve as touch attacks and deal 1d10 points of fire damage. This damage is not modified further by Strength. When the laser torch is used as a tool or as a weapon to sunder, its damage bypasses up to 20 points of hardness, and damage is not halved (as is normally the case for energy damage applied to objects) unless the object is particularly fire-resistant. A laser torch's cutting beam passes through <Link to="/tech-misc/force_field_brown">force fields</Link> and force effects without damaging the field. Invisible objects and creatures can't be harmed by a laser torch.</p>
</>};
const _stun_baton = {title: "Stun baton", jsx: <><h2 id="tech-weapon-stun_baton-stun-baton">Stun baton</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 20</Link></p>
<p><strong>Cost</strong> 5,000 gp<br/><strong>Type</strong> one-handed melee; <strong>Proficiency</strong> martial; <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> B and electricity (special); <strong>Critical</strong> &times;2<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge/round; <strong>Special</strong> <Link to="/misc/touch">Touch</Link></p>
<h3 id="tech-weapon-stun_baton-construction">Construction</h3>
<p><strong>Craft DC</strong> 24; <strong>Cost</strong> 2,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>This slender rod has an insulated grip and a conductive tip. All bludgeoning damage dealt by an active stun baton is nonlethal, while the electrical charge can be either nonlethal or lethal. By activating a control in the handle as a swift action, the wielder can switch the attack between a nonlethal jolt and a lethal shock. On a confirmed critical hit, a target must succeed at a Fortitude saving throw (DC = 10 + the damage dealt by the critical hit) or be <Link to="/misc/staggered">staggered</Link> for 1 round. When it's not activated, a stun baton functions as a <Link to="/eq-weapon/sap">sap</Link>. A character who is proficient with saps is proficient with a stun baton.</p>
</>};
const _starfall_spade = {title: "Starfall spade", jsx: <><h2 id="tech-weapon-starfall_spade-starfall-spade">Starfall spade</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_89_palace_of_fallen_stars">Pathfinder #89: Palace of Fallen Stars pg. 63</Link></p>
<p><strong>Cost</strong> 8,620 gp<br/><strong>Type</strong> two-handed melee; <strong>Proficiency</strong> martial; <strong>Weight</strong> 12 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &times;2<br/><strong>Range</strong> -; <strong>Capacity</strong> 10; <strong>Usage</strong> see text; <strong>Special</strong> See text</p>
<h3 id="tech-weapon-starfall_spade-construction">Construction</h3>
<p><strong>Craft DC</strong> 26; <strong>Cost</strong> 4,620 gp<br/><Link to="/feat/craft_magic_arms_and_armor">Craft Magic Arms and Armor</Link>, <Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link>, <Link to="/spell/scorching_ray">scorching ray</Link>, <Link to="/spell/shocking_grasp">shocking grasp</Link></p>
<p><strong>Aura</strong> moderate evocation; <strong>CL</strong> 7th<br/>The Technic League produces these unusual weapons as signature tools for the guards of Starfall and the Palace of Fallen Stars. A Starfall spade is a +1/+1 <Link to="/eq-weapon/monks_spade">monk's spade</Link> and has a capacity of 10 charges. When the weapon strikes a foe, it automatically consumes a charge and deals an additional 2 points of plasma damage (1 electricity, 1 fire) on that hit. Attack that miss don't consume charges. A crystal button on the shaft allows for a secondary attack: a beam of plasma that fires from the forked tip of the spade. This beam is a ranged touch attack that deals 4d6 points of plasma damage (half electricity, half fire) on a hit - it has a maximum range of 40 feet with no range increment. Firing this plasma beam consumes 10 charges.</p>
</>};
const _arc_pistol = {title: "Arc pistol", jsx: <><h2 id="tech-weapon-arc_pistol-arc-pistol">Arc pistol</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 10,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d6 (small), 1d8 (medium); <strong>Damage Type</strong> electricity; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 50 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/semi_automatic">Semi-automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-arc_pistol-construction">Construction</h3>
<p><strong>Craft DC</strong> 23; <strong>Cost</strong> 5,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>An arc pistol emits bolts of ionized particles that it then electrifies, creating a crackling beam of electricity between it and its target. Arc pistols gain a +2 circumstance bonus on attack rolls against targets that are metal or are wearing medium or heavy metal armor.</p>
</>};
const _dart_gun = {title: "Dart gun", jsx: <><h2 id="tech-weapon-dart_gun-dart-gun">Dart gun</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 3,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Damage Type</strong> P; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 30 ft.; <strong>Capacity</strong> 1 nanite canister; <strong>Usage</strong> 1 charge; <strong>Special</strong> -</p>
<h3 id="tech-weapon-dart_gun-construction">Construction</h3>
<p><strong>Craft DC</strong> 24; <strong>Cost</strong> 1,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">nanotech lab</Link></p>
<p>A dart gun makes use of nanotechnology to craft a small pointed projectile that does minimal damage on its own. Unlike other nanotech weapons, the nanites that make up a dart do not have any additional effect on the target. Instead, a dart gun contains a small reservoir above its handle into which a single dose of a pharmaceutical, drug, poison, or even potion can be poured as a standard action. The next dart fired from the dart gun delivers that liquid into the target immediately upon a hit.</p>
</>};
const _death_ray = {title: "Death ray", jsx: <><h2 id="tech-weapon-death_ray-death-ray">Death ray</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 140,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 1 lb.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &mdash;<br/><strong>Range</strong> 200 ft. (see text); <strong>Capacity</strong> 1 nanite canister; <strong>Usage</strong> Varies; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-death_ray-construction">Construction</h3>
<p><strong>Craft DC</strong> 32; <strong>Cost</strong> 70,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">nanotech lab</Link></p>
<p>A death ray is a handheld, wand-like weapon that fires a harmless carrier beam of energy at a target. When the beam hits a target, the death ray then projects a stream of specialized nanites through the beam into the body of the target. When firing a death ray, the wielder must decide how many charges of nanites she is consuming, to a maximum of 10. Even if the wielder engineers a method of using a larger reserve of nanites than normally come in a canister, this maximum does not increase. Immediately upon being struck, the nanites inflict incredible pain on the target, which must succeed at a Fortitude saving throw to avoid a grisly fate (DC = 10 + twice the number of charges consumed by the attack). For example, if 1 charge is consumed, the target must succeed at a DC 12 Fortitude save to resist the death ray, but if all 10 charges are consumed in the attack, the DC to resist the effects is 30.</p>
<p>If the target fails this save, it takes 100 points of damage as the nanites tear apart the victim's cardiovascular system. On a successful saving throw, the victim takes only 6d6 points of damage. Creatures slain by a death ray die spectacularly, seeming to melt into a pool of blood that swiftly fades away. The victim's gear is unaffected by this attack. A death ray has no effect on creatures that aren't living (such as constructs or undead) and can't penetrate a <Link to="/tech-misc/force_field">force field</Link>. The wielder can't score critical hits with a death ray. A death ray has a maximum range of 200 feet with no range increment.</p>
</>};
const _emp_pistol = {title: "EMP pistol", jsx: <><h2 id="tech-weapon-emp_pistol-emp-pistol">EMP pistol</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 12,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d10 (small), 2d6 (medium); <strong>Damage Type</strong> electricity; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 50 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/semi_automatic">Semi-automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-emp_pistol-construction">Construction</h3>
<p><strong>Craft DC</strong> 25; <strong>Cost</strong> 6,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>An EMP pistol emits a beam of electromagnetic energy that cannot harm living creatures, but deals terrible damage to robots. An EMP pistol can harm androids and creatures with cybernetic implants, but they take half damage from a hit. A creature that is critically hit by an EMP pistol and takes damage from that hit must succeed at a DC 15 Fortitude save or be <Link to="/misc/staggered">staggered</Link> for 1d4 rounds.</p>
</>};
const _flare_gun = {title: "Flare gun", jsx: <><h2 id="tech-weapon-flare_gun-flare-gun">Flare gun</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 300 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 1 lb.<br/><strong>Damage</strong> 1d6 (small), 1d8 (medium); <strong>Damage Type</strong> fire; <strong>Critical</strong> &times;3<br/><strong>Range</strong> 240 ft.; <strong>Capacity</strong> 1; <strong>Usage</strong> Disposable; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-flare_gun-construction">Construction</h3>
<p><strong>Craft DC</strong> 18; <strong>Cost</strong> 150 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">production lab</Link></p>
<p>A flare gun looks like a wide-barreled pistol, and although it can be used in combat, the item's primary use is to send signals. A flare gun and its ammunition (a small, rocket-propelled magnesium charge) are completely self-contained and disposable - once fired, a flare gun is useless. While a flare gun has excellent range, the flare tends to wobble and spiral in flight, incurring a 20% miss chance if it's being used to target a specific point. The flare detonates once it hits a target or reaches its maximum range of 2,400 feet, bursting into a sphere of fire that illuminates a 120-foot-radius area for 1 minute as it drifts slowly back to the ground. Any creatures within 20 feet of the flare must succeed at a DC 12 Fortitude saving throw each round or be <Link to="/misc/dazzled">dazzled</Link> by the intense light for as long as they remain in the area. Creatures adjacent to a lit flare are also <Link to="/misc/blinded">blinded</Link> for 1d4 rounds on a failed save. A creature struck by a flare takes 1d8 points of fire damage (1d6 points of fire damage from Small flare guns), and continues to take the same amount of fire damage each round until the flare is removed. Removing a flare is a full-round action.</p>
</>};
const _gravity_pistol = {title: "Gravity pistol", jsx: <><h2 id="tech-weapon-gravity_pistol-gravity-pistol">Gravity pistol</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 95,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d6 (small), 1d8 (medium); <strong>Damage Type</strong> Force; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 50 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/semi_automatic">Semi-automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-gravity_pistol-construction">Construction</h3>
<p><strong>Craft DC</strong> 32; <strong>Cost</strong> 52,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">graviton lab</Link></p>
<p>A gravity pistol is one of the most advanced pieces of technology found in Numeria. It uses a focused beam of gravitons to create a bolt of force. A gravity pistol has two settings - switching between settings is a swift action. On its pulse setting, it can be used as a typical beam weapon, but on it sustained setting, holding the pistol's trigger down creates a stable beam of gravitons rather than a short, destructive burst. In this mode, the gravity pistol can be used to move and manipulate objects at a distance, similar to a <Link to="/spell/telekinesis">telekinesis</Link> spell in its sustained force or combat maneuver versions (a gravity pistol cannot duplicate the violent thrust option of a telekinesis spell). In this mode, a gravity pistol consumes 1 charge per round. The graviton beam can move objects weighing no more than 225 pounds up to 20 feet per round. A creature can negate this effect on an object in its possession with a successful DC 19 Reflex save. If used to perform a combat maneuver, the beam uses the wielder's CMB, but uses her Intelligence modifier in place of her Strength or Dexterity modifier.</p>
</>};
const _inferno_pistol = {title: "Inferno pistol", jsx: <><h2 id="tech-weapon-inferno_pistol-inferno-pistol">Inferno pistol</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_85_fires_of_creation">Pathfinder #85: Fires of Creation pg. 60</Link></p>
<p><strong>Cost</strong> 5,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d4 (small), 1d6 (medium); <strong>Damage Type</strong> fire; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 30 ft.; <strong>Capacity</strong> 1 nanite canister; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/touch">Touch</Link></p>
<h3 id="tech-weapon-inferno_pistol-construction">Construction</h3>
<p><strong>Craft DC</strong> 21; <strong>Cost</strong> 2,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">nanotech lab</Link></p>
<p>An inferno pistol is a less refined variant of the longer-range laser pistol. Unlike a <Link to="/tech-weapon/laser_pistol">laser pistol</Link>, which uses an intensely focused beam of light to burn a target, an inferno pistol is much less elegant - it generates a blob of molten, red-hot material and fires what appears to be a burning pellet of fire with a soft hissing sound. This material is consumed swiftly in firing, leaving behind nothing but ash and painful burns on anything it strikes. On a critical hit, a shot from an inferno pistol also inflicts 1 point of <Link to="/umr/burn">burn</Link> damage (Reflex DC 12 negates). An inferno pistol has a maximum range of 5 increments.</p>
</>};
const _laser_pistol = {title: "Laser pistol", jsx: <><h2 id="tech-weapon-laser_pistol-laser-pistol">Laser pistol</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 10,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d6 (small), 1d8 (medium); <strong>Damage Type</strong> fire; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 50 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/semi_automatic">Semi-automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-laser_pistol-construction">Construction</h3>
<p><strong>Craft DC</strong> 23; <strong>Cost</strong> 5,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A laser pistol emits a beam of intensely focused light capable of burning anything it strikes. A laser attack can pass through <Link to="/tech-misc/force_field_brown">force fields</Link> and force effects, such as a <Link to="/spell/wall_of_force">wall of force</Link>, to strike a foe beyond without damaging that field. Objects like glass or other transparent barriers do not provide <Link to="/rule/cover">cover</Link> from lasers - but unlike force barriers, a transparent physical barrier still takes damage from a laser passing through it. Invisible creatures are immune to damage caused by a laser weapon. Fog, smoke, and other clouds provide cover in addition to <Link to="/rule/concealment">concealment</Link> from laser attacks. Darkness (magical or otherwise) has no effect on lasers other than providing concealment, and though a laser consists of highly focused light, it does not provide any illumination.</p>
</>};
const _mind_burner = {title: "Mind burner", jsx: <><h2 id="tech-weapon-mind_burner-mind-burner">Mind burner</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_86_lords_of_rust">Pathfinder #86: Lords of Rust pg. 63</Link></p>
<p><strong>Cost</strong> 8,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 20 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/touch">Touch</Link></p>
<h3 id="tech-weapon-mind_burner-construction">Construction</h3>
<p><strong>Craft DC</strong> 28; <strong>Cost</strong> 4,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A mind burner is a pistol with a dish-like adornment at the tip of its barrel. When this weapon is fired, a pulse of white smoke pools in the dish an instant before a thin beam of white light lances out to strike its target. A mind burner is silent when fired, but stray particles from the mind-altering beam can cause those nearby to catch unexpected scents associated with powerful memories - the odor of a bouquet of flowers given to one's first lover, the scent of a parent's perfume or sweat, or maybe even the odor of a favorite food that hasn't been eaten in years. These fragmentary memories generally have no additional effect on those who experience them, but at the GM's discretion, they could cause the resurfacing of repressed memories or forgotten fears.</p>
<p>On a successful hit, a mind burner causes intense headaches that dull the senses and weaken willpower. Each hit deals 1d4 points of nonlethal damage, but also imposes a -2 penalty on Perception checks and a -1 penalty on saving throws against mind-affecting effects. These penalties stack with themselves, up to a maximum penalty of -10 on Perception checks and -5 on mind-affecting saving throws. A creature can resist the penalties caused by a shot from a mind burner with a successful DC 14 Will save; otherwise, the penalties persist for 1 hour after the previous successful shot. On a critical hit, a mind burner's penalties are doubled along with its nonlethal damage.</p>
</>};
const _mindrender = {title: "Mindrender", jsx: <><h2 id="tech-weapon-mindrender-mindrender">Mindrender</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 56,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 40 ft.; <strong>Capacity</strong> 1 nanite canister; <strong>Usage</strong> 2 charges; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-mindrender-construction">Construction</h3>
<p><strong>Craft DC</strong> 33; <strong>Cost</strong> 28,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">nanotech lab</Link></p>
<p>A mindrender is a cruel weapon that emits a carrier wave of light which transmits a mass of nanites into the body of the creature struck. The victim must succeed at a DC 17 Fortitude save or it takes 1 negative level and is <Link to="/misc/staggered">staggered</Link> for 1 round as the nanites flood the victim's brain and suppress long term memories. If the victim succeeds, he's instead <Link to="/misc/sickened">sickened</Link> for 1d4 rounds and is immune to further attacks from a mindrender for 1 hour. A creature can attempt a new saving throw every 24 hours to remove the negative level. These are mind-affecting effects.</p>
</>};
const _sonic_pistol = {title: "Sonic pistol", jsx: <><h2 id="tech-weapon-sonic_pistol-sonic-pistol">Sonic pistol</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 13,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d6 (small), 1d8 (medium); <strong>Damage Type</strong> Sonic; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 50 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/semi_automatic">Semi-automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-sonic_pistol-construction">Construction</h3>
<p><strong>Craft DC</strong> 23; <strong>Cost</strong> 6,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A sonic pistol emits a blast of devastating sound waves that shatter and blast flesh, bone, and anything else they happen to strike. A creature critically hit by a sonic pistol must succeed at a DC 15 Fortitude save to resist being permanently <Link to="/misc/deafened">deafened</Link>.</p>
</>};
const _stun_gun = {title: "Stun gun", jsx: <><h2 id="tech-weapon-stun_gun-stun-gun">Stun gun</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 3,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 3 lbs.<br/><strong>Damage</strong> 1d6 (small), 1d8 (medium); <strong>Damage Type</strong> &mdash;; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 20 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/nonlethal">Nonlethal</Link>, <Link to="/misc/semi_automatic">semi-automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-stun_gun-construction">Construction</h3>
<p><strong>Craft DC</strong> 22; <strong>Cost</strong> 1,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>This weapon uses a sonic amplifier to produce powerful low-frequency blasts of energy that pummel targets. The weapon has a relatively short range, but the fact that it deals nonlethal damage at range and can knock targets <Link to="/rule/prone">prone</Link> makes it a favorite for those seeking to capture their foes alive. A hit by a stun gun deals nonlethal damage - on a critical hit, the gun can attempt a free <Link to="/rule/trip">trip</Link> combat maneuver check against the target (CMB = user's base attack bonus + 10); this attempt doesn't provoke attacks of opportunity.</p>
</>};
const _zero_pistol = {title: "Zero pistol", jsx: <><h2 id="tech-weapon-zero_pistol-zero-pistol">Zero pistol</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 10,000 gp<br/><strong>Type</strong> one-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 2 lbs.<br/><strong>Damage</strong> 1d6 (small), 1d8 (medium); <strong>Damage Type</strong> cold; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 50 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/semi_automatic">Semi-automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-zero_pistol-construction">Construction</h3>
<p><strong>Craft DC</strong> 23; <strong>Cost</strong> 5,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A zero pistol fires a beam of freezing particles at high velocity, dealing cold damage to anything it strikes. Any creature critically hit by a zero pistol ray must succeed at a DC 15 Fortitude saving throw or become <Link to="/misc/staggered">staggered</Link> by the cold for 1 round.</p>
</>};
const _arc_rifle = {title: "Arc rifle", jsx: <><h2 id="tech-weapon-arc_rifle-arc-rifle">Arc rifle</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 20,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 6 lbs.<br/><strong>Damage</strong> 1d10 (small), 2d6 (medium); <strong>Damage Type</strong> electricity; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 150 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-arc_rifle-construction">Construction</h3>
<p><strong>Craft DC</strong> 27; <strong>Cost</strong> 10,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>An arc rifle is a larger, more powerful version of an <Link to="/tech-weapon/arc_pistol">arc pistol</Link>, and functions as such except for the differences listed here.</p>
</>};
const _autograpnel = {title: "Autograpnel", jsx: <><h2 id="tech-weapon-autograpnel-autograpnel">Autograpnel</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 4,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 10 lbs.<br/><strong>Damage</strong> 1d6+6 (small), 1d8+6 (medium); <strong>Damage Type</strong> P; <strong>Critical</strong> &times;3<br/><strong>Range</strong> 30 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/grapple">Grapple</Link>, <Link to="/misc/slow_firing">slow-firing</Link></p>
<h3 id="tech-weapon-autograpnel-construction">Construction</h3>
<p><strong>Craft DC</strong> 20; <strong>Cost</strong> 2,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>An autograpnel looks like a rifle with a small <Link to="/eq-material/adamantine">adamantine</Link> spike protruding from its barrel. When fired, an autograpnel launches the spike with a muffled bang. The spike trails an incredibly strong and thin metal cable behind it. An instant after the spike punches into a solid target, tiny spurs lance out of it, anchoring the spike in place. An autograpnel's cord is long enough to allow the grapnel to reach its maximum range of 300 feet, and the internal retraction motors are strong enough to hold up to 500 pounds of weight. If the grapnel misses its target, it can be rewound into the gun as a standard action; reattaching the grapnel to the gun barrel is a move action.</p>
<p>An autograpnel strikes with an effective Strength score of 22 for the purposes of determining damage. If it strikes a creature, it remains lodged in the target and connected to the rifle and its wielder by the metal cord. This cord has AC 12, hardness 10, and 20 hp. A successful DC 32 Strength check is required to snap the cord. If the wielder retracts the cord while it's attached to a creature, the autograpnel attempts a pull combat maneuver check with a CMB of +16. If used against objects, an autograpnel can pull an item that weighs 25 pounds or less back to the user as a full-round action, or it can pull a heavier object that weighs no more than 100 pounds back to the user at a speed of 20 feet.</p>
<p>When attached to a solid object, the gun's retraction rate can be set to maintain a taut line while the gun is attached to a harness worn to aid climbing checks.</p>
</>};
const _emp_rifle = {title: "EMP rifle", jsx: <><h2 id="tech-weapon-emp_rifle-emp-rifle">EMP rifle</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 24,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 6 lbs.<br/><strong>Damage</strong> 2d6 (small), 3d6 (medium); <strong>Damage Type</strong> electricity; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 150 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-emp_rifle-construction">Construction</h3>
<p><strong>Craft DC</strong> 29; <strong>Cost</strong> 12,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>An EMP rifle is a larger, more powerful version of an EMP pistol. It emits a beam of electromagnetic energy that can't harm living creatures, but deals significant damage to robots. It functions as an <Link to="/tech-weapon/emp_pistol">EMP pistol</Link> except for the differences listed here.</p>
</>};
const _gravity_rifle = {title: "Gravity rifle", jsx: <><h2 id="tech-weapon-gravity_rifle-gravity-rifle">Gravity rifle</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 165,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 6 lbs.<br/><strong>Damage</strong> 1d10 (small), 2d6 (medium); <strong>Damage Type</strong> Force; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 150 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-gravity_rifle-construction">Construction</h3>
<p><strong>Craft DC</strong> 34; <strong>Cost</strong> 82,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">graviton lab</Link></p>
<p>A gravity rifle is a larger, more powerful version of the <Link to="/tech-weapon/gravity_pistol">gravity pistol</Link>, and functions as such except for the differences listed here. When a gravity rifle is on sustained setting, it can move objects weighing no more than 350 pounds up to 20 feet per round, and the wielder gains a +4 bonus on combat maneuver checks; she still substitutes her Intelligence modifier in place of her Strength or Dexterity modifier when calculating her CMB for these maneuvers.</p>
</>};
const _id_rifle = {title: "Id rifle", jsx: <><h2 id="tech-weapon-id_rifle-id-rifle">Id rifle</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 50,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 5 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 50 ft.; <strong>Capacity</strong> 1 nanite canister; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-id_rifle-construction">Construction</h3>
<p><strong>Craft DC</strong> 32; <strong>Cost</strong> 25,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">nanotech lab</Link></p>
<p>An id rifle looks like a sleek, low-caliber rifle made of burnished <Link to="/eq-material/skymetal">skymetal</Link>. It fires a tiny barb of solid nanites with a range increment of 50 feet. Although this barb does minimal damage on a hit, any creature damaged by an id rifle barb must succeed at a DC 16 Fortitude saving throw or have its central nervous system flooded with nanites that swiftly overwhelm the creature's brain, reducing its mind to the instinctive level of an animal. The victim takes 1d4 points of <Link to="/rule/intelligence_damage">Intelligence damage</Link> each round, but the total amount of damage taken can never equal the victim's actual Intelligence score. Each round after the first, the victim can resist the Intelligence damage by succeeding at a DC 16 Fortitude saving throw, at which point the damage ceases. The recurring Intelligence damage automatically ends after 6 rounds. A victim already suffering from the effects of an id rifle who is affected by an additional shot has the save DC increased by 2 per additional shot.</p>
<p>An id rifle has a microphone built into its stock. During any round in which a creature takes Intelligence damage from an id rifle, as a move action the wielder of that rifle can speak a short command into the microphone. Any applicable target within 50 feet of the wielder must then succeed at a DC 16 Will save to resist following the command, as if under the effect of a <Link to="/spell/suggestion">suggestion</Link> spell. A victim follows only the latest suggestion spoken into the microphone, and abandons any previous suggestion if it fails a saving throw against a new suggestion. A victim continues to follow the suggestion for up to 5 hours after succumbing to its effects.</p>
<p>The effects created by an id rifle are mind-affecting effects.</p>
</>};
const _laser_rifle = {title: "Laser rifle", jsx: <><h2 id="tech-weapon-laser_rifle-laser-rifle">Laser rifle</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 20,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 6 lbs.<br/><strong>Damage</strong> 1d10 (small), 2d6 (medium); <strong>Damage Type</strong> fire; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 150 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-laser_rifle-construction">Construction</h3>
<p><strong>Craft DC</strong> 27; <strong>Cost</strong> 10,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A laser rifle is a larger, more powerful version of a <Link to="/tech-weapon/laser_pistol">laser pistol</Link>, and functions as such except for the differences listed here.</p>
</>};
const _sonic_rifle = {title: "Sonic rifle", jsx: <><h2 id="tech-weapon-sonic_rifle-sonic-rifle">Sonic rifle</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 26,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 6 lbs.<br/><strong>Damage</strong> 1d10 (small), 2d6 (medium); <strong>Damage Type</strong> Sonic; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 150 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-sonic_rifle-construction">Construction</h3>
<p><strong>Craft DC</strong> 27; <strong>Cost</strong> 13,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A sonic rifle is a larger, more powerful version of the <Link to="/tech-weapon/sonic_pistol">sonic pistol</Link>, and functions as such except for the differences listed here.</p>
</>};
const _zero_rifle = {title: "Zero rifle", jsx: <><h2 id="tech-weapon-zero_rifle-zero-rifle">Zero rifle</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 20,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (firearms); <strong>Weight</strong> 6 lbs.<br/><strong>Damage</strong> 1d10 (small), 2d6 (medium); <strong>Damage Type</strong> cold; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 150 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<h3 id="tech-weapon-zero_rifle-construction">Construction</h3>
<p><strong>Craft DC</strong> 27; <strong>Cost</strong> 10,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A zero rifle is a larger, more powerful version of the <Link to="/tech-weapon/zero_pistol">zero pistol</Link>, and functions as such except for the differences listed here.</p>
</>};
const _atom_gun = {title: "Atom gun", jsx: <><h2 id="tech-weapon-atom_gun-atom-gun">Atom gun</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 144,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 24 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &mdash;<br/><strong>Range</strong> 40-ft. cone; <strong>Capacity</strong> &mdash;; <strong>Usage</strong> &mdash;; <strong>Special</strong> <Link to="/misc/scatter">Scatter</Link>, <Link to="/misc/slow_firing">slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<p>An atom gun is a cruel weapon that harnesses the devastating energies of a miniaturized nuclear reactor to create a focused cone of <Link to="/rule/radiation">radiation</Link> that blasts and sickens those caught in the beam. An atom gun's range is relatively short, and the weapon can fire only scattering shots. The beams of radiation created when the wielder fires an atom gun do not fill the cone in a homogeneous area, and she must still make a ranged touch attack to irradiate a target. A creature struck by an atom gun attack suffers the effects of medium radiation. The small core of radioactive material in an atom gun is powerful enough to keep the weapon charged for tens of thousands of years, but the weapon becomes incredibly hot when fired, dealing 1d6 points of damage to the user and subsequently beginning a cool-down protocol, during which the weapon cannot be fired for 1 minute.</p>
<p>An atom gun cannot be fired more than 3 times per day. A functional atom gun's power source is shielded well, and the gun itself is not a source of dangerous radioactivity. If an atom gun gains the <Link to="/misc/broken">broken</Link> condition, it begins to leak radiation and becomes a source of low radiation to all creatures that touch it. An atom gun that gains the destroyed condition becomes a source of high radiation to those in contact with it, a source of medium radiation to those within 10 feet of it, and a source of low radiation to those within 30 feet of it.</p>
<h3 id="tech-weapon-atom_gun-construction">Construction</h3>
<p><strong>Craft DC</strong> 35; <strong>Cost</strong> 72,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
</>};
const _beam_cannon = {title: "Beam Cannon (arc cannon)", jsx: <><h2 id="tech-weapon-beam_cannon-beam-cannon-arc-cannon">Beam cannon (arc cannon)</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_89_palace_of_fallen_stars">Pathfinder #89: Palace of Fallen Stars pg. 62</Link></p>
<p><strong>Cost</strong> 40,000 gp (arc cannon, laser cannon, zero cannon), 58,000 gp (EMP cannon, sonic cannon)<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 18 lbs.<br/><strong>Damage</strong> 2d6 (small), 3d6 (medium); <strong>Damage Type</strong> See below; <strong>Critical</strong> &times;2<br/><strong>Range</strong> 300 ft.; <strong>Capacity</strong> 50; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link>, <Link to="/misc/touch">touch</Link></p>
<p>A beam cannon is an immense version of one of the six more common beam rifle types. Beam cannons are generally referred to by type as summarized below. In addition to the standard automatic <Link to="/main/tech_weapons">firing mode options</Link>, a beam cannon can be used to launch a devastating blast of energy. This is a full-round action, and these blasts can't be used to make iterative attacks. When a beam cannon is used to launch a blast, no attack roll is made - you simply target a 20-foot-radius <Link to="/misc/spread">spread</Link> within a maximum range of 300 feet. You must have line of effect to your target when you launch a blast; if the blast impacts a solid object before reaching the target area, it explodes at that point. All creatures caught in the blast radius take 6d6 points of damage of the energy type appropriate to the cannon (Reflex DC 14 half). Each blast also has an additional effect as determined by the type of cannon. Firing a blast from a beam cannon consumes 10 charges.</p>
<p>An <strong className="hl">arc cannon</strong> deals electricity damage. Against metallic targets or creatures wearing medium or heavy metal armor, an arc cannon grants a +2 circumstance bonus on attack rolls, and the save DC against its blast mode increases by 2. An arc cannon costs 40,000 gp and has a Craft DC of 31.</p>
<p>An <strong className="hl">EMP cannon</strong> fires electromagnetic energy that cannot harm most living creatures. It deals 4d6 points of electricity damage against robots, and half as much damage against androids and creatures with cybernetic implants. A creature that takes damage from a critical hit by an EMP cannon must succeed at a DC 15 Fortitude save or be <Link to="/misc/staggered">staggered</Link> for 1d4 rounds. An EMP cannon's blast deals 8d6 points of electricity damage of the same electromagnetic nature. An EMP cannon costs 58,000 gp and has a Craft DC of 33.</p>
<p>A <strong className="hl">laser cannon</strong> deals fire damage. All attacks fired from it pass through transparent barriers, but treat fog, smoke, and other clouds as <Link to="/rule/cover">cover</Link>; see the <Link to="/tech-weapon/laser_pistol">laser pistol</Link> for more information. A laser cannon costs 40,000 gp and has a Craft DC of 31.</p>
<p>A <strong className="hl">sonic cannon</strong> deals sonic damage. A creature that is critically hit by a sonic cannon or fails its saving throw against the cannon's blast must succeed at a DC 15 Fortitude saving throw or be permanently <Link to="/misc/deafened">deafened</Link>. A sonic cannon costs 58,000 gp and has a Craft DC of 33.</p>
<p>A <strong className="hl">zero cannon</strong> deals cold damage. A creature that is critically hit by a zero cannon or fails its saving throw against the cannon's blast must succeed at a DC 15 Fortitude saving throw or become staggered for 1 round. A zero cannon costs 40,000 gp and has a Craft DC of 31.</p>
<h3 id="tech-weapon-beam_cannon-construction">Construction</h3>
<p><strong>Craft DC</strong> 31 (arc cannon, laser cannon, zero cannon), 33 (EMP cannon, sonic cannon); <strong>Cost</strong> 20,000 gp (arc cannon, laser cannon, zero cannon), 29,000 gp (EMP cannon, sonic cannon)<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
</>};
const _fleshnet_cannon = {title: "Fleshnet cannon", jsx: <><h2 id="tech-weapon-fleshnet_cannon-fleshnet-cannon">Fleshnet cannon</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_88_valley_of_the_brain_collectors">Pathfinder #88: Valley of the Brain Collectors pg. 63</Link></p>
<p><strong>Cost</strong> 3,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 11 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Special; <strong>Critical</strong> &mdash;<br/><strong>Range</strong> 20 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 (disposable); <strong>Special</strong> Single shot, <Link to="/misc/touch">touch</Link></p>
<p>This Dominion weapon is a 3-foot-long device constructed from a hard, fleshlike material of mottled dark hues. Its barrel tapers down and flares into something disturbingly like a mouth. The triggering mechanism is built for a <Link to="/monster/neh_thalggu">neh-thalggu's</Link> pincers and tendrils, but it can be fired by a humanoid with a bit of work - creatures other than neh-thalggu takes a -2 penalty on attack rolls with a fleshnet cannon. Fleshnet cannons are built for Large creatures, and smaller creatures take <Link to="/misc/weapon_size">additional penalties as appropriate</Link> when using these weapons.</p>
<p>When a fleshnet cannon is fired, it makes a low, wet, sucking noise as the barrel seems to convulse an instant before expelling a glob of pink fleshy material. This glob expands rapidly so that by the time it strikes its target, the flesh unfurls into a net. Unlike a typical net, this net doesn't trail ropes, nor does it have a maximum range of 10 feet.</p>
<p>The net automatically <Link to="/rule/entangled">entangles</Link> a creature of Huge or larger size it hits. As soon as it entangles a creature, and then again at the start of every round that follows for the next 5 rounds, the fleshnet squeezes and crushes the target, dealing 2d6+6 points of bludgeoning damage as it excretes a powerful soporific - the victim must make a DC 15 Fortitude save to avoid being rendered <Link to="/misc/unconscious">unconscious</Link> for 2d6 minutes. A fleshnet does not continue to crush a sleeping or unconscious foe.</p>
<p>An entangled creature can escape a fleshnet with a successful DC 25 Escape Artist check (a full-round action). The net has 10 hit points and DR 10/slashing; it can be burst with a successful DC 28 Strength check (also a full-round action).</p>
<h3 id="tech-weapon-fleshnet_cannon-construction">Construction</h3>
<p><strong>Craft DC</strong> 30; <strong>Cost</strong> 1,500 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">nanotech lab</Link></p>
</>};
const _grenade_launcher = {title: "Grenade launcher", jsx: <><h2 id="tech-weapon-grenade_launcher-grenade-launcher">Grenade launcher</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 8,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 8 lbs.<br/><strong>Damage</strong> Varies (small), Varies (medium); <strong>Damage Type</strong> Varies; <strong>Critical</strong> &mdash;<br/><strong>Range</strong> 100 ft.; <strong>Capacity</strong> 20 (5 grenades); <strong>Usage</strong> 1 grenade and 1 charge; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link></p>
<p>A grenade launcher is a bulky weapon that can fire any <Link to="/tech-weapon/grenade">grenade</Link> a great distance. Grenades propelled by a launcher can be set to detonate upon impact or at the start of the wielder's next turn. A grenade launcher requires charges to fire, but unless the weapon is also loaded with a grenade, any charges that are consumed are wasted. A grenade launcher can hold up to 5 grenades at a time. Loading a single grenade into a grenade launcher is a move action.</p>
<h3 id="tech-weapon-grenade_launcher-construction">Construction</h3>
<p><strong>Craft DC</strong> 28; <strong>Cost</strong> 4,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
</>};
const _nuclear_resonator = {title: "Nuclear resonator", jsx: <><h2 id="tech-weapon-nuclear_resonator-nuclear-resonator">Nuclear resonator</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 90,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 11 lbs.<br/><strong>Damage</strong> Special (small), Special (medium); <strong>Damage Type</strong> Sonic; <strong>Critical</strong> 18-20/&times;2<br/><strong>Range</strong> 80 ft. (see text); <strong>Capacity</strong> 20; <strong>Usage</strong> 5 charges; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<p>A nuclear resonator is a bulky weapon that creates a droning shriek when fired - and even when it's not being fired, it buzzes, whirs, and flashes. The wielder takes a -4 penalty on any Stealth checks made while it is active. It can be powered off completely to negate this penalty; either activating or deactivating is a standard action.</p>
<p>When this weapon is fired, it creates a highly focused beam of sound that swiftly modulates to resonate at the atomic frequencies of the first target it strikes. The wielder make one attack roll when firing a nuclear resonator, then resolves that roll against the Armor Class of every creature in an 80 foot line from his position. The resonator's beam tunes itself to the precise molecular structure of the first creature in the line he hits, dealing 9d6 points of sonic damage to that target. Any other targets of the same creature type in the line which are subsequently struck take 5d6 points of sonic damage, while creatures of different types than the initial target take 3d6 points of sonic damage. If the attack roll is a critical threat, choose one target hit by the attack to resolve the critical confirmation against. A creature that's critically hit by a nuclear resonator must succeed at a DC 18 Fortitude saving throw to resist being <Link to="/misc/stunned">stunned</Link> for 1 round and <Link to="/misc/deafened">deafened</Link> for 1d6 rounds. A creature slain by a nuclear resonator is completely disintegrated (any gear carried remains unaffected).</p>
<p><Link to="/tech-misc/force_field_brown">Force fields</Link> and force effects are not damaged by a nuclear resonator's beam, and completely block its effects. The beam emitted by a nuclear resonator is a sonic effect, and cannot pass through an area of magical silence or an area under the effects of a <Link to="/tech-misc/signal_jammer">signal jammer</Link>.</p>
<h3 id="tech-weapon-nuclear_resonator-construction">Construction</h3>
<p><strong>Craft DC</strong> 35; <strong>Cost</strong> 45,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
</>};
const _plasmathrower = {title: "Plasmathrower", jsx: <><h2 id="tech-weapon-plasmathrower-plasmathrower">Plasmathrower</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 30,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 15 lbs.<br/><strong>Damage</strong> 2d10 (small), 4d6 (medium); <strong>Damage Type</strong> electricity and fire; <strong>Critical</strong> 19-20/&times;2<br/><strong>Range</strong> 60 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 2 charges; <strong>Special</strong> <Link to="/misc/automatic">Automatic</Link> or <Link to="/misc/slow_firing">slow-firing</Link>, <Link to="/misc/scatter">scatter</Link>, <Link to="/misc/touch">touch</Link></p>
<p>A plasmathrower is a devastating weapon that fires blasts of superheated, electrically charged gas. This weapon has two firing modes: slow-firing and automatic. When used on the slow-firing setting, the weapon fires a scattering shot with no range increment; on the automatic setting, it fires individual bursts of plasma that can reach up to 3 range increments. Half the damage dealt by a plasmathrower is fire damage and the other half is electricity damage.</p>
<h3 id="tech-weapon-plasmathrower-construction">Construction</h3>
<p><strong>Craft DC</strong> 32; <strong>Cost</strong> 15,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
</>};
const _rail_gun = {title: "Rail gun", jsx: <><h2 id="tech-weapon-rail_gun-rail-gun">Rail gun</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 30,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 14 lbs.<br/><strong>Damage</strong> 3d8 (small), 3d10 (medium); <strong>Damage Type</strong> B and P; <strong>Critical</strong> &times;4<br/><strong>Range</strong> 200 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 charge; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<p>A rail gun uses gravitons to compress raw metal scrap placed in its sequencing chamber into hyperdense shells that it then accelerates to astounding speed and fires from its electromagnetically charged barrel. The weapon's rate of fire is slow compared to most other technological weapons, yet its relatively high damage combined with its potential for particularly grisly critical hits makes it a much sought-after weapon for long-range combat. Shots fired from a rail gun bypass an object's first 10 points of hardness, and can completely penetrate targets without hardness.</p>
<p>When making an attack with a rail gun, make a single attack roll and compare that result to the ACs of all creatures in a line extending out to the weapon's maximum range. This weapon damages all targets with an AC equal to or lower than the attack roll. However, if the attack's damage fails to penetrate any target's hardness or damage reduction, this shot is blocked and cannot damage targets that are farther away.</p>
<h3 id="tech-weapon-rail_gun-construction">Construction</h3>
<p><strong>Craft DC</strong> 32; <strong>Cost</strong> 15,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">graviton lab</Link></p>
</>};
const _rocket_launcher = {title: "Rocket launcher", jsx: <><h2 id="tech-weapon-rocket_launcher-rocket-launcher">Rocket launcher</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 10,800 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 10 lbs.<br/><strong>Damage</strong> 8d6 (small), 12d6 (medium); <strong>Damage Type</strong> B and fire; <strong>Critical</strong> &mdash;<br/><strong>Range</strong> 120 ft.; <strong>Capacity</strong> 10; <strong>Usage</strong> 1 (disposable); <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/touch">touch</Link></p>
<p>A newly created rocket launcher contains its entire load of rockets and energy charges. It cannot be reloaded, and once its final rocket is fired, the weapon is useless. Rockets fired from a rocket launcher can target a single target or a grid intersection. A creature that takes a direct hit from a rocket cannot attempt a saving throw to reduce the damage taken. When a rocket strikes its target, it explodes in a 30-foot-radius <Link to="/misc/burst">burst</Link> that deals fire and bludgeoning damage to all creatures within that area of effect - a successful DC 15 Reflex save halves the damage for all but the target. Some rocket launchers carry alternate loads, replacing the fire damage with electricity or cold damage, and there are rumors of rocket launchers capable of doing even more damage, firing gravity-based weapons or using radioactive payloads.</p>
<h3 id="tech-weapon-rocket_launcher-construction">Construction</h3>
<p><strong>Craft DC</strong> 28; <strong>Cost</strong> 5,400 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
</>};
const _vortex_gun = {title: "Vortex gun", jsx: <><h2 id="tech-weapon-vortex_gun-vortex-gun">Vortex gun</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 182,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 15 lbs.<br/><strong>Damage</strong> 8d6 (small), 10d6 (medium); <strong>Damage Type</strong> Force; <strong>Critical</strong> 19-20/&times;2<br/><strong>Range</strong> 100-ft. cone; <strong>Capacity</strong> 30; <strong>Usage</strong> 10 charges; <strong>Special</strong> <Link to="/misc/slow_firing">Slow-firing</Link>, <Link to="/misc/scatter">scatter</Link>, <Link to="/misc/touch">touch</Link></p>
<p>A vortex gun looks like a sleek shotgun with three barrels arranged in a triangular formation. When this weapon is fired, the three barrels release a beam of gravitons that spiral around each other to create a 100-foot-long cone-shaped vortex of devastating energy. This energy tears, crushes, and twists everything in its path. Being struck by a vortex gun induces overwhelming vertigo in living victims. A living creature damaged by a vortex gun must succeed at a DC 18 Fortitude saving throw to avoid being <Link to="/misc/nauseated">nauseated</Link> for 1 round. A critical hit also allows the user of the gun to attempt a <Link to="/rule/trip">trip</Link> combat maneuver check against the target (CMB = user's base attack bonus + 15); this attempt doesn't provoke attacks of opportunity. Flying creatures struck by a vortex gun are affected as if they were struck by hurricane force <Link to="/rule/winds">winds</Link>. A creature protected by a <Link to="/tech-misc/force_field">force field</Link> takes no damage from a vortex gun but must succeed at a DC 18 Reflex save or the shot automatically depletes all of the force field's remaining hit points.</p>
<h3 id="tech-weapon-vortex_gun-construction">Construction</h3>
<p><strong>Craft DC</strong> 33; <strong>Cost</strong> 91,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">graviton lab</Link></p>
</>};
const _x_laser = {title: "X-laser", jsx: <><h2 id="tech-weapon-x_laser-x-laser">X-laser</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 21</Link></p>
<p><strong>Cost</strong> 40,000 gp<br/><strong>Type</strong> two-handed ranged; <strong>Proficiency</strong> exotic (heavy weaponry); <strong>Weight</strong> 10 lbs.<br/><strong>Damage</strong> 6d4 (small), 5d6 (medium); <strong>Damage Type</strong> fire; <strong>Critical</strong> &times;4<br/><strong>Range</strong> 200 ft.; <strong>Capacity</strong> 20; <strong>Usage</strong> 5 charges; <strong>Special</strong> <Link to="/misc/touch">Touch</Link></p>
<p>An x-laser is a super-charged laser with devastating effects. It fires a highly focused, incredibly powerful beam of high-frequency light. An x-laser's beam functions as a <Link to="/tech-weapon/laser_rifle">laser rifle's</Link> beam, but it bores holes through any creature or object it damages. The beam is stopped if it cannot penetrate the hardness, fire resistance, or fire immunity of a barrier or creature. When making an attack with an x-laser, make a single attack roll and compare that result to the ACs of all creatures in a line extending out to the weapon's maximum range. This weapon damages all targets with an AC equal to or lower than the attack roll. The hole created by an x-laser is less than an inch in diameter and serves primarily as evidence of the weapon's discharge rather than significantly altering an object's structural integrity beyond the damage the laser blast deals as part of the attack.</p>
<h3 id="tech-weapon-x_laser-construction">Construction</h3>
<p><strong>Craft DC</strong> 33; <strong>Cost</strong> 20,000 gp<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
</>};
const _grenade = {title: "Grenade", jsx: <><h2 id="tech-weapon-grenade-grenade">Grenade</h2>
<p><strong>Sources</strong> <Link to="/source/technology_guide">Technology Guide pg. 46</Link><br/><strong>Price</strong> 750 gp (arc grenade), 6,000 gp (atom grenade), 250 gp (bang grenade), 3,300 gp (bio grenade), 750 gp (concussion grenade), 750 gp (EMP grenade), 750 gp (flash grenade), 750 gp (flechette grenade), 750 gp (fragmentation grenade), 70 gp (gas grenade), 2,250 gp (gravity grenade), 750 gp (inferno grenade), 1,600 gp (plasma grenade), 750 gp (soft grenade), 1,000 gp (sonic grenade), 750 gp (zero grenade)<br/><strong>Slot</strong> none; <strong>Weight</strong> 1 lb. (all)<br/><strong>Capacity</strong> -; <strong>Usage</strong> disposable</p>
<h3 id="tech-weapon-grenade-construction">Construction</h3>
<p><strong>Craft DC</strong> 20 (all)<br/><strong>Cost</strong> 375 gp (arc grenade), 3,000 gp (atom grenade), 125 gp (bang grenade), 1,650 gp (bio grenade), 375 gp (concussion grenade), 375 gp (EMP grenade), 375 gp (flash grenade), 375 gp (flechette grenade), 375 gp (fragmentation grenade), 375 gp (gas grenade), 1,125 gp (gravity grenade), 375 gp (inferno grenade), 800 gp (plasma grenade), 375 gp (soft grenade), 500 gp (sonic grenade), 375 gp (zero grenade)<br/><Link to="/feat/craft_technological_arms_and_armor">Craft Technological Arms and Armor</Link>, <Link to="/rule/crafting_laboratories">military lab</Link></p>
<p>A grenade is a small, cylindrical device that is designed to be thrown as a splash weapon or fired from a <Link to="/tech-weapon/grenade_launcher">grenade launcher</Link>. Before being thrown by hand, the grenade must be primed with a quick twist of a dial at one end and then armed with a click of a button at the center of that dial. Priming and arming a grenade is a free action; a grenade launcher primes and arms all grenades it fires. The grenade detonates at the beginning of the wielder's next turn, hopefully in the area targeted. When a grenade detonates, it damages all targets within a 20-foot-radius <Link to="/misc/spread">spread</Link>. A successful DC 15 Reflex save halves any damage dealt by a grenade.</p>
<p>The type of damage dealt by grenades varies widely and depends upon the nature of the specific grenade. The different types of grenades and the damage types they deal (along with any additional effects their damage deals) are listed below.</p>
<ul>
<li><strong>Arc Grenade:</strong> Deals 5d6 points of electricity damage.</li>
<li><strong>Atom Grenade:</strong> Creates a 20-foot-radius area of medium <Link to="/rule/radiation">radiation</Link> that persists for 24 hours.</li>
<li><strong>Bang Grenade:</strong> Deals no damage but <Link to="/misc/stagger">staggers</Link> creatures for 1 round and <Link to="/misc/deafen">deafens</Link> them for 1d4 rounds (DC 15 Fortitude save negates).</li>
<li><strong>Bio Grenade:</strong> Infects creatures who fail a DC 15 Fortitude save with <Link to="/disease/bubonic_plague">bubonic plague</Link> (no onset).</li>
<li><strong>Concussion Grenade:</strong> Deals 5d6 points of bludgeoning damage.</li>
<li><strong>EMP Grenade:</strong> Deals 5d6 points of electricity damage to robots and electronic-based gear, half damage to cyborgs and androids, and no damage to other creatures.</li>
<li><strong>Flash Grenade:</strong> <Link to="/misc/blind">Blinds</Link> creatures for 1d4 rounds (DC 15 Fortitude save negates).</li>
<li><strong>Flechette Grenade:</strong> Deals 5d6 points of piercing damage.</li>
<li><strong>Fragmentation Grenade:</strong> Deals 5d6 points of slashing damage.</li>
<li><strong>Gas Grenade:</strong> Creates a 20-foot spread of foul-smelling toxic gas. All creatures in this area of effect must succeed at a DC 14 Fortitude save or become <Link to="/misc/nauseated">nauseated</Link>. This condition lasts as long as the creature is in the cloud and for 1d4+1 rounds after it leaves. The gas created lingers in the area for 5 rounds, and any creature that succeeds at its initial save but remains in the cloud must continue to save each round on its turn. The gas is not thick enough to obscure vision, and is a poison effect. The vapors can be dispersed in 1 round by moderate or stronger wind. -- <Link to="/source/pathfinder_86_lords_of_rust">Pathfinder #86: Lords of Rust pg. 62</Link></li>
<li><strong>Gravity Grenade:</strong> Deals 5d6 points of force damage. Creatures damaged by a gravity grenade are automatically subjected to a <Link to="/rule/trip">trip</Link> attack (grenade's CMB = +15).</li>
<li><strong>Inferno Grenade:</strong> Deals 5d6 points of fire damage.</li>
<li><strong>Plasma Grenade:</strong> Deals 4d6 points of fire damage and 4d6 points of electricity damage.</li>
<li><strong>Soft Grenade:</strong> Deals 5d6 points of nonlethal damage.</li>
<li><strong>Sonic Grenade:</strong> Deals 5d6 points of sonic damage; creatures who fail a DC 15 Fortitude save are also <Link to="/misc/deafened">deafened</Link> for 1d4 rounds.</li>
<li><strong>Zero Grenade:</strong> Deals 5d6 points of cold damage.</li>
</ul>
</>};
const _beam_cannon_emp_cannon = {..._beam_cannon, title: "Beam Cannon (EMP cannon)"};
const _beam_cannon_laser_cannon = {..._beam_cannon, title: "Beam Cannon (laser cannon)"};
const _beam_cannon_sonic_cannon = {..._beam_cannon, title: "Beam Cannon (sonic cannon)"};
const _beam_cannon_zero_cannon = {..._beam_cannon, title: "Beam Cannon (zero cannon)"};
const _arc_grenade = {..._grenade, title: "Grenade (arc grenade)"};
const _atom_grenade = {..._grenade, title: "Grenade (atom grenade)"};
const _bang_grenade = {..._grenade, title: "Grenade (bang grenade)"};
const _bio_grenade = {..._grenade, title: "Grenade (bio grenade)"};
const _concussion_grenade = {..._grenade, title: "Grenade (concussion grenade)"};
const _emp_grenade = {..._grenade, title: "Grenade (emp grenade)"};
const _flash_grenade = {..._grenade, title: "Grenade (flash grenade)"};
const _flechette_grenade = {..._grenade, title: "Grenade (flechette grenade)"};
const _fragmentation_grenade = {..._grenade, title: "Grenade (fragmentation grenade)"};
const _gas_grenade = {..._grenade, title: "Grenade (gas grenade)"};
const _gravity_grenade = {..._grenade, title: "Grenade (gravity grenade)"};
const _inferno_grenade = {..._grenade, title: "Grenade (inferno grenade)"};
const _plasma_grenade = {..._grenade, title: "Grenade (plasma grenade)"};
const _soft_grenade = {..._grenade, title: "Grenade (soft grenade)"};
const _sonic_grenade = {..._grenade, title: "Grenade (sonic grenade)"};
const _zero_grenade = {..._grenade, title: "Grenade (zero grenade)"};
export default {not_found:_not_found,monowhip:_monowhip,null_blade:_null_blade,plasma_blade:_plasma_blade,chainsaw:_chainsaw,neural_inhibitor:_neural_inhibitor,laser_torch:_laser_torch,stun_baton:_stun_baton,starfall_spade:_starfall_spade,arc_pistol:_arc_pistol,dart_gun:_dart_gun,death_ray:_death_ray,emp_pistol:_emp_pistol,flare_gun:_flare_gun,gravity_pistol:_gravity_pistol,inferno_pistol:_inferno_pistol,laser_pistol:_laser_pistol,mind_burner:_mind_burner,mindrender:_mindrender,sonic_pistol:_sonic_pistol,stun_gun:_stun_gun,zero_pistol:_zero_pistol,arc_rifle:_arc_rifle,autograpnel:_autograpnel,emp_rifle:_emp_rifle,gravity_rifle:_gravity_rifle,id_rifle:_id_rifle,laser_rifle:_laser_rifle,sonic_rifle:_sonic_rifle,zero_rifle:_zero_rifle,atom_gun:_atom_gun,beam_cannon:_beam_cannon,fleshnet_cannon:_fleshnet_cannon,grenade_launcher:_grenade_launcher,nuclear_resonator:_nuclear_resonator,plasmathrower:_plasmathrower,rail_gun:_rail_gun,rocket_launcher:_rocket_launcher,vortex_gun:_vortex_gun,x_laser:_x_laser,grenade:_grenade,beam_cannon_emp_cannon:_beam_cannon_emp_cannon,beam_cannon_laser_cannon:_beam_cannon_laser_cannon,beam_cannon_sonic_cannon:_beam_cannon_sonic_cannon,beam_cannon_zero_cannon:_beam_cannon_zero_cannon,arc_grenade:_arc_grenade,atom_grenade:_atom_grenade,bang_grenade:_bang_grenade,bio_grenade:_bio_grenade,concussion_grenade:_concussion_grenade,emp_grenade:_emp_grenade,flash_grenade:_flash_grenade,flechette_grenade:_flechette_grenade,fragmentation_grenade:_fragmentation_grenade,gas_grenade:_gas_grenade,gravity_grenade:_gravity_grenade,inferno_grenade:_inferno_grenade,plasma_grenade:_plasma_grenade,soft_grenade:_soft_grenade,sonic_grenade:_sonic_grenade,zero_grenade:_zero_grenade}