import Link from '../../components/Link';
const _brawling_blademaster = {title: "Brawling Blademaster", jsx: <><h2 id="arc-samurai-brawling_blademaster-brawling-blademaster">Brawling Blademaster</h2>
<p><strong>Sources</strong> <Link to="/source/martial_arts_handbook">Martial Arts Handbook pg. 10</Link><br/>While some martial arts traditions focus on the strength of the body, most schools of combat and self-defense know the importance of using weapons as well. Brawling blademaster samurai use weapon strikes and unarmed attacks in equal measure - foes expecting to defend themselves against a dagger or a sword are often caught off guard by a brawling blademaster's brutal kicks or punches.</p>
<p><strong>Weapon and Armor Proficiency:</strong> Brawling blademasters are proficient with all simple and martial weapons, plus the <Link to="/eq-weapon/katana">katana</Link> and <Link to="/eq-weapon/wakizashi">wakizashi</Link>. Brawling blademasters are proficient with light armor, but not with shields.</p>
<p>This alters the samurai's <strong className="hl">weapon and armor proficiency</strong>.</p>
<p><strong>Empty Hand (Ex):</strong> A brawling blademaster gains <Link to="/feat/improved_unarmed_strike">Improved Unarmed Strike</Link> as a bonus feat. She uses her samurai level as her <Link to="/class/monk">monk</Link> level for determining the amount of damage she deals with an unarmed strike. These levels stack with monk levels to determine the brawling blademaster's unarmed strike damage.</p>
<p>This replaces <strong className="hl">mount</strong>.</p>
<p><strong>Nimble (Ex):</strong> At 2nd level, a brawling blademaster gains the <Link to="/class/gunslinger">gunslinger's</Link> nimble class feature, using her samurai level as his gunslinger level.</p>
<p><strong>Dual Expertise (Ex):</strong> At 3rd level, a brawling blademaster gains <Link to="/feat/two_weapon_fighting">Two-Weapon Fighting</Link> as a bonus feat, even if she doesn't meet the prerequisites. Furthermore, when the brawling blademaster selects a feat with the bonus feat class feature, she can ignore any Dexterity requirements for the feat if its prerequisites include the Two-Weapon Fighting feat.</p>
<p>This replaces <strong className="hl">weapon expertise</strong>.</p>
<p><strong>Harmonious Flow (Ex):</strong> At 4th level, the brawling blademaster becomes skilled at combining weapon attacks and unarmed strikes into a harmonious combat style. When attacking the target of her challenge, the brawling blademaster doesn't take the usual -2 penalty on attack rolls associated with attacking with two weapons if her main-hand weapon is a light or one-handed manufactured weapon and her off-hand weapon is an unarmed strike (or vice versa). While she's using this ability, one of her hands must be empty even if she uses another body part to make an unarmed strike.</p>
<p>This replaces <strong className="hl">mounted archer</strong>.</p>
<p><strong>Perfect Clarity (Ex):</strong> At 5th level, the brawling blademaster sees all her foes with perfect clarity even when focused on one opponent. She no longer takes a penalty to her AC during a challenge.</p>
<p>This ability replaces <strong className="hl">banner</strong>.</p>
<p><strong>Superior Focus (Ex):</strong> At 14th level, the brawling blademaster gains a +2 bonus on saving throws during a challenge.</p>
<p>This replaces <strong className="hl">greater banner</strong>.</p>
</>};
const _ironbound_sword = {title: "Ironbound Sword", jsx: <><h2 id="arc-samurai-ironbound_sword-ironbound-sword">Ironbound Sword</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_ancients">Blood of the Ancients pg. 20</Link><br/>The ironbound sword's fighting style, focused on incapacitating opponents rather than killing them, is founded on a philosophy that cares both for the samurai and for her attacker. This style became prevalent during the peaceful and stable periods of Lung Wa, and reflected those values. Using these techniques, an ironbound sword can subdue a foe without causing permanent harm, leaving the soul of the samurai unstained by deaths of her enemies.</p>
<p><strong>Merciful Combatant (Ex):</strong> At 3rd level, an ironbound sword becomes an expert at defeating foes without killing them. An ironbound sword can use any weapon to deal nonlethal damage without taking the normal -4 penalty on attack rolls. Additionally, the ironbound sword gains a +2 bonus on combat maneuvers against a target so long as the last successful attack she made against that target dealt nonlethal damage. Her samurai levels count as fighter levels and stack with fighter levels for the purposes of fighter and samurai prerequisites and class features.</p>
<p>This replaces <strong className="hl">weapon expertise</strong>.</p>
<p><strong>Subduing Knockout (Ex):</strong> At 5th level, once per day, an ironbound sword can unleash a devastating attack that can instantly knock a target unconscious. She must announce this intent before making her attack roll. If the ironbound sword's attack hits and the target takes damage from the blow, the target must succeed at a Fortitude saving throw (DC = 10 + half the ironbound sword's level + the higher of the ironbound sword's Strength or Dexterity modifier) or fall unconscious for 1d6 rounds. Each round on its turn, the unconscious target can attempt a new saving throw to end the effect as a full-round action that does not provoke attacks of opportunity. Creatures immune to critical hits or nonlethal damage are immune to this ability. At 10th level, the ironbound sword can use this ability twice per day; at 15th level, she can use it three times per day.</p>
<p>This replaces <strong className="hl">banner</strong>.</p>
<p><strong>Blade Reversal (Ex):</strong> At 14th level, an ironbound sword can turn the force of an opponent's attacks back against them. Whenever the ironbound sword takes a <Link to="/misc/full_defense">full defense</Link> action, she can expend an attack of opportunity to attempt to counter melee attacks made against her. This counter is a single attack roll at the ironbound blade's full base attack bonus that resolves before the enemy's attack. If the counter successfully hits the attacking enemy's AC and if the ironbound sword's attack roll is higher than the attacking creature's attack roll, the ironbound sword takes no damage from the enemy's attack and can initiate a disarm combat maneuver against the attacking enemy as a free action. If the triggering attack was made with a natural attack or unarmed strike, a successful disarm combat maneuver renders that natural attack or unarmed strike unusable until the victim spends a standard action to reset dislocated joints. In addition, the ironbound sword can spend one use of her resolve when she hits with a nonlethal attack to initiate a disarm combat maneuver against her target as a free action.</p>
<p>This replaces <strong className="hl">greater banner</strong>.</p>
</>};
const _sovereign_blade = {title: "Sovereign Blade", jsx: <><h2 id="arc-samurai-sovereign_blade-sovereign-blade">Sovereign Blade</h2>
<p><strong>Sources</strong> <Link to="/source/legacy_of_dragons">Legacy of Dragons pg. 14</Link><br/>In Tian Xia, many samurai are tutored in the ways of honor using lessons that originate from sovereign dragons and their dedication to safeguarding harmony.</p>
<p><strong>Alignment:</strong> A sovereign blade's alignment must be at least partially neutral. If the sovereign blade's alignment is not partially neutral, she is treated as if she had violated her order's edicts each day until her alignment is again partially neutral.</p>
<p><strong>Dogmatic Denial (Ex):</strong> A sovereign blade gains a +2 bonus on saving throws against spells with any of the following descriptors that don't match part of the character's own alignment: chaotic, evil, good, or lawful.</p>
<p>This ability replaces <strong className="hl">mount</strong>.</p>
<p><strong>Golden Armor (Su):</strong> At 4th level, a sovereign blade can spend one use of her resolve to cause her armor to become golden for 1 round per class level, gaining energy resistance equal to 1/2 her samurai level against one energy type of her choice.</p>
<p>This ability replaces <strong className="hl">mounted archer</strong>.</p>
<p><strong>Sovereign Breath (Sp):</strong> At 6th level, the sovereign blade can issue forth an immense roar similar to the breath weapon of a <Link to="/family/sovereign_dragon">sovereign dragon</Link>. This functions as dragon's breath, except it deals sonic damage in a 30-foot cone and has a caster level equal to half the sovereign blade's samurai level. The sovereign blade can use this ability once per day, plus one additional time per day at 12th and 18th levels.</p>
<p>This replaces the <strong className="hl">bonus feats</strong> a samurai gained at 6th, 12th, and 18th level.</p>
</>};
const _sword_saint = {title: "Sword Saint", jsx: <><h2 id="arc-samurai-sword_saint-sword-saint">Sword Saint</h2>
<p><strong>Sources</strong> <Link to="/source/dragon_empires_primer">Dragon Empires Primer pg. 22</Link><br/>Sword saints hail from lands where samurai are prevalent, and are often ronin who wander the world seeking new challenges to perfect their intricate style of swordplay called iaijutsu. The following benefits apply only when a sword saint is using a sword and carrying nothing in his other hand. The sword saint is an archetype of the <Link to="/class/samurai">samurai</Link>.</p>
<p><strong>Iaijutsu Strike (Ex):</strong> A sword saint can perform a lightning-quick iaijutsu strike against the target of his challenge to inflict devastating wounds while drawing his sword. After the sword saint has challenged a foe but before he has attacked the target of his challenge, he may choose to use his iaijutsu strike as a full-round action, making an attack roll with his weapon as normal. In order to use this ability, the sword saint's weapon must be sheathed at the start of his turn. If he successfully hits his opponent with an iaijutsu strike, his attack deals an additional +1d6 points of damage. This bonus damage increases by an additional +1d6 at 3rd level and every two levels thereafter to a maximum of +10d6 damage at 19th level. Any extra damage as a result of a successful iaijutsu strike is not multiplied by a critical hit.</p>
<p>After making an iaijutsu strike, a sword saint takes a -4 penalty to his AC until his next turn, but his weapon is now drawn and he may continually to fight normally. Regardless of whether he hits his opponent with the iaijutsu strike, a sword saint cannot use this ability on the same foe more than once per day.</p>
<p>At 10th level, a sword saint learns to focus faster and is able to make an iaijutsu strike as a standard action, and the penalty to his AC is reduced to -2.</p>
<p>This ability replaces a samurai's <strong className="hl">mount</strong>.</p>
<p><strong>Brutal Slash (Ex):</strong> At 3rd level, a sword saint's iaijutsu strike becomes even more deadly. If a sword saint threatens a critical hit with his iaijutsu strike, he adds a bonus equal to 1/2 his class level to the attack roll to confirm a critical hit.</p>
<p>This ability replaces <strong className="hl">mounted charge</strong>.</p>
<p><strong>Terrifying Iaijutsu (Ex):</strong> At 5th level, a sword saint's iaijutsu strike devastates the morale of foes that witness it. When a sword saint successfully hits with an iaijutsu strike, all foes within 30 feet must succeed at a Will save (DC 10 + 1/2 the sword saint's class level + the sword saint's Cha modifier) or become shaken for 1d4+1 rounds.</p>
<p>This ability replaces <strong className="hl">banner</strong>.</p>
<p><strong>Roaring Iaijutsu (Ex):</strong> At 14th level, a sword saint's iaijutsu strike deafens foes upon impact. When a sword saint successfully hits with an iaijutsu strike, all foes within 30 feet must succeed at a Fortitude save (DC 10 + 1/2 the sword saint's class level + the sword saint's Str modifier) or be deafened for 1d4 minutes.</p>
<p>This ability replaces <strong className="hl">greater banner</strong>.</p>
</>};
const _ward_speaker = {title: "Ward Speaker", jsx: <><h2 id="arc-samurai-ward_speaker-ward-speaker">Ward Speaker</h2>
<p><strong>Sources</strong> <Link to="/source/disciples_doctrine">Disciple's Doctrine pg. 26</Link><br/>The ward speaker draws power from simple rituals to honor the spirits found throughout the world so that he might better protect those entrusted to his care.</p>
<p><strong>Alignment:</strong> A ward speaker must be of a nonevil alignment.</p>
<p>This alters the samurai's <strong className="hl">alignment</strong>.</p>
<p><strong>Propitiation (Ex, Su, Sp):</strong> A ward speaker can perform a special ritual to propitiate <Link to="/family/kami">kami</Link> and gain a sliver of their power. This ritual must be performed at a shrine or a location warded by a specific type of kami. The propitiation takes 1 minute and involves clapping, ringing bells, bowing, and token offerings of coins, food, incense, or other gifts. The ward speaker's propitiation must be performed uninterrupted to receive any benefits from it. At the end of this ritual, the ward speaker immediately gains a fortune depending on the type of kami he sought to propitiate.</p>
<p>As an immediate action, the ward speaker can dismiss the fortune to reroll one d20 roll before the results of the roll are revealed; he must use the result of the second roll, even if it's worse. If not dismissed, a fortune remains in effect until the ward speaker regains the use of his daily abilities, at which point the fortune and its benefits end. If a ward speaker dismisses a fortune to receive a benefit based on the specific kami he propitiated (see below), he does not also gain the reroll described here.</p>
<p>The ward speaker can perform this ritual once per day at 1st level, plus one additional time per day for every 3 levels beyond 1st, to a maximum of seven times per day at 19th level. He can maintain only one fortune at a time; performing a propitiation while he already has a fortune active ends the previous fortune and its benefits.</p>
<p>This replaces <strong className="hl">resolve</strong>, <strong className="hl">greater resolve</strong>, and <strong className="hl">true resolve</strong>.</p>
<blockquote>
<p><strong>Jinushigami (Ex, Sp):</strong> The ward speaker (and his mount, if he has one) gains a 10-foot enhancement bonus to base speed. At 9th level, this enhancement bonus increases to 20 feet. At 17th level, once per day, he can dismiss this fortune as an immediate action to cast <Link to="/spell/earthquake">earthquake</Link> as a spell-like ability, using his samurai level as his caster level.</p>
<p><strong>Kodama (Su):</strong> As a standard action, the ward speaker can afflict one target that can see him with a distracting gaze. If the target fails a Will save (DC = 10 + half the ward speaker's samurai level), it is staggered for 1d4 rounds. At 9th level, it is instead staggered for 2d4 rounds. At 17th level, it is instead staggered for 1 minute. Once a creature has been targeted by this ability, it cannot be targeted by it again for 24 hours.</p>
<p><strong>Shikigami (Ex):</strong> The ward speaker gains <Link to="/feat/catch_off_guard">Catch Off-Guard</Link> and <Link to="/feat/throw_anything">Throw Anything</Link> as bonus feats. At 9th level, he gains <Link to="/feat/toughness">Toughness</Link> and <Link to="/feat/step_up">Step Up</Link>. At 17th level, he gains <Link to="/feat/following_step">Following Step</Link> and <Link to="/feat/step_up_and_strike">Step Up and Strike</Link>, even if he does not meet the prerequisites.</p>
<p><strong>Toshigami (Sp):</strong> The ward speaker can speak with plants, as the <Link to="/spell/speak_with_plants">speak with plants</Link> spell. At 9th level, the ward speaker can dismiss this fortune as an immediate action to cast <Link to="/spell/haste">haste</Link> as a spell-like ability. Once per day at 17th level, the ward speaker can instead dismiss this fortune to cast <Link to="/spell/temporal_stasis">temporal stasis</Link> as a spell-like ability. The ward speaker's caster level for these spell-like abilities is equal to his samurai level.</p>
<p><strong>Zuishin (Sp):</strong> As an immediate action, the ward speaker can dismiss this fortune to cast <Link to="/spell/cure_light_wounds">cure light wounds</Link> as a spell-like ability. At 9th level, the ward speaker can dismiss this fortune to cast <Link to="/spell/cure_serious_wounds">cure serious wounds</Link>, <Link to="/spell/lesser_restoration">lesser restoration</Link>, <Link to="/spell/remove_curse">remove curse</Link>, or <Link to="/spell/remove_disease">remove disease</Link>; at 17th level, he also adds <Link to="/spell/breath_of_life">breath of life</Link> and <Link to="/spell/heal">heal</Link> to this list. The ward speaker's caster level for these spell-like abilities is equal to his samurai level.</p>
</blockquote>
<p><strong>Resilient Stand (Ex):</strong> At 11th level, the spirits can bolster a ward speaker's willpower and resolve, granting him an inner reservoir he can use when he needs it most. If a ward speaker has not expended his daily uses of propitiation, he can call upon the spirits to reroll a saving throw during an honorable stand instead of expending a use of resolve to do so. He must take the result of the second roll, even if it is worse. This expends a daily use of propitiation.</p>
<p>This alters <strong className="hl">honorable stand</strong>.</p>
</>};
const _warrior_poet = {title: "Warrior Poet", jsx: <><h2 id="arc-samurai-warrior_poet-warrior-poet">Warrior Poet</h2>
<p><strong>Sources</strong> <Link to="/source/heroes_from_the_fringe">Heroes from the Fringe pg. 13</Link><br/>Warrior poets often study calligraphy, flower arrangement, poetry, and other courtly arts, but when called to battle, they treat combat as its own art form, fighting with beauty and grace. While these traditions first arose among the Jininese elves and are still extremely common in Jinin, the warrior poet's art has spread to different nations and peoples in Tian Xia over centuries.</p>
<p><strong>Dancer's Grace (Ex):</strong> When wearing no armor and not using a shield, the warrior poet gains a bonus to Armor Class equal to her Charisma bonus (to a maximum of her samurai level). A warrior poet loses this bonus while flat-footed or otherwise denied her Dexterity bonus.</p>
<p>This replaces the samurai's <strong className="hl">proficiency with medium armor, heavy armor, and shields</strong>.</p>
<p><strong>Flourish (Ex):</strong> The warrior poet is skilled at performing elegant moves in battle. At 1st level, the warrior poet gains a flourish of her choice from the list below. She gains another flourish at 3rd, 5th, 9th, 13th, 17th, and 20th levels.</p>
<blockquote>
<p><strong>Chrysanthemum's Blooming:</strong> The warrior poet gains <Link to="/feat/vital_strike">Vital Strike</Link> as a bonus feat and can apply its benefit when using <Link to="/feat/spring_attack">Spring Attack</Link>. If the warrior poet is at least 16th level and has <Link to="/feat/improved_vital_strike">Improved Vital Strike</Link>, she can apply that feat's benefit instead. The warrior poet must be at least 11th level to select this flourish.</p>
<p><strong>Exodus of Jinin:</strong> As long as the warrior poet is wearing light or no armor and carrying no more than a light load, her land speed increases by 10 feet. A warrior poet can select this flourish up to three times.</p>
<p><strong>Harmony of the Tranquil Garden:</strong> The warrior poet can focus her senses as a move action to gain <Link to="/umr/blindsense">blindsense</Link> out to 5 feet for 1 round. For every 5 samurai levels she has, the range of this blindsense increases by 5 feet.</p>
<p><strong>Jininsiel's Guidance:</strong> The warrior poet gains the rogue's <Link to="/ability/uncanny_dodge">uncanny dodge</Link> class feature. This flourish can be selected up to twice; selecting it a second time grants the warrior poet the rogue's <Link to="/ability/improved_uncanny_dodge">improved uncanny dodge</Link> class feature. The warrior poet must be at least 4th level to select this flourish the first time and at least 8th level to select this flourish the second time.</p>
<p><strong>Kitsune's Mystique:</strong> The warrior poet gains <Link to="/feat/improved_feint">Improved Feint</Link> as a bonus feat, ignoring its prerequisites. When the warrior poet uses Spring Attack or takes a move action to move, she can attempt to feint against one creature she threatens during her movement as part of her movement.</p>
<p><strong>Petals on the Wind:</strong> Whenever a foe provokes an attack of opportunity from the warrior poet, she can move 5 feet before making the attack of opportunity. This movement does not provoke attacks of opportunity. If the warrior poet takes an action to move during her next turn, she subtracts 5 feet from her total movement for each time she has used this ability since her last turn.</p>
<p><strong>Wrath of the Heavens:</strong> The warrior poet gains <Link to="/feat/shot_on_the_run">Shot on the Run</Link> as a bonus feat, ignoring its prerequisites.</p>
</blockquote>
<p>This replaces <strong className="hl">mount</strong>, <strong className="hl">weapon expertise</strong>, <strong className="hl">banner</strong>, and <strong className="hl">greater banner</strong>.</p>
<p><strong>Graceful Warrior (Ex):</strong> The warrior poet gains <Link to="/feat/weapon_finesse">Weapon Finesse</Link> as a bonus feat and can apply its benefits to <Link to="/eq-weapon/glaive">glaives</Link>, <Link to="/eq-weapon/katana">katanas</Link>, and <Link to="/eq-weapon/naginata">naginatas</Link> as if they were light weapons. This does not alter the weapons' properties for the purposes of any other effects.</p>
<p><strong>Skirmisher's Challenge (Ex):</strong> The warrior poet adds her samurai level to her damage rolls only on her first successful attack against a challenged target each round.</p>
<p>This modifies <strong className="hl">challenge</strong>.</p>
<p><strong>Graceful Strike (Ex):</strong> At 4th level, when the warrior poet uses Weapon Finesse to make a melee attack that adds her Dexterity bonus to attack rolls and her Strength bonus to damage rolls, she also adds half her samurai level to damage rolls.</p>
<p>This replaces <strong className="hl">mounted archer</strong> and <strong className="hl">demanding challenge</strong>.</p>
<p><strong>Battle Dance (Ex):</strong> At 6th level, the warrior poet gains Spring Attack as a bonus feat. At 12th level, she gains <Link to="/feat/improved_spring_attack">Improved Spring Attack</Link> as a bonus feat, and at 18th level, she gains <Link to="/feat/greater_spring_attack">Greater Spring Attack</Link> as a bonus feat. The warrior poet does not need to meet the prerequisites for these feats.</p>
<p>This replaces the samurai's <strong className="hl">bonus combat feats</strong>.</p>
</>};
const _yojimbo = {title: "Yojimbo", jsx: <><h2 id="arc-samurai-yojimbo-yojimbo">Yojimbo</h2>
<p><strong>Sources</strong> <Link to="/source/armor_masters_handbook">Armor Master's Handbook pg. 7</Link><br/>Yojimbo are highly trained bodyguards favored by the nobles and warlords of distant Minkai. Yojimbo who follow the order of the warrior loyally guard a single master, while ronin serve whoever can pay for their protection. Yojimbo often accompany visitors to the Inner Sea region from Tian Xia; a few have chosen to stay, and some have even passed on their training to bodyguards of this region.</p>
<p><strong>Resolute Defense (Ex):</strong> At 1st level, whenever a yojimbo issues a challenge, he can select one ally as his ward for the duration of the challenge. Whenever the yojimbo is adjacent to his ward, he can use resolve, greater resolve, and true resolve on his ward rather than targeting himself.</p>
<p>This ability replaces <strong className="hl">mount</strong>.</p>
<p><strong>Armor Expertise (Ex):</strong> At 3rd level, a yojimbo selects one type of armor, such as <Link to="/eq-armor/chain_shirt">chain shirt</Link> or <Link to="/eq-armor/scale_mail">scale mail</Link>. The yojimbo gains armor training, treating his samurai level as his <Link to="/class/fighter">fighter</Link> level, when wearing the selected armor.</p>
<p>This ability replaces <strong className="hl">weapon expertise</strong>.</p>
<p><strong>Intercept (Ex):</strong> At 4th level, a yojimbo learns to better disrupt the attacks of his enemies. He gains <Link to="/feat/bodyguard">Bodyguard</Link> as a bonus feat, even if he does not meet the prerequisite. In addition, whenever the yojimbo uses the aid another action to increase an ally's Armor Class, the bonus to Armor Class from the aid another action increases by 1.</p>
<p>This ability replaces <strong className="hl">mounted archer</strong>.</p>
</>};
export default {brawling_blademaster:_brawling_blademaster,ironbound_sword:_ironbound_sword,sovereign_blade:_sovereign_blade,sword_saint:_sword_saint,ward_speaker:_ward_speaker,warrior_poet:_warrior_poet,yojimbo:_yojimbo}