import Link from '../../components/Link';
import ScrollContainer from '../../components/ScrollContainer';
import InnerLink from '../../components/InnerLink';
const _not_found = {title: "Unknown", jsx: <><h2 id="eq-armor-not_found-error">Error</h2>
<p>Unable to find the requested armor.</p>
</>};
const _mithral_shirt = {title: "Mithral Shirt", jsx: <><h2 id="eq-armor-mithral_shirt-mithral-shirt">Mithral Shirt</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 128</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 464</Link><br/><strong>Cost</strong> 1,100 gp <strong>Weight</strong> 10 lbs.<br/><strong>Armor Bonus</strong> +4; <strong>Max Dex Bonus</strong> +6; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 10%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This extremely light <Link to="/eq-armor/chain_shirt">chain shirt</Link> is made of very fine <Link to="/eq-material/mithral">mithral</Link> links. The armor has an arcane spell failure chance of 10%, a maximum Dexterity bonus of +6, and no armor check penalty. It is considered light armor.</p>
</>};
const _elven_chain = {title: "Elven Chain", jsx: <><h2 id="eq-armor-elven_chain-elven-chain">Elven Chain</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 126</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 464</Link><br/><strong>Cost</strong> 5,150 gp <strong>Weight</strong> 20 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +4; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 20%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This extremely light <Link to="/eq-armor/chainmail">chainmail</Link> is made of very fine <Link to="/eq-material/mithral">mithral</Link> links. This armor is treated, in all ways, like light armor, including when determining proficiency. The armor has an arcane spell failure chance of 20%, a maximum Dexterity bonus of +4, and an armor check penalty of -2.</p>
</>};
const _adamantine_breastplate = {title: "Adamantine Breastplate", jsx: <><h2 id="eq-armor-adamantine_breastplate-adamantine-breastplate">Adamantine Breastplate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 124</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 464</Link><br/><strong>Cost</strong> 10,200 gp <strong>Weight</strong> 30 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -3<br/><strong>Arcane Spell Failure Chance</strong> 25%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>This nonmagical <Link to="/eq-armor/breastplate">breastplate</Link> is made of <Link to="/eq-material/adamantine">adamantine</Link>, giving its wearer damage reduction 2/-.</p>
</>};
const _dragonhide_plate = {title: "Dragonhide Plate", jsx: <><h2 id="eq-armor-dragonhide_plate-dragonhide-plate">Dragonhide Plate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 126</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 464</Link><br/><strong>Cost</strong> 3,300 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +9; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -5<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>This suit of <Link to="/eq-armor/full_plate">full plate</Link> is made of <Link to="/eq-material/dragonhide">dragonhide</Link>, rather than metal, so druids can wear it. It is otherwise identical to <Link to="/rule/masterwork_a">masterwork</Link> full plate.</p>
<p>The wearer of dragonhide plate tends to draw the ire of dragons of the same type as that used in the armor's creation.</p>
</>};
const _dwarven_plate = {title: "Dwarven Plate", jsx: <><h2 id="eq-armor-dwarven_plate-dwarven-plate">Dwarven Plate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 126</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 464</Link><br/><strong>Cost</strong> 16,500 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +9; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -5<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>This full plate is made of <Link to="/eq-material/adamantine">adamantine</Link>, giving its wearer damage reduction 3/-.</p>
</>};
const _barding = {title: "Barding", jsx: <><h2 id="eq-armor-barding-barding">Barding</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 81</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 159</Link><br/><strong>Price</strong> &times;4 (Large creature), &times;2 (Medium creature); <strong>Weight</strong> &times;2 (Large creature), &times;1 (Medium creature)</p>
<p>Barding is a type of armor that covers the head, neck, chest, body, and possibly legs of a horse or other mount. Barding made of medium or heavy armor provides better protection than light barding, but at the expense of speed. Barding can be made of any armor type.</p>
<p>Armor for a horse (a Large non-humanoid creature) costs four times as much as armor for a human (a Medium humanoid creature) and also weighs twice as much (see <Link to="/rule/armor_for_unusual_creatures">Armor for Unusual Creatures</Link>). If the barding is for a pony or other Medium mount, the price is only double, and the weight is the same as for Medium armor worn by a humanoid. Medium or heavy barding slows a mount that wears it, as shown on the table below.</p>
<p>Flying mounts can't fly in medium or heavy barding.</p>
<p>Removing and fitting barding takes five times as long as the figures given in <Link to="/rule/getting_into_and_out_of_armor">Getting Into and Out of Armor</Link>. A barded animal cannot be used to carry any load other than a rider, and normal saddlebags.</p>
<ScrollContainer id="eq-armor-barding--table-0"><table>
<thead>
<tr>
<th>Type</th>
<th>40 ft.</th>
<th>50 ft.</th>
<th>60 ft.</th>
</tr>
</thead>
<tbody><tr>
<td>Barding</td>
<td>40 ft.</td>
<td>50 ft.</td>
<td>60 ft.</td>
</tr>
<tr>
<td>Medium armor</td>
<td>30 ft.</td>
<td>35 ft.</td>
<td>40 ft.</td>
</tr>
<tr>
<td>Heavy armor<sup><InnerLink showBacklink="backlink-eq-armor-barding-ref-H-1" id="eq-armor-barding-ref-H-1" data-hash-target to="eq-armor-barding-H">1</InnerLink></sup></td>
<td>30 ft.</td>
<td>35 ft.</td>
<td>40 ft.</td>
</tr>
</tbody></table></ScrollContainer>
<section data-footnotes>
<h3 id="eq-armor-barding-label">Footnotes</h3>
<ol>
<li id="eq-armor-barding-H">
<p>A mount wearing heavy armor moves at only triple its normal speed when running instead of quadruple. <InnerLink id="backlink-eq-armor-barding-ref-H-1" data-hash-target to="eq-armor-barding-ref-H-1" aria-label="Back to reference H-1">↩</InnerLink></p>
</li>
</ol>
</section>
</>};
const _poh_armor = {title: "Poh armor", jsx: <><h2 id="eq-armor-poh_armor-poh-armor">Poh armor</h2>
<p><strong>Sources</strong> <Link to="/source/merchants_manifest">Merchant's Manifest pg. 24</Link><br/><strong>Price</strong> 500 gp; <strong>Weight</strong> 65 lbs.</p>
<p>Named after a ferocious unicorn-tiger hybrid, this suit of <Link to="/eq-armor/scale_mail">scale mail</Link> <Link to="/eq-armor/barding">barding</Link> bears a vicious horn on the forehead plate and metal tiger claws protruding from the poitrel. The armor is heavily reinforced to protect a horse's chest and neck. A horse wearing poh armor gains a gore attack as a secondary <Link to="/umr/natural_attack">natural attack</Link> that deals 1d8 points of damage. Additionally, a horse wearing poh armor deals 2d6 points of damage to any foe it knocks <Link to="/rule/prone">prone</Link> when using an <Link to="/rule/overrun">overrun</Link> combat maneuver. Poh armor otherwise functions like barding.</p>
<p>The price and weight listed is for poh armor for a Large mount. Poh armor for a Medium mount costs 250 gp and weighs 35 pounds. Poh armor slows a mount with a base speed of 40 feet to 30 feet, 50 feet to 35 feet, or 60 feet to 40 feet.</p>
</>};
const _hellknight_barding = {title: "Hellknight barding", jsx: <><h2 id="eq-armor-hellknight_barding-hellknight-barding">Hellknight barding</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_guide">Adventurer's Guide pg. 96</Link>, <Link to="/source/path_of_the_hellknight">Path of the Hellknight pg. 63</Link><br/><strong>Price</strong> varies; <strong>Weight</strong> varies  </p>
<p><Link to="/rule/hellknights">Hellknights</Link> often equip their steeds with armor similar to their own. Typical barding for Hellknight steeds is spiked (the spikes are ornamental, however, and cannot deal damage). Such barding is usually designed to look similar to the armor of the horse's rider, or to look skeletal, fiendish, or similar to a nightmare. Hellknight barding can be made from <Link to="/eq-armor/hellknight_leather">Hellknight leather</Link>, <Link to="/eq-armor/hellknight_plate">Hellknight plate</Link>, or <Link to="/eq-armor/hellknight_half_plate">Hellknight half-plate</Link>; it costs four times as much and weighs twice as much. Hellknight leather barding slows a mount from 40 feet to 30 feet, from 50 feet to 35 feet, or from 60 feet to 40 feet. Hellknight half-plate barding or Hellknight plate barding also slows a mount, and a mount wearing such armor moves at only triple its normal speed when running instead of quadruple.</p>
</>};
const _armored_kilt = {title: "Armored kilt", jsx: <><h2 id="eq-armor-armored_kilt-armored-kilt">Armored kilt</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory">Adventurer's Armory pg. 18</Link>, <Link to="/source/pathfinder_campaign_setting">Pathfinder Campaign Setting pg. 211</Link><br/><strong>Cost</strong> 20 gp <strong>Weight</strong> 10 lbs.<br/><strong>Armor Bonus</strong> +1; <strong>Max Dex Bonus</strong> +6; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 0%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Popular among the Keleshite soldiers of Qadira, the armored kilt is made of a thick cloth skirt with bars of steel hanging down from the waist and a ring of horizontal steel plates just above the hem. An armored kilt can be worn separately as light armor, or it can be added to other suits of light or medium armor. Adding an armored kilt increases a suit of armor's armor bonus by +1, but it lowers the maximum Dex bonus by 1, and increases the armor's weight category (from light to medium and from medium to heavy). Adding an armored kilt to heavy armor does not provide an armor bonus increase.</p>
</>};
const _haramaki = {title: "Haramaki", jsx: <><h2 id="eq-armor-haramaki-haramaki">Haramaki</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 3 gp <strong>Weight</strong> 1 lb.<br/><strong>Armor Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 0%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Also called a belly-warmer, a haramaki is a simple silken sash lined with chainmail or articulated metal plates and tied about the stomach to protect it.</p>
</>};
const _martial_arts_training_gear = {title: "Martial arts training gear", jsx: <><h2 id="eq-armor-martial_arts_training_gear-martial-arts-training-gear">Martial arts training gear</h2>
<p><strong>Sources</strong> <Link to="/source/merchants_manifest">Merchant's Manifest pg. 11</Link><br/><strong>Cost</strong> 45 gp <strong>Weight</strong> 5 lbs.<br/><strong>Armor Bonus</strong> +1; <strong>Max Dex Bonus</strong> +8; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 5%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This armor consists of several sections of curved padding held together by an assembly of leather straps. Meant to be worn during martial arts sparring contests, the armor absorbs blows from training weapons and unarmed strikes. The wearer reduces nonlethal damage caused by physical attacks, including natural attacks, by 2 points of damage. The wearer also ignores the first point of lethal bludgeoning damage from natural attacks.</p>
</>};
const _padded = {title: "Padded", jsx: <><h2 id="eq-armor-padded-padded">Padded</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 5 gp <strong>Weight</strong> 10 lbs.<br/><strong>Armor Bonus</strong> +1; <strong>Max Dex Bonus</strong> +8; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 5%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>More than simple clothing, padded armor combines heavy, quilted cloth and layers of densely packed stuffing to create a cheap and basic protection. It is typically worn by those not intending to face lethal combat or those who wish their maneuverability to be impacted as little as possible.</p>
</>};
const _quilted_cloth = {title: "Quilted cloth", jsx: <><h2 id="eq-armor-quilted_cloth-quilted-cloth">Quilted cloth</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide pg. 179</Link><br/><strong>Cost</strong> 100 gp <strong>Weight</strong> 15 lbs.<br/><strong>Armor Bonus</strong> +1; <strong>Max Dex Bonus</strong> +8; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 10%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This enhanced form of padded armor has internal layers specifically designed to trap arrows, bolts, darts, shuriken, thrown daggers, and other small ranged piercing weapons. When these kinds of weapons strike you, they tend to become snagged in these layers and fail to harm you. Wearing quilted cloth armor gives you DR 3/- against attacks of this kind. The special layers of the armor have no effect on other kinds of weapons.</p>
</>};
const _reinforced_tunic = {title: "Reinforced tunic", jsx: <><h2 id="eq-armor-reinforced_tunic-reinforced-tunic">Reinforced tunic</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link><br/><strong>Cost</strong> 1 gp <strong>Weight</strong> 5 lbs.<br/><strong>Armor Bonus</strong> +1; <strong>Max Dex Bonus</strong> +5; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 5%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Sometimes called a leine, this belted tunic has thick cords woven through it that cover vital areas. A reinforced tunic's armor bonus is increased by 2 against attack rolls made to confirm critical hits against the wearer.</p>
</>};
const _silken_ceremonial = {title: "Silken ceremonial", jsx: <><h2 id="eq-armor-silken_ceremonial-silken-ceremonial">Silken ceremonial</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 129</Link><br/><strong>Cost</strong> 30 gp <strong>Weight</strong> 4 lbs.<br/><strong>Armor Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 0%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Used for ceremonial displays or occasionally worn (albeit with no additional benefit) over heavier armor, these robes consist of several layers of cloth and an outer layer of silk intricately woven with gold brocade designs and covered with metal studs.</p>
</>};
const _lamellar_cuirass = {title: "Lamellar cuirass", jsx: <><h2 id="eq-armor-lamellar_cuirass-lamellar-cuirass">Lamellar cuirass</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 15 gp <strong>Weight</strong> 8 lbs.<br/><strong>Armor Bonus</strong> +2; <strong>Max Dex Bonus</strong> +4; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 5%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This armor consists of a light breastplate and shoulder guards made from lacquered leather plates bound together and fitted over a silk shirt.</p>
</>};
const _leather = {title: "Leather", jsx: <><h2 id="eq-armor-leather-leather">Leather</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 10 gp <strong>Weight</strong> 15 lbs.<br/><strong>Armor Bonus</strong> +2; <strong>Max Dex Bonus</strong> +6; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 10%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Leather armor is made up of multiple overlapping pieces of leather, boiled to increase their natural toughness and then deliberately stitched together. Although not as sturdy as metal armor, the flexibility it allows wearers makes it among the most widely used types of armor.</p>
</>};
const _rosewood_armor = {title: "Rosewood armor", jsx: <><h2 id="eq-armor-rosewood_armor-rosewood-armor">Rosewood armor</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory">Adventurer's Armory pg. 18</Link>, <Link to="/source/pathfinder_campaign_setting">Pathfinder Campaign Setting pg. 211</Link>, <Link to="/source/conquest_of_bloodsworn_vale">Conquest of Bloodsworn Vale pg. 32</Link><br/><strong>Cost</strong> 50 gp <strong>Weight</strong> 15 lbs.<br/><strong>Armor Bonus</strong> +2; <strong>Max Dex Bonus</strong> +6; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 10%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This suit of leather armor is wrapped in special rose vines. Treat this as <Link to="/eq-armor/leather_armor">leather armor</Link> with <Link to="/eq-armorenh/armor_spikes">armor spikes</Link>. The vines must be watered with at least 1 gallon of water each day or they wither and die, turning the armor into normal leather armor.</p>
</>};
const _varisian_dancing_scarves = {title: "Varisian dancing scarves", jsx: <><h2 id="eq-armor-varisian_dancing_scarves-varisian-dancing-scarves">Varisian dancing scarves</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link><br/><strong>Cost</strong> 150 gp <strong>Weight</strong> 8 lbs.<br/><strong>Armor Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> &mdash;%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This set of colorful scarves, is made of heavy silk and reinforced with leather straps. As you move, they flutter and flow, obscuring your shape and protecting against enemy attacks. Varisian dancing scarves provide no benefit while you are standing still. Whenever you move at least 10 feet during your turn, you gain a +2 armor bonus to AC until the beginning of your next turn. Varisian dancing scarves add their enhancement bonus to this armor bonus instead of providing a constant benefit; other magical enhancements (such as <Link to="/magic-enh/light_fortification">light fortification</Link>) apply whether or not you are moving. In addition, Varisian dancing scarves provide a +2 circumstance bonus on Bluff checks made to <Link to="/rule/feint">feint</Link> in combat.</p>
</>};
const _hellknight_leather = {title: "Hellknight leather", jsx: <><h2 id="eq-armor-hellknight_leather-hellknight-leather">Hellknight leather</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_guide">Adventurer's Guide pg. 96</Link>, <Link to="/source/path_of_the_hellknight">Path of the Hellknight pg. 63</Link><br/><strong>Cost</strong> 30 gp <strong>Weight</strong> 25 lbs.<br/><strong>Armor Bonus</strong> +3; <strong>Max Dex Bonus</strong> +5; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 15%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>There are instances where wearing full plate armor can jeopardize a Hellknight's life. Primarily worn by <Link to="/rule/hellknights">Hellknight</Link> sailors, this studded leather armor includes heavy gloves and a helm of sculpted leather designed to look like a skull: either a human's or that of some aquatic creature. Hellknight leather's statistics are identical to those of <Link to="/eq-armor/studded_leather">studded leather</Link>, except it costs 5 gp more and weighs 5 pounds more.</p>
</>};
const _hide_shirt = {title: "Hide shirt", jsx: <><h2 id="eq-armor-hide_shirt-hide-shirt">Hide shirt</h2>
<p><strong>Sources</strong> <Link to="/source/varisia_birthplace_of_legends">Varisia, Birthplace of Legends pg. 14</Link>, <Link to="/source/rise_of_the_runelords_players_guide">Rise of the Runelords Player's Guide pg. 11</Link>, <Link to="/source/curse_of_the_crimson_throne_players_guide">Curse of the Crimson Throne Player's Guide pg. 13</Link><br/><strong>Cost</strong> 20 gp <strong>Weight</strong> 18 lbs.<br/><strong>Armor Bonus</strong> +3; <strong>Max Dex Bonus</strong> +4; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 15%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Made from animal hide and giant lizard scales over a shirt of interwoven cords, these chest and shoulder coverings protect Shoanti riders without restricting their mobility. The wearer of a hide shirt can make a DC 15 Strength check as a standard action. If he succeeds, the armor gains the <Link to="/misc/broken">broken</Link> condition and drops to the ground rather than requiring the usual 1 minute it would take to remove it. The armor must be repaired as though it had taken 8 points of damage before it can be used again; a broken hide shirt grants no bonus to Armor Class.</p>
</>};
const _leaf_armor = {title: "Leaf armor", jsx: <><h2 id="eq-armor-leaf_armor-leaf-armor">Leaf armor</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_world_guide">Inner Sea World Guide pg. 291</Link>, <Link to="/source/adventurers_armory">Adventurer's Armory pg. 18</Link>, <Link to="/source/gallery_of_evil">Gallery of Evil pg. 31</Link>, <Link to="/source/pathfinder_campaign_setting">Pathfinder Campaign Setting pg. 211</Link><br/><strong>Cost</strong> 500 gp <strong>Weight</strong> 20 lbs.<br/><strong>Armor Bonus</strong> +3; <strong>Max Dex Bonus</strong> +5; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 15%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Druidic elves use alchemical compounds to treat special leaves used in crafting armor for their warriors. Leaf armor is always of masterwork quality.</p>
</>};
const _parade = {title: "Parade", jsx: <><h2 id="eq-armor-parade-parade">Parade</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/adventurers_armory">Adventurer's Armory pg. 5</Link><br/><strong>Cost</strong> 25 gp <strong>Weight</strong> 20 lbs.<br/><strong>Armor Bonus</strong> +3; <strong>Max Dex Bonus</strong> +5; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 15%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Most wealthy countries with standing armies have a different uniform for use in showy noncombat situations such as parades, coronation ceremonies, and so on. The appearance of this armor varies by the country of origin and the branch of the military, but still provides some protection in case the soldier needs to fight while in parade dress. For example, one country's parade armor may be a chain shirt, tabard, leather greaves, and a winged helm. If you're wearing a country's parade armor, you gain a +2 circumstance bonus on Diplomacy and Intimidate checks to influence a person from that country. Depending on the country, parade armor may be crafted from leather, metal, or a mixture of both.</p>
</>};
const _spider_silk_bodysuit = {title: "Spider-silk bodysuit", jsx: <><h2 id="eq-armor-spider_silk_bodysuit-spider-silk-bodysuit">Spider-silk bodysuit</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link><br/><strong>Cost</strong> 850 gp <strong>Weight</strong> 4 lbs.<br/><strong>Armor Bonus</strong> +3; <strong>Max Dex Bonus</strong> +6; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 10%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This exotic form-fitting garment is woven entirely from alchemically treated silk harvested from giant spiders or other arachnid creatures. If you have the <Link to="/race/drow">drow's</Link> weapon familiarity racial trait, you treat the spider-silk bodysuit's maximum Dexterity bonus as 2 higher.</p>
</>};
const _studded_leather = {title: "Studded leather", jsx: <><h2 id="eq-armor-studded_leather-studded-leather">Studded leather</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 25 gp <strong>Weight</strong> 20 lbs.<br/><strong>Armor Bonus</strong> +3; <strong>Max Dex Bonus</strong> +5; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 15%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>An improved form of <Link to="/eq-armor/leather">leather</Link> armor, studded leather armor is covered with dozens of metal protuberances. While these rounded studs offer little defense individually, in the numbers they are arrayed in upon such armor, they help catch lethal edges and channel them away from vital spots. The rigidity caused by the additional metal does, however, result in less mobility than is afforded by a suit of normal leather armor.</p>
</>};
const _wooden = {title: "Wooden", jsx: <><h2 id="eq-armor-wooden-wooden">Wooden</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide pg. 179</Link><br/><strong>Cost</strong> 20 gp <strong>Weight</strong> 25 lbs.<br/><strong>Armor Bonus</strong> +3; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 15%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>This suit of leather armor has plates of fire-treated wood sewn over vital areas. Though not as effective as metal armor, it offers better protection than leather alone. Unlike metal armor, the wood is slightly buoyant, and the armor check penalty for swimming in this armor is 0.</p>
</>};
const _chain_shirt = {title: "Chain shirt", jsx: <><h2 id="eq-armor-chain_shirt-chain-shirt">Chain shirt</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 100 gp <strong>Weight</strong> 25 lbs.<br/><strong>Armor Bonus</strong> +4; <strong>Max Dex Bonus</strong> +4; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 20%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Covering the torso, this shirt is made up of thousands of interlocking metal rings.</p>
</>};
const _lamellar_leather = {title: "Lamellar (leather)", jsx: <><h2 id="eq-armor-lamellar_leather-lamellar-leather">Lamellar (leather)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 60 gp <strong>Weight</strong> 25 lbs.<br/><strong>Armor Bonus</strong> +4; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 20%; <strong>Speed</strong> 30 ft./20 ft.<br/><strong>Category</strong> Light armor</p>
<p>Lamellar is a type of armor in which small plates of various types of materials are strung together in parallel rows using fine cord. Lamellar plates can be constructed from lacquered leather, horn, or even stone, though suits of iron and steel are the most common. Lamellar armor can be crafted into various shapes, including partial pieces such as breastplates, greaves, or even entire coats. The properties of specific suits and pieces of lamellar armor are determined by their material.</p>
</>};
const _armored_coat = {title: "Armored coat", jsx: <><h2 id="eq-armor-armored_coat-armored-coat">Armored coat</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide pg. 179</Link><br/><strong>Cost</strong> 50 gp <strong>Weight</strong> 20 lbs.<br/><strong>Armor Bonus</strong> +4; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 20%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>This sturdy leather coat is reinforced with metal plates sewn into the lining. An armored coat is more cumbersome than light armor but less effective than most medium armors. The advantage of it is that a person can don it or remove it as a move action (there is no "don hastily" option for an armored coat). If worn over other armor, use the better AC bonus and worse value in all other categories; an armored coat has no effect if worn with heavy armor. The only magic effects that apply are those of armor, clothing, or items worn on top.</p>
</>};
const _chain_coat = {title: "Chain coat", jsx: <><h2 id="eq-armor-chain_coat-chain-coat">Chain coat</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link><br/><strong>Cost</strong> 75 gp <strong>Weight</strong> 40 lbs.<br/><strong>Armor Bonus</strong> +4; <strong>Max Dex Bonus</strong> +5; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 30%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>This relatively simple armor consists of heavy chains that wrap around your body and limbs. While it weighs more and provides less protection than other medium armors, it is also less of a hindrance. In addition, if you are wielding a <Link to="/eq-weapon/spiked_chain">spiked chain</Link>, you can affix it to one hand. This functions as a <Link to="/eq-armorenh/locked_gauntlet">locked gauntlet</Link>, and if you are proficient with spiked chains, you can treat the spiked chain as a one-handed weapon while it is attached. You can affix a spiked chain to each hand this way, but you can't wear locked gauntlets while wearing a chain coat, and you can't attach any weapon to a chain coat except spiked chains.</p>
</>};
const _erutaki_coat = {title: "Erutaki coat", jsx: <><h2 id="eq-armor-erutaki_coat-erutaki-coat">Erutaki coat</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link><br/><strong>Cost</strong> 80 gp <strong>Weight</strong> 24 lbs.<br/><strong>Armor Bonus</strong> +4; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 20%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>Used by the Erutaki human tribes and snowcaster elves native to the arctic tundra of the Crown of the World, this heavy parka is treated as an <Link to="/eq-armor/armored_coat">armored coat</Link>. It provides the benefits of a <Link to="/eq-misc/cold_weather_outfit">cold-weather outfit</Link>, and it can be donned or removed as a move action. In addition, the fluffy white fur of the parka blends into arctic landscapes, providing a +2 circumstance bonus on Stealth checks in snowy environments.</p>
</>};
const _hide = {title: "Hide", jsx: <><h2 id="eq-armor-hide-hide">Hide</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 15 gp <strong>Weight</strong> 25 lbs.<br/><strong>Armor Bonus</strong> +4; <strong>Max Dex Bonus</strong> +4; <strong>Armor Check Penalty</strong> -3<br/><strong>Arcane Spell Failure Chance</strong> 20%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>Hide armor is made from the tanned skin of particularly thick-hided beasts, stitched with either multiple overlapping layers of crude leather or exterior pieces of leather stuffed with padding or fur. Damage to the armor is typically repaired by restitching gashes or adding new pieces of hide, giving the most heavily used suits a distinctively patchwork quality.</p>
</>};
const _do_maru = {title: "Do-maru", jsx: <><h2 id="eq-armor-do_maru-do-maru">Do-maru</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 200 gp <strong>Weight</strong> 30 lbs.<br/><strong>Armor Bonus</strong> +5; <strong>Max Dex Bonus</strong> +4; <strong>Armor Check Penalty</strong> -4<br/><strong>Arcane Spell Failure Chance</strong> 25%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>The lightest of armors typically favored by samurai, do-maru wraps around the wearer's body like a short armored coat. It consists primarily of lamellar and lacks a solid breastplate or sleeves, leaving the shoulders and upper body somewhat exposed, but permitting the wearer greater flexibility than do the majority of heavier armors.</p>
</>};
const _kikko = {title: "Kikko", jsx: <><h2 id="eq-armor-kikko-kikko">Kikko</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 250 gp <strong>Weight</strong> 25 lbs.<br/><strong>Armor Bonus</strong> +5; <strong>Max Dex Bonus</strong> +4; <strong>Armor Check Penalty</strong> -3<br/><strong>Arcane Spell Failure Chance</strong> 20%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>Kikko armor consists of a clever arrangement of hexagonal plates made from iron and sewn to cloth, granting the wearer greater flexibility than that provided by many armors that afford similar defense. The plates may be left exposed or hidden by a layer of cloth.</p>
</>};
const _lamellar_horn = {title: "Lamellar (horn)", jsx: <><h2 id="eq-armor-lamellar_horn-lamellar-horn">Lamellar (horn)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 100 gp <strong>Weight</strong> 30 lbs.<br/><strong>Armor Bonus</strong> +5; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -4<br/><strong>Arcane Spell Failure Chance</strong> 25%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>Lamellar is a type of armor in which small plates of various types of materials are strung together in parallel rows using fine cord. Lamellar plates can be constructed from lacquered leather, horn, or even stone, though suits of iron and steel are the most common. Lamellar armor can be crafted into various shapes, including partial pieces such as breastplates, greaves, or even entire coats. The properties of specific suits and pieces of lamellar armor are determined by their material.</p>
</>};
const _scale_mail = {title: "Scale mail", jsx: <><h2 id="eq-armor-scale_mail-scale-mail">Scale mail</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 50 gp <strong>Weight</strong> 30 lbs.<br/><strong>Armor Bonus</strong> +5; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -4<br/><strong>Arcane Spell Failure Chance</strong> 25%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>Scale mail is made up of dozens of small, overlapping metal plates. Similar to both <Link to="/eq-armor/splint_mail">splint mail</Link> and <Link to="/eq-armor/banded_mail">banded mail</Link>, scalemail has a flexible arrangement of scales in an attempt to avoid hindering the wearer's mobility, but at the expense of omitting additional protective layers of armor. A suit of scale mail includes gauntlets.</p>
</>};
const _agile_breastplate = {title: "Agile breastplate", jsx: <><h2 id="eq-armor-agile_breastplate-agile-breastplate">Agile breastplate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide pg. 179</Link><br/><strong>Cost</strong> 400 gp <strong>Weight</strong> 25 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -4<br/><strong>Arcane Spell Failure Chance</strong> 25%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>This breastplate is specially crafted in a manner that allows extra maneuverability for some physical activities. The armor check penalty for Climb checks and Acrobatics checks made to jump is only -1 (<Link to="/rule/masterwork_a">masterwork</Link> and <Link to="/eq-material/mithral">mithral</Link> versions of this armor reduce this penalty as well as the normal penalty).</p>
</>};
const _breastplate = {title: "Breastplate", jsx: <><h2 id="eq-armor-breastplate-breastplate">Breastplate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 200 gp <strong>Weight</strong> 30 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -4<br/><strong>Arcane Spell Failure Chance</strong> 25%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>A breastplate protects a wearer's torso with a single piece of sculpted metal, similar to the core piece of a suit of full plate. Despite its sturdiness, its inflexibility and open back make it inferior to complete suits of metal armor, but still an improvement over most non-metal armors.</p>
</>};
const _chainmail = {title: "Chainmail", jsx: <><h2 id="eq-armor-chainmail-chainmail">Chainmail</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 150 gp <strong>Weight</strong> 40 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +2; <strong>Armor Check Penalty</strong> -5<br/><strong>Arcane Spell Failure Chance</strong> 30%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>Unlike a chain shirt, which covers only the chest, chainmail protects the wearer with a complete mesh of chain links that cover the torso and arms, and extends below the waist. Multiple interconnected pieces offer additional protection over vital areas. The suit includes gauntlets.</p>
</>};
const _four_mirror = {title: "Four-mirror", jsx: <><h2 id="eq-armor-four_mirror-four-mirror">Four-mirror</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 125 gp <strong>Weight</strong> 45 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +2; <strong>Armor Check Penalty</strong> -5<br/><strong>Arcane Spell Failure Chance</strong> 30%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>This armor consists of four plates harnessed together with leather shoulder straps. Two round plates protect your front and back, while two smaller rectangular plates cover the sides of the torso. Four-mirror armor is worn over chainmail to provide added protection, and comes with a spiked helmet with a chainmail hood.</p>
</>};
const _lamellar_steel = {title: "Lamellar (steel)", jsx: <><h2 id="eq-armor-lamellar_steel-lamellar-steel">Lamellar (steel)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 150 gp <strong>Weight</strong> 35 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -5<br/><strong>Arcane Spell Failure Chance</strong> 25%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>Lamellar is a type of armor in which small plates of various types of materials are strung together in parallel rows using fine cord. Lamellar plates can be constructed from lacquered leather, horn, or even stone, though suits of iron and steel are the most common. Lamellar armor can be crafted into various shapes, including partial pieces such as breastplates, greaves, or even entire coats. The properties of specific suits and pieces of lamellar armor are determined by their material.</p>
</>};
const _mountain_pattern = {title: "Mountain pattern", jsx: <><h2 id="eq-armor-mountain_pattern-mountain-pattern">Mountain pattern</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 250 gp <strong>Weight</strong> 40 lbs.<br/><strong>Armor Bonus</strong> +6; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -4<br/><strong>Arcane Spell Failure Chance</strong> 30%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Medium armor</p>
<p>This medium armor consists of hundreds of small, interlocking pieces of steel shaped to resemble an ancient symbol for the word "mountain." The mail is then riveted to a cloth or leather backing. It is worn like a mail coat and covers your torso, shoulders, and thighs.</p>
</>};
const _banded_mail = {title: "Banded mail", jsx: <><h2 id="eq-armor-banded_mail-banded-mail">Banded mail</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 250 gp <strong>Weight</strong> 35 lbs.<br/><strong>Armor Bonus</strong> +7; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -6<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Banded mail is made up of overlapping strips of metal, fastened to a sturdy backing of leather and chain. The size of the metal plates, interconnected metal bands, and layers of underlying armor make it a more significant defense than similar armors, like <Link to="/eq-armor/scale_mail">scale mail</Link> or <Link to="/eq-armor/splint_mail">splint mail</Link>.</p>
</>};
const _field_plate = {title: "Field plate", jsx: <><h2 id="eq-armor-field_plate-field-plate">Field plate</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_world_guide">Inner Sea World Guide pg. 291</Link>, <Link to="/source/pathfinder_campaign_setting">Pathfinder Campaign Setting pg. 211</Link>, <Link to="/source/adventurers_armory">Adventurer's Armory pg. 18</Link><br/><strong>Cost</strong> 1,200 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +7; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -5<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>This heavy armor is similar to <Link to="/eq-armor/full_plate">full plate</Link> but lighter in construction, sacrificing a bit of protection for greater flexibility and mobility.</p>
</>};
const _kusari_gusoku = {title: "Kusari gusoku", jsx: <><h2 id="eq-armor-kusari_gusoku-kusari-gusoku">Kusari gusoku</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 350 gp <strong>Weight</strong> 45 lbs.<br/><strong>Armor Bonus</strong> +7; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Kusari gusoku is similar to <Link to="/eq-armor/tatami_do">tatami-do</Link> armor; however, a katabira (a type of chain jacket) is worn in place of the chest armor.</p>
</>};
const _lamellar_iron = {title: "Lamellar (iron)", jsx: <><h2 id="eq-armor-lamellar_iron-lamellar-iron">Lamellar (iron)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 200 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +7; <strong>Max Dex Bonus</strong> +0; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 40%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Lamellar is a type of armor in which small plates of various types of materials are strung together in parallel rows using fine cord. Lamellar plates can be constructed from lacquered leather, horn, or even stone, though suits of iron and steel are the most common. Lamellar armor can be crafted into various shapes, including partial pieces such as breastplates, greaves, or even entire coats. The properties of specific suits and pieces of lamellar armor are determined by their material.</p>
</>};
const _splint_mail = {title: "Splint mail", jsx: <><h2 id="eq-armor-splint_mail-splint-mail">Splint mail</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 200 gp <strong>Weight</strong> 45 lbs.<br/><strong>Armor Bonus</strong> +7; <strong>Max Dex Bonus</strong> +0; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 40%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Splint mail is made up of overlapping layers of metal strips attached to a backing of leather or sturdy fabric. These splints are of greater size and durability than those that compose a suit of <Link to="/eq-armor/scale_mail">scale mail</Link>, improving the protection they afford the wearer, but at the cost of flexibility. A suit of splint mail includes gauntlets.</p>
</>};
const _tatami_do = {title: "Tatami-do", jsx: <><h2 id="eq-armor-tatami_do-tatami-do">Tatami-do</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 129</Link><br/><strong>Cost</strong> 1,000 gp <strong>Weight</strong> 45 lbs.<br/><strong>Armor Bonus</strong> +7; <strong>Max Dex Bonus</strong> +3; <strong>Armor Check Penalty</strong> -6<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Worn by samurai as a lighter-weight alternative to <Link to="/eq-armor/o_yoroi">o-yoroi</Link>, tatami-do is a full-body field armor that combines both metal lamellar and kikko components into a suit of mail with a cloth backing. It typically includes a collapsible kabuto helmet or an armored hood, as well as arm, shoulder, and thigh guards.</p>
</>};
const _agile_half_plate = {title: "Agile half-plate", jsx: <><h2 id="eq-armor-agile_half_plate-agile-half-plate">Agile half-plate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide pg. 179</Link><br/><strong>Cost</strong> 850 gp <strong>Weight</strong> 55 lbs.<br/><strong>Armor Bonus</strong> +8; <strong>Max Dex Bonus</strong> +0; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 40%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>This style of <Link to="/eq-armor/half_plate">half-plate</Link> is specially crafted in a manner that allows extra maneuverability for some physical activities. The armor check penalty for Climb checks and jump checks is only -4 (<Link to="/rule/masterwork_a">masterwork</Link> and <Link to="/eq-material/mithral">mithral</Link> versions of this armor reduce this penalty as well as the normal penalty). In addition, unlike with most heavy armors, the wearer can still run at quadruple speed instead of triple speed.</p>
</>};
const _alkenstar_fortress_plate = {title: "Alkenstar fortress plate", jsx: <><h2 id="eq-armor-alkenstar_fortress_plate-alkenstar-fortress-plate">Alkenstar fortress plate</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link><br/><strong>Cost</strong> 2,100 gp <strong>Weight</strong> 75 lbs.<br/><strong>Armor Bonus</strong> +8; <strong>Max Dex Bonus</strong> +0; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 40%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>This <Link to="/race/dwarf">dwarf</Link>-forged armor features layers of overlapping plates molded to deflect projectiles - especially those from firearms. Whenever you are the target of a ranged weapon attack that would ignore your armor bonus to AC, you add half the fortress plate's armor bonus (including enhancement bonuses) to your AC against that attack. This benefit does not apply to energy attacks or magical touch attacks such as rays. Because the armor is designed with dwarves in mind, If you have the dwarf's weapon familiarity racial trait, you increase this projectile-only bonus by 1. Fortress plate is incredibly bulky, and its armor category can't be reduced by any effect (including by special materials, such as <Link to="/eq-material/mithral">mithral</Link>). Fortress plate includes gauntlets and a helm.</p>
</>};
const _half_plate = {title: "Half-plate", jsx: <><h2 id="eq-armor-half_plate-half-plate">Half-plate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 600 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +8; <strong>Max Dex Bonus</strong> +0; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 40%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Half-plate armor combines elements of <Link to="/eq-armor/full_plate">full plate</Link> and <Link to="/eq-armor/chainmail">chainmail</Link>, incorporating several sizable plates of sculpted metal with an underlying mesh of chain links. While this suit protects vital areas with several layers of armor, it is not sculpted to a single individual's frame, reducing its wearer's mobility even more than a suit of full plate. Half-plate armor includes gauntlets and a helm.</p>
</>};
const _hellknight_half_plate = {title: "Hellknight half-plate", jsx: <><h2 id="eq-armor-hellknight_half_plate-hellknight-half-plate">Hellknight half-plate</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_guide">Adventurer's Guide pg. 96</Link>, <Link to="/source/path_of_the_hellknight">Path of the Hellknight pg. 63</Link><br/><strong>Cost</strong> 850 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +8; <strong>Max Dex Bonus</strong> +0; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 40%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>The armor worn by a <Link to="/pclass/hellknight_signifer">Hellknight signifer</Link> is a vestment of armored plates, chain, and dark fabric. It functions as <Link to="/eq-armor/half_plate">half-plate</Link>, but it can be donned and removed as though it were medium armor. Any spellcaster who wears this armor is treated as if he were wearing Hellknight plate for the purposes of any feats and effects that require one to be wearing Hellknight plate. This armor includes a <Link to="/eq-misc/signifer_mask">signifer mask</Link>, though signifer masks can be purchased separately.</p>
</>};
const _lamellar_stone = {title: "Lamellar (stone)", jsx: <><h2 id="eq-armor-lamellar_stone-lamellar-stone">Lamellar (stone)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 500 gp <strong>Weight</strong> 45 lbs.<br/><strong>Armor Bonus</strong> +8; <strong>Max Dex Bonus</strong> +0; <strong>Armor Check Penalty</strong> -7<br/><strong>Arcane Spell Failure Chance</strong> 40%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Lamellar is a type of armor in which small plates of various types of materials are strung together in parallel rows using fine cord. Lamellar plates can be constructed from lacquered leather, horn, or even stone, though suits of iron and steel are the most common. Lamellar armor can be crafted into various shapes, including partial pieces such as breastplates, greaves, or even entire coats. The properties of specific suits and pieces of lamellar armor are determined by their material.</p>
</>};
const _o_yoroi = {title: "O-yoroi", jsx: <><h2 id="eq-armor-o_yoroi-o-yoroi">O-yoroi</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/ultimate_combat">Ultimate Combat pg. 128</Link><br/><strong>Cost</strong> 1,700 gp <strong>Weight</strong> 45 lbs.<br/><strong>Armor Bonus</strong> +8; <strong>Max Dex Bonus</strong> +2; <strong>Armor Check Penalty</strong> -6<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>Worn almost exclusively by highranking samurai, o-yoroi - or "great armor" - is a heavy combat armor that consists of various supplementary components that include both plate and lamellar elements. Each suit is crafted for a specific individual and displays the owner's aesthetic. Upon completion, the suit is colored and sealed with a final lacquer finish. The centerpiece of o-yoroi is a cuirass consisting of two parts - a separate reinforcement for the right side called a waidate, and a kikko cuirass. The upper part of the waidate consists of a leather-covered iron plate. The cuirass's leather shoulder straps - called watagami - are likewise armored with metal plates. Affixed to the cuirass are a number of supplementary pieces, including wide lamellar shoulder guards, a kikko sleeve for the shield arm, lacquered iron greaves worn over padded silk leggings, and a groin protector. The signature component of each suit of armor is the tiered kabuto helmet and its accompanying ho-ate mask. Ho-ate masks can be made of hardened leather or metal and are fashioned into fearsome visages such as oni, dragons, or other mythical beings.</p>
</>};
const _full_plate = {title: "Full plate", jsx: <><h2 id="eq-armor-full_plate-full-plate">Full plate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 1,500 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +9; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -6<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>This metal suit comprises multiple pieces of interconnected and overlaying metal plates, incorporating the benefits of numerous types of lesser armor. A complete suit of full plate (or platemail, as it is often called) includes gauntlets, heavy leather boots, a visored helmet, and a thick layer of padding that is worn underneath the armor. Each suit of full plate must be individually fitted to its owner by a master armorsmith, although a captured suit can be resized to fit a new owner at a cost of 200 to 800 (2d4 &times; 100) gold pieces.</p>
</>};
const _gray_maiden_plate = {title: "Gray maiden plate", jsx: <><h2 id="eq-armor-gray_maiden_plate-gray-maiden-plate">Gray maiden plate</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_guide">Adventurer's Guide pg. 84</Link><br/><strong>Cost</strong> 1,500 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +9; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -6<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>The <Link to="/rule/gray_maidens">Gray Maidens'</Link> distinctive armor is one of their most iconic identifiers. Gray Maiden plate is mechanically identical to <Link to="/eq-armor/full_plate">full plate</Link>, and any effect that functions with full plate functions with Gray Maiden plate. Certain options for Gray Maidens function only when they wear Gray Maiden plate.</p>
</>};
const _hellknight_plate = {title: "Hellknight plate", jsx: <><h2 id="eq-armor-hellknight_plate-hellknight-plate">Hellknight plate</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_guide">Adventurer's Guide pg. 97</Link>, <Link to="/source/inner_sea_world_guide">Inner Sea World Guide pg. 291</Link><br/><strong>Cost</strong> 2,000 gp <strong>Weight</strong> 50 lbs.<br/><strong>Armor Bonus</strong> +9; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -5<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 20 ft./15 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>These distinctive suits of armor are a special type of <Link to="/rule/masterwork_a">masterwork</Link> <Link to="/eq-armor/full_plate">full plate</Link> that grant additional effects when worn by a character with levels in the <Link to="/pclass/hellknight">Hellknight</Link> prestige class. Apart from its distinctive look (each order of <Link to="/rule/hellknights">Hellknights</Link> has its own style of armor), a suit of Hellknight plate functions the same as a suit of masterwork full plate.</p>
</>};
const _stoneplate = {title: "Stoneplate", jsx: <><h2 id="eq-armor-stoneplate-stoneplate">Stoneplate</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/inner_sea_world_guide">Inner Sea World Guide pg. 291</Link>, <Link to="/source/adventurers_armory">Adventurer's Armory pg. 19</Link>, <Link to="/source/pathfinder_campaign_setting">Pathfinder Campaign Setting pg. 211</Link><br/><strong>Cost</strong> 1,800 gp <strong>Weight</strong> 75 lbs.<br/><strong>Armor Bonus</strong> +9; <strong>Max Dex Bonus</strong> +1; <strong>Armor Check Penalty</strong> -6<br/><strong>Arcane Spell Failure Chance</strong> 35%; <strong>Speed</strong> 15 ft./10 ft.<br/><strong>Category</strong> Heavy armor</p>
<p>This armor is crafted by dwarven stonesmiths from alchemically strengthened plates of shale or basalt. Stoneplate is heavy and unwieldy, but offers incredible protection to its wearer. It is primarily used by dwarven druids who cannot wear metal armor.</p>
</>};
const _buckler = {title: "Buckler", jsx: <><h2 id="eq-armor-buckler-buckler">Buckler</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 5 gp <strong>Weight</strong> 5 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>This small metal shield is worn strapped to your forearm. You can use a bow or crossbow without penalty while carrying it. You can also use your shield arm to wield a weapon (whether you are using an off-hand weapon or using your off hand to help wield a two-handed weapon), but you take a -1 penalty on attack rolls while doing so. This penalty stacks with those that may apply for fighting with your off hand and for fighting with two weapons. In any case, if you use a weapon in your off hand, you lose the buckler's AC bonus until your next turn. You can cast a spell with somatic components using your shield arm, but you lose the buckler's AC bonus until your next turn. You can't make a <Link to="/misc/shield_bash">shield bash</Link> with a buckler.</p>
</>};
const _poisoners_buckler = {title: "Poisoner's Buckler", jsx: <><h2 id="eq-armor-poisoners_buckler-poisoners-buckler">Poisoner's Buckler</h2>
<p><strong>Sources</strong> <Link to="/source/heroes_from_the_fringe">Heroes from the Fringe pg. 23</Link><br/><strong>Cost</strong> 1,505 gp <strong>Weight</strong> 3 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> &mdash;<br/><strong>Arcane Spell Failure Chance</strong> &mdash;%</p>
<p>Half-drow make these bucklers to allow for quick application of exactly the right poison in the middle of combat. This <Link to="/eq-material/mithral">mithral</Link> <Link to="/eq-armor/buckler">buckler</Link> is painted black with three deep grooves running over the surface, each fitted with a slot that can hold a vial of poison. As a move action, the user can swipe a weapon over the surface of the buckler, coating it with a single dose of poison. The buckler can hold 3 doses of poison. If the wearer does not have the <Link to="/ability/poison_use">poison use</Link> ability, she faces the standard risk of poisoning herself.</p>
</>};
const _light_shield = {title: "Light Shield", notBookmarkable: true, jsx: <><h2 id="eq-armor-light_shield-light-shield">Light Shield</h2>
<p>"Light Shield" can refer to any of these shields.</p>
<ol>
<li><Link to="/eq-armor/light_wooden_shield">light wooden shield</Link><ul>
<li><Link to="/eq-armor/light_wooden_quickdraw_shield">light wooden quickdraw shield</Link></li>
</ul>
</li>
<li><Link to="/eq-armor/light_steel_shield">light steel shield</Link><ul>
<li><Link to="/eq-armor/light_steel_quickdraw_shield">light steel quickdraw shield</Link></li>
</ul>
</li>
<li><Link to="/eq-armor/leather_madu">leather madu</Link></li>
<li><Link to="/eq-armor/steel_madu">steel madu</Link></li>
<li><Link to="/eq-armor/dwarven_war_shield">dwarven war shield</Link></li>
<li><Link to="/eq-armor/klar">klar</Link></li>
</ol>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d2 (small), 1d3 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> Light; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _klar = {title: "Klar", jsx: <><h2 id="eq-armor-klar-klar">Klar</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/varisia_birthplace_of_legends">Varisia, Birthplace of Legends pg. 14</Link>, <Link to="/source/pathfinder_campaign_setting">Pathfinder Campaign Setting pg. 211</Link>, <Link to="/source/curse_of_the_crimson_throne_players_guide">Curse of the Crimson Throne Player's Guide pg. 13</Link>, <Link to="/source/rise_of_the_runelords_players_guide">Rise of the Runelords Player's Guide pg. 11</Link>, <Link to="/source/inner_sea_world_guide">Inner Sea World Guide pg. 291</Link>, <Link to="/source/adventurers_armory">Adventurer's Armory pg. 18</Link><br/><strong>Cost</strong> 12 gp <strong>Weight</strong> 6 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d4 (small), 1d6 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> S; <strong>Special</strong> see text<br/><strong>Category</strong> One-Handed; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Blades, Heavy; Close</p>
<p>The traditional form of this tribal weapon is a short blade bound to the skull of a large horned lizard, but a skilled smith can craft one entirely out of metal. A traditional klar counts as a <Link to="/eq-armor/light_wooden_shield">light wooden shield</Link> with <Link to="/eq-armorenh/armor_spikes">armor spikes</Link>; a metal klar counts as a <Link to="/eq-armor/light_steel_shield">light steel shield</Link> with armor spikes.</p>
</>};
const _light_steel_shield = {title: "Light steel shield", jsx: <><h2 id="eq-armor-light_steel_shield-light-steel-shield">Light steel shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 9 gp <strong>Weight</strong> 6 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>You strap a light steel shield to your forearm and grip it with your hand. A light steel shield's weight lets you carry other items in that hand, although you cannot use weapons with it. Whether wooden or steel, a light shield offers the same basic protection and attack benefits, though the two varieties respond differently to some spells and effects (such as <Link to="/spell/rusting_grasp">rusting grasp</Link>). A druid can use a <Link to="/eq-armor/light_wooden_shield">light wooden shield</Link>, but not a light steel shield.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d2 (small), 1d3 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> Light; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _light_steel_quickdraw_shield = {title: "Light steel quickdraw shield", jsx: <><h2 id="eq-armor-light_steel_quickdraw_shield-light-steel-quickdraw-shield">Light steel quickdraw shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide pg. 179</Link><br/><strong>Cost</strong> 59 gp <strong>Weight</strong> 7 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>This light steel shield is specially crafted with a series of straps to allow a character proficient in shields to ready or stow it on her back quickly and easily. If you have a base attack bonus of +1 or higher, you may don or put away a quickdraw shield as a swift action combined with a regular move. If you have the <Link to="/feat/two_weapon_fighting">Two-Weapon Fighting</Link> feat, you can draw a light or one-handed weapon with one hand and a quickdraw shield with the other in the time it would normally take you to draw one weapon. If you have the <Link to="/feat/quick_draw">Quick Draw</Link> feat, you may don or put away a quickdraw shield as a free action.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d2 (small), 1d3 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> Light; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _light_wooden_shield = {title: "Light wooden shield", jsx: <><h2 id="eq-armor-light_wooden_shield-light-wooden-shield">Light wooden shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 3 gp <strong>Weight</strong> 5 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>A light wooden shield is essentially the same as a <Link to="/eq-armor/light_steel_shield">light steel shield</Link>, except it responds differently to some spells and effects (such as <Link to="/spell/rusting_grasp">rusting grasp</Link>). A druid can use a light wooden shield, but not a light steel shield.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d2 (small), 1d3 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> Light; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _light_wooden_quickdraw_shield = {title: "Light wooden quickdraw shield", jsx: <><h2 id="eq-armor-light_wooden_quickdraw_shield-light-wooden-quickdraw-shield">Light wooden quickdraw shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/advanced_players_guide">Advanced Player's Guide pg. 179</Link><br/><strong>Cost</strong> 53 gp <strong>Weight</strong> 6 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>A wooden quickdraw shield is essentially the same as a <Link to="/eq-armor/light_steel_quickdraw_shield">steel quickdraw shield</Link>, except it responds differently to some spells and effects (such as <Link to="/spell/rusting_grasp">rusting grasp</Link>). A druid can use a light wooden quickdraw shield, but not a steel quickdraw shield.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d2 (small), 1d3 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> Light; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _madu_shield_leather = {title: "Madu shield (leather)", jsx: <><h2 id="eq-armor-madu_shield_leather-madu-shield-leather">Madu shield (leather)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/adventurers_armory">Adventurer's Armory pg. 5</Link>, <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide pg. 22</Link><br/><strong>Cost</strong> 40 gp <strong>Weight</strong> 5 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>The madu is a round, light leather shield with two animal horns - usually from an antelope - extending from opposite edges of the shield. If you are proficient with the madu, you may use it to <Link to="/misc/fight_defensively">fight defensively</Link> with a -2 penalty instead of the normal -4, and your attack penalty for using <Link to="/feat/combat_expertise">Combat Expertise</Link> improves by +1 (minimum -1 penalty). You cannot hold anything else in the hand that bears a madu. If you are not proficient with the madu, treat it as a <Link to="/eq-armor/light_wooden_shield">light shield</Link> with <Link to="/eq-armorenh/shield_spikes">spikes</Link>. A madu can't be disarmed. While traditional madus are crafted from leather and animal horn, they can be made entirely out of metal. Whether leather or steel, a madu offers the same basic protection and attack benefits, though the two varieties respond differently to some spells and effects (such as <Link to="/spell/rusting_grasp">rusting grasp</Link>). A druid can use a leather madu, but not a <Link to="/eq-armor/steel_madu">steel madu</Link>.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> P; <strong>Special</strong> <Link to="/misc/performance">performance</Link><br/><strong>Category</strong> Light; <strong>Proficiency</strong> Exotic<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Blades, Light; Close</p>
</>};
const _madu_shield_steel = {title: "Madu shield (steel)", jsx: <><h2 id="eq-armor-madu_shield_steel-madu-shield-steel">Madu shield (steel)</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/legacy_of_fire_players_guide">Legacy of Fire Player's Guide pg. 22</Link>, <Link to="/source/adventurers_armory">Adventurer's Armory pg. 5</Link><br/><strong>Cost</strong> 50 gp <strong>Weight</strong> 6 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>The madu is a round, light leather shield with two animal horns - usually from an antelope - extending from opposite edges of the shield. If you are proficient with the madu, you may use it to <Link to="/misc/fight_defensively">fight defensively</Link> with a -2 penalty instead of the normal -4, and your attack penalty for using <Link to="/feat/combat_expertise">Combat Expertise</Link> improves by +1 (minimum -1 penalty). You cannot hold anything else in the hand that bears a madu. If you are not proficient with the madu, treat it as a <Link to="/eq-armor/light_steel_shield">light shield</Link> with <Link to="/eq-armorenh/shield_spikes">spikes</Link>. A madu can't be disarmed. While traditional madus are crafted from leather and animal horn, they can be made entirely out of metal. Whether leather or steel, a madu offers the same basic protection and attack benefits, though the two varieties respond differently to some spells and effects (such as <Link to="/spell/rusting_grasp">rusting grasp</Link>). A druid can use a <Link to="/eq-armor/leather_madu">leather madu</Link>, but not a steel madu.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> P; <strong>Special</strong> <Link to="/misc/performance">performance</Link><br/><strong>Category</strong> Light; <strong>Proficiency</strong> Exotic<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Blades, Light; Close</p>
</>};
const _war_shield_dwarven = {title: "War-shield, dwarven", jsx: <><h2 id="eq-armor-war_shield_dwarven-war-shield-dwarven">War-shield, dwarven</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link><br/><strong>Cost</strong> 50 gp <strong>Weight</strong> 8 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -1<br/><strong>Arcane Spell Failure Chance</strong> 20%</p>
<p>This shield's sides are cut into jagged angles and honed to razor sharpness. Dwarven skirmishers often wield these shields in pairs, savagely hacking opponents to pieces, while some dwarven scoundrels enjoy the shields' imposing appearance and ease of use. If you have the <Link to="/feat/two_weapon_fighting">Two-Weapon Fighting</Link> feat and are wielding two dwarven war-shields, increase the higher of the two shield bonuses by 1. You lose this benefit for 1 round when you make a shield bash with one or both dwarven war-shields (unless you have the <Link to="/feat/improved_shield_bash">Improved Shield Bash</Link> feat or a similar benefit). A hand holding a dwarven warshield can't be used for anything else. A dwarven war-shield gains no benefit from <Link to="/eq-armorenh/shield_spikes">shield spikes</Link>.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a light shield. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d4 (small), 1d6 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> P or S; <strong>Special</strong> see text<br/><strong>Category</strong> Light; <strong>Proficiency</strong> Exotic<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close</p>
</>};
const _heavy_shield = {title: "Heavy Shield", notBookmarkable: true, jsx: <><h2 id="eq-armor-heavy_shield-heavy-shield">Heavy Shield</h2>
<p>"Heavy Shield" can refer to any of these shields.</p>
<ol>
<li><Link to="/eq-armor/heavy_wooden_shield">heavy wooden shield</Link></li>
<li><Link to="/eq-armor/heavy_steel_shield">heavy steel shield</Link></li>
<li><Link to="/eq-armor/wooden_snarlshield">wooden snarlshield</Link></li>
<li><Link to="/eq-armor/steel_snarlshield">steel snarlshield</Link></li>
</ol>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a heavy shield. Used this way, a heavy shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a heavy shield as a one-handed weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> One-Handed; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _heavy_steel_shield = {title: "Heavy steel shield", jsx: <><h2 id="eq-armor-heavy_steel_shield-heavy-steel-shield">Heavy steel shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 20 gp <strong>Weight</strong> 15 lbs.<br/><strong>Shield Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 15%</p>
<p>You strap a heavy steel shield to your forearm and grip it with your hand. A heavy steel shield is so heavy that you can't use your shield hand for anything else. Whether wooden or steel, a heavy shield offers the same basic protection and attack benefits, though the two versions respond differently to some spells and effects (such as <Link to="/spell/rusting_grasp">rusting grasp</Link>). A druid can use a <Link to="/eq-armor/heavy_wooden_shield">heavy wooden shield</Link>, but not a heavy steel shield.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a heavy shield. Used this way, a heavy shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a heavy shield as a one-handed weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> One-Handed; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _heavy_wooden_shield = {title: "Heavy wooden shield", jsx: <><h2 id="eq-armor-heavy_wooden_shield-heavy-wooden-shield">Heavy wooden shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 7 gp <strong>Weight</strong> 10 lbs.<br/><strong>Shield Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 15%</p>
<p>A heavy wooden shield is essentially the same as a <Link to="/eq-armor/heavy_steel_shield">heavy steel shield</Link>, except that it responds differently to some spells and effects (such as <Link to="/spell/rusting_grasp">rusting grasp</Link>). A druid can use a heavy wooden shield, but not a heavy steel shield.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a heavy shield. Used this way, a heavy shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a heavy shield as a one-handed weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> One-Handed; <strong>Proficiency</strong> Martial<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close; Tribal</p>
</>};
const _snarlshield_steel = {title: "Snarlshield, steel", jsx: <><h2 id="eq-armor-snarlshield_steel-snarlshield-steel">Snarlshield, steel</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link>, <Link to="/source/gnomes_of_golarion">Gnomes of Golarion pg. 22</Link><br/><strong>Cost</strong> 50 gp <strong>Weight</strong> 20 lbs.<br/><strong>Shield Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -3<br/><strong>Arcane Spell Failure Chance</strong> 15%</p>
<p>The snarlshield is a heavy shield that features a dozen rods protruding from its surface. When used as a weapon to bash an opponent, a snarlshield has the <Link to="/misc/disarm">disarm</Link> quality.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a heavy shield. Used this way, a heavy shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a heavy shield as a one-handed weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> One-Handed; <strong>Proficiency</strong> Exotic<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close</p>
</>};
const _snarlshield_wooden = {title: "Snarlshield, wooden", jsx: <><h2 id="eq-armor-snarlshield_wooden-snarlshield-wooden">Snarlshield, wooden</h2>
<p><strong>Sources</strong> <Link to="/source/adventurers_armory_2">Adventurer's Armory 2 pg. 6</Link>, <Link to="/source/gnomes_of_golarion">Gnomes of Golarion pg. 22</Link><br/><strong>Cost</strong> 37 gp <strong>Weight</strong> 15 lbs.<br/><strong>Shield Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -3<br/><strong>Arcane Spell Failure Chance</strong> 15%</p>
<p>The snarlshield is a heavy shield that features a dozen rods protruding from its surface. When used as a weapon to bash an opponent, a snarlshield has the <Link to="/misc/disarm">disarm</Link> quality.</p>
<p><strong className="hl">Shield Bash Attacks:</strong> You can bash an opponent with a heavy shield. Used this way, a heavy shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a heavy shield as a one-handed weapon. If you use your shield as a weapon, you lose its AC bonus until your next turn. An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.</p>
<p><strong>Damage</strong> 1d3 (small), 1d4 (medium); <strong>Critical</strong> &times;2; <strong>Range</strong> -; <strong>Type</strong> B; <strong>Special</strong> -<br/><strong>Category</strong> One-Handed; <strong>Proficiency</strong> Exotic<br/><strong><Link to="/ability/weapon_groups">Weapon Group</Link></strong> Close</p>
</>};
const _tower_shield = {title: "Tower shield", jsx: <><h2 id="eq-armor-tower_shield-tower-shield">Tower shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 9</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 151</Link><br/><strong>Cost</strong> 30 gp <strong>Weight</strong> 45 lbs.<br/><strong>Shield Bonus</strong> +4; <strong>Max Dex Bonus</strong> +2; <strong>Armor Check Penalty</strong> -10<br/><strong>Arcane Spell Failure Chance</strong> 50%</p>
<p>This massive wooden shield is nearly as tall as its user. In most situations, it provides the indicated shield bonus to your AC. As a standard action, however, you can use a tower shield to grant you <Link to="/rule/cover">total cover</Link> until the beginning of your next turn. When using a tower shield in this way, you must choose one edge of your space. That edge is treated as a solid wall for attacks targeting you only. You gain total cover for attacks that pass through this edge and no cover for attacks that do not pass through this edge (see <Link to="/rule/cover">cover</Link>). The shield does not, however, provide cover against targeted spells; a spellcaster can cast a spell on you by targeting the shield you are holding. You cannot bash with a tower shield, nor can you use your shield hand for anything else.</p>
<p>When employing a tower shield in combat, you take a -2 penalty on attack rolls because of the shield's encumbrance.</p>
</>};
const _living_steel_heavy_shield = {title: "Living Steel Heavy Shield", jsx: <><h2 id="eq-armor-living_steel_heavy_shield-living-steel-heavy-shield">Living Steel Heavy Shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 132</Link><br/><strong>Cost</strong> 30 gp <strong>Weight</strong> 15 lbs.<br/><strong>Shield Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> -2<br/><strong>Arcane Spell Failure Chance</strong> 15%</p>
<p>This nonmagical <Link to="/eq-armor/heavy_steel_shield">heavy steel shield</Link> is made out of <Link to="/eq-material/living_steel">living steel</Link>. It has no enhancement bonus, but its material and construction can damage metal weapons that strike it. Whenever the wielder of a metal weapon (other than one made of adamantine) rolls a natural 1 on an attack against a creature wielding this shield, the item must make a DC 20 Fortitude save or gain the <Link to="/misc/broken">broken</Link> condition. If the weapon already has the broken condition, it is instead destroyed.</p>
</>};
const _darkwood_buckler = {title: "Darkwood Buckler", jsx: <><h2 id="eq-armor-darkwood_buckler-darkwood-buckler">Darkwood Buckler</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 131</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 467</Link><br/><strong>Cost</strong> 203 gp <strong>Weight</strong> 2-1/2 lbs.<br/><strong>Shield Bonus</strong> +1; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>This nonmagical masterwork <Link to="/eq-armor/light_wooden_shield">light wooden shield</Link> is made out of <Link to="/eq-material/darkwood">darkwood</Link>. It has no enhancement bonus, but its construction material makes it lighter than a normal wooden shield. It has no armor check penalty.</p>
</>};
const _darkwood_shield = {title: "Darkwood Shield", jsx: <><h2 id="eq-armor-darkwood_shield-darkwood-shield">Darkwood Shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 131</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 467</Link><br/><strong>Cost</strong> 257 gp <strong>Weight</strong> 5 lbs.<br/><strong>Shield Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 15%</p>
<p>This nonmagical masterwork <Link to="/eq-armor/heavy_wooden_shield">heavy wooden shield</Link> is made out of <Link to="/eq-material/darkwood">darkwood</Link>. It has no enhancement bonus, but its construction material makes it lighter than a normal wooden shield. It has no armor check penalty.</p>
</>};
const _mithral_heavy_shield = {title: "Mithral Heavy Shield", jsx: <><h2 id="eq-armor-mithral_heavy_shield-mithral-heavy-shield">Mithral Heavy Shield</h2>
<p><strong>Sources</strong> <Link to="/source/ultimate_equipment">Ultimate Equipment pg. 132</Link>, <Link to="/source/prpg_core_rulebook">PRPG Core Rulebook pg. 467</Link><br/><strong>Cost</strong> 1,020 gp <strong>Weight</strong> 5 lbs.<br/><strong>Shield Bonus</strong> +2; <strong>Max Dex Bonus</strong> &mdash;; <strong>Armor Check Penalty</strong> 0<br/><strong>Arcane Spell Failure Chance</strong> 5%</p>
<p>This <Link to="/eq-armor/heavy_steel_shield">heavy shield</Link> is made of <Link to="/eq-material/mithral">mithral</Link> and is thus much lighter than a standard steel shield. It has a 5% arcane spell failure chance and no armor check penalty.</p>
</>};
export default {not_found:_not_found,mithral_shirt:_mithral_shirt,elven_chain:_elven_chain,adamantine_breastplate:_adamantine_breastplate,dragonhide_plate:_dragonhide_plate,dwarven_plate:_dwarven_plate,barding:_barding,poh_armor:_poh_armor,hellknight_barding:_hellknight_barding,armored_kilt:_armored_kilt,haramaki:_haramaki,martial_arts_training_gear:_martial_arts_training_gear,padded:_padded,quilted_cloth:_quilted_cloth,reinforced_tunic:_reinforced_tunic,silken_ceremonial:_silken_ceremonial,lamellar_cuirass:_lamellar_cuirass,leather:_leather,rosewood_armor:_rosewood_armor,varisian_dancing_scarves:_varisian_dancing_scarves,hellknight_leather:_hellknight_leather,hide_shirt:_hide_shirt,leaf_armor:_leaf_armor,parade:_parade,spider_silk_bodysuit:_spider_silk_bodysuit,studded_leather:_studded_leather,wooden:_wooden,chain_shirt:_chain_shirt,lamellar_leather:_lamellar_leather,armored_coat:_armored_coat,chain_coat:_chain_coat,erutaki_coat:_erutaki_coat,hide:_hide,do_maru:_do_maru,kikko:_kikko,lamellar_horn:_lamellar_horn,scale_mail:_scale_mail,agile_breastplate:_agile_breastplate,breastplate:_breastplate,chainmail:_chainmail,four_mirror:_four_mirror,lamellar_steel:_lamellar_steel,mountain_pattern:_mountain_pattern,banded_mail:_banded_mail,field_plate:_field_plate,kusari_gusoku:_kusari_gusoku,lamellar_iron:_lamellar_iron,splint_mail:_splint_mail,tatami_do:_tatami_do,agile_half_plate:_agile_half_plate,alkenstar_fortress_plate:_alkenstar_fortress_plate,half_plate:_half_plate,hellknight_half_plate:_hellknight_half_plate,lamellar_stone:_lamellar_stone,o_yoroi:_o_yoroi,full_plate:_full_plate,gray_maiden_plate:_gray_maiden_plate,hellknight_plate:_hellknight_plate,stoneplate:_stoneplate,buckler:_buckler,poisoners_buckler:_poisoners_buckler,light_shield:_light_shield,klar:_klar,light_steel_shield:_light_steel_shield,light_steel_quickdraw_shield:_light_steel_quickdraw_shield,light_wooden_shield:_light_wooden_shield,light_wooden_quickdraw_shield:_light_wooden_quickdraw_shield,madu_shield_leather:_madu_shield_leather,madu_shield_steel:_madu_shield_steel,war_shield_dwarven:_war_shield_dwarven,heavy_shield:_heavy_shield,heavy_steel_shield:_heavy_steel_shield,heavy_wooden_shield:_heavy_wooden_shield,snarlshield_steel:_snarlshield_steel,snarlshield_wooden:_snarlshield_wooden,tower_shield:_tower_shield,living_steel_heavy_shield:_living_steel_heavy_shield,darkwood_buckler:_darkwood_buckler,darkwood_shield:_darkwood_shield,mithral_heavy_shield:_mithral_heavy_shield}