import {IonIcon} from '@ionic/react';
import Link, {ThLink} from '../../components/Link';
import ScrollContainer from '../../components/ScrollContainer';
import InnerLink from '../../components/InnerLink';
const _not_found = {title: "Unknown", jsx: <><h2 id="drug-not_found-error">Error</h2>
<p>Unable to find the requested drug.</p>
</>};
const _keleshite_coffee = {title: "Keleshite Coffee", jsx: <><h2 id="drug-keleshite_coffee-keleshite-coffee">Keleshite Coffee</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-keleshite_coffee--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-keleshite_coffee--haunt-type">Type</th><td headers="drug-keleshite_coffee--haunt-type">ingested</td><th id="drug-keleshite_coffee--haunt-addict">Addiction</th><td headers="drug-keleshite_coffee--haunt-addict">minor, Fortitude DC 12</td></tr><tr><th scope="row">Price</th><td colSpan={3}>5 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>8 hours; user ignores the effects of the <Link to="/misc/fatigued">fatigued</Link> condition</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after 8 hours; the user becomes <Link to="/misc/exhausted">exhausted</Link>, and he becomes fatigued only after 8 hours of rest (instead of 1)</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1 Wis</td></tr></tbody></table></ScrollContainer></div><p>This particularly strong coffee is popular throughout the Padishah Empire of Kelesh, though it also has aficionados in Absalom, Oppara, and beyond. A morning cup is a good cure for lack of rest, but many find that it becomes a habit.</p>
</>};
const _flayleaf = {title: "Flayleaf", jsx: <><h2 id="drug-flayleaf-flayleaf">Flayleaf</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-flayleaf--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-flayleaf--haunt-type">Type</th><td headers="drug-flayleaf--haunt-type">Inhaled or ingested</td><th id="drug-flayleaf--haunt-addict">Addiction</th><td headers="drug-flayleaf--haunt-addict">minor, Fortitude DC 12</td></tr><tr><th scope="row">Price</th><td colSpan={3}>10 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +2 alchemical bonus on saves against mind-affecting effects, <Link to="/misc/fatigue">fatigue</Link></td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1 Wis</td></tr></tbody></table></ScrollContainer></div></>};
const _morgod_jelly = {title: "Morgod Jelly", jsx: <><h2 id="drug-morgod_jelly-morgod-jelly">Morgod Jelly</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_99_dance_of_the_damned">Pathfinder #99: Dance of the Damned pg. 86</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-morgod_jelly--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-morgod_jelly--haunt-type">Type</th><td headers="drug-morgod_jelly--haunt-type">Ingested or injury</td><th id="drug-morgod_jelly--haunt-addict">Addiction</th><td headers="drug-morgod_jelly--haunt-addict">special (see below), Fortitude DC 15</td></tr><tr><th scope="row">Price</th><td colSpan={3}>10 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d2 Cha and all creatures are considered to have <Link to="/rule/concealment">concealment</Link> against the user</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis and 1d2 Cha</td></tr></tbody></table></ScrollContainer></div><p>Morgod jelly causes vivid hallucinations and a sense of euphoria, and proves remarkably addictive to most humanoids. <Link to="/monster/morgodea">Morgodeas</Link> not only coat their stingers in this jelly, but also collect it in vials or wax-covered paper to sell to victims once they become addicted.</p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-morgod_jelly--table-1"><table><tbody><tr><ThLink scope="row" rowSpan={9} to="/rule/diseases"><IonIcon aria-label="Disease" icon="/icons/paramecia.svg" /></ThLink><th colSpan={4} scope="col" className="title">Morgod Addiction</th></tr><tr><th scope="row">Type</th><td colSpan={3}>Disease; variable</td></tr><tr><th scope="row">Save DC</th><td colSpan={3}>Will 15</td></tr><tr><th scope="row">Onset</th><td colSpan={3}>1 day</td></tr><tr><th scope="row">Frequency</th><td colSpan={3}>1/day</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>-2 penalty to Wis and Cha, target cannot naturally heal ability damage caused by morgod jelly</td></tr><tr><th scope="row">Cure</th><td colSpan={3}>3 consecutive saves</td></tr></tbody></table></ScrollContainer></div></>};
const _magesight = {title: "Magesight", jsx: <><h2 id="drug-magesight-magesight">Magesight</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-magesight--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-magesight--haunt-type">Type</th><td headers="drug-magesight--haunt-type">inhaled</td><th id="drug-magesight--haunt-addict">Addiction</th><td headers="drug-magesight--haunt-addict">minor, Fortitude DC 15</td></tr><tr><th scope="row">Price</th><td colSpan={3}>15 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d4 &times; 10 minutes; the user gains the benefits of a constant <Link to="/spell/detect_magic">detect magic</Link> effect, but she treats illumination in the area as <Link to="/rule/dim_light">dim light</Link>; areas of dim light and darkness are treated as darkness</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; the user gains the <Link to="/misc/dazzled">dazzled</Link> condition</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>Dilettantes pursue the visions from magesight simply for the wonder of the experience, while back-alley shopkeeps in Absalom, Katapesh, Katheer, and other major trade cities rely on it to provide a valuable ability they have no other way to obtain.</p>
</>};
const _muscaria = {title: "Muscaria", jsx: <><h2 id="drug-muscaria-muscaria">Muscaria</h2>
<p><strong>Sources</strong> <Link to="/source/pathfinder_110_the_thrushmoor_terror">Pathfinder #110: The Thrushmoor Terror pg. 14</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-muscaria--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-muscaria--haunt-type">Type</th><td headers="drug-muscaria--haunt-type">ingested</td><th id="drug-muscaria--haunt-addict">Addiction</th><td headers="drug-muscaria--haunt-addict">minor, Fortitude DC 14</td></tr><tr><th scope="row">Price</th><td colSpan={3}>15 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>3 hours; +1d6 alchemical bonus on a single Knowledge (any one), Perception, or Sense Motive check once per minute for the duration of the effect Onset 30 minutes</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Cha</td></tr></tbody></table></ScrollContainer></div><p>These small mushrooms, grown in dark forests, have red caps dotted with white spots. Able to induce strong hallucinogenic states, they have long been used by shamans and other spiritual leaders to enter trances to seek flashes of insight.</p>
</>};
const _pesh = {title: "Pesh", jsx: <><h2 id="drug-pesh-pesh">Pesh</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-pesh--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-pesh--haunt-type">Type</th><td headers="drug-pesh--haunt-type">Ingested or inhaled</td><th id="drug-pesh--haunt-addict">Addiction</th><td headers="drug-pesh--haunt-addict">moderate, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>15 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d2 alchemical bonus to Strength, -2 penalty on saves against illusions and mind-affecting effects</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after 1 hour; 1d2 hours of <Link to="/misc/fatigue">fatigue</Link></td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con and 1d2 Wis</td></tr></tbody></table></ScrollContainer></div></>};
const _vigilance = {title: "Vigilance", jsx: <><h2 id="drug-vigilance-vigilance">Vigilance</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-vigilance--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-vigilance--haunt-type">Type</th><td headers="drug-vigilance--haunt-type">ingested</td><th id="drug-vigilance--haunt-addict">Addiction</th><td headers="drug-vigilance--haunt-addict">moderate, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>15 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d3 hours; +10 alchemical bonus on Perception checks</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>4 hours; user is denied his Dexterity bonus to AC</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Con</td></tr></tbody></table></ScrollContainer></div><p>Scholars and students are often willing to accept the clumsiness and slow reactions in exchange for the benefits gained in research and study from this bitter white powder.</p>
</>};
const _aether = {title: "Aether", jsx: <><h2 id="drug-aether-aether">Aether</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-aether--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-aether--haunt-type">Type</th><td headers="drug-aether--haunt-type">inhaled</td><th id="drug-aether--haunt-addict">Addiction</th><td headers="drug-aether--haunt-addict">moderate, Fortitude DC 16</td></tr><tr><th scope="row">Price</th><td colSpan={3}>20 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1 caster level</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d4 hours; user must make a caster check to cast spells, DC 15 + spell level</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con</td></tr></tbody></table></ScrollContainer></div></>};
const _gossamer_veil = {title: "Gossamer Veil", jsx: <><h2 id="drug-gossamer_veil-gossamer-veil">Gossamer Veil</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 26</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-gossamer_veil--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-gossamer_veil--haunt-type">Type</th><td headers="drug-gossamer_veil--haunt-type">ingested</td><th id="drug-gossamer_veil--haunt-addict">Addiction</th><td headers="drug-gossamer_veil--haunt-addict">minor, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>20 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 day; +4 alchemical bonus on saving throws against disease effects</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after 1 day; -4 penalty on saving throws against disease effects for 7 days</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Wis</td></tr></tbody></table></ScrollContainer></div><p>Cultists of <Link to="/faith/ghlaunder">Ghlaunder</Link> and similar manipulators wander the streets of impoverished neighborhoods, administering this "vaccine" to prevent diseases common in squalid conditions, often with an admonition that it remains effective only as long as the recipient maintains faith in the priest's deity.</p>
</>};
const _slavers_drops = {title: "Slaver's Drops", jsx: <><h2 id="drug-slavers_drops-slavers-drops">Slaver's Drops</h2>
<p><strong>Sources</strong> <Link to="/source/rival_guide">Rival Guide pg. 53</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-slavers_drops--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-slavers_drops--haunt-type">Type</th><td headers="drug-slavers_drops--haunt-type">ingested</td><th id="drug-slavers_drops--haunt-addict">Addiction</th><td headers="drug-slavers_drops--haunt-addict">minor, Fortitude DC 13</td></tr><tr><th scope="row">Price</th><td colSpan={3}>20 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>3 hours; -3 on Will saves, +3 on Perception checks</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Str</td></tr></tbody></table></ScrollContainer></div><p>Dropped into the eyes, this clear liquid awakens the senses but makes the user mentally pliant and open to suggestion. This drug is often used during interrogations or by slavers who seek to force compliance via enchantment effects or similar methods of mind-control.</p>
</>};
const _bloodbrush_extract = {title: "Bloodbrush Extract", jsx: <><h2 id="drug-bloodbrush_extract-bloodbrush-extract">Bloodbrush Extract</h2>
<p><strong>Sources</strong> <Link to="/source/numeria_land_of_fallen_stars">Numeria, Land of Fallen Stars pg. 23</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-bloodbrush_extract--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-bloodbrush_extract--haunt-type">Type</th><td headers="drug-bloodbrush_extract--haunt-type">ingested</td><th id="drug-bloodbrush_extract--haunt-addict">Addiction</th><td headers="drug-bloodbrush_extract--haunt-addict">minor, Fortitude DC 14</td></tr><tr><th scope="row">Price</th><td colSpan={3}>25 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>2 hours; +2 on Knowledge (arcana, planes, or religion) and Spellcraft checks, victim is distracted for the purposes of <Link to="/skill/perception">Perception</Link> checks</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>Refined from the thorns of <Link to="/monster/bloodbrush">bloodbrush</Link>, this extract numbs the senses and evokes vivid hallucinations, heightened awareness, and altered thought processes. Although repeated doses can be toxic, bloodbrush extract is not widely used as a poison but rather as a recreational drug.</p>
</>};
const _opium = {title: "Opium", jsx: <><h2 id="drug-opium-opium">Opium</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-opium--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-opium--haunt-type">Type</th><td headers="drug-opium--haunt-type">Inhaled, ingested, or injury</td><th id="drug-opium--haunt-addict">Addiction</th><td headers="drug-opium--haunt-addict">severe, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>25 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d8 temporary hit points, +2 alchemical bonus on Fortitude saves, <Link to="/misc/fatigue">fatigue</Link></td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Con and 1d4 Wis</td></tr></tbody></table></ScrollContainer></div></>};
const _tears_of_razmir = {title: "Tears of Razmir", jsx: <><h2 id="drug-tears_of_razmir-tears-of-razmir">Tears of Razmir</h2>
<p><strong>Sources</strong> <Link to="/source/inner_sea_world_guide">Inner Sea World Guide pg. 293</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-tears_of_razmir--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-tears_of_razmir--haunt-type">Type</th><td headers="drug-tears_of_razmir--haunt-type">ingested</td><th id="drug-tears_of_razmir--haunt-addict">Addiction</th><td headers="drug-tears_of_razmir--haunt-addict">severe, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>25 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1 alchemical bonus to Constitution, -2 penalty on Wisdom-based skill checks</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con</td></tr></tbody></table></ScrollContainer></div><p>Razmir's faithful utilize a number of tools to help them control the populace, but few are more insidious than the tears of Razmir. This alchemical concoction contains mild narcotics and hallucinogens that bolster the user's energy and resistance to pain. It is also highly addictive. Although the clergy gives away tears of Razmir to non-users, it eventually demands payment - as much as 10 gp per dose from wealthy addicts.</p>
</>};
const _scour = {title: "Scour", jsx: <><h2 id="drug-scour-scour">Scour</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-scour--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-scour--haunt-type">Type</th><td headers="drug-scour--haunt-type">Ingested or inhaled</td><th id="drug-scour--haunt-addict">Addiction</th><td headers="drug-scour--haunt-addict">severe, Fortitude DC 24</td></tr><tr><th scope="row">Price</th><td colSpan={3}>45 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>3 hours; +1d4 alchemical bonus to Dexterity, -1d4 penalty to Wisdom</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d6 Con</td></tr></tbody></table></ScrollContainer></div></>};
const _stings_savor = {title: "Sting's Savor", jsx: <><h2 id="drug-stings_savor-stings-savor">Sting's Savor</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-stings_savor--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-stings_savor--haunt-type">Type</th><td headers="drug-stings_savor--haunt-type">injury</td><th id="drug-stings_savor--haunt-addict">Addiction</th><td headers="drug-stings_savor--haunt-addict">minor, Fortitude DC 15</td></tr><tr><th scope="row">Price</th><td colSpan={3}>45 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>user immediately heals 1d8+2 points of nonlethal damage</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d4 hours; an opponent who attempts a Bluff check to fool the user or a Diplomacy check to change the user's attitude can roll twice and take the better result</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>The "sting" administered to willing recipients at some <Link to="/faith/calistria">Calistrian</Link> temples helps nervous visitors relax. Black-market alchemists have reverse-engineered the drug to meet demand from less savory individuals who appreciate the pliability it elicits in users.</p>
</>};
const _dwarven_fire_ale = {title: "Dwarven Fire Ale", jsx: <><h2 id="drug-dwarven_fire_ale-dwarven-fire-ale">Dwarven Fire Ale</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-dwarven_fire_ale--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-dwarven_fire_ale--haunt-type">Type</th><td headers="drug-dwarven_fire_ale--haunt-type">ingested</td><th id="drug-dwarven_fire_ale--haunt-addict">Addiction</th><td headers="drug-dwarven_fire_ale--haunt-addict">moderate, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>50 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d4 rounds; <Link to="/spell/rage">rage</Link> as per the spell</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; cold resistance 5</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con</td></tr></tbody></table></ScrollContainer></div></>};
const _serpents_kiss = {title: "Serpent's Kiss", jsx: <><h2 id="drug-serpents_kiss-serpents-kiss">Serpent's Kiss</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-serpents_kiss--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-serpents_kiss--haunt-type">Type</th><td headers="drug-serpents_kiss--haunt-type">ingested</td><th id="drug-serpents_kiss--haunt-addict">Addiction</th><td headers="drug-serpents_kiss--haunt-addict">moderate, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>50 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +2 alchemical bonus on Bluff, Diplomacy, and Intimidate checks</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after 1 hour; the user gains the <Link to="/misc/fatigued">fatigued</Link> condition for 1d4 hours</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Dex</td></tr></tbody></table></ScrollContainer></div><p>Relied upon by politicians and shy noble scions, this emerald syrup boosts the user's confidence, allowing her to navigate social situations with aplomb, though the tremor it imparts to her hands can cause an unseemly clatter of cutlery or stemware.</p>
</>};
const _zerk = {title: "Zerk", jsx: <><h2 id="drug-zerk-zerk">Zerk</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-zerk--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-zerk--haunt-type">Type</th><td headers="drug-zerk--haunt-type">injury</td><th id="drug-zerk--haunt-addict">Addiction</th><td headers="drug-zerk--haunt-addict">minor, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>50 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1 alchemical bonus to initiative. If addicted, the user also gains a +1d4 alchemical bonus to Strength for as long as he is addicted</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con</td></tr></tbody></table></ScrollContainer></div></>};
const _ruk_tar = {title: "Ruk Tar", jsx: <><h2 id="drug-ruk_tar-ruk-tar">Ruk Tar</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-ruk_tar--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-ruk_tar--haunt-type">Type</th><td headers="drug-ruk_tar--haunt-type">injury</td><th id="drug-ruk_tar--haunt-addict">Addiction</th><td headers="drug-ruk_tar--haunt-addict">moderate, Fortitude DC 25</td></tr><tr><th scope="row">Price</th><td colSpan={3}>55 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +2 alchemical bonus to Strength and immunity to pain effects</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after 1 hour; the user gains the <Link to="/misc/exhausted">exhausted</Link> condition</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Int</td></tr></tbody></table></ScrollContainer></div><p>Common among desperate adventurers, gladiatorial combatants, and orc tribes, ruk tar is often applied after the first blood of a fight is spilled, using the wound as an opportunity to enhance the user's abilities to ensure victory.</p>
</>};
const _harlot_sweets = {title: "Harlot Sweets", jsx: <><h2 id="drug-harlot_sweets-harlot-sweets">Harlot Sweets</h2>
<p><strong>Sources</strong> <Link to="/source/rival_guide">Rival Guide pg. 53</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-harlot_sweets--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-harlot_sweets--haunt-type">Type</th><td headers="drug-harlot_sweets--haunt-type">ingested</td><th id="drug-harlot_sweets--haunt-addict">Addiction</th><td headers="drug-harlot_sweets--haunt-addict">moderate, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>60 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d4 Cha and +1 Dex damage</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Int</td></tr></tbody></table></ScrollContainer></div><p>These amber-colored lozenges instill within the user a slightly increased agility and enhance both physical beauty and speech. So named for the fact that prostitutes often abuse the drug, harlot sweets are gaining popularity among certain circles in the aristocracy as well.</p>
</>};
const _inspiration_dust = {title: "Inspiration Dust", jsx: <><h2 id="drug-inspiration_dust-inspiration-dust">Inspiration Dust</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 26</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-inspiration_dust--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-inspiration_dust--haunt-type">Type</th><td headers="drug-inspiration_dust--haunt-type">inhaled</td><th id="drug-inspiration_dust--haunt-addict">Addiction</th><td headers="drug-inspiration_dust--haunt-addict">moderate, Fortitude DC 22</td></tr><tr><th scope="row">Price</th><td colSpan={3}>75 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>4 hours; +1d4 alchemical bonus on Knowledge, Linguistics, and Spellcraft checks</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after 4 hours; for 24 hours, the user takes a -4 penalty on <Link to="/skill/sense_motive">Sense Motive</Link> checks and assumes everything heard is a lie, but she can attempt a DC 20 Sense Motive check to determine if someone is telling the truth</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Wis</td></tr></tbody></table></ScrollContainer></div><p>The mind-opening properties of this translucent dust enable the user to process information and draw connections rapidly, though the accompanying paranoia can make it difficult to act effectively on the knowledge thus gleaned.</p>
</>};
const _fireskin_elixir = {title: "Fireskin elixir", jsx: <><h2 id="drug-fireskin_elixir-fireskin-elixir">Fireskin elixir</h2>
<p><strong>Sources</strong> <Link to="/source/blood_of_the_elements">Blood of the Elements pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-fireskin_elixir--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-fireskin_elixir--haunt-type">Type</th><td headers="drug-fireskin_elixir--haunt-type">ingested</td><th id="drug-fireskin_elixir--haunt-addict">Addiction</th><td headers="drug-fireskin_elixir--haunt-addict">severe, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>100 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 day; +10 alchemical bonus on Disguise checks to appear as an efreeti, -1 penalty on all saves</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>This elixir turns its imbiber fiery red, making it easier to pass as an <Link to="/monster/efreeti">efreeti</Link>. Unscrupulous efreet can sell <Link to="/eq-misc/fireskin_elixir">fireskin elixir</Link> to guests who have been barred from citizen-only districts and must rely on disguises. Fireskin is highly addictive. Many once-savvy merchants have fallen into destitution as they scrambled to maintain efreet favor and secure a steady supply of the drug.</p>
</>};
const _oblivion = {title: "Oblivion", jsx: <><h2 id="drug-oblivion-oblivion">Oblivion</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-oblivion--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-oblivion--haunt-type">Type</th><td headers="drug-oblivion--haunt-type">ingested</td><th id="drug-oblivion--haunt-addict">Addiction</th><td headers="drug-oblivion--haunt-addict">severe, Fortitude DC 26</td></tr><tr><th scope="row">Price</th><td colSpan={3}>100 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>a user under the effect of a <Link to="/spell/suggestion">suggestion</Link> spell can attempt another saving throw (with the effect's original DC) to shake off the spell's effect, but he loses all memories from the previous 1d4 hours, as per <Link to="/spell/modify_memory">modify memory</Link> but without the 5-minute limit</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 damage to a random ability score</td></tr></tbody></table></ScrollContainer></div><p>A less pure version of refined <Link to="/eq-poison/cytillesh_extract">cytillesh</Link>, oblivion retains the unpredictable side effects and highly addictive properties of the source material. Oblivion is common in Cassomir's slums and the Puddles district of Absalom.</p>
</>};
const _dreamtime_tea = {title: "Dreamtime Tea", jsx: <><h2 id="drug-dreamtime_tea-dreamtime-tea">Dreamtime Tea</h2>
<p><strong>Sources</strong> <Link to="/source/rival_guide">Rival Guide pg. 53</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-dreamtime_tea--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-dreamtime_tea--haunt-type">Type</th><td headers="drug-dreamtime_tea--haunt-type">ingested</td><th id="drug-dreamtime_tea--haunt-addict">Addiction</th><td headers="drug-dreamtime_tea--haunt-addict">moderate, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>120 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>2d12 minutes; <Link to="/misc/unconscious">unconscious</Link>, gain vivid dreams acting as the <Link to="/spell/augury">augury</Link> spell, but with only a 60% chance of receiving a meaningful reply</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d3 Wis</td></tr></tbody></table></ScrollContainer></div><p>This tea carries a complex aroma combining the unlikely mix of citrus and dung. Originally developed in Vudra from a mix of rare herbs and flowers, dreamtime tea is gaining popularity in many cities in the Inner Sea region, particularly among those who seek dreams as an escape from reality.</p>
</>};
const _blood_sap = {title: "Blood Sap", jsx: <><h2 id="drug-blood_sap-blood-sap">Blood Sap</h2>
<p><strong>Sources</strong> <Link to="/source/rival_guide">Rival Guide pg. 53</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-blood_sap--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-blood_sap--haunt-type">Type</th><td headers="drug-blood_sap--haunt-type">ingested</td><th id="drug-blood_sap--haunt-addict">Addiction</th><td headers="drug-blood_sap--haunt-addict">moderate, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>150 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>30 minutes; +1d4 Str and +1d3 <Link to="/rule/dex_damage">Dex damage</Link>, then slowed (as per the spell <Link to="/spell/slow">slow</Link>) for 3 hours</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Con</td></tr></tbody></table></ScrollContainer></div><p>Blood sap is distilled from the crimson sap exuded by a pale green vine native to swamplands in the Mwangi Expanse. Users of this deep red syrup justify the negative effects of the drug with their increased agility and strength. Blood sap addicts often display vividly red lips and teeth.</p>
</>};
const _synthetic_mumia = {title: "Synthetic mumia", jsx: <><h2 id="drug-synthetic_mumia-synthetic-mumia">Synthetic mumia</h2>
<p><strong>Sources</strong> <Link to="/source/undead_slayers_handbook">Undead Slayer's Handbook pg. 9</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-synthetic_mumia--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-synthetic_mumia--haunt-type">Type</th><td headers="drug-synthetic_mumia--haunt-type">Ingested or injury</td><th id="drug-synthetic_mumia--haunt-addict">Addiction</th><td headers="drug-synthetic_mumia--haunt-addict">moderate, Fortitude DC 14</td></tr><tr><th scope="row">Price</th><td colSpan={3}>150 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +2 alchemical bonus on saving throws against spells and effects with the curse or disease descriptor, fatigue</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>A laboratory-created version of the expensive and infamous Osirian drug <Link to="/drug/mumia">mumia</Link>, <Link to="/eq-misc/synthetic_mumia">synthetic mumia</Link> is a mixture of honey, embalming fluids, and various animal organs. The murky liquid comes enclosed in small packets made of intestine. Mumia and synthetic mumia may be taken interchangeably to stave off the effects of addiction to either substance, and is thus used by some mumia junkies hoping to quit their addiction.</p>
</>};
const _hush = {title: "Hush", jsx: <><h2 id="drug-hush-hush">Hush</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 26</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-hush--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-hush--haunt-type">Type</th><td headers="drug-hush--haunt-type">ingested</td><th id="drug-hush--haunt-addict">Addiction</th><td headers="drug-hush--haunt-addict">moderate, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>200 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d6 hours; the user gains sonic resistance 5, but must roll twice and take the worse result for Perception checks based on sound and increases her arcane spell failure chance by 5%</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Wis</td></tr></tbody></table></ScrollContainer></div><p>This slate-gray powder is often mixed into alcohol and consumed by those working in the noisy testing ranges at Alkenstar's Gunworks. Its similarity in appearance to gunpowder has led to more than a few fatal mishaps.</p>
</>};
const _starspore = {title: "Starspore", jsx: <><h2 id="drug-starspore-starspore">Starspore</h2>
<p><strong>Sources</strong> <Link to="/source/numeria_land_of_fallen_stars">Numeria, Land of Fallen Stars pg. 25</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-starspore--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-starspore--haunt-type">Type</th><td headers="drug-starspore--haunt-type">Ingested or inhaled</td><th id="drug-starspore--haunt-addict">Addiction</th><td headers="drug-starspore--haunt-addict">severe, Fortitude DC 15</td></tr><tr><th scope="row">Price</th><td colSpan={3}>300 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; gains darkvision with a range of 60 feet, the ability to see invisible creatures (as <Link to="/spell/see_invisibility">see invisibility</Link>), and vulnerability to sonic damage</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con and 1 Wisdom drain</td></tr></tbody></table></ScrollContainer></div><p>A resilient, iridescent mold that blooms with a peridot-colored encrustation before releasing invisible spores, starspore grows on <Link to="/eq-material/adamantine">adamantine</Link> and other <Link to="/eq-material/skymetal">skymetals</Link> as well as their alloys. It requires trace toxins found in the rains and water of Numeria to grow. Ingesting or inhaling starspore opens the mind, enhances the senses, and bestows a feeling of invulnerability upon the user, but these sensations come at a price.</p>
</>};
const _elven_absinthe = {title: "Elven Absinthe", jsx: <><h2 id="drug-elven_absinthe-elven-absinthe">Elven Absinthe</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-elven_absinthe--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-elven_absinthe--haunt-type">Type</th><td headers="drug-elven_absinthe--haunt-type">ingested</td><th id="drug-elven_absinthe--haunt-addict">Addiction</th><td headers="drug-elven_absinthe--haunt-addict">moderate, Fortitude DC 16</td></tr><tr><th scope="row">Price</th><td colSpan={3}>500 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d4 Cha damage</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Con</td></tr></tbody></table></ScrollContainer></div></>};
const _mumia = {title: "Mumia", jsx: <><h2 id="drug-mumia-mumia">Mumia</h2>
<p><strong>Sources</strong> <Link to="/source/lost_kingdoms">Lost Kingdoms pg. 22</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-mumia--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-mumia--haunt-type">Type</th><td headers="drug-mumia--haunt-type">Inhaled, ingested, or injury</td><th id="drug-mumia--haunt-addict">Addiction</th><td headers="drug-mumia--haunt-addict">severe, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>500 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d8 temporary hit points, +2 alchemical bonus on saving throws made against spells and effects with the curse or disease descriptor, <Link to="/misc/fatigue">fatigue</Link>. If the user is addicted for more than a week straight, she has a cumulative +5% chance of transforming into a <Link to="/monster/ghoul">ghoul</Link> every week she remains addicted.</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>Perhaps the strangest of the valuables removed from the dusty tombs of Osirion is the flesh of the dead itself. During the years of satrapy-dominated Osirion and later under the rule of Keleshite sultans, a highly prized royal physician of Osirian descent by the name of Merenfren used a previously unknown black, tar-like substance as an ingredient in numerous salves, potions, and pills she concocted to treat ailments and revitalize her wealthy clientele.</p>
<p>Calling the drug mumia, Merenfren managed to keep the key ingredient of her potent cure - all hidden from her patients until 2271 AR, when a rival scholar finally discovered her sinister secret: Mumia was nothing more than the flesh of carefully preserved corpses excavated from Osirian tombs. Even the sweet elixir that she sold as the "water of life" was merely a diluted substance derived from the body of a young child preserved in a jar of honey. Merenfren was quickly tried and executed for her crimes, including the desecration of the dead as well as tricking her noble patients into consuming the vile substance. However, it was too late to undo the chemist's discoveries - she had already left her mark on Osirian society by inspiring an entire subculture based on the trade and consumption of mumia. An extensive black market took hold in Osirion's grisly underworld, and even the Keleshite masters of Osirion continued to partake of the foul drug made from the dead. The mysterious disappearances of mumia addicts were often attributed to their contact with the Osirian criminal element rather than any of the drug's long-lasting side effects, but mumia sellers knew better and took care to not get hooked to the drug themselves.</p>
<p>Even today, mumia made from the bodies of properly prepared and aged corpses - as well as cheap, knock-off mumia made from the embalmed bodies of animals or the recently dead - fetches a fine price in the back alleys of Sothis and other major cities in northern Garund. An unscrupulous graverobber need not hawk only fineries and art anymore, but can profit immensely from the act of plundering mummified bodies as well if she knows where to pawn them.</p>
<p>Cheap, imitation mumia made from the recently deceased or improperly treated bodies has the same stats as mumia, but the benefits are rendered at 50% their normal potency and for half the duration.</p>
</>};
const _numerian_fluids = {hasJL:true,title: "Numerian Fluids", jsx: <><div className="jumpList" id="drug-numerian_fluids-jumplist"><h2>Jump to:</h2><ul><li><InnerLink toTop to="drug-numerian_fluids-numerian-fluids-side-effects">Numerian Fluids Side Effects</InnerLink></li></ul></div><h2 id="drug-numerian_fluids-numerian-fluids">Numerian Fluids</h2>
<p><strong>Sources</strong> <Link to="/source/numeria_land_of_fallen_stars">Numeria, Land of Fallen Stars pg. 28</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-numerian_fluids--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-numerian_fluids--haunt-type">Type</th><td headers="drug-numerian_fluids--haunt-type">ingested</td><th id="drug-numerian_fluids--haunt-addict">Addiction</th><td headers="drug-numerian_fluids--haunt-addict">minor, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>500 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d4 hours; +1d4 <Link to="/rule/wis_damage">Wis damage</Link>, roll on the <em>Numerian Fluids Side Effects</em> table</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after the initial 1d4 hours; -5 penalty to Perception and Sense Motive checks, -2 penalty on saving throws against mind-affecting effects for 2d4 hours</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con</td></tr></tbody></table></ScrollContainer></div><p>Over the centuries, strange fluids have seeped from the wreckage of Silver Mount and other crash sites. Engine fluid, coolant, hydraulic fluids, and stranger substances have mixed together, the chemicals further transformed by the strange radiations of the ship's drives. Fluids can be found in pools or springs, or collected as they drip from larger pieces of wreckage. Odd behavior in animal life or an abundance of mutations can indicate a nearby source of alien fluids. While many such fluids are no more magical or marvelous than crude oil - and often highly poisonous to humanoids - others have strange and sometimes desirable effects on biological life.</p>
<p>The elite of Numeria cultivate a taste for these latter fluids, ostensibly for the insights and pleasant fugues induced by some of the chemicals. Indeed, repeated exposure to such fluids leads first to addiction, then to dependency. Yet beyond these prosaic effects, the fluids of Numeria unleash change: alterations in mind and body both terrible and wonderful.</p>
<p>Numerian fluids are considered drugs. Initially, the fluids expand perception and insight, opening the mind to new sensations. This overstimulation gives way to mental fatigue, leaving the imbiber distracted and vulnerable to suggestion. A pleasant euphoria lasts as long as the drug's effects. Unlike most drugs, the effects of Numerian fluids can be negated with a successful DC 20 Fortitude saving throw. Success at this saving throw precludes the need to save against addiction, but also prevents the dose from countering the effects of addiction. A person partaking of Numerian fluids can open his mind and body to the fluid's effects, voluntarily forgoing a Fortitude save. Of course, this also entails accepting the risk of addiction and any side effects from the specific type of fluids consumed.</p>
<p>Each distinct dose of Numerian fluids requires a new roll for side effects, even if multiple doses were recovered from the same source. The inherent instability of the fluid contributes to this variability, as the fluids undergo further reactions even after collection. At the Game Master's option, fluids collected from the same source at the same time can have a higher chance of providing the same side effect. One option for handling such variation is to roll two d20s of different colors for each subsequent drink from a sample, adding one and subtracting the other from the previous result. Another option is rolling twice, and using the second result only if it matches the previous side effect. Either variant increases the potential value of a dose of Numerian fluids, and the potential for unintended consequences in the campaign.</p>
<p>At least 1 pint of Numerian fluids must be consumed to experience euphoria and expose the drinker to side effects. Smaller amounts leave the drinker slightly disoriented (no game effect). If a drinker consumes a full dose within a single 24-hour period, the drug takes effect when the final portion is consumed.</p>
<p>In addition to imparting normal addiction to the fluids, certain results also addict the imbiber to a particular side effect. This extra addiction and its strength are listed on the Numerian Fluids Side Effects table. Only rolling the same type of side effect for a dose of fluids alleviates this addiction. This is handled as a distinct case of addiction, rather than being grouped in with other addictions, as is normally the case. This special type of addiction has a frequency and a dose requirement of once per week, rather than once per day. If a given creature has to save against the effects of both general addiction and this special addiction on the same day, only roll for the more serious addiction that day.</p>
<p>Identifying the effects of a dose of Numerian fluids presents a challenge, as the composition of the fluids changes constantly. A successful DC 25 Craft (alchemy) check has a 75% chance of correctly identifying a fluid's effects on a specific drinker, and a 25% chance of misidentifying a random effect instead. The dose must be consumed within 1 hour for the results to remain accurate.</p>
<h3 id="drug-numerian_fluids-numerian-fluids-side-effects" data-hash-target>Numerian Fluids Side Effects</h3>
<ScrollContainer id="drug-numerian_fluids--table-1"><table>
<thead>
<tr>
<th>d%</th>
<th>Result</th>
</tr>
</thead>
<tbody><tr>
<td>01</td>
<td>The drinker's cellular structure breaks down, and her flesh dissolves off of her bones. The victim dies in 1 round unless a <Link to="/spell/limited_wish">limited wish</Link>, <Link to="/spell/regenerate">regenerate</Link> (not just the regeneration ability), or <Link to="/spell/wish">wish</Link> spell is administered. Immunity to <Link to="/rule/ability_drain">ability drain</Link> prevents death, but immunity to death effects or poison does not.</td>
</tr>
<tr>
<td>02-04</td>
<td>The drinker permanently loses a random sense (roll 1d4: 1-hearing, 2-sight, 3-smell, 4-taste). A regenerate spell restores lost smell or taste. Moderate addiction.</td>
</tr>
<tr>
<td>05-07</td>
<td>The drinker ages 2d10 years.</td>
</tr>
<tr>
<td>08-10</td>
<td>The drinker takes 2d6 points of damage to all ability scores (roll once for damage, apply it to each). If any score reaches 0, death results. If the imbiber survives, roll again for an additional side effect, rerolling a result of 15 or lower.</td>
</tr>
<tr>
<td>11-15</td>
<td>The drinker takes 2d4 points of drain to a random ability score.</td>
</tr>
<tr>
<td>16-20</td>
<td>The drinker takes 1d4 points of Intelligence damage and loses the ability to speak or write (but not to listen and read) for 1d4 days. Moderate addiction.</td>
</tr>
<tr>
<td>21-30</td>
<td>The drinker contracts a random form of <Link to="/rule/madness">insanity</Link> for 1d4 days.</td>
</tr>
<tr>
<td>31-35</td>
<td>The fluids impart 1d4 negative levels to the drinker (Fortitude DC 20 to remove).</td>
</tr>
<tr>
<td>36-40</td>
<td>The drinker is rendered <Link to="/misc/unconscious">unconscious</Link> until the effects of the dose wear off. Mild addiction.</td>
</tr>
<tr>
<td>41-50</td>
<td>The drinker is <Link to="/misc/nauseated">nauseated</Link> for 2d6&times;10 minutes.</td>
</tr>
<tr>
<td>51-60</td>
<td>The drinker is <Link to="/misc/sickened">sickened</Link> until the effects of the dose wear off.</td>
</tr>
<tr>
<td>61-65</td>
<td>The drinker is <Link to="/misc/fascinated">fascinated</Link> by visions of a far-off reality for 1d4 hours. An interruption that ends the fascination provokes incoherent anger (attack nearest creature) for 1d4 rounds. Strong addiction.</td>
</tr>
<tr>
<td>66-70</td>
<td>The drinker exudes an unpleasant odor, as the <Link to="/umr/stench">stench</Link> ability, for 24 hours.</td>
</tr>
<tr>
<td>71-75</td>
<td>The drinker gains increased empathy with mechanical minds for 24 hours, gaining a +10 bonus on Bluff, Diplomacy, Intimidate, and Sense Motive checks against androids and robots, but takes a -5 penalty on such checks against other creatures.</td>
</tr>
<tr>
<td>76-80</td>
<td>For 1d4 hours, the drinker is healed by a random energy type (acid, cold, electricity, fire, or sonic) instead of harmed. Being healed in this fashion <Link to="/misc/stagger">staggers</Link> the drinker for 1 round.</td>
</tr>
<tr>
<td>81-85</td>
<td>The drinker's skin thickens into armor-like plates. This gives a +2 bonus to natural armor and a -2 penalty to Dexterity. Multiple doses do not stack. It takes 1d4 months for the excess skin to slough off.</td>
</tr>
<tr>
<td>86-90</td>
<td>Roll twice. If the first result is below 20, add 20 to the result. If the second result is above 80, subtract 20 from the result. If the same side effect results on both rolls, apply it only once, but the drinker becomes severely addicted to that result.</td>
</tr>
<tr>
<td>91-92</td>
<td>The drinker gains <Link to="/umr/fast_healing">fast healing</Link> 5 for 24 hours, but must consume twice as much food and water as normal.</td>
</tr>
<tr>
<td>93-94</td>
<td>The drinker gains a +6 enhancement bonus to a random ability score for 2d4 days.</td>
</tr>
<tr>
<td>95-96</td>
<td>The drinker gains <Link to="/umr/telepathy">telepathy</Link> with a range of 100 feet for 2d4 days.</td>
</tr>
<tr>
<td>97</td>
<td>The drinker gains the ability to see possible futures a few seconds ahead for 24 hours. Because the visions are distracting, the drinker takes a -2 penalty on ability checks, attack rolls, saving throws, and skill checks, but for one such roll, she can ignore the penalty and roll twice, keeping the better result. The drinker must decide to use this ability before rolling.</td>
</tr>
<tr>
<td>98</td>
<td>The drinker becomes 1d6 years younger. If this changes her <Link to="/rule/age">age category</Link>, adjust physical attributes but not mental. Mental attributes don't increase when the original age category is reached again (see <Link to="/rule/young_characters">Young Characters</Link>).</td>
</tr>
<tr>
<td>99</td>
<td>The drinker foresees her death in a cryptic and disjointed vision. The next time an effect would cause her death, she can take an extra standard action just before she dies (including actions like healing spells that prevent the impending death).</td>
</tr>
<tr>
<td>100</td>
<td>Roll on the table below. All exceptional effects are permanent.</td>
</tr>
</tbody></table></ScrollContainer>
<h3 id="drug-numerian_fluids-exceptional-side-effects">Exceptional Side Effects</h3>
<ScrollContainer id="drug-numerian_fluids--table-2"><table>
<thead>
<tr>
<th>d10</th>
<th>Exceptional Side Effect</th>
</tr>
</thead>
<tbody><tr>
<td>1</td>
<td><strong>Immortality:</strong> The drinker no longer takes penalties for aging (bonuses still apply) and does not die from old age.</td>
</tr>
<tr>
<td>2</td>
<td><strong>Mutant:</strong> The drinker gains the <Link to="/template/mutant">mutant template</Link>. The mutations should reflect the drinker's inner personality, as determined by the GM.</td>
</tr>
<tr>
<td>3</td>
<td><strong>Phasing:</strong> The drinker gains the ability to become <Link to="/umr/incorporeal">incorporeal</Link> for 1d4 rounds as a swift action, but takes 1 point of Con damage when he does so. Phasing can be extended as a free action by taking 1 additional point of Con damage. Coming out of phase inside a solid object is instantly fatal. Phasing cannot be used by creatures that are immune to Con damage.</td>
</tr>
<tr>
<td>4</td>
<td><strong>Three-Dimensional Touch:</strong> The drinker gains <Link to="/umr/blindsense">blindsense</Link> with a range of 60 feet. Focusing on this sense as a move action improves it to <Link to="/umr/blindsight">blindsight</Link> with a range of 60 feet until the start of the drinker's next turn.</td>
</tr>
<tr>
<td>5</td>
<td><strong>Wings:</strong> The drinker grows a pair of bat-like wings that grant a fly speed of 30 feet and average maneuverability.</td>
</tr>
<tr>
<td>6</td>
<td><strong>Ability Score Bonus:</strong> The drinker gains a +2 inherent bonus to a random ability score.</td>
</tr>
<tr>
<td>7</td>
<td><strong>Fluid Generation:</strong> The drinker's body naturally creates its own approximation of Numerian fluids, which he can, as a standard action once a day, redirect into his system to gain the effects of drinking 1 dose of Numerian fluids. Treat the addiction, effects, and side effects of this dose as normal, save that it cannot provide an additional exceptional effect (reroll results of 100).</td>
</tr>
<tr>
<td>8</td>
<td><strong>Grounding Skin:</strong> The drinker grows a metal mesh surrounding his skin that grants him electricity resistance 10.</td>
</tr>
<tr>
<td>9</td>
<td><strong>Bioluminescence:</strong> The drinker's body glows as <Link to="/magic-wondrous/gem_of_brightness">gem of brightness</Link>. The drinker can produce this effect 5 times per day.</td>
</tr>
<tr>
<td>10</td>
<td><strong>Sleep of Experience:</strong> For 24 hours, the drinker falls into a coma and cannot be awakened. During this time, he dreams of living an entire lifetime on a different planet in an alien body. The drinker gains the number of bonus experience points needed to advance 1 level. A creature can gain this exceptional effect only once (reroll all future exceptional effect rolls of 10).</td>
</tr>
</tbody></table></ScrollContainer>
</>};
const _shiver = {title: "Shiver", jsx: <><h2 id="drug-shiver-shiver">Shiver</h2>
<p><strong>Sources</strong> <Link to="/source/gamemastery_guide">GameMastery Guide pg. 237</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-shiver--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-shiver--haunt-type">Type</th><td headers="drug-shiver--haunt-type">Injury or ingested</td><th id="drug-shiver--haunt-addict">Addiction</th><td headers="drug-shiver--haunt-addict">severe, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>500 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>variable; 50% chance to sleep for 1d4 hours or gain immunity to fear for 1d4 minutes</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Con</td></tr></tbody></table></ScrollContainer></div></>};
const _wyrm_pesh = {title: "Wyrm pesh", jsx: <><h2 id="drug-wyrm_pesh-wyrm-pesh">Wyrm pesh</h2>
<p><strong>Sources</strong> <Link to="/source/dragonslayers_handbook">Dragonslayer's Handbook pg. 19</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-wyrm_pesh--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-wyrm_pesh--haunt-type">Type</th><td headers="drug-wyrm_pesh--haunt-type">Ingested or inhaled</td><th id="drug-wyrm_pesh--haunt-addict">Addiction</th><td headers="drug-wyrm_pesh--haunt-addict">severe, Fortitude DC 24</td></tr><tr><th scope="row">Price</th><td colSpan={3}>500 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; 25 temporary hit points</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 day; +2 alchemical bonus on saves against sleep and paralysis effects</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>This rare and expensive <Link to="/eq-misc/wyrm_pesh">variant</Link> of standard Garundi <Link to="/drug/pesh">pesh</Link> is produced by introducing a vial of dragon's blood into a dose of pesh during the refining process, and has a noticeable reddish tint. While the drug provides a more potent high and fewer immediate penalties, it is highly addictive, and unless a user has a steady supply of dragon's blood, the cost to her well-being can be severe.</p>
</>};
const _esoterum = {title: "Esoterum", jsx: <><h2 id="drug-esoterum-esoterum">Esoterum</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 26</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-esoterum--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-esoterum--haunt-type">Type</th><td headers="drug-esoterum--haunt-type">inhaled</td><th id="drug-esoterum--haunt-addict">Addiction</th><td headers="drug-esoterum--haunt-addict">severe, Fortitude DC 24</td></tr><tr><th scope="row">Price</th><td colSpan={3}>600 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>24 hours; the user gains the benefits of the <Link to="/feat/psychic_sensitivity">Psychic Sensitivity</Link> feat but takes a -4 penalty on Will saves and automatically fails Will saves against possession attempts</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Con and 1d4 Wis</td></tr></tbody></table></ScrollContainer></div><p>Legends tell of esoterum dens in Tian Xia and Vudra where dream chasers open their minds to the spirit world, gaining deep insights and abilities beyond mortal ken. Such tales usually continue to describe the destructive rampages that follow when malevolent spirits take advantage of an opened mind and possess the unfortunate individual.</p>
</>};
const _old_mage = {title: "Old-Mage", jsx: <><h2 id="drug-old_mage-old-mage">Old-Mage</h2>
<p><strong>Sources</strong> <Link to="/source/potions_and_poisons">Potions and Poisons pg. 27</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-old_mage--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-old_mage--haunt-type">Type</th><td headers="drug-old_mage--haunt-type">injury</td><th id="drug-old_mage--haunt-addict">Addiction</th><td headers="drug-old_mage--haunt-addict">severe, Fortitude DC 18</td></tr><tr><th scope="row">Price</th><td colSpan={3}>1500 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>12 hours; the user gains the ability to activate scrolls as if she had succeeded at a <Link to="/skill/use_magic_device">Use Magic Device</Link> check to activate a given scroll. Each time the user activates a scroll this way, she takes 1d4 points of <Link to="/rule/charisma_damage">Charisma damage</Link> and an amount of nonlethal damage equal to the scroll's caster level. Charisma damage taken this way is counted as ability damage caused by the drug for the purpose of calculating the DC of saving throws to resist addiction to the drug. Neither the Charisma damage nor the nonlethal damage can be healed until the user takes a full 8 hours of rest.</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>see Effects</td></tr></tbody></table></ScrollContainer></div><p>In higher circles of Avistani nobility, some petty nobles pretend to be mighty wizards. Typically created in and smuggled north from Sargava, old-mage offers a temporary taste of eldritch power at an exorbitant cost - both financial and physical.</p>
</>};
const _adyton = {title: "Adyton", jsx: <><h2 id="drug-adyton-adyton">Adyton</h2>
<p><strong>Sources</strong> <Link to="/source/book_of_the_damned">Book of the Damned pg. 183</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-adyton--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-adyton--haunt-type">Type</th><td headers="drug-adyton--haunt-type">contact</td><th id="drug-adyton--haunt-addict">Addiction</th><td headers="drug-adyton--haunt-addict">severe, Fortitude DC 20</td></tr><tr><th scope="row">Price</th><td colSpan={3}>2000 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>An affected creature that succeeds at an additional DC 20 Will saving throw has its consciousness transported into the <Link to="/rule/mindscapes">mindscape</Link> called the Adyton, where it can linger for as long as it likes and return as a full-round action whenever it so pleases. Those that fail this secondary saving throw sleep fitfully for 2d4 hours and wake remembering snippets of surreal dreams.</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Str</td></tr></tbody></table></ScrollContainer></div><p>The drug adyton is central to <Link to="/faith/mahathallah">Mahathallah's</Link> worship and the spreading of her mysteries. It can be purchased only from worshipers of Mahathallah, and typically only by servants of the goddess.</p>
</>};
const _felwil = {title: "Felwil", jsx: <><h2 id="drug-felwil-felwil">Felwil</h2>
<p><strong>Sources</strong> <Link to="/source/bastards_of_golarion">Bastards of Golarion pg. 21</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-felwil--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-felwil--haunt-type">Type</th><td headers="drug-felwil--haunt-type">inhaled</td><th id="drug-felwil--haunt-addict">Addiction</th><td headers="drug-felwil--haunt-addict">minor, Fortitude DC 13</td></tr><tr><th scope="row">Price</th><td colSpan={3}>20 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d2 alchemical bonus to Charisma, -2 penalty on saves against illusions</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>after 1 hour; 75% chance to become <Link to="/misc/sickened">sickened</Link> for 1d4 hours</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>The gnome prima donnas of Wispil in Taldor are thought to be the inventors of this mild, dizzying powder, but its use has spread throughout much of southern Avistan. Once taken, this sparkling, honeydew-colored inhalant gives the user a euphoric sensation that can quickly become overwhelming and even sickening. While the long-term effects are relatively minor, few except the hardy care to risk stomaching this toxin.</p>
</>};
const _silvertongue = {title: "Silvertongue", jsx: <><h2 id="drug-silvertongue-silvertongue">Silvertongue</h2>
<p><strong>Sources</strong> <Link to="/source/bastards_of_golarion">Bastards of Golarion pg. 21</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-silvertongue--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={5} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-silvertongue--haunt-type">Type</th><td headers="drug-silvertongue--haunt-type">ingested</td><th id="drug-silvertongue--haunt-addict">Addiction</th><td headers="drug-silvertongue--haunt-addict">moderate, Fortitude DC 16</td></tr><tr><th scope="row">Price</th><td colSpan={3}>75 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; +1d2 alchemical bonus to Charisma</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1d4 hours; +2 alchemical bonus on saves against mind-affecting effects</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d4 Con</td></tr></tbody></table></ScrollContainer></div><p>The potent performance enhancer known as silvertongue is a sweet alchemical elixir with a metallic aftertaste. A single dose loosens the lips and sharpens the wit. More than one begins to mark the user, and frequent use causes the imbiber's gums and tongue to take on a silvery sheen that advertises her habit.</p>
</>};
const _midnight_milk = {title: "Midnight Milk", jsx: <><h2 id="drug-midnight_milk-midnight-milk">Midnight Milk</h2>
<p><strong>Sources</strong> <Link to="/source/lost_cities_of_golarion">Lost Cities of Golarion pg. 12</Link></p>
<div className="sideNoteWrap startAlign"><ScrollContainer id="drug-midnight_milk--table-0"><table><tbody><tr><ThLink scope="row" rowSpan={4} to="/rule/drugs"><IonIcon aria-label="Drug" icon="/icons/syringe.svg" /></ThLink><th id="drug-midnight_milk--haunt-type">Type</th><td headers="drug-midnight_milk--haunt-type">ingested</td><th id="drug-midnight_milk--haunt-addict">Addiction</th><td headers="drug-midnight_milk--haunt-addict">moderate, Fortitude DC 16</td></tr><tr><th scope="row">Price</th><td colSpan={3}>50 gp</td></tr><tr><th scope="row">Effect</th><td colSpan={3}>1 hour; <Link to="/misc/fatigued">fatigued</Link>, plus the user takes a -4 penalty on all saving throws made to resist sleep effects. If the user falls asleep while under the effects of midnight milk, he dreams vividly; these dreams last for 1 hour per dose of midnight milk taken in the past month (including this one). Upon awakening, the user is revitalized as if he had enjoyed a full 8 hours of sleep.</td></tr><tr><th scope="row"><Link to="/rule/ability_damage">Damage</Link></th><td colSpan={3}>1d2 Wis</td></tr></tbody></table></ScrollContainer></div><p>While a <em>dream lens</em><sup><InnerLink showBacklink="backlink-drug-midnight_milk-ref-D-1" id="drug-midnight_milk-ref-D-1" data-hash-target to="drug-midnight_milk-D">1</InnerLink></sup> is active nearby, there's a 1% chance each time a user takes the drug that he ends up in a body already used by an <Link to="/monster/intellect_devourer">intellect devourer</Link> - this chance increases by 1% for each previous dose of midnight milk the user has taken. If the dreamer is unfortunate enough to end up sharing a host body with an intellect devourer, the intellect devourer immediately makes its way toward the <em>dream lens</em> - this takes 1d10 hours. If the dream ends before the intellect devourer reaches the <em>dream lens,</em> the dreamer awakens with no ill effect. If the intellect devourer reaches the <em>dream lens</em> in time, the intellect devourer can attempt to use its body thief ability on the dreamer. If the attempt fails, the dreamer awakes with a start with blood pouring from eyes, mouth, nostrils, and ears, but no real memories of what caused the incredible pain.</p>
<hr/>
<p>The strange and powerful drug known as midnight milk is the cornerstone of Ilvarandin's most recent attempt to bolster its armies against the worms of Denebrum. Distilled from the excretions and seepings of vast <Link to="/monster/mu_spore">mu spores</Link> that float in the skies above the Midnight Mountains, midnight milk has a strange connection to the powerful and alien dreams these immense slumbering monsters spend the majority of their time pursuing. By distilling the fluids and mixing them with other alchemical elixirs and catalysts, the intellect devourers and their <Link to="/monster/ghast">ghast</Link> ally Bereshkhani have concocted an elixir capable of allowing an intellect devourer to use its body thief ability at great range. The only tricky part - getting the targets addicted to the stuff, for it takes time for midnight milk to work its unwelcome magic upon the dreaming mind.</p>
<p>Midnight milk is imbibed through the mouth. A single dose is enough to send most drinkers into a deep sleep, during which the user experiences very vivid dreams. All of these dreams are superficially similar, starting with a sensation of an endless fall into what seems a bottomless pit that eventually reveals itself to be a fall downward toward a vast range of subterranean mountains lit by strange moon-like shapes floating near the vast cavern roof.</p>
<p>If the dreaming victim dreams long enough (with successive doses of midnight milk, each dream lasts longer and allows the dreamer to travel farther), they travel ghostlike to the west and eventually reach Ilvarandin, at which point the dreaming mind "lands" in the body of a creature that dwells there - typically a <Link to="/monster/troglodyte">troglodyte</Link>, <Link to="/monster/drow">drow</Link>, <Link to="/monster/duergar">duergar</Link>, <Link to="/monster/derro">derro</Link>, <Link to="/monster/mongrelman">mongrelman</Link>, or <Link to="/monster/morlock">morlock</Link>, but sometimes stranger things like <Link to="/monster/drider">driders</Link> or <Link to="/monster/gug">gugs</Link> or <Link to="/monster/roper">ropers</Link>, or even <Link to="/monster/black_pudding">black puddings</Link> or <Link to="/monster/purple_worm">purple worms</Link>. The "dreamer" experiences his explorations of Ilvarandin unaware of the fact that he's in a strange new body, but has no control over his actions since he's basically just watching and experiencing the actions of his host body, and when he finally wakes remembers the dreams as vague memories. The addictive quality of the drug colors these memories and makes his stay in Ilvarandin feel like a visit to paradise.</p>
<p>Yet the truth is far more insidious, for these experiences are not just dreams. The user's slumbering mind actually leaves his body, seeks out a denizen of Ilvarandin, and enjoys that body's experiences for a time. The <em>dream lens</em> acts as a strange spiritual magnet, drawing the dreamer deep into Ilvarandin where, it becomes increasingly likely on successive visits that the dreamer's mind inhabits a body already inhabited by an intellect devourer.</p>
<p>An intellect devourer automatically notices the arrival of a dreaming mind in its already shared body. If the intellect devourer can reach the <em>dream lens</em> before the dreamer awakens, it can abandon its current host body to merge with the dreaming creature's mind - when the dreamer awakens, the intellect devourer travels with it and immediately devourers the dreamer's brain, proceeding from that point forward as if it had successfully used its body thief ability on the victim. At this point, the intellect devourer is free to use its new body on the surface as it wills - most quickly seek out other cells of intellect devourers active in the area to secure <Link to="/spell/gentle_repose">gentle repose</Link> spells to keep their new host bodies fresh, or to volunteer their aid in spreading the midnight milk further into society.</p>
<section data-footnotes>
<h3 id="drug-midnight_milk-label">Footnotes</h3>
<ol>
<li id="drug-midnight_milk-D">
<p><em>Dream lenses</em> are artifacts mentioned in <em>Lost Cities of Golarion</em> but not given any statistics. The <em>lens</em> is described as "the artifact allowing the invasion into Golarion's dreaming minds," and is located in Ilvarandin in Orv, the deepest part of the Darklands. <InnerLink id="backlink-drug-midnight_milk-ref-D-1" data-hash-target to="drug-midnight_milk-ref-D-1" aria-label="Back to reference D-1">↩</InnerLink></p>
</li>
</ol>
</section>
</>};
export default {not_found:_not_found,keleshite_coffee:_keleshite_coffee,flayleaf:_flayleaf,morgod_jelly:_morgod_jelly,magesight:_magesight,muscaria:_muscaria,pesh:_pesh,vigilance:_vigilance,aether:_aether,gossamer_veil:_gossamer_veil,slavers_drops:_slavers_drops,bloodbrush_extract:_bloodbrush_extract,opium:_opium,tears_of_razmir:_tears_of_razmir,scour:_scour,stings_savor:_stings_savor,dwarven_fire_ale:_dwarven_fire_ale,serpents_kiss:_serpents_kiss,zerk:_zerk,ruk_tar:_ruk_tar,harlot_sweets:_harlot_sweets,inspiration_dust:_inspiration_dust,fireskin_elixir:_fireskin_elixir,oblivion:_oblivion,dreamtime_tea:_dreamtime_tea,blood_sap:_blood_sap,synthetic_mumia:_synthetic_mumia,hush:_hush,starspore:_starspore,elven_absinthe:_elven_absinthe,mumia:_mumia,numerian_fluids:_numerian_fluids,shiver:_shiver,wyrm_pesh:_wyrm_pesh,esoterum:_esoterum,old_mage:_old_mage,adyton:_adyton,felwil:_felwil,silvertongue:_silvertongue,midnight_milk:_midnight_milk}